// Optional NTFS deletion protection. Rules are explicit, never inherited by working files.
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.AccessControl;
using System.Security.Principal;
using System.Text;
using System.Threading;
namespace AstroArchive {
 public class ProtectionState {public string Mode="Off",Sid,Root;}
 public class ProtectionRule {public string Path;public bool Directory;public int Bits;}
 public class ProtectionRecord {public string Kind,Id;public ProtectionRule Rule;public string[] Paths,Affected;public bool Capture;}
 public sealed class ArchiveProtection {
  readonly string root,meta,statePath,logPath;ProtectionState state;
  readonly Dictionary<string,ProtectionRule> rules=new Dictionary<string,ProtectionRule>(StringComparer.OrdinalIgnoreCase);
  readonly HashSet<string> pending=new HashSet<string>(StringComparer.OrdinalIgnoreCase);
  readonly Dictionary<string,ProtectionRecord> unlocked=new Dictionary<string,ProtectionRecord>();
  public bool Enabled{get{return state.Mode=="Enabled";}}
  public string Availability{get{if(Environment.OSVersion.Platform!=PlatformID.Win32NT)return "Protection requires Windows and an NTFS drive.";try{string drive=Path.GetPathRoot(root);if(drive.StartsWith("\\\\")||new DriveInfo(drive).DriveFormat!="NTFS")return "Protection requires a local NTFS drive.";if(Enabled&&state.Sid!=CurrentSid())return "Protection was set by another Windows account. Turn it off and on to protect this account.";return null;}catch{return "Windows permissions could not be checked for this archive.";}}}
  string CurrentSid(){using(var identity=WindowsIdentity.GetCurrent()){if(identity.User==null)throw new IOException("Windows account could not be identified.");return identity.User.Value;}}
  public ArchiveProtection(string root,string meta){this.root=root;this.meta=meta;statePath=Path.Combine(meta,"protection.json");logPath=Path.Combine(meta,"protection-rules.jsonl");state=File.Exists(statePath)?Util.Deserialize<ProtectionState>(File.ReadAllText(statePath)):new ProtectionState();if(state==null||!new[]{"Off","Enabling","Enabled","Disabling"}.Contains(state.Mode))throw new InvalidDataException("Archive protection settings are invalid: "+statePath);if(state.Mode=="Off")return;
   if(Environment.OSVersion.Platform!=PlatformID.Win32NT)throw new IOException("This archive has Windows deletion protection. Open it on Windows to change the protection setting.");
   if(string.IsNullOrEmpty(state.Sid))throw new InvalidDataException("Archive protection account is missing.");
   if(File.Exists(logPath)){string[] lines=File.ReadAllLines(logPath);for(int i=0;i<lines.Length;i++){ProtectionRecord record;try{record=Decode(Util.Deserialize<ProtectionRecord>(lines[i]));}catch{if(i==lines.Length-1&&!File.ReadAllText(logPath).EndsWith("\n")){TruncateIncompleteLog();break;}throw new InvalidDataException("Archive protection recovery record is invalid: "+logPath);}Replay(record);}}
   if(state.Mode=="Enabling"||state.Mode=="Disabling"){Disable(CancellationToken.None,null);return;}
   if(!string.Equals(state.Root,root,StringComparison.OrdinalIgnoreCase)){foreach(var rule in rules.Values.ToArray()){if(Exists(rule)){Append(new ProtectionRecord{Kind="add",Rule=rule});Change(rule,rule.Bits,0);Append(new ProtectionRecord{Kind="ready",Id=rule.Path});}}state.Root=root;SaveState();}
   foreach(string path in pending.ToArray()){ProtectionRule rule;if(rules.TryGetValue(path,out rule)&&Exists(rule))Change(rule,rule.Bits,0);Append(new ProtectionRecord{Kind="ready",Id=path});}
   foreach(var record in unlocked.Values.ToArray())Restore(record);
  }
  void TruncateIncompleteLog(){string text=File.ReadAllText(logPath);int end=text.LastIndexOf('\n');DurableText(logPath,end<0?"":text.Substring(0,end+1));}
  string Relative(string path){if(path==null)return null;Validate(path);return path.TrimEnd('\\','/').Equals(root.TrimEnd('\\','/'),StringComparison.OrdinalIgnoreCase)?".":path.Substring(root.TrimEnd('\\','/').Length+1);}
  string Absolute(string path){if(path==null)return null;string full=Path.GetFullPath(Path.Combine(root,path));Validate(full);return full;}
  ProtectionRecord Transform(ProtectionRecord record,Func<string,string> path){if(record==null)return null;return new ProtectionRecord{Kind=record.Kind,Id=record.Kind=="ready"||record.Kind=="forget"?path(record.Id):record.Id,Rule=record.Rule==null?null:new ProtectionRule{Path=path(record.Rule.Path),Directory=record.Rule.Directory,Bits=record.Rule.Bits},Paths=record.Paths==null?null:record.Paths.Select(path).ToArray(),Affected=record.Affected==null?null:record.Affected.Select(path).ToArray(),Capture=record.Capture};}
  ProtectionRecord Encode(ProtectionRecord record){return Transform(record,Relative);}
  ProtectionRecord Decode(ProtectionRecord record){return Transform(record,Absolute);}
  void Replay(ProtectionRecord r){if(r==null)throw new InvalidDataException("Empty protection record.");if(r.Kind=="add"){Validate(r.Rule.Path);rules[r.Rule.Path]=r.Rule;pending.Add(r.Rule.Path);}else if(r.Kind=="ready")pending.Remove(r.Id);else if(r.Kind=="forget"){rules.Remove(r.Id);pending.Remove(r.Id);}else if(r.Kind=="unlock"){foreach(string p in r.Paths.Concat(r.Affected))Validate(p);unlocked[r.Id]=r;}else if(r.Kind=="lock")unlocked.Remove(r.Id);else throw new InvalidDataException("Unknown protection record.");}
  void Append(ProtectionRecord record){byte[] bytes=Encoding.UTF8.GetBytes(Util.Serialize(Encode(record))+"\n");using(var stream=new FileStream(logPath,FileMode.Append,FileAccess.Write,FileShare.Read)){stream.Write(bytes,0,bytes.Length);stream.Flush(true);}Replay(record);}
  void SaveState(){DurableText(statePath,Util.Serialize(state));}
  static void DurableText(string path,string text){string temp=path+"."+Guid.NewGuid().ToString("N")+".partial";try{using(var stream=new FileStream(temp,FileMode.CreateNew,FileAccess.Write,FileShare.None)){byte[] bytes=Encoding.UTF8.GetBytes(text);stream.Write(bytes,0,bytes.Length);stream.Flush(true);}Repository.CommitTemporary(temp,path,CancellationToken.None);}finally{Repository.TryRemove(temp);}}
  void Validate(string path){if(!Util.Within(path,root))throw new IOException("Protection path escapes the archive.");if(!path.TrimEnd('\\','/').Equals(root.TrimEnd('\\','/'),StringComparison.OrdinalIgnoreCase))Repository.CheckManagedPath(path,root);else if(!FileStamp.CanTraverse(new DirectoryInfo(root)))throw new IOException("Linked archive folders cannot be protected.");if(File.Exists(path)&&(File.GetAttributes(path)&FileAttributes.ReparsePoint)!=0)throw new IOException("Linked files cannot be protected: "+path);}
  bool CapturePath(string path){return Util.Within(path,root)&&!Util.Within(path,meta)&&!Util.Within(path,Path.Combine(root,"Edited"))&&!Util.Within(path,Path.Combine(root,"Dump"));}
  static bool Exists(ProtectionRule rule){return rule.Directory?System.IO.Directory.Exists(rule.Path):File.Exists(rule.Path);}
  FileSystemSecurity Security(ProtectionRule rule){return rule.Directory?(FileSystemSecurity)System.IO.Directory.GetAccessControl(rule.Path,AccessControlSections.Access):File.GetAccessControl(rule.Path,AccessControlSections.Access);}
  IEnumerable<FileSystemAccessRule> Matching(FileSystemSecurity security){return security.GetAccessRules(true,false,typeof(SecurityIdentifier)).Cast<FileSystemAccessRule>().Where(r=>r.IdentityReference.Value==state.Sid&&r.AccessControlType==AccessControlType.Deny&&r.InheritanceFlags==InheritanceFlags.None&&r.PropagationFlags==PropagationFlags.None);}
  int Mask(FileSystemSecurity security){return Matching(security).Aggregate(0,(mask,r)=>mask|(int)r.FileSystemRights);}
  void Change(ProtectionRule rule,int add,int remove){Validate(rule.Path);if(!Exists(rule))return;var security=Security(rule);int old=Mask(security),next=(old|add)&~remove;if(old==next)return;foreach(var entry in Matching(security).ToArray())security.RemoveAccessRuleSpecific(entry);if(next!=0)security.AddAccessRule(new FileSystemAccessRule(new SecurityIdentifier(state.Sid),(FileSystemRights)next,InheritanceFlags.None,PropagationFlags.None,AccessControlType.Deny));if(rule.Directory)System.IO.Directory.SetAccessControl(rule.Path,(DirectorySecurity)security);else File.SetAccessControl(rule.Path,(FileSecurity)security);}
  void Add(string path,bool directory,int desired){Validate(path);ProtectionRule owned;if(rules.TryGetValue(path,out owned)){if(pending.Contains(path)){Change(owned,owned.Bits,0);Append(new ProtectionRecord{Kind="ready",Id=path});}return;}var rule=new ProtectionRule{Path=path,Directory=directory};rule.Bits=desired&~Mask(Security(rule));if(rule.Bits==0)return;Append(new ProtectionRecord{Kind="add",Rule=rule});Change(rule,rule.Bits,0);Append(new ProtectionRecord{Kind="ready",Id=path});}
  public void ProtectCapture(string path){if(!Enabled||!CapturePath(path)||!File.Exists(path))return;EnsureCapture(path);}
  void EnsureCapture(string path){Validate(path);string parent=Path.GetDirectoryName(path);var parents=new Stack<string>();while(parent!=null&&Util.Within(parent,root)){parents.Push(parent);if(parent.TrimEnd('\\','/').Equals(root.TrimEnd('\\','/'),StringComparison.OrdinalIgnoreCase))break;parent=Path.GetDirectoryName(parent);}foreach(string folder in parents)Add(folder,true,(int)(FileSystemRights.Delete|FileSystemRights.DeleteSubdirectoriesAndFiles));Add(path,false,(int)FileSystemRights.Delete);}
  public void Enable(IEnumerable<string> files,CancellationToken ct,Action<ProgressInfo> progress){if(Enabled)return;string reason=Availability;if(reason!=null)throw new IOException(reason);state.Sid=CurrentSid();state.Root=root;state.Mode="Enabling";rules.Clear();pending.Clear();unlocked.Clear();DurableText(logPath,"");SaveState();try{var list=files.Distinct(StringComparer.OrdinalIgnoreCase).Where(CapturePath).ToArray();for(int i=0;i<list.Length;i++){ct.ThrowIfCancellationRequested();if(progress!=null)progress(new ProgressInfo{Stage="Protecting originals",Text=Path.GetFileName(list[i]),Done=i,Total=list.Length});if(!File.Exists(list[i]))throw new IOException("Archive file is missing: "+list[i]);EnsureCapture(list[i]);}ct.ThrowIfCancellationRequested();state.Mode="Enabled";SaveState();}catch{Disable(CancellationToken.None,null);throw;}}
  public void Disable(CancellationToken ct,Action<ProgressInfo> progress){if(state.Mode=="Off")return;ct.ThrowIfCancellationRequested();state.Mode="Disabling";SaveState();int done=0,total=rules.Count;foreach(var rule in rules.Values.ToArray()){if(progress!=null)progress(new ProgressInfo{Stage="Removing protection",Text=Path.GetFileName(rule.Path),Done=done++,Total=total});Change(rule,0,rule.Bits);Append(new ProtectionRecord{Kind="forget",Id=rule.Path});}state.Mode="Off";SaveState();rules.Clear();pending.Clear();unlocked.Clear();DurableText(logPath,"");}
  public IDisposable Unlock(string source,string destination,bool capture=true){if(!Enabled)return new Scope(null,null);Validate(source);if(destination!=null)Validate(destination);var affected=new[]{source,Path.GetDirectoryName(source)}.Where(p=>p!=null&&rules.ContainsKey(p)).ToArray();var record=new ProtectionRecord{Kind="unlock",Id=Guid.NewGuid().ToString("N"),Paths=destination==null?new[]{source}:new[]{source,destination},Affected=affected,Capture=capture};Append(record);try{foreach(string path in affected){var rule=rules[path];int remove=path.Equals(source,StringComparison.OrdinalIgnoreCase)?rule.Bits:rule.Bits&(int)FileSystemRights.DeleteSubdirectoriesAndFiles;Change(rule,0,remove);}return new Scope(this,record);}catch{Restore(record);throw;}}
  void Restore(ProtectionRecord record){foreach(string path in record.Affected){ProtectionRule rule;if(rules.TryGetValue(path,out rule)){if(Exists(rule))Change(rule,rule.Bits,0);else Append(new ProtectionRecord{Kind="forget",Id=path});}}if(record.Capture)foreach(string path in record.Paths)if(CapturePath(path)&&File.Exists(path))EnsureCapture(path);Append(new ProtectionRecord{Kind="lock",Id=record.Id});}
  sealed class Scope:IDisposable {ArchiveProtection owner;readonly ProtectionRecord record;public Scope(ArchiveProtection owner,ProtectionRecord record){this.owner=owner;this.record=record;}public void Dispose(){if(owner==null)return;owner.Restore(record);owner=null;}}
 }
 public sealed partial class Repository {
  ArchiveProtection protection;
  public bool OriginalsProtected{get{return protection!=null&&protection.Enabled;}}
  public string ProtectionAvailability{get{return protection==null?"Open an archive first.":protection.Availability;}}
  public void SetOriginalsProtection(bool enabled,CancellationToken ct,Action<ProgressInfo> progress){if(enabled)protection.Enable(All().Select(FilePath),ct,progress);else protection.Disable(ct,progress);}
  void ProtectCapture(string path){protection.ProtectCapture(path);}
  void MoveCapture(string source,string destination){var scope=protection.Unlock(source,destination);bool moved=false;try{File.Move(source,destination);moved=true;scope.Dispose();}catch(Exception failure){try{if(moved&&File.Exists(destination)&&!File.Exists(source)){using(protection.Unlock(destination,source)){File.Move(destination,source);}}scope.Dispose();}catch(Exception recovery){throw new AggregateException("The file operation could not restore protection. Reopen the archive to recover it.",failure,recovery);}throw;}}
  void DeleteEmptyCaptureFolder(string path){using(protection.Unlock(path,null,false)){Directory.Delete(path);}}
 }
}
