// Portable, byte-preserving backups. Only a completely verified backup is published.
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
namespace AstroArchive {
 public class BackupFile {public string Path,Hash;public long Bytes;}
 public class BackupManifest {public int Version=1;public string CreatedUtc,Archive;public List<BackupFile> Files=new List<BackupFile>();}
 public class BackupResult {public string Path;public int Files;public long Bytes;public bool Compressed;}
 public sealed partial class Repository {
  const string BackupIdentityName="backup-origin.txt";
  string BackupIdentity(){string path=Path.Combine(Meta,BackupIdentityName);if(!File.Exists(path))return "";Guid id;string text=File.ReadAllText(path).Trim();if(!Guid.TryParseExact(text,"N",out id))throw new InvalidDataException("The backup restore identity is invalid: "+path);return "|backup:"+text;}
  sealed class BackupSource {public string Source,Relative;public FileStamp Stamp;}
  public static void ValidateBackupDestination(string destination,string root){
   string full=Path.GetFullPath(destination);if(Util.Within(full,root))throw new IOException("Choose a backup folder outside the archive. A separate drive is best.");
   string parent=full;while(parent!=null){if(Directory.Exists(parent)&&!FileStamp.CanTraverse(new DirectoryInfo(parent)))throw new IOException("Choose a backup folder without linked directories: "+parent);parent=Path.GetDirectoryName(parent);}
  }
  bool BackupExcluded(string relative){string portable=relative.Replace('\\','/');return portable==".astroarchive/"+BackupIdentityName||portable==".astroarchive/index.sqlite"||portable.StartsWith(".astroarchive/index.sqlite.",StringComparison.OrdinalIgnoreCase)||portable.StartsWith(".astroarchive/index.sqlite-",StringComparison.OrdinalIgnoreCase)||portable.StartsWith(".astroarchive/protection.",StringComparison.OrdinalIgnoreCase)||portable.StartsWith(".astroarchive/protection-rules.",StringComparison.OrdinalIgnoreCase)||portable==".astroarchive/staging"||portable.StartsWith(".astroarchive/staging/",StringComparison.OrdinalIgnoreCase);}
  List<BackupSource> BackupSources(CancellationToken ct){var files=new List<BackupSource>();var folders=new Stack<string>();folders.Push(Root);while(folders.Count>0){ct.ThrowIfCancellationRequested();string folder=folders.Pop();if(!FileStamp.CanTraverse(new DirectoryInfo(folder)))throw new IOException("Backup cannot follow a linked archive folder: "+folder);foreach(string path in Directory.EnumerateFileSystemEntries(folder)){ct.ThrowIfCancellationRequested();string relative=path.Substring(Root.TrimEnd('\\','/').Length+1);if(BackupExcluded(relative))continue;var attrs=File.GetAttributes(path);if((attrs&FileAttributes.Directory)!=0)folders.Push(path);else{if((attrs&FileAttributes.ReparsePoint)!=0&&!FileStamp.Read(path).Cloud)throw new IOException("Backup cannot follow a linked archive file: "+path);files.Add(new BackupSource{Source=path,Relative=relative.Replace('\\','/'),Stamp=FileStamp.Read(path)});}}}return files.OrderBy(f=>f.Relative,StringComparer.OrdinalIgnoreCase).ToList();}
  static string BackupHash(Stream input,Stream output,CancellationToken ct,Action<int> pulse){using(var lease=FileTransfer.Rent()){byte[] buffer=lease.Buffer;using(var hash=SHA256.Create()){int n;while((n=input.Read(buffer,0,buffer.Length))>0){ct.ThrowIfCancellationRequested();if(output!=null)output.Write(buffer,0,n);hash.TransformBlock(buffer,0,n,buffer,0);if(pulse!=null)pulse(n);}ct.ThrowIfCancellationRequested();hash.TransformFinalBlock(new byte[0],0,0);return BitConverter.ToString(hash.Hash).Replace("-","").ToLowerInvariant();}}}
  const string RestoreInstructions="AstroArchive backup\r\n\r\nIf this is a ZIP, extract it first. The Repository folder contains your images, edited files and archive database in their original structure. In AstroArchive, choose this Repository folder in Settings > Repository to open the restored archive. You can also copy that folder to another location before opening it.\r\n\r\nImage files are preserved byte for byte. ZIP compression is lossless and does not change resolution, quality or metadata. backup.json lists every archived file with its size and SHA-256 checksum.\r\n\r\nBackups use ordinary permissions. To protect restored originals, enable protection in Settings > Preferences. Keep another backup on a separate drive to protect against drive failure.\r\n";
  public BackupResult CreateBackup(string destination,bool compressed,CancellationToken ct,Action<ProgressInfo> progress){
   ValidateBackupDestination(destination,Root);if(!FileStamp.CanTraverse(new DirectoryInfo(Root)))throw new IOException("Choose an archive without linked root directories before backing up.");Directory.CreateDirectory(destination);
   string name="AstroArchive-backup-"+DateTime.Now.ToString("yyyyMMdd-HHmmss")+"-"+Guid.NewGuid().ToString("N").Substring(0,6),final=Path.Combine(destination,name+(compressed?".zip":"")),work=final+".partial",snapshot=Path.Combine(destination,"."+name+".index.partial");string identity=snapshot+".origin";long bytesDone=0,total=0;int done=0,count=0;DateTime last=DateTime.MinValue;string stage="Preparing backup",current="Saving current archive database";
   Action<bool> pulse=force=>{if(progress!=null&&(force||(DateTime.UtcNow-last).TotalMilliseconds>=150)){last=DateTime.UtcNow;progress(new ProgressInfo{Stage=stage,Text=current,Done=done,Total=count*2,BytesDone=bytesDone,BytesTotal=total,TotalKnown=count>0});}};
   try{
    ct.ThrowIfCancellationRequested();pulse(true);db.BackupTo(snapshot,ct);File.WriteAllText(identity,Guid.NewGuid().ToString("N"),new UTF8Encoding(false));var sources=BackupSources(ct);sources.Add(new BackupSource{Source=snapshot,Relative=".astroarchive/index.sqlite",Stamp=FileStamp.Read(snapshot)});sources.Add(new BackupSource{Source=identity,Relative=".astroarchive/"+BackupIdentityName,Stamp=FileStamp.Read(identity)});count=sources.Count;total=sources.Sum(f=>f.Stamp.Size)*2;
    var manifest=new BackupManifest{CreatedUtc=DateTime.UtcNow.ToString("o"),Archive=Path.GetFileName(Root.TrimEnd('\\','/'))};stage="Creating backup";
    Action<BackupSource,Stream> copy=(file,output)=>{ct.ThrowIfCancellationRequested();current=file.Relative;pulse(true);FileStamp before=FileStamp.Read(file.Source);if(!before.ContentSame(file.Stamp))throw new IOException("A file changed while preparing the backup: "+file.Relative);string hash;using(var input=new FileStream(file.Source,FileMode.Open,FileAccess.Read,FileShare.Read))hash=BackupHash(input,output,ct,n=>{bytesDone+=n;pulse(false);});if(!before.ContentSame(FileStamp.Read(file.Source)))throw new IOException("A file changed while backing up: "+file.Relative);manifest.Files.Add(new BackupFile{Path="Repository/"+file.Relative,Bytes=before.Size,Hash=hash});done++;};
    if(compressed){using(var output=new FileStream(work,FileMode.CreateNew,FileAccess.ReadWrite,FileShare.None)){using(var zip=new ZipArchive(output,ZipArchiveMode.Create,true)){foreach(var file in sources){var entry=zip.CreateEntry("Repository/"+file.Relative,CompressionLevel.Optimal);using(var entryStream=entry.Open())copy(file,entryStream);}WriteBackupEntry(zip,"backup.json",Util.Serialize(manifest));WriteBackupEntry(zip,"Restore.txt",RestoreInstructions);}output.Flush(true);}}
    else{Directory.CreateDirectory(work);foreach(var file in sources){string target=Path.Combine(work,"Repository",file.Relative.Replace('/',Path.DirectorySeparatorChar));Directory.CreateDirectory(Path.GetDirectoryName(target));using(var output=new FileStream(target,FileMode.CreateNew,FileAccess.Write,FileShare.None)){copy(file,output);output.Flush(true);}}Util.AtomicText(Path.Combine(work,"backup.json"),Util.Serialize(manifest));Util.AtomicText(Path.Combine(work,"Restore.txt"),RestoreInstructions);}
    stage="Verifying backup";
    Action<BackupFile,Stream> verify=(file,input)=>{ct.ThrowIfCancellationRequested();current=file.Path;pulse(true);long length=0;string hash=BackupHash(input,null,ct,n=>{length+=n;bytesDone+=n;pulse(false);});if(hash!=file.Hash||length!=file.Bytes)throw new InvalidDataException("Backup verification failed: "+file.Path);done++;};
    if(compressed){using(var input=new FileStream(work,FileMode.Open,FileAccess.Read,FileShare.Read))using(var zip=new ZipArchive(input,ZipArchiveMode.Read)){if(zip.Entries.Count!=manifest.Files.Count+2)throw new InvalidDataException("Backup contents are incomplete.");VerifyBackupText(zip,"backup.json",Util.Serialize(manifest));VerifyBackupText(zip,"Restore.txt",RestoreInstructions);foreach(var file in manifest.Files){var entry=zip.GetEntry(file.Path);if(entry==null||entry.Length!=file.Bytes)throw new InvalidDataException("Backup entry is missing: "+file.Path);using(var stream=entry.Open())verify(file,stream);}}}
    else{if(File.ReadAllText(Path.Combine(work,"backup.json"))!=Util.Serialize(manifest)||File.ReadAllText(Path.Combine(work,"Restore.txt"))!=RestoreInstructions)throw new InvalidDataException("Backup recovery files could not be verified.");foreach(var file in manifest.Files)using(var input=new FileStream(Path.Combine(work,file.Path.Replace('/',Path.DirectorySeparatorChar)),FileMode.Open,FileAccess.Read,FileShare.Read))verify(file,input);}
    // Refuse a success message if a source changed or a new file appeared during the copy.
    foreach(var file in sources){ct.ThrowIfCancellationRequested();if(!file.Stamp.ContentSame(FileStamp.Read(file.Source)))throw new IOException("The archive changed during backup: "+file.Relative);}
    var after=BackupSources(ct);if(!sources.Where(f=>f.Source!=snapshot&&f.Source!=identity).Select(f=>f.Relative).SequenceEqual(after.Select(f=>f.Relative),StringComparer.OrdinalIgnoreCase))throw new IOException("Files were added or removed while the backup was being created. Try again.");
    ct.ThrowIfCancellationRequested();if(compressed)File.Move(work,final);else Directory.Move(work,final);stage="Backup complete";current="Verified "+manifest.Files.Count+" files";pulse(true);return new BackupResult{Path=final,Files=manifest.Files.Count,Bytes=manifest.Files.Sum(f=>f.Bytes),Compressed=compressed};
   }finally{TryRemove(identity);TryRemove(snapshot);TryRemove(snapshot+"-journal");TryRemove(work);if(Directory.Exists(work))try{Directory.Delete(work,true);}catch{}}
  }
  static void WriteBackupEntry(ZipArchive zip,string name,string text){using(var stream=zip.CreateEntry(name,CompressionLevel.Optimal).Open())using(var writer=new StreamWriter(stream,new UTF8Encoding(false)))writer.Write(text);}
  static void VerifyBackupText(ZipArchive zip,string name,string expected){var entry=zip.GetEntry(name);if(entry==null)throw new InvalidDataException("Missing backup recovery file: "+name);using(var stream=entry.Open())using(var reader=new StreamReader(stream))if(reader.ReadToEnd()!=expected)throw new InvalidDataException("Backup recovery file failed verification: "+name);}
 }
}
