// Common astrophotography labels supplement OpenNGC without changing positions.
namespace AstroArchive {
 public static class CatalogNames {
  // Canonical ID | preferred common name | additional names (semicolon separated).
  public static readonly string[] Entries={
   "M1|Crab Nebula|",
   "M8|Lagoon Nebula|",
   "M16|Eagle Nebula|Star Queen Nebula",
   "M17|Omega Nebula|Swan Nebula;Horseshoe Nebula",
   "M20|Trifid Nebula|",
   "M27|Dumbbell Nebula|Apple Core Nebula",
   "M31|Andromeda Galaxy|Andromeda",
   "M33|Triangulum Galaxy|Triangulum;Pinwheel Galaxy in Triangulum",
   "M42|Orion Nebula|Great Orion Nebula;Great Nebula in Orion",
   "M45|Pleiades|Seven Sisters",
   "M51|Whirlpool Galaxy|",
   "M57|Ring Nebula|",
   "M63|Sunflower Galaxy|",
   "M64|Black Eye Galaxy|Black-Eye Galaxy;Sleeping Beauty Galaxy",
   "M76|Little Dumbbell Nebula|",
   "M81|Bode's Galaxy|Bodes Galaxy;Bode’s Galaxy",
   "M82|Cigar Galaxy|",
   "M97|Owl Nebula|",
   "M101|Pinwheel Galaxy|",
   "M104|Sombrero Galaxy|",
   "NGC253|Sculptor Galaxy|Silver Dollar Galaxy",
   "NGC281|Pacman Nebula|Pac-Man Nebula",
   "NGC7293|Helix Nebula|",
   "NGC7380|Wizard Nebula|",
   "NGC6888|Crescent Nebula|Crescent",
   "NGC1499|California Nebula|",
   "NGC2024|Flame Nebula|",
   "NGC2174|Monkey Head Nebula|Monkey-Head Nebula",
   "NGC2237|Rosette Nebula|Rosette A",
   "NGC2359|Thor's Helmet|Thors Helmet;Thor’s Helmet;Thor's Helmet Nebula",
   "NGC2392|Clown Face Nebula|",
   "NGC4565|Needle Galaxy|",
   "NGC4631|Whale Galaxy|",
   "NGC6334|Cat's Paw Nebula|Cats Paw Nebula;Cat’s Paw Nebula",
   "NGC6357|Lobster Nebula|War and Peace Nebula",
   "NGC6960|Western Veil Nebula|Western Veil;Witch's Broom Nebula;Witch’s Broom Nebula",
   "NGC6992|Eastern Veil Nebula|Eastern Veil;Network Nebula",
   "NGC7000|North America Nebula|North American Nebula",
   "NGC7023|Iris Nebula|",
   "NGC7635|Bubble Nebula|",
   "IC1805|Heart Nebula|",
   "IC1848|Soul Nebula|Westerhout 5",
   "IC1396|Elephant’s Trunk Nebula|Elephant's Trunk Nebula;Elephant Trunk Nebula",
   "IC2177|Seagull Nebula|",
   "IC342|Hidden Galaxy|",
   "IC443|Jellyfish Nebula|",
   "IC5070|Pelican Nebula|",
   "B33|Horsehead Nebula|Barnard 33",
   // Caldwell-only entries in the bundled position catalogue.
   "C9|Cave Nebula|Caldwell 9;SH2155;Sh2-155;Sharpless 155",
   "C14|Double Cluster|Caldwell 14;h and chi Persei",
   "C41|Hyades|Caldwell 41;Melotte 25;Mel 25",
   "C99|Coalsack Nebula|Caldwell 99;Coalsack"
  };
 }
}
