using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Media;
using System.Windows.Media.Imaging;
namespace AstroArchive {
 public partial class MainUi {
  void SmokeEdited(string output){
   var original=repo;var windowState=Window.WindowState;int page=((TabControl)Window.FindName("MainTabs")).SelectedIndex;string directory=Path.Combine(Path.GetTempPath(),"AstroArchive-edited-ui-"+Guid.NewGuid().ToString("N")),source=directory+"-source";Repository temporary=null;
   try{
    Directory.CreateDirectory(source);string filename="M31_Ha_120x60s_starless.png",path=Path.Combine(source,filename);var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(BitmapSource.Create(2,2,96,96,PixelFormats.Gray8,null,new byte[]{50,100,150,200},2)));using(var stream=File.Create(path))encoder.Save(stream);
    temporary=new Repository(directory);repo=temporary;var project=repo.AddEditedImages(new[]{path},null,"Andromeda edits",CancellationToken.None,null);RefreshEdited(project.Id);GoToPage(2);PumpPopupLayout();
    if(EditedProjectsList.Items.Count!=2||G("EditedGrid").Items.Count!=1||!B("EditedAddButton").IsEnabled||!B("EditedImportFolderButton").IsEnabled)throw new Exception("Edited project navigation or import controls did not render.");
    File.Copy(path,Path.Combine(source,"renamed-copy.png"));string revisionFolder=Path.Combine(source,"revision");Directory.CreateDirectory(revisionFolder);var revisionEncoder=new PngBitmapEncoder();revisionEncoder.Frames.Add(BitmapFrame.Create(BitmapSource.Create(2,2,96,96,PixelFormats.Gray8,null,new byte[]{60,110,160,210},2)));using(var stream=File.Create(Path.Combine(revisionFolder,filename)))revisionEncoder.Save(stream);
    var duplicateReview=repo.ScanEditedFolder(source,true,CancellationToken.None,null);if(duplicateReview.Images.Count(i=>i.Status=="Duplicate")!=2||duplicateReview.Images.Count(i=>i.Status=="New version (same name)")!=1)throw new Exception("Edited review did not distinguish copies from a changed same-name image.");
    var reviewTable=EditedImportReviewTable(duplicateReview);var reviewDialog=new FormWindow(Window,"Edited duplicate review",1000,600);reviewDialog.Add(reviewTable);reviewDialog.CloseOnly();reviewDialog.Window.Show();
    try{PumpPopupLayout();foreach(var candidate in duplicateReview.Images){reviewTable.ScrollIntoView(candidate);reviewTable.UpdateLayout();PumpPopupLayout();var check=reviewTable.Columns[0].GetCellContent(candidate) as CheckBox;if(check==null||check.IsEnabled!=candidate.CanInclude||check.IsChecked!=candidate.Include)throw new Exception("Duplicate import choices are editable or a new version cannot be selected.");}SavePopup((FrameworkElement)reviewDialog.Window.Content,Path.Combine(output,"AstroArchive_Edited_Duplicate_Review.png"));}finally{reviewDialog.Window.Close();}
    EditedImportComplete(project.Id,new EditedImportResult{SkippedDuplicates=2});WaitForSearches();PumpPopupLayout();if(!((FrameworkElement)Window.FindName("EditedImportNotice")).IsVisible||!L("EditedImportNoticeText").Text.Contains("2 duplicates skipped"))throw new Exception("Duplicate-only import summary was hidden after progress closed.");Capture(Path.Combine(output,"AstroArchive_Edited_Import_Result.png"));B("DismissEditedImportNotice").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));if(((FrameworkElement)Window.FindName("EditedImportNotice")).IsVisible)throw new Exception("Edited import summary cannot be dismissed.");
    var image=G("EditedGrid").Items.Cast<EditedImage>().Single();G("EditedGrid").SelectedItem=image;PumpPopupLayout();if(!B("EditedPreviewButton").IsEnabled||!B("EditedDetailsButton").IsEnabled||image.Metadata.ImageClass!="Starless"||image.Metadata.TotalExposure!=7200)throw new Exception("Edited selection/acquisition details missing.");
    if(EditedTargets.Items.Count!=2||Window.FindName("EditedPreviewPane")==null||Window.FindName("EditedBody")==null)throw new Exception("Edited targets/table/preview layout missing.");
    T("EditedSearchBox").Text="stars only";WaitForSearches();if(G("EditedGrid").Items.Count!=0)throw new Exception("Edited class search did not filter.");T("EditedSearchBox").Text="M31 starless";WaitForSearches();if(G("EditedGrid").Items.Count!=1)throw new Exception("Edited object/class search lost a match.");T("EditedSearchBox").Clear();WaitForSearches();
    foreach(string mode in new[]{"Light","Dark"}){Theme.Apply(Window,mode);PumpPopupLayout();Readable(L("EditedSummary").Foreground,Window.Background,mode+" edited summary");Capture(Path.Combine(output,"AstroArchive_Edited_"+mode+".png"));}
    G("EditedGrid").SelectedIndex=0;WaitPreview(()=>((Image)Window.FindName("EditedPreviewImage")).Source!=null,"Edited inline preview did not decode.");
    EditedProjectsList.SelectedIndex=0;PumpPopupLayout();if(G("EditedGrid").Items.Count!=1)throw new Exception("All projects lost the edited image.");
    G("EditedGrid").SelectedIndex=0;if(!B("EditedFolderButton").IsEnabled||EditedImageProject==null)throw new Exception("All projects cannot act on the selected image's project.");
    // New outputs appear on refresh without entering the capture index.
    File.Copy(repo.EditedPath(project,project.Sources[0].RelativePath),Path.Combine(repo.EditedProjectFolder(project),"M31_10x60s_stars.png"));RefreshEdited(project.Id);if(G("EditedGrid").Items.Count!=2||repo.All().Count!=0)throw new Exception("Editor output discovery altered the capture index.");
    var exposureColumn=G("EditedGrid").Columns.First(c=>c.SortMemberPath=="Metadata.TotalExposure");SortTable("EditedGrid",exposureColumn,false);if(G("EditedGrid").Items.Cast<EditedImage>().First().Metadata.TotalExposure!=600)throw new Exception("Edited exposure sorting was textual rather than numeric.");
    if(G("EditedGrid").Columns.Count(c=>c.Visibility==Visibility.Visible)!=6||G("EditedGrid").Columns.Single(c=>c.SortMemberPath=="FileType").Visibility!=Visibility.Visible||exposureColumn.Visibility!=Visibility.Collapsed)throw new Exception("Edited default headings lack file type or still display total exposure.");
    string gif=Path.Combine(source,"Whirlpol_Galaxy_processing.gif");File.WriteAllBytes(gif,Convert.FromBase64String("R0lGODlhAgACAIEAAP8AAAAAAAAAAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh+QQICgAAACwAAAAAAgACAAAIBgABCAQQEAAh+QQIFAAAACwAAAAAAgACAIEAAP8AAAAAAAAAAAAIBgABCAQQEAA7"));repo.AddEditedImages(new[]{gif},project,null,CancellationToken.None,null);RefreshEdited(project.Id);C("EditedClassFilter").SelectedItem="GIF";PumpPopupLayout();var animation=G("EditedGrid").Items.Cast<EditedImage>().Single();if(animation.FileType!="GIF"||animation.Metadata.Object!="M51"||animation.Metadata.ImageClass!="GIF")throw new Exception("Edited GIF class/filter, file type or fuzzy target binding failed.");C("EditedClassFilter").SelectedIndex=0;var typeColumn=G("EditedGrid").Columns.Single(c=>c.SortMemberPath=="FileType");SortTable("EditedGrid",typeColumn,false);if(G("EditedGrid").Items.Cast<EditedImage>().First().FileType!="GIF")throw new Exception("Edited file types did not sort.");
    cancel=new CancellationTokenSource();SetBusy(true);PumpPopupLayout();var operationPopup=(Popup)Window.FindName("OperationPopup");if(operationProgressWindow==null||!OperationProgressVisible||operationProgressWindow.Owner!=Window||operationPopup.IsOpen||!B("CancelButton").IsVisible||B("EditedAddButton").IsEnabled)throw new Exception("Operation progress/cancel panel did not replace the bottom bar.");
    Window.WindowState=WindowState.Minimized;PumpPopupLayout();SetBusy(true);PumpPopupLayout();if(OperationProgressVisible||operationPopup.IsOpen||cancel.IsCancellationRequested)throw new Exception("Minimising left operation progress visible or cancelled the operation.");
    Window.WindowState=windowState;PumpPopupLayout();if(!OperationProgressVisible||operationPopup.IsOpen||cancel.IsCancellationRequested)throw new Exception("Restoring did not recover active operation progress.");
    Window.Hide();PumpPopupLayout();if(OperationProgressVisible)throw new Exception("Hiding the main window left scan progress visible.");Window.Show();PumpPopupLayout();if(!OperationProgressVisible||cancel.IsCancellationRequested)throw new Exception("Showing the main window lost active scan progress.");
    B("CancelButton").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));if(!cancel.IsCancellationRequested)throw new Exception("Progress Cancel did not cancel the operation.");cancel.Dispose();cancel=null;SetBusy(false);PumpPopupLayout();if(OperationProgressVisible||operationPopup.IsOpen)throw new Exception("Operation panel retained idle space.");
    Window.WindowState=WindowState.Minimized;cancel=new CancellationTokenSource();SetBusy(true);PumpPopupLayout();if(OperationProgressVisible||operationPopup.IsOpen)throw new Exception("An operation started while minimised opened its popup.");cancel.Dispose();cancel=null;SetBusy(false);Window.WindowState=windowState;PumpPopupLayout();if(OperationProgressVisible||operationPopup.IsOpen)throw new Exception("Restoring reopened completed operation progress.");
    repo.EnsureDumpFolder();Directory.CreateDirectory(Path.Combine(repo.DumpFolder,"empty-session"));File.WriteAllText(Path.Combine(repo.DumpFolder,"shotsInfo.json"),"{}");
    ProcessDumpUi();var dumpCheckClock=System.Diagnostics.Stopwatch.StartNew();while(dumpChecking&&dumpCheckClock.Elapsed.TotalSeconds<10){PumpPopupLayout();Thread.Sleep(10);}
    if(dumpChecking||cancel!=null||dumpProgressWindow!=null||OperationProgressVisible)throw new Exception("Dump with only empty folders and metadata did not finish quietly.");
    Window.WindowState=WindowState.Minimized;PumpPopupLayout();OpenDumpProgress();cancel=new CancellationTokenSource();SetBusy(true);latestProgress=new ProgressInfo{Stage="Copying",Text="Dump progress fixture",TotalKnown=true,Total=2,Done=1,ProgressFraction=0.5};LiveTick();PumpPopupLayout();if(dumpProgressWindow.IsVisible||OperationProgressVisible||operationPopup.IsOpen||cancel.IsCancellationRequested)throw new Exception("Dump started while minimised appeared or was cancelled.");Window.WindowState=windowState;PumpPopupLayout();dumpProgressWindow.UpdateLayout();
    if(!dumpProgressWindow.IsVisible||OperationProgressVisible||((Popup)Window.FindName("OperationPopup")).IsOpen||dumpProgressBar.Value!=0.5||!dumpProgressStatus.Text.Contains("Dump progress fixture"))throw new Exception("Dump progress window did not show live progress or duplicated the operation panel.");
    Window.WindowState=WindowState.Minimized;PumpPopupLayout();SetBusy(true);LiveTick();PumpPopupLayout();if(dumpProgressWindow.IsVisible||OperationProgressVisible||operationPopup.IsOpen||cancel.IsCancellationRequested)throw new Exception("Minimising left Dump progress visible or cancelled it.");Window.WindowState=windowState;PumpPopupLayout();if(!dumpProgressWindow.IsVisible||dumpProgressBar.Value!=0.5||cancel.IsCancellationRequested)throw new Exception("Restoring lost active Dump progress.");
    SavePopup((FrameworkElement)dumpProgressWindow.Content,Path.Combine(output,"AstroArchive_Dump_Progress.png"));var dumpWindow=dumpProgressWindow;dumpWindow.Close();if(!cancel.IsCancellationRequested||!dumpWindow.IsVisible)throw new Exception("Closing Dump progress did not wait for safe cancellation.");cancel.Dispose();cancel=null;latestProgress=null;SetBusy(false);if(dumpWindow.IsVisible||dumpProgressWindow!=null)throw new Exception("Dump progress window remained open after finishing.");
    OpenDumpProgress();cancel=new CancellationTokenSource();SetBusy(true);Window.WindowState=WindowState.Minimized;PumpPopupLayout();dumpWindow=dumpProgressWindow;cancel.Dispose();cancel=null;SetBusy(false);Window.WindowState=windowState;PumpPopupLayout();if(dumpWindow.IsVisible||dumpProgressWindow!=null||OperationProgressVisible||operationPopup.IsOpen)throw new Exception("Restoring reopened finished Dump progress.");
    File.WriteAllText(Path.Combine(output,"edited-smoke.txt"),"PASS Edited projects, image/object/class search, acquisition metadata, editor output refresh, light/dark display, active-only operation panel with Cancel, and operation/Dump progress minimising, restoring, background updates and completion.");
   }finally{CancelEditedPreview();if(cancel!=null){cancel.Dispose();cancel=null;}CloseDumpProgress();latestProgress=null;((Popup)Window.FindName("OperationPopup")).IsOpen=false;repo=original;if(temporary!=null)temporary.Dispose();RefreshEdited();GoToPage(page);SetBusy(false);Window.WindowState=windowState;if(Directory.Exists(directory))Directory.Delete(directory,true);if(Directory.Exists(source))Directory.Delete(source,true);}
  }
 }
}
