using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Media;
using System.Windows.Media.Imaging;
namespace AstroArchive {
 public partial class MainUi {
  static bool EditedSmokeHasProjectControl(DependencyObject parent){if(parent is ComboBox)return true;if(parent==null)return false;foreach(object child in LogicalTreeHelper.GetChildren(parent)){var node=child as DependencyObject;if(node!=null&&EditedSmokeHasProjectControl(node))return true;}return false;}
  void SmokeEdited(string output){
   var original=repo;var windowState=Window.WindowState;int page=((TabControl)Window.FindName("MainTabs")).SelectedIndex;string directory=Path.Combine(Path.GetTempPath(),"AstroArchive-edited-ui-"+Guid.NewGuid().ToString("N")),source=directory+"-source";Repository temporary=null;
   try{
    Directory.CreateDirectory(source);string filename="M31_Ha_120x60s_starless.png",path=Path.Combine(source,filename);var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(BitmapSource.Create(2,2,96,96,PixelFormats.Gray8,null,new byte[]{50,100,150,200},2)));using(var stream=File.Create(path))encoder.Save(stream);
    temporary=new Repository(directory);repo=temporary;var project=repo.AddEditedImages(new[]{path},null,"Andromeda edits",CancellationToken.None,null);RefreshEdited(project.Id);WaitForSearches();GoToPage(2);PumpPopupLayout();
    if(Window.FindName("EditedProjectsList")!=null||G("EditedGrid").Items.Count!=1||!B("EditedAddButton").IsEnabled||!B("EditedImportFolderButton").IsEnabled)throw new Exception("Edited gallery or import controls did not render.");
    File.Copy(path,Path.Combine(source,"renamed-copy.png"));string revisionFolder=Path.Combine(source,"revision");Directory.CreateDirectory(revisionFolder);var revisionEncoder=new PngBitmapEncoder();revisionEncoder.Frames.Add(BitmapFrame.Create(BitmapSource.Create(2,2,96,96,PixelFormats.Gray8,null,new byte[]{60,110,160,210},2)));using(var stream=File.Create(Path.Combine(revisionFolder,filename)))revisionEncoder.Save(stream);
    var duplicateReview=repo.ScanEditedFolder(source,true,CancellationToken.None,null);if(duplicateReview.Images.Count(i=>i.Status=="Duplicate")!=2||duplicateReview.Images.Count(i=>i.Status=="New version (same name)")!=1)throw new Exception("Edited review did not distinguish copies from a changed same-name image.");
    var reviewTable=EditedImportReviewTable(duplicateReview);var reviewDialog=new FormWindow(Window,"Edited duplicate review",1000,600);reviewDialog.Add(reviewTable);reviewDialog.CloseOnly();reviewDialog.Window.Show();
    try{PumpPopupLayout();foreach(var candidate in duplicateReview.Images){reviewTable.ScrollIntoView(candidate);reviewTable.UpdateLayout();PumpPopupLayout();var check=reviewTable.Columns[0].GetCellContent(candidate) as CheckBox;if(check==null||check.IsEnabled!=candidate.CanInclude||check.IsChecked!=candidate.Include)throw new Exception("Duplicate import choices are editable or a new version cannot be selected.");}SavePopup((FrameworkElement)reviewDialog.Window.Content,Path.Combine(output,"AstroArchive_Edited_Duplicate_Review.png"));}finally{reviewDialog.Window.Close();}
    EditedImportComplete(project.Id,new EditedImportResult{SkippedDuplicates=2});WaitForSearches();PumpPopupLayout();if(!((FrameworkElement)Window.FindName("EditedImportNotice")).IsVisible||!L("EditedImportNoticeText").Text.Contains("2 duplicates skipped"))throw new Exception("Duplicate-only import summary was hidden after progress closed.");Capture(Path.Combine(output,"AstroArchive_Edited_Import_Result.png"));B("DismissEditedImportNotice").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));if(((FrameworkElement)Window.FindName("EditedImportNotice")).IsVisible)throw new Exception("Edited import summary cannot be dismissed.");
    var image=G("EditedGrid").Items.Cast<EditedImage>().Single();G("EditedGrid").SelectedItem=image;PumpPopupLayout();if(!B("EditedPreviewButton").IsEnabled||!B("EditedDetailsButton").IsEnabled||image.Metadata.ImageClass!="Starless"||image.Metadata.TotalExposure!=7200)throw new Exception("Edited selection/acquisition details missing.");
    if(EditedTargets.Items.Count!=2||Window.FindName("EditedPreviewPane")==null||Window.FindName("EditedBody")==null)throw new Exception("Edited targets/table/preview layout missing.");
    T("EditedSearchBox").Text="stars only";WaitForSearches();if(G("EditedGrid").Items.Count!=0)throw new Exception("Edited class search did not filter.");T("EditedSearchBox").Text="M31 starless";WaitForSearches();if(G("EditedGrid").Items.Count!=1)throw new Exception("Edited object/class search lost a match.");T("EditedSearchBox").Clear();WaitForSearches();
    foreach(string mode in new[]{"Light","Dark"}){Theme.Apply(Window,mode);PumpPopupLayout();Readable(L("EditedSummary").Foreground,Window.Background,mode+" edited summary");Capture(Path.Combine(output,"AstroArchive_Edited_"+mode+".png"));}
    G("EditedGrid").SelectedIndex=0;WaitPreview(()=>((Image)Window.FindName("EditedPreviewImage")).Source!=null,"Edited inline preview did not decode.");
    RefreshEdited();WaitForSearches();PumpPopupLayout();if(G("EditedGrid").Items.Count!=1)throw new Exception("Refresh lost the edited image.");
    G("EditedGrid").SelectedIndex=0;if(!B("EditedFolderButton").IsEnabled||EditedImageProject==null)throw new Exception("Gallery cannot open the selected image folder.");
    // New outputs appear on refresh without entering the capture index.
    File.Copy(repo.EditedPath(project,project.Sources[0].RelativePath),Path.Combine(repo.EditedProjectFolder(project),"M31_10x60s_stars.png"));RefreshEdited(project.Id);WaitForSearches();if(G("EditedGrid").Items.Count!=2||repo.All().Count!=0)throw new Exception("Editor output discovery altered the capture index.");
    var exposureColumn=G("EditedGrid").Columns.First(c=>c.SortMemberPath=="Metadata.TotalExposure");SortTable("EditedGrid",exposureColumn,false);WaitForSearches();if(G("EditedGrid").Items.Cast<EditedImage>().First().Metadata.TotalExposure!=600)throw new Exception("Edited exposure sorting was textual rather than numeric.");SmokeEditedRefresh(project,output);
    if(G("EditedGrid").Columns.Count(c=>c.Visibility==Visibility.Visible)!=4||G("EditedGrid").Columns.Single(c=>c.SortMemberPath=="FileType").Visibility!=Visibility.Visible||exposureColumn.Visibility!=Visibility.Collapsed||G("EditedGrid").Columns.Any(c=>c.SortMemberPath=="Metadata.FiltersLabel"))throw new Exception("Edited default headings lack file type or retain the removed filter/hidden exposure columns.");
    string gif=Path.Combine(source,"Whirlpol_Galaxy_processing.gif");File.WriteAllBytes(gif,Convert.FromBase64String("R0lGODlhAgACAIEAAP8AAAAAAAAAAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh+QQICgAAACwAAAAAAgACAAAIBgABCAQQEAAh+QQIFAAAACwAAAAAAgACAIEAAP8AAAAAAAAAAAAIBgABCAQQEAA7"));repo.AddEditedImages(new[]{gif},project,null,CancellationToken.None,null);RefreshEdited(project.Id);WaitForSearches();C("EditedClassFilter").SelectedItem="GIF";PumpPopupLayout();var animation=G("EditedGrid").Items.Cast<EditedImage>().Single();if(animation.FileType!="GIF"||animation.Metadata.Object!="M51"||animation.Metadata.ImageClass!="GIF")throw new Exception("Edited GIF class/filter, file type or fuzzy target binding failed.");C("EditedClassFilter").SelectedIndex=0;var typeColumn=G("EditedGrid").Columns.Single(c=>c.SortMemberPath=="FileType");SortTable("EditedGrid",typeColumn,false);WaitForSearches();if(G("EditedGrid").Items.Cast<EditedImage>().First().FileType!="GIF")throw new Exception("Edited file types did not sort.");
    if(G("EditedGrid").Columns.Any(c=>c.SortMemberPath=="Metadata.ImageClass"||c.SortMemberPath=="Project.Name"))throw new Exception("Edited still offers class/project headings.");
    var plan=repo.ScanEditedFolder(source,false,CancellationToken.None,null);if(plan.Images.Any(i=>i.Include)||plan.Images.Any(i=>i.Status!="Duplicate"))throw new Exception("Existing imports were selected again.");DataGrid review;var galleryReviewDialog=EditedImportDialog(plan,out review);galleryReviewDialog.Window.Show();SmokeImportPreferencesButton(galleryReviewDialog,true);PumpPopupLayout();if(EditedSmokeHasProjectControl(galleryReviewDialog.Window.Content as DependencyObject))throw new Exception("Edited import offers project selection.");SavePopup((FrameworkElement)galleryReviewDialog.Window.Content,Path.Combine(output,"AstroArchive_Edited_Import.png"));galleryReviewDialog.Window.Close();
    string second=Path.Combine(source,"M51_20x60s_Ha.png");var secondEncoder=new PngBitmapEncoder();secondEncoder.Frames.Add(BitmapFrame.Create(BitmapSource.Create(2,2,96,96,PixelFormats.Gray8,null,new byte[]{70,120,170,220},2)));using(var stream=File.Create(second))secondEncoder.Save(stream);var another=repo.AddEditedImages(new[]{second},null,"Old second project",CancellationToken.None,null);RefreshEdited(another.Id);WaitForSearches();if(G("EditedGrid").Items.Count!=4||ActiveEditedImage.Project.Id!=another.Id)throw new Exception("New import hid existing Edited images.");
    G("EditedGrid").SelectedItem=G("EditedGrid").Items.Cast<EditedImage>().First(i=>i.Project.Id==project.Id&&i.Filename==filename);EditedMetadataFields fields;var metadataDialog=EditedMetadataDialog(SelectedEditedImages(),out fields);if(fields.Values().TotalExposure!=null||fields.TotalExposure.Text!="7200")throw new Exception("Metadata editor did not preserve unchanged fields.");metadataDialog.Window.Show();PumpPopupLayout();fields.TotalExposure.Text="3600";fields.Filters.Text="L, Ha";repo.SaveEditedMetadata(project,SelectedEditedImages(),fields.Values(),CancellationToken.None);SavePopup((FrameworkElement)metadataDialog.Window.Content,Path.Combine(output,"AstroArchive_Edited_Metadata.png"));metadataDialog.Window.Close();RefreshEdited();WaitForSearches();if(G("EditedGrid").Items.Count!=4||G("EditedGrid").Items.Cast<EditedImage>().Single(i=>i.Project.Id==project.Id&&i.Filename==filename).Metadata.TotalExposure!=3600||!B("EditedEditButton").IsEnabled)throw new Exception("Saved metadata or combined gallery did not survive refresh.");
    tableSorts["EditedGrid"].Clear();RefreshEdited();WaitForSearches();var defaultRows=G("EditedGrid").Items.Cast<EditedImage>().ToArray();if(defaultRows.Last().FileType!="GIF")throw new Exception("Default Edited ordering did not put GIFs last.");
    var deletedRows=defaultRows.Where(i=>i.Kind=="Editor output"||i.Project.Id==another.Id).ToList();G("EditedGrid").SelectedItems.Clear();foreach(var row in deletedRows)G("EditedGrid").SelectedItems.Add(row);var fileMenu=ThemedMenu();BuildEditedFileMenu(fileMenu,SelectedEditedImages());
    var deleteItem=fileMenu.Items.OfType<MenuItem>().Single(i=>Convert.ToString(i.Header)=="Delete files…");if(deletedRows.Count!=2||!deleteItem.IsEnabled||!Convert.ToString(((MenuItem)fileMenu.Items[0]).Header).StartsWith("2 selected")||((SolidColorBrush)deleteItem.Foreground).Color!=Color.FromRgb(183,40,51)||fileMenu.Items.OfType<MenuItem>().Single(i=>Convert.ToString(i.Header)=="Preview image…").IsEnabled)throw new Exception("Edited multi-selection deletion menu is missing or unsafe.");
    var deletionDialog=EditedDeletionDialog(deletedRows);deletionDialog.Window.Show();PumpPopupLayout();SavePopup((FrameworkElement)deletionDialog.Window.Content,Path.Combine(output,"AstroArchive_Edited_Delete.png"));deletionDialog.Window.Close();if(deletedRows.Any(i=>!File.Exists(repo.EditedPath(i.Project,i.RelativePath))))throw new Exception("Closing deletion review deleted a file.");
    CancelEditedPreview();var deletion=repo.DeleteEditedImages(deletedRows,CancellationToken.None,null);RefreshEdited();WaitForSearches();if(deletion.Deleted!=2||deletion.Errors.Count!=0||G("EditedGrid").Items.Count!=2||SelectedEditedImages().Count!=0||!File.Exists(path)||!File.Exists(second)||repo.All().Count!=0)throw new Exception("Edited deletion did not refresh selection or preserve source originals.");
    cancel=new CancellationTokenSource();SetBusy(true);PumpPopupLayout();var operationPopup=(Popup)Window.FindName("OperationPopup");if(OperationProgressVisible||operationPopup.IsOpen||B("EditedAddButton").IsEnabled)throw new Exception("Background work opened an operation window or enabled conflicting imports.");
    Window.WindowState=WindowState.Minimized;PumpPopupLayout();if(cancel.IsCancellationRequested)throw new Exception("Minimising canceled background work.");Window.WindowState=windowState;PumpPopupLayout();if(OperationProgressVisible||operationPopup.IsOpen||cancel.IsCancellationRequested)throw new Exception("Restore opened a progress window or canceled work.");
    B("CancelButton").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));if(!cancel.IsCancellationRequested)throw new Exception("Cancel did not cancel the operation.");cancel.Dispose();cancel=null;SetBusy(false);
    repo.EnsureDumpFolder();Directory.CreateDirectory(Path.Combine(repo.DumpFolder,"empty-session"));File.WriteAllText(Path.Combine(repo.DumpFolder,"shotsInfo.json"),"{}");
    ProcessDumpUi();var dumpCheckClock=System.Diagnostics.Stopwatch.StartNew();while(dumpChecking&&dumpCheckClock.Elapsed.TotalSeconds<10){PumpPopupLayout();Thread.Sleep(10);}
    if(dumpChecking||cancel!=null||OperationProgressVisible)throw new Exception("Empty Dump did not finish quietly.");
    File.WriteAllText(Path.Combine(output,"edited-smoke.txt"),"PASS Combined Edited gallery, additive duplicate review, saved metadata, image/object/class search, acquisition metadata, editor output refresh, default GIF-last ordering and explicit column sorting, multi-selection deletion menu and review, deletion refresh with source originals preserved, light/dark display, active-only operation panel with Cancel, and operation/Dump progress minimising, restoring, background updates and completion.");
   }finally{CancelEditedPreview();if(cancel!=null){cancel.Dispose();cancel=null;}CloseDumpProgress();latestProgress=null;((Popup)Window.FindName("OperationPopup")).IsOpen=false;repo=original;if(temporary!=null)temporary.Dispose();RefreshEdited();WaitForSearches();GoToPage(page);SetBusy(false);Window.WindowState=windowState;if(Directory.Exists(directory))Directory.Delete(directory,true);if(Directory.Exists(source))Directory.Delete(source,true);}
  }
 }
}
