using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
namespace AstroArchive {
 public partial class Tests {
  static void EditedRegressions(){
   Test("Repeated Edited imports add checked images and preserve unchecked existing images",()=>{
    string source=Path.Combine(root,"edited-repeat-source"),old=Path.Combine(source,"M31_starless.fit"),fresh=Path.Combine(source,"M51_stars.fit"),excluded=Path.Combine(source,"Moon.fit");Write(old,64,48,(x,y)=>1300,new Dictionary<string,string>());
    using(var repo=new Repository(Path.Combine(root,"edited-repeat-repo"))){var first=repo.ImportEditedFolder(repo.ScanEditedFolder(source,true,ct,NoProgress),"Older import",ct,NoProgress);string saved=repo.EditedPath(first,first.Sources.Single().RelativePath),manifest=Path.Combine(repo.EditedProjectFolder(first),"edited-project.json"),before=File.ReadAllText(manifest),hash=Util.Hash(saved,ct);
     Write(fresh,64,48,(x,y)=>2100,new Dictionary<string,string>());Write(excluded,64,48,(x,y)=>2500,new Dictionary<string,string>());var plan=repo.ScanEditedFolder(source,true,ct,NoProgress);Check(plan.Images.Single(i=>i.Path==old).AlreadyImported&&!plan.Images.Single(i=>i.Path==old).Include,"Existing duplicate was checked by default");plan.Images.Single(i=>i.Path==excluded).Include=false;var added=repo.ImportEditedFolder(plan,"New import",ct,NoProgress);List<string> errors;var projects=repo.EditedProjects(out errors);Check(projects.SelectMany(p=>repo.EditedImages(p)).Count()==2&&repo.EditedImages(added).Single().Filename=="M51_stars.fit"&&File.ReadAllText(manifest)==before&&Util.Hash(saved,ct)==hash&&File.Exists(excluded),"Import hid/deleted an old file or imported unchecked files");
     var none=repo.ScanEditedFolder(source,true,ct,NoProgress);foreach(var row in none.Images)row.Include=false;Expect(()=>repo.ImportEditedFolder(none,"Empty",ct,NoProgress),"Unchecked-only import succeeded");Check(repo.EditedProjects(out errors).Count==2&&Util.Hash(saved,ct)==hash,"Unchecked-only import touched existing images");
     plan=repo.ScanEditedFolder(source,true,ct,NoProgress);foreach(var row in plan.Images)row.Include=row.Path==old;repo.ImportEditedFolder(plan,"Explicit duplicate",ct,NoProgress);Check(repo.EditedProjects(out errors).SelectMany(p=>repo.EditedImages(p)).Count()==3&&Util.Hash(saved,ct)==hash,"Explicit duplicate overwrote an existing image");
     plan=repo.ScanEditedFolder(source,true,ct,NoProgress);foreach(var row in plan.Images)row.Include=row.Path==excluded;File.AppendAllText(excluded,"changed");Expect(()=>repo.ImportEditedFolder(plan,"Failed",ct,NoProgress),"Stale new import accepted");Check(repo.EditedProjects(out errors).Count==3&&File.ReadAllText(manifest)==before,"Failed new import removed earlier images");
    }
   });
   Test("Duplicate review hashes current editor outputs and still matches GIF metadata from unchecked images",()=>{
    string source=Path.Combine(root,"edited-current-source"),original=Path.Combine(source,"finish.fit"),gif=Path.Combine(source,"finish_processing.gif");Write(original,64,48,(x,y)=>1500,new Dictionary<string,string>{{"OBJECT","'M31'"},{"NCOMBINE","'40'"},{"SUBEXP","'60'"}});
    using(var repo=new Repository(Path.Combine(root,"edited-current-repo"))){var project=repo.AddEditedImages(new[]{original},null,"Current",ct,NoProgress);string saved=repo.EditedPath(project,project.Sources.Single().RelativePath);File.WriteAllBytes(gif,Convert.FromBase64String("R0lGODlhAgACAIEAAP8AAAAAAAAAAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh+QQICgAAACwAAAAAAgACAAAIBgABCAQQEAAh+QQIFAAAACwAAAAAAgACAIEAAP8AAAAAAAAAAAAIBgABCAQQEAA7"));var plan=repo.ScanEditedFolder(source,true,ct,NoProgress);Check(!plan.Images.Single(i=>i.Path==original).Include&&plan.Images.Single(i=>i.Path==gif).Metadata.TotalExposure==2400,"Unchecked still lost GIF association");
     Write(saved,64,48,(x,y)=>2800,new Dictionary<string,string>());string renamed=Path.Combine(source,"renamed.fit");File.Copy(saved,renamed);string output=Path.Combine(Path.GetDirectoryName(saved),"M51_stars.fit");Write(output,64,48,(x,y)=>3200,new Dictionary<string,string>());string copy=Path.Combine(source,"output_renamed.fit");File.Copy(output,copy);plan=repo.ScanEditedFolder(source,true,ct,NoProgress);Check(plan.Images.Single(i=>i.Path==original).Include&&!plan.Images.Single(i=>i.Path==renamed).Include&&!plan.Images.Single(i=>i.Path==copy).Include,"Review used stale hashes or missed an editor output");Check(Util.Hash(saved,ct)==Util.Hash(renamed,ct)&&repo.All().Count==0,"Review mutated editor files");
    }
   });
   Test("Edited metadata assignments persist as patches without changing images or inferred fields",()=>{
    string source=Path.Combine(root,"edited-metadata-source"),file=Path.Combine(source,"M31_10x60s_Ha_starless.fit"),directory=Path.Combine(root,"edited-metadata-repo"),moved=directory+"-moved";Write(file,64,48,(x,y)=>2000,new Dictionary<string,string>());string id;
    using(var repo=new Repository(directory)){var project=repo.AddEditedImages(new[]{file},null,"Metadata",ct,NoProgress);id=project.Id;var row=repo.EditedImages(project).Single();string saved=repo.EditedPath(project,row.RelativePath),hash=Util.Hash(saved,ct);repo.SaveEditedMetadata(project,new[]{row},new EditedMetadata{Object="C20",TotalExposure=1800,Filters="L, Ha",Subs=30,RA="12:30:00",Dec="+40:00:00"},ct);List<string> errors;project=repo.EditedProjects(out errors).Single();row=repo.EditedImages(project).Single();Check(row.Metadata.Object=="NGC7000"&&row.Metadata.TotalExposure==1800&&row.Metadata.Subs==30&&row.Metadata.SubExposure==60&&row.Metadata.ImageClass=="Starless"&&row.Metadata.RA=="12:30:00","Manual assignments or unchanged fields lost");Check(Util.Hash(saved,ct)==hash&&Util.Hash(file,ct)==hash&&project.Sources.Single().Metadata.TotalExposure==600&&repo.All().Count==0,"Metadata save changed pixels/source provenance/index");
     repo.SaveEditedMetadata(project,new[]{row},new EditedMetadata{ImageClass="Stars only"},ct);Write(saved,64,48,(x,y)=>2300,new Dictionary<string,string>{{"SUBEXP","'90'"},{"NCOMBINE","'20'"}});string output=Path.Combine(Path.GetDirectoryName(saved),"M51_starless.fit");Write(output,64,48,(x,y)=>3100,new Dictionary<string,string>());project=repo.EditedProjects(out errors).Single();var outputRow=repo.EditedImages(project).Single(i=>i.Filename=="M51_starless.fit");repo.SaveEditedMetadata(project,new[]{outputRow},new EditedMetadata{TotalExposure=4200},ct);project=repo.EditedProjects(out errors).Single();row=repo.EditedImages(project).Single(i=>i.RelativePath==row.RelativePath);Check(row.Metadata.SubExposure==90&&row.Metadata.ImageClass=="Stars only"&&row.Metadata.TotalExposure==1800&&row.Metadata.Filters=="L, Ha","Patch froze inferred fields or lost an earlier assignment");
    }
    Directory.Move(directory,moved);using(var repo=new Repository(moved)){List<string> errors;var project=repo.EditedProjects(out errors).Single();var images=repo.EditedImages(project);Check(project.Id==id&&images.Single(i=>i.Filename=="M51_starless.fit").Metadata.TotalExposure==4200&&images.Single(i=>i.Filename!= "M51_starless.fit").Metadata.Object=="NGC7000","Moved repository lost saved metadata");}
   });
   Test("Batch Edited metadata preserves per-image fields and GIF overrides survive matching",()=>{
    string source=Path.Combine(root,"edited-metadata-batch-source"),one=Path.Combine(source,"M31_10x60s_Ha_starless.fit"),two=Path.Combine(source,"M51_20x90s_OIII_stars.fit");Write(one,64,48,(x,y)=>2000,new Dictionary<string,string>());Write(two,64,48,(x,y)=>3000,new Dictionary<string,string>());
    using(var repo=new Repository(Path.Combine(root,"edited-metadata-batch-repo"))){var project=repo.AddEditedImages(new[]{one,two},null,"Batch",ct,NoProgress);var images=repo.EditedImages(project);repo.SaveEditedMetadata(project,images,new EditedMetadata{RA="12:00:00"},ct);List<string> errors;project=repo.EditedProjects(out errors).Single();images=repo.EditedImages(project);Check(images.Single(i=>i.Filename==Path.GetFileName(one)).Metadata.TotalExposure==600&&images.Single(i=>i.Filename==Path.GetFileName(two)).Metadata.TotalExposure==1800&&images.All(i=>i.Metadata.RA=="12:00:00"),"Batch assignment replaced distinct inferred fields");
     string gif=Path.Combine(Path.GetDirectoryName(repo.EditedPath(project,images.First().RelativePath)),"M31_10x60s_Ha_starless_processing.gif");File.WriteAllBytes(gif,Convert.FromBase64String("R0lGODlhAgACAIEAAP8AAAAAAAAAAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh+QQICgAAACwAAAAAAgACAAAIBgABCAQQEAAh+QQIFAAAACwAAAAAAgACAIEAAP8AAAAAAAAAAAAIBgABCAQQEAA7"));var gifRow=repo.EditedImages(project).Single(i=>MediaFiles.Gif(i.RelativePath));Check(gifRow.RelatedImage!=null&&gifRow.Metadata.TotalExposure==600,"New GIF did not inherit still data");repo.SaveEditedMetadata(project,new[]{gifRow},new EditedMetadata{TotalExposure=3000,Filters="RGB"},ct);project=repo.EditedProjects(out errors).Single();gifRow=repo.EditedImages(project).Single(i=>MediaFiles.Gif(i.RelativePath));Check(gifRow.RelatedImage!=null&&gifRow.Metadata.TotalExposure==3000&&gifRow.Metadata.Filters=="RGB"&&gifRow.Metadata.RA=="12:00:00","GIF matching discarded own assignments or inherited still edits");
    }
   });
   Test("Edited metadata validates values and paths and preserves Meteor identity rules",()=>{
    string source=Path.Combine(root,"edited-metadata-invalid-source"),file=Path.Combine(source,"M31_meteor.fit");Write(file,64,48,(x,y)=>2200,new Dictionary<string,string>());
    using(var repo=new Repository(Path.Combine(root,"edited-metadata-invalid-repo"))){var project=repo.AddEditedImages(new[]{file},null,"Validation",ct,NoProgress);var row=repo.EditedImages(project).Single();string manifest=Path.Combine(repo.EditedProjectFolder(project),"edited-project.json"),before=File.ReadAllText(manifest);foreach(double invalid in new[]{0.0,-1,double.NaN,double.PositiveInfinity})Expect(()=>repo.SaveEditedMetadata(project,new[]{row},new EditedMetadata{TotalExposure=invalid},ct),"Invalid exposure accepted");Expect(()=>repo.SaveEditedMetadata(project,new[]{row},new EditedMetadata{Subs=-1},ct),"Invalid subs accepted");Expect(()=>repo.SaveEditedMetadata(project,new[]{row},new EditedMetadata{ImageClass="unsupported"},ct),"Invalid class accepted");Expect(()=>repo.SaveEditedMetadata(project,new[]{new EditedImage{RelativePath="../escape.fit"}},new EditedMetadata{Filters="Ha"},ct),"Traversal metadata path accepted");using(var cancelled=new CancellationTokenSource()){cancelled.Cancel();Expect(()=>repo.SaveEditedMetadata(project,new[]{row},new EditedMetadata{Filters="L"},cancelled.Token),"Cancelled metadata save accepted");}Check(File.ReadAllText(manifest)==before,"Rejected edit changed saved metadata");repo.SaveEditedMetadata(project,new[]{row},new EditedMetadata{Object="M51",ImageClass="Stars only",TotalExposure=100},ct);List<string> errors;project=repo.EditedProjects(out errors).Single();row=repo.EditedImages(project).Single();Check(row.Metadata.Object==null&&row.Metadata.ImageClass=="Meteor"&&row.Metadata.TotalExposure==100,"Manual edit restored a Meteor object ID");project.MetadataEdits["../../escape.fit"]=new EditedMetadata{Filters="L"};File.WriteAllText(manifest,Util.Serialize(project));Check(repo.EditedProjects(out errors).Count==0&&errors.Count==1,"Forged metadata override path accepted");}
   });
   Test("GIF import uniquely matches nearby edited images and preserves acquisition details",()=>{
    string source=Path.Combine(root,"gif-source"),still=Path.Combine(source,"finish.fit"),gif=Path.Combine(source,"finish_processing.gif");
    Write(still,64,48,(x,y)=>2000,new Dictionary<string,string>{{"OBJECT","'M31'"},{"NCOMBINE","'40'"},{"SUBEXP","'60'"},{"FILTER","'Ha'"}});
    File.WriteAllBytes(gif,Convert.FromBase64String("R0lGODlhAgACAIEAAP8AAAAAAAAAAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh+QQICgAAACwAAAAAAgACAAAIBgABCAQQEAAh+QQIFAAAACwAAAAAAgACAIEAAP8AAAAAAAAAAAAIBgABCAQQEAA7"));
    Check(Assets.Supported(gif)&&Assets.Inspect(gif).Format=="GIF"&&Assets.Inspect(gif).Header.Width==2,"GIF import unsupported or canvas incorrect");
    using(var repo=new Repository(Path.Combine(root,"gif-repo"))){var plan=repo.ScanEditedFolder(source,true,ct,NoProgress);var review=plan.Images.Single(i=>MediaFiles.Gif(i.Path));Check(review.Include&&review.Metadata.Object=="M31"&&review.Metadata.TotalExposure==2400&&review.Metadata.Subs==40,"GIF review lost matching acquisition data");var project=repo.ImportEditedFolder(plan,"Processing",ct,NoProgress);var image=repo.EditedImages(project).Single(i=>MediaFiles.Gif(i.RelativePath));Check(image.RelatedImage!=null&&image.Metadata.TotalExposure==2400&&image.Metadata.Filters=="Ha","Imported GIF lost its association");}
    Check(MediaFiles.MatchingImage("finish_processing.gif",new[]{"finish.fit","finish.png"})==null,"Ambiguous GIF guessed a source");Check(MediaFiles.MatchingImage("finish.gif",new[]{"nested/finish.fit"})==null,"GIF matched another folder");Check(MediaFiles.MatchingImage("FINISH.gif",new[]{"finish.fit"})=="finish.fit","Case-insensitive exact match missing");
    var mismatch=new FitsHeader();mismatch.Values["OBJECT"]="M51";Check(!EditedMetadata.Read("finish.gif",mismatch,EditedMetadata.Read("M31_40x60s.fit",null)).TotalExposure.HasValue,"Conflicting GIF metadata inherited exposure");
   });
   Test("Moon and Lunar share one target in old archives edited metadata and filenames",()=>{
    var old=Util.Deserialize<Frame>("{\"Target\":\"Lunar\"}");Check(old.Target=="Moon"&&Catalog.TargetFromFilename("Lunar_001.fit")=="Moon"&&EditedMetadata.Read("Lunar_starless.fit",null).Object=="Moon","Lunar alias remained separate");var targets=TargetNavigation.Build(new[]{old,new Frame{Target="Moon"}});Check(targets.Count==2&&targets.Single(t=>t.Name=="Moon").Files==2,"Moon and Lunar did not merge");
   });
   Test("Subframe summaries separate targets sessions devices and unknown acquisition dates",()=>{
    var a=new Frame{Kind="Light",Target="M31",Session="night1",Telescope="Scope1",Camera="Tele",Exposure=60,Filter="Ha"};var b=a.Clone();b.Exposure=null;
    var stack=a.Clone();stack.Kind="Stack";stack.Exposure=9999;var target=a.Clone();target.Target="M51";var session=a.Clone();session.Session="night2";var device=a.Clone();device.Telescope="Scope2";
    var groups=SubframeSessions.Build(new[]{a,b,stack,target,session,device});Check(groups.Count==1&&groups[0].Frames.Count==2&&groups[0].Label.Contains("1 exposure unknown")&&!groups[0].Expanded,"Subframe totals or collapsed state incorrect");
    a.Session=null;b.Session=null;a.SourcePath="capture/a.fit";b.SourcePath="capture/b.fit";Check(SubframeSessions.Build(new[]{a,b}).Count==0,"Unknown sessions were guessed");a.AcquisitionDate="2026-10-08";b.AcquisitionDate="2026-10-09";Check(SubframeSessions.Build(new[]{a,b}).Count==0,"Different nights were combined by parent folder");
   });
   Test("Edited filename classes distinguish starless and stars only without guessing star fields",()=>{
    Check(EditedMetadata.Read("M31_starless_120x60s_Ha.fit",null).ImageClass=="Starless","Starless filename missed");Check(EditedMetadata.Read("M31_stars-only.tif",null).ImageClass=="Stars only","Stars-only filename missed");Check(EditedMetadata.Read("M31_stars.fit",null).ImageClass=="Stars only","Stars layer missed");Check(EditedMetadata.Read("M31_starfield.fits",null).ImageClass=="Edited image","Star field misclassified");Check(EditedMetadata.Read("M31_starless_stars.fit",null).ImageClass.Contains("conflicting"),"Conflicting class invented");
   });
   Test("Meteor filename labels clear catalogue identity in existing archives and edited images",()=>{
    foreach(string filename in new[]{"M31_meteor.fit","Light_M51_METEOR_001.fits","meteor.png"}){
     var frame=Util.Deserialize<Frame>("{\"Target\":\"M31\",\"OriginalName\":\""+filename+"\"}");Check(frame.Target=="Meteor"&&frame.TargetName=="Meteor"&&frame.ObjectId==""&&TargetNavigation.Group(frame.Target)=="Meteors","Existing meteor retained its object ID");
     var header=new FitsHeader();header.Values["OBJECT"]="M51";header.Values["TOTEXP"]="120";var metadata=EditedMetadata.Read(filename,header,new EditedMetadata{Object="M31",Subs=2,SubExposure=60});Check(metadata.ImageClass=="Meteor"&&metadata.Object==null&&metadata.ObjectLabel=="Meteor"&&metadata.TotalExposure==120,"Meteor inherited or retained object identity");
    }
    Check(!Util.MeteorFilename("meteorite_M31.fit")&&!Util.MeteorFilename(Path.Combine("meteor","M31.fit")),"Partial word or directory classified as Meteor");
    string source=Path.Combine(root,"meteor-label-source"),file=Path.Combine(source,"Light_M31_meteor.fit");Write(file,64,48,(x,y)=>1700,LightHeaders(new DateTime(2026,10,8,21,0,0),"M51"));var classified=Classifier.Read(file,source,"Scope-1","Auto");Check(classified.Target=="Meteor"&&classified.ObjectId==""&&classified.TargetEvidence.Contains("Meteor"),"Import metadata overrode Meteor");
    using(var repo=new Repository(Path.Combine(root,"meteor-label-repo"))){repo.Import(repo.Scan(source,"Scope-1","Auto",ct,NoProgress).Frames,ct,NoProgress);var project=repo.CreateEditedWorkingCopy(repo.All().Single(),"Meteor edit","Other editor",ct,NoProgress);Check(project.Sources.Single().Metadata.Object==null&&repo.EditedImages(project).Single().Metadata.ImageClass=="Meteor","Working copy restored a Meteor object ID");}
   });
   Test("Edited filename products recover objects filters subs and total exposure including mixed durations",()=>{
    var metadata=EditedMetadata.Read("M31_120x60s_Ha_starless.fit",null);Check(metadata.Object=="M31"&&metadata.Filters=="Ha"&&metadata.Subs==120&&metadata.SubExposure==60&&metadata.TotalExposure==7200,"Filename acquisition data wrong");
    metadata=EditedMetadata.Read("NGC7000_Ha_20x5min_OIII_40x180s_stars.tif",null);Check(metadata.Subs==60&&metadata.SubExposure==null&&metadata.TotalExposure==13200&&metadata.Filters=="Ha, OIII","Mixed durations combined incorrectly");Check(EditedMetadata.Read("M51_subs120_total2h.fit",null).TotalExposure==7200,"Labelled total missed");Check(EditedMetadata.Read("M31_20261008_starless.fit",null).TotalExposure==null,"Calendar date invented exposure");
   });
   Test("Explicit edited metadata wins and ambiguous exposure is retained without inventing a total",()=>{
    var header=new FitsHeader();header.Values["OBJECT"]="M51";header.Values["FILTER"]="L";header.Values["NCOMBINE"]="50";header.Values["EXPTIME"]="120";
    var result=EditedMetadata.Read("M31_starless.fit",header);Check(result.Object=="M51"&&result.Subs==50&&result.ReportedExposure==120&&result.TotalExposure==null&&result.SubExposure==null,"Ambiguous EXPTIME multiplied");header.Values["SUBEXP"]="120";result=EditedMetadata.Read("M51_starless.fit",header);Check(result.TotalExposure==6000,"Explicit per-sub duration lost");header.Values.Remove("SUBEXP");header.Comments["EXPTIME"]="Total integrated exposure (s)";Check(EditedMetadata.Read("M51.fit",header).TotalExposure==120,"Explicit total comment ignored");
    header.Values["TOTEXP"]="6000";result=EditedMetadata.Read("M51_40x60s.fit",header);Check(result.TotalExposure==6000&&result.Subs==50&&result.SubExposure==null&&result.Evidence.Contains("disagrees"),"Conflicting filename overwritten metadata");
   });
   Test("Unknown edited acquisition data stays unknown and malformed numeric fields are refused",()=>{
    var header=new FitsHeader();header.Values["TOTEXP"]="NaN";header.Values["NCOMBINE"]="-2";header.Values["SUBEXP"]="Infinity";var result=EditedMetadata.Read("holiday_starless.tif",header);Check(result.Object==null&&result.Subs==null&&result.TotalExposure==null&&result.SubExposure==null,"Invalid metadata invented numbers");Check(EditedMetadata.Read("M31_M51_stars.fit",null).Object==null,"Ambiguous target guessed");
   });
   Test("Siril handoff automatically creates a portable independent Edited working copy",()=>{
    string source=Path.Combine(root,"edited-siril-source");var header=LightHeaders(new DateTime(2026,10,8,21,0,0),"M51");header["NCOMBINE"]="12";header["SUBEXP"]="60";string file=Path.Combine(source,"Stacked_M51.fit");Write(file,64,48,(x,y)=>1700,header);string app=Path.Combine(root,"siril.exe");File.WriteAllText(app,"fixture");
    using(var repo=new Repository(Path.Combine(root,"edited-siril-repo"))){repo.Import(repo.Scan(source,"Scope-1","Auto",ct,NoProgress).Frames,ct,NoProgress);var capture=repo.All().Single();var project=SirilHandoff.CreateWorkingCopy(repo,new List<Frame>{capture},"Whirlpool edit",app,ct,NoProgress);List<string> errors;Check(repo.EditedProjects(out errors).Single().Id==project.Id&&errors.Count==0,"Working copy not registered");string image=repo.EditedPath(project,project.Sources[0].RelativePath);Check(Util.Hash(image,ct)==capture.Hash&&SirilHandoff.LaunchInfo(app,image).WorkingDirectory==Path.GetDirectoryName(image),"Editor got wrong working copy");
     File.AppendAllText(image,"editor update");Check(Util.Hash(repo.FilePath(capture),ct)==capture.Hash&&Util.Hash(file,ct)==capture.Hash,"Editing changed archived/original pixels");string output=Path.Combine(Path.GetDirectoryName(image),"M51_starless.fits");Write(output,64,48,(x,y)=>2300,new Dictionary<string,string>());var row=repo.EditedImages(project).Single(i=>i.Filename=="M51_starless.fits");Check(row.Kind=="Editor output"&&row.Metadata.ImageClass=="Starless"&&row.Metadata.TotalExposure==720,"Output lost working-copy acquisition provenance");
     repo.Scan(repo.Root,"Scope-1","Auto",ct,NoProgress,true);Check(repo.All().Count==1,"Reindex imported mutable editor images");repo.ResetArchive(ct,NoProgress);Check(File.Exists(output)&&repo.EditedProjects(out errors).Count==1,"Archive reset deleted Edited project");
    }
   });
   Test("Multiple archived selections create independent working copies for other editors",()=>{
    string source=Path.Combine(root,"edited-multiple-source");Write(Path.Combine(source,"M31_10x60s_Ha.fit"),64,48,(x,y)=>1900,LightHeaders(new DateTime(2026,10,8,21,0,0),"M31"));Write(Path.Combine(source,"M51_20x60s_OIII.fit"),64,48,(x,y)=>2300,LightHeaders(new DateTime(2026,10,8,21,0,0),"M51"));
    using(var repo=new Repository(Path.Combine(root,"edited-multiple-repo"))){repo.Import(repo.Scan(source,"Scope-1","Auto",ct,NoProgress).Frames,ct,NoProgress);var project=repo.CreateEditedWorkingCopies(repo.All(),"Manual editor","Other editor",ct,NoProgress);Check(project.Sources.Count==2&&project.Sources.All(s=>Util.Hash(repo.EditedPath(project,s.RelativePath),ct)==s.ArchiveHash),"Selection was not copied and verified");string output=Path.Combine(repo.EditedProjectFolder(project),"unnamed_starless.fit");Write(output,64,48,(x,y)=>1200,new Dictionary<string,string>());Check(repo.EditedImages(project).Single(i=>i.Filename=="unnamed_starless.fit").Metadata.TotalExposure==null,"Unrelated multi-input output inherited a guessed exposure");}
   });
   Test("Invalid Siril handoffs create no Edited project",()=>{
    using(var repo=new Repository(Path.Combine(root,"edited-invalid-app-repo"))){string app=Path.Combine(root,"fake-siril.exe");File.WriteAllText(app,"invalid build");Expect(()=>SirilHandoff.CreateWorkingCopy(repo,new List<Frame>{new Frame{Kind="Stack",OriginalName="stack.fit"}},"Must not exist",app,ct,NoProgress),"Invalid editor accepted");Check(!Directory.Exists(repo.EditedFolder),"Invalid editor created a project");}
   });
   Test("Adding edited images preserves filename collisions and survives repository moves",()=>{
    string source=Path.Combine(root,"edited-add-source");string one=Path.Combine(source,"one","M31_starless.fit"),two=Path.Combine(source,"two","M31_starless.fit");Write(one,64,48,(x,y)=>1400,new Dictionary<string,string>());Write(two,64,48,(x,y)=>2200,new Dictionary<string,string>());string destination=Path.Combine(root,"edited-add-repo"),moved=destination+"-moved";
    using(var repo=new Repository(destination)){var project=repo.AddEditedImages(new[]{one,two},null,"Andromeda",ct,NoProgress);Check(repo.EditedImages(project).Count==2&&project.Sources.Select(s=>s.RelativePath).Distinct().Count()==2,"Collision overwrote an image");Check(project.Sources.Select(s=>Util.Hash(repo.EditedPath(project,s.RelativePath),ct)).OrderBy(h=>h).SequenceEqual(new[]{Util.Hash(one,ct),Util.Hash(two,ct)}.OrderBy(h=>h)),"Copies lost bytes");Check(repo.All().Count==0,"Edited images entered capture index");}
    Directory.Move(destination,moved);using(var repo=new Repository(moved)){List<string> errors;Check(repo.EditedImages(repo.EditedProjects(out errors).Single()).Count==2,"Moving repository lost Edited images");}
   });
   Test("Folder crawl reviews nested metadata and unreadable images before verified copying",()=>{
    string source=Path.Combine(root,"edited-folder-source");Write(Path.Combine(source,"M31_10x60s_Ha_starless.fit"),64,48,(x,y)=>1900,new Dictionary<string,string>());Write(Path.Combine(source,"nested","M31_10x60s_Ha_stars.fit"),64,48,(x,y)=>2400,new Dictionary<string,string>());File.WriteAllText(Path.Combine(source,"broken.fit"),"not FITS");File.WriteAllText(Path.Combine(source,"notes.txt"),"retain");
    using(var repo=new Repository(Path.Combine(root,"edited-folder-repo"))){var top=repo.ScanEditedFolder(source,false,ct,NoProgress);Check(top.Images.Count==2,"Non-recursive scan entered a subfolder");var plan=repo.ScanEditedFolder(source,true,ct,NoProgress);Check(plan.Images.Count==3&&plan.Images.Count(i=>i.Include)==2&&plan.Images.Single(i=>i.Filename=="broken.fit").Problem!=null,"Unreadable images were not isolated");Check(!Directory.Exists(repo.EditedFolder),"Review copied images");var project=repo.ImportEditedFolder(plan,"Existing edits",ct,NoProgress);var images=repo.EditedImages(project);Check(images.Count==2&&images.All(i=>i.Metadata.Subs==10&&i.Metadata.TotalExposure==600)&&project.Sources.Any(s=>s.RelativePath.Contains("nested")),"Folder structure or metadata lost");Check(Directory.GetFiles(source,"*.fit",SearchOption.AllDirectories).Length==3&&repo.All().Count==0,"Crawl altered sources or original index");}
   });
   Test("Folder import refuses changed sources and removes its unpublished project",()=>{
    string source=Path.Combine(root,"edited-stale-source"),file=Path.Combine(source,"M31_starless.fit");Write(file,64,48,(x,y)=>1800,new Dictionary<string,string>());using(var repo=new Repository(Path.Combine(root,"edited-stale-repo"))){var plan=repo.ScanEditedFolder(source,true,ct,NoProgress);File.AppendAllText(file,"changed");Expect(()=>repo.ImportEditedFolder(plan,"Stale",ct,NoProgress),"Changed source accepted");List<string> errors;Check(repo.EditedProjects(out errors).Count==0&&errors.Count==0&&!Directory.EnumerateDirectories(repo.EditedFolder).Any(),"Changed import left a partial project");}
   });
   Test("Edited parent-folder crawl skips repository database trees and archived copies by content",()=>{
    string parent=Path.Combine(root,"edited-mixed-parent"),source=Path.Combine(parent,"captures"),file=Path.Combine(source,"Light_M31.fit");Write(file,64,48,(x,y)=>1000,LightHeaders(new DateTime(2026,10,8,21,0,0),"M31"));
    using(var repo=new Repository(Path.Combine(parent,"archive"))){repo.Import(repo.Scan(source,"Scope-01","Auto",ct,NoProgress).Frames,ct,NoProgress);string renamed=Path.Combine(source,"M31_unprocessed_renamed.fit");File.Copy(file,renamed);string edited=Path.Combine(source,"M31_starless.fit");Write(edited,64,48,(x,y)=>2000,new Dictionary<string,string>());string database=Path.Combine(parent,".ASTROARCHIVE","do-not-import.fit");Write(database,64,48,(x,y)=>3000,new Dictionary<string,string>());
     var plan=repo.ScanEditedFolder(parent,true,ct,NoProgress);Check(plan.Images.Count==1&&plan.Images[0].Path==edited&&plan.SkippedArchived==2&&plan.SkippedFolders.Count==2,"Parent crawl entered repository/database folders or included renamed archived originals");var project=repo.ImportEditedFolder(plan,"Mixed edits",ct,NoProgress);Check(repo.EditedImages(project).Count==1&&repo.All().Count==1&&File.Exists(file)&&File.Exists(renamed)&&File.Exists(database),"Mixed import changed archive or source data");
     var after=repo.ScanEditedFolder(source,true,ct,NoProgress);repo.Import(repo.Scan(source,"Scope-01","Auto",ct,NoProgress).Frames,ct,NoProgress);Expect(()=>repo.ImportEditedFolder(after,"Already archived",ct,NoProgress),"Capture archived after review was imported again");
    }
   });
   Test("Cancelled edited copies retain sources and no partial project",()=>{
    string source=Path.Combine(root,"edited-cancel-source"),file=Path.Combine(source,"M51_starless.fit");Write(file,64,48,(x,y)=>1800,new Dictionary<string,string>());using(var repo=new Repository(Path.Combine(root,"edited-cancel-repo")))using(var cancel=new CancellationTokenSource()){Expect(()=>repo.AddEditedImages(new[]{file},null,"Cancelled",cancel.Token,p=>cancel.Cancel()),"Cancelled copy succeeded");List<string> errors;Check(repo.EditedProjects(out errors).Count==0&&errors.Count==0&&File.Exists(file)&&!Directory.GetFiles(repo.EditedFolder,"*",SearchOption.AllDirectories).Any(),"Cancellation retained a partial image or lost original");}
   });
   Test("Edited paths and malformed manifests cannot escape the workspace",()=>{
    string source=Path.Combine(root,"edited-boundary-source"),file=Path.Combine(source,"M51.fit");Write(file,64,48,(x,y)=>1800,new Dictionary<string,string>());using(var repo=new Repository(Path.Combine(root,"edited-boundary-repo"))){var project=repo.AddEditedImages(new[]{file},null,"Boundary",ct,NoProgress);Expect(()=>repo.EditedPath(project,"../escape.fit"),"Traversal accepted");project.Sources[0].RelativePath="../../../../escape.fit";File.WriteAllText(Path.Combine(repo.EditedProjectFolder(project),"edited-project.json"),Util.Serialize(project));List<string> errors;Check(repo.EditedProjects(out errors).Count==0&&errors.Count==1&&File.Exists(file),"Forged manifest accepted or source affected");Expect(()=>repo.ScanEditedFolder(repo.Root,true,ct,NoProgress),"Repository crawled into itself");}
   });
  }
 }
}
