// Creates copy-based projects. Calibration suggestions never alter science data.
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Text.RegularExpressions;
namespace AstroArchive {
 public class ExportOptions {public string Parent;public string Name;public string Mode="Subs";public bool AddMetadata=false;public bool CreateNewFolder=false;public bool SeparateSessions=false;public bool IncludeCalibration=true;public bool IncludeRejected=false;public bool IncludeUnknownCalibration=false;public bool ConvertToFits=false;}
 public static class Exporter {
  public static bool MatchesCalibration(Frame light,Frame cal){return CalibrationMatching.Evaluate(light,cal).Accepted;}
  public static List<Frame> ExistingCalibrations(Repository repo,IEnumerable<Frame> frames){return frames.Where(f=>Assets.IsCalibration(f.Kind)&&!f.Rejected&&!CaptureScreening.FileProblem(f)&&f.Status!="Failed"&&File.Exists(repo.FilePath(f))).ToList();}
  public static List<Frame> CalibrationFor(IEnumerable<Frame> inputs,List<Frame> all,bool allowUnknown){
   var lights=inputs.ToList();if(lights.Count==0)return new List<Frame>();Frame light=lights[0];
   if(light.Calibration!="Uncalibrated"&&!(light.Calibration=="Unknown"&&allowUnknown))return new List<Frame>();
   var cals=all.Where(c=>!c.Rejected&&Assets.IsCalibration(c.Kind)&&lights.All(f=>MatchesCalibration(f,c))).ToList();
   foreach(string kind in new[]{"Dark","Flat","Bias"}){var raw=cals.Where(c=>c.Kind==kind).ToList();var masters=cals.Where(c=>c.Kind=="Master "+kind.ToLowerInvariant()).OrderBy(c=>Math.Abs((c.Temperature??0)-(light.Temperature??0))).ThenByDescending(c=>c.StackCount).ToList();if(raw.Count>0)cals.RemoveAll(c=>c.Kind=="Master "+kind.ToLowerInvariant());else if(masters.Count>1){var keep=masters.First();cals.RemoveAll(c=>c.Kind==keep.Kind&&c.Hash!=keep.Hash);}}
   var flatInputs=cals.Where(c=>c.Kind=="Flat").ToList();foreach(var flatGroup in flatInputs.GroupBy(f=>f.Group)){var darkFlats=all.Where(c=>(c.Kind=="Dark flat"||c.Kind=="Master dark flat")&&flatGroup.All(flat=>MatchesCalibration(flat,c))).ToList();if(darkFlats.Any(c=>c.Kind=="Dark flat"))darkFlats.RemoveAll(c=>c.Kind=="Master dark flat");else darkFlats=darkFlats.OrderByDescending(c=>c.StackCount).Take(1).ToList();foreach(var darkFlat in darkFlats)if(!cals.Any(c=>c.Hash==darkFlat.Hash))cals.Add(darkFlat);}return cals;
  }
  public static List<Frame> AvailableCalibrations(IEnumerable<Frame> selection,List<Frame> all,bool separateSessions,bool allowUnknown){return selection.Where(f=>f.Kind=="Light").GroupBy(f=>f.Target+"|"+f.Group+(separateSessions?"|"+f.Session:"")).SelectMany(g=>CalibrationFor(g,all,allowUnknown)).GroupBy(f=>f.Hash).Select(g=>g.First()).ToList();}
  static string FlatBucket(Frame frame){return Util.Safe("exp"+Util.Num(frame.Exposure)+"s_"+Util.HashText(frame.Group).Substring(0,8));}
  public static bool RequiresConversion(Frame f){var image=Assets.Selected(f);return !string.IsNullOrEmpty(f.Format)&&(f.Format!="FITS"||image!=null&&(image.Compression=="cfitsio"||image.Count>1||f.Images.Count>1));}
  static string SubFolder(Frame light,int index){return Path.Combine("subs",index.ToString("00")+"_"+Util.Safe(light.MakeText)+"_"+Util.Safe(light.Telescope)+"_"+Util.Safe(light.Camera)+"_"+Util.Safe(light.Filter)+"_"+Util.Safe(Util.Num(light.Exposure)+"s"));}
  public static string Destination(Repository repo,ExportOptions options){
   if(string.IsNullOrWhiteSpace(options.Parent)||!Directory.Exists(options.Parent))throw new IOException("Choose an existing destination folder.");
   string parent=Path.GetFullPath(options.Parent);if(parent.Length>Path.GetPathRoot(parent).Length)parent=parent.TrimEnd(Path.DirectorySeparatorChar,Path.AltDirectorySeparatorChar);
   if(Util.Within(parent,repo.Root))throw new IOException("Choose a destination outside the repository.");CheckDestinationPath(parent);
   if(!options.CreateNewFolder)return parent;
   if(string.IsNullOrWhiteSpace(options.Name))throw new IOException("Enter a name for the new folder.");
   string dest=Path.Combine(parent,Util.Safe(options.Name));if(Directory.Exists(dest)||File.Exists(dest))throw new IOException("This folder name already exists. Choose a new name.");return dest;
  }
  internal static void CheckDestinationPath(string path){for(string p=Path.GetFullPath(path);p!=null;p=Path.GetDirectoryName(p)){if(Directory.Exists(p)&&!FileStamp.CanTraverse(new DirectoryInfo(p)))throw new IOException("Choose an export destination without linked directories: "+p);}}
  static string OutputName(string original){string name=Regex.Replace(Path.GetFileName(original??""),"[<>:\"/\\\\|?*\\x00-\\x1F]","_").Trim().TrimEnd('.', ' ');if(name.Length==0)name="Unknown";if(Regex.IsMatch(name,@"^(CON|PRN|AUX|NUL|COM[0-9]|LPT[0-9])(?:\.|$)",RegexOptions.IgnoreCase))name="_"+name;return name;}
  static string UniquePath(string path,Dictionary<string,HashSet<string>> folders=null){
   string directory=Path.GetDirectoryName(path);CheckDestinationPath(directory);if(folders==null)folders=new Dictionary<string,HashSet<string>>(StringComparer.OrdinalIgnoreCase);HashSet<string> names;
   if(!folders.TryGetValue(directory,out names)){names=new HashSet<string>(Directory.Exists(directory)?Directory.EnumerateFileSystemEntries(directory).Select(Path.GetFileName):Enumerable.Empty<string>(),StringComparer.OrdinalIgnoreCase);folders[directory]=names;}
   string name=Path.GetFileName(path);var match=Regex.Match(name,@"(\.(fit|fits|fts)(\.gz)?)$",RegexOptions.IgnoreCase);string ext=match.Success?match.Value:Path.GetExtension(name);string stem=name.Substring(0,name.Length-ext.Length);int index=1;
   while(names.Contains(Path.GetFileName(path))||File.Exists(path)||Directory.Exists(path))path=Path.Combine(directory,stem+" ("+(++index)+")"+ext);names.Add(Path.GetFileName(path));return path;
  }
  public static string WriteMetadataText(string path,string text,CancellationToken ct=default(CancellationToken)){
   ct.ThrowIfCancellationRequested();path=UniquePath(path);string temp=Path.Combine(Path.GetDirectoryName(path),".astroarchive-export-"+Guid.NewGuid().ToString("N")+".partial");try{using(var output=new FileStream(temp,FileMode.CreateNew,FileAccess.Write,FileShare.None))using(var writer=new StreamWriter(output,new UTF8Encoding(false)))writer.Write(text);ct.ThrowIfCancellationRequested();File.Move(temp,path);return path;}finally{if(File.Exists(temp))File.Delete(temp);}
  }
  static void CopyMetadata(string from,string target,string hash,CancellationToken ct){
   target=UniquePath(target);string temp=Path.Combine(Path.GetDirectoryName(target),".astroarchive-export-"+Guid.NewGuid().ToString("N")+".partial");try{Repository.CopyVerified(from,temp,hash,ct);ct.ThrowIfCancellationRequested();File.Move(temp,target);}finally{if(File.Exists(temp))File.Delete(temp);}
  }
  public static string Create(Repository repo,List<Frame> selection,ExportOptions options,CancellationToken ct,Action<ProgressInfo> progress){
   var metrics=new PipelineMetrics(progress);metrics.Stage="Preparing export";metrics.Current="Building file list";metrics.Pulse(true);
   if(selection.Count==0)throw new InvalidOperationException("Select files to export.");if(!new[]{"Files","Subs","Stacks","Both"}.Contains(options.Mode))throw new InvalidOperationException("Unknown export mode.");ct.ThrowIfCancellationRequested();
   string dest=Destination(repo,options);
   var manifest=new List<object>();var recipes=new List<object>();var warnings=new List<string>();var all=ExistingCalibrations(repo,repo.All());var copy=new List<Tuple<Frame,string>>();var workflows=new List<Tuple<string,string>>();bool subs=options.Mode=="Subs"||options.Mode=="Both",stacks=options.Mode=="Stacks"||options.Mode=="Both";
   bool multipleTargets=selection.Where(f=>f.Kind=="Light"||f.Kind=="Stack").Select(f=>f.Target).Distinct().Count()>1;
   if(options.Mode=="Files"){int index=0;foreach(var group in selection.Where(f=>f.Kind=="Light").GroupBy(f=>f.Target+"|"+f.Group).OrderBy(g=>g.Key)){Frame light=group.First();string directory=Path.Combine(SubFolder(light,++index),"lights");if(multipleTargets)directory=Path.Combine("targets",Util.Safe(light.Target),directory);foreach(var f in group.GroupBy(f=>f.Hash).Select(g=>g.First()))copy.Add(Tuple.Create(f,directory));}foreach(var f in selection.Where(f=>f.Kind!="Light").GroupBy(f=>f.Hash).Select(g=>g.First()))copy.Add(Tuple.Create(f,""));}
   if(subs){var groups=selection.Where(f=>f.Kind=="Light"&&(options.IncludeRejected||!f.Rejected)).GroupBy(f=>f.Target+"|"+f.Group+(options.SeparateSessions?"|"+f.Session:"")).OrderBy(g=>g.Key).ToList();int index=0;
    foreach(var g in groups){Frame light=g.First();string group=Path.Combine(options.SeparateSessions?Path.Combine("sessions",Util.Safe(light.Night)+"_"+Util.Safe(light.Session),"subs"):"subs",Path.GetFileName(SubFolder(light,++index)));
     if(multipleTargets)group=Path.Combine("targets",Util.Safe(light.Target),group);
     foreach(var f in g)copy.Add(Tuple.Create(f,Path.Combine(group,"lights")));
     var cals=new List<Frame>();if(options.IncludeCalibration&&(light.Calibration=="Uncalibrated"||(light.Calibration=="Unknown"&&options.IncludeUnknownCalibration))) {
      cals=CalibrationFor(g,all,options.IncludeUnknownCalibration);
      foreach(var c in cals){if(c.Kind=="Dark flat")foreach(var flats in cals.Where(f=>f.Kind=="Flat").GroupBy(f=>f.Group).Where(flatSet=>flatSet.All(f=>MatchesCalibration(f,c))))copy.Add(Tuple.Create(c,Path.Combine(group,"dark-flats",FlatBucket(flats.First()))));else copy.Add(Tuple.Create(c,Path.Combine(group,c.Kind.StartsWith("Master")?"masters":c.Kind=="Dark"?"darks":c.Kind=="Flat"?Path.Combine("flats",FlatBucket(c)):"biases")));}
     }
     if(light.Calibration=="Unknown")warnings.Add(group+": calibration status is unknown. Confirm before applying darks/flats/biases.");if(light.Calibration=="Calibrated")warnings.Add(group+": already calibrated; additional calibration files were not supplied.");
     if(options.IncludeCalibration&&light.Calibration=="Uncalibrated"&&!cals.Any(c=>c.Kind=="Dark"||c.Kind=="Master dark"))warnings.Add(group+": no darks with verified matching identity, exposure, gain, dimensions and temperature were found.");
     recipes.Add(new{Group=group,FlatPreparation=cals.Where(c=>c.Kind=="Flat").GroupBy(f=>f.Group).Select(flats=>new{Directory=FlatBucket(flats.First()),Flats=flats.Select(f=>f.Hash).ToList(),DarkFlats=cals.Where(c=>(c.Kind=="Dark flat"||c.Kind=="Master dark flat")&&flats.All(f=>MatchesCalibration(f,c))).Select(c=>c.Hash).ToList()}).ToList(),Inputs=g.Select(f=>f.Hash).ToList(),Calibration=cals.Select(c=>new{c.Hash,c.Kind,AppliesTo=c.Kind=="Dark flat"||c.Kind=="Master dark flat"?"flats":"lights",Decision=CalibrationMatching.Evaluate(c.Kind=="Dark flat"||c.Kind=="Master dark flat"?cals.First(f=>f.Kind=="Flat"&&MatchesCalibration(f,c)):light,c)}).ToList()});
     workflows.Add(Tuple.Create(group,light.Calibration));
    }
   }
   if(stacks){foreach(var f in selection.Where(f=>f.Kind=="Stack"&&(options.IncludeRejected||!f.Rejected)))copy.Add(Tuple.Create(f,options.Mode=="Stacks"&&!options.SeparateSessions?"":Path.Combine(multipleTargets?Path.Combine("targets",Util.Safe(f.Target)):"",options.SeparateSessions?Path.Combine("sessions",Util.Safe(f.Night)+"_"+Util.Safe(f.Session),"stacks"):"stacks",Util.Safe(f.MakeText),Util.Safe(f.Telescope),Util.Safe(f.Camera),Util.Safe(f.Filter))));warnings.Add("Existing stacks are separate from individual lights. Do not mix a telescope stack with its constituent subs, or combine overlapping live-stack snapshots as independent integrations. Exposure overlap cannot be established from filenames alone.");}
   if(options.Mode!="Files"){var ineligible=copy.Where(item=>!Assets.CanStack(item.Item1)).ToList();if(ineligible.Count>0)throw new InvalidOperationException("Scientific export requires linear, decodable data. Review metadata or export original files: "+string.Join(", ",ineligible.Take(4).Select(item=>item.Item1.OriginalName)));if(!options.ConvertToFits&&copy.Any(item=>RequiresConversion(item.Item1)))throw new InvalidOperationException("Enable conversion to FITS for these formats or multi-image containers. Original-file export is also available.");}
   if(copy.Count==0)throw new InvalidOperationException("The selected export mode contains no eligible files.");
   // An existing destination may contain the repository as a child. Never copy into it.
   var outputDirectories=copy.Select(item=>Path.Combine(dest,item.Item2)).ToList();
   foreach(var workflow in workflows)foreach(string directory in new[]{"lights","darks","flats","dark-flats","biases","masters","process","output"})outputDirectories.Add(Path.Combine(dest,workflow.Item1,directory));
   if(options.AddMetadata){outputDirectories.Add(Path.Combine(dest,"session-metadata"));}
   foreach(string directory in outputDirectories){if(Util.Within(directory,repo.Root))throw new IOException("An export folder overlaps the repository. Choose another destination.");CheckDestinationPath(directory);}
   ct.ThrowIfCancellationRequested();Directory.CreateDirectory(dest);
   foreach(var workflow in workflows)foreach(string directory in new[]{"lights","darks","flats","dark-flats","biases","masters","process","output"})Directory.CreateDirectory(Path.Combine(dest,workflow.Item1,directory));

   var outputFolders=new Dictionary<string,HashSet<string>>(StringComparer.OrdinalIgnoreCase);int n=0;metrics.Phase(copy.Count,copy.Sum(item=>item.Item1.Bytes),"Copying project",true);string etaKey="exporteta150:"+Util.HashText(repo.Root+"|"+Path.GetFullPath(options.Parent));double priorRatio;if(double.TryParse(repo.CacheGet(etaKey),System.Globalization.NumberStyles.Float,System.Globalization.CultureInfo.InvariantCulture,out priorRatio))metrics.SeedVerificationWeight(priorRatio);
   foreach(var item in copy){ct.ThrowIfCancellationRequested();Frame f=item.Item1;metrics.Current="Exporting "+f.OriginalName;var transfer=metrics.Track(f.Bytes);string dir=Path.Combine(dest,item.Item2);CheckDestinationPath(dir);Directory.CreateDirectory(dir);string p=UniquePath(Path.Combine(dir,options.Mode!="Files"&&options.ConvertToFits&&RequiresConversion(f)?OutputName(Path.GetFileNameWithoutExtension(f.OriginalName)+".fits"):OutputName(f.OriginalName)),outputFolders);string rel=p.Substring(dest.TrimEnd(Path.DirectorySeparatorChar,Path.AltDirectorySeparatorChar).Length+1);string temp=Path.Combine(dir,".astroarchive-export-"+Guid.NewGuid().ToString("N")+".partial");bool derived=options.Mode!="Files"&&options.ConvertToFits&&RequiresConversion(f);string outputHash=f.Hash;try{if(derived){repo.ValidateCapture(f,ct);ScientificFits.Write(temp,Assets.Read(f,repo.FilePath(f),f.ImageIndex??0,ct),f,ct);outputHash=Util.Hash(temp,ct);var decoded=Fits.Inspect(temp);if(decoded.Images.Count!=1)throw new InvalidDataException("Derived FITS validation failed.");}else Repository.CopyVerified(repo.FilePath(f),temp,f.Hash,ct,metrics,transfer);ct.ThrowIfCancellationRequested();File.Move(temp,p);transfer.Resolve(true);}finally{if(File.Exists(temp))File.Delete(temp);}manifest.Add(new{ExportPath=rel,OutputHash=outputHash,SourceHash=f.Hash,ImageKey=f.ImageKey,ImageIndex=f.ImageIndex,Conversion=derived?"Decoded physical values to Float64 FITS":"Original bytes",Metadata=f});n++;}
   metrics.Finalise(options.AddMetadata?"Preserving session metadata and writing project manifest":"Finishing verified export");if(metrics.HasVerificationTiming){try{repo.CachePut(etaKey,metrics.VerificationWeight.ToString("R",System.Globalization.CultureInfo.InvariantCulture));}catch(Exception e){warnings.Add("ETA profile could not be saved: "+e.Message);}}
   if(options.AddMetadata){
   foreach(var workflow in workflows){string group=workflow.Item1;WriteMetadataText(Path.Combine(dest,group,"WORKFLOW.txt"),"Use lights for registration and stacking.\r\nCalibration state: "+workflow.Item2+"\r\nRaw calibration sets belong in darks/flats/biases. Calibrate raw flats using dark-flats (or a suitable bias), then build a master flat. Never subtract both a dark flat and a bias from the same flat. Dark flats are not light-frame darks. Masters in masters must be selected explicitly in your stacking software.\r\nEach group is separate because target, camera, filter, dimensions, exposure, gain or calibration differ. Combine compatible group results later with appropriate weighting.\r\n",ct);}
   foreach(string sidecar in copy.Select(item=>item.Item1.SidecarRelativePath).Where(p=>!string.IsNullOrEmpty(p)).Distinct()){string from=Path.Combine(repo.Root,sidecar);if(Util.Within(from,repo.Root)&&File.Exists(from)){string dir=Path.Combine(dest,"session-metadata");CheckDestinationPath(dir);Directory.CreateDirectory(dir);CopyMetadata(from,Path.Combine(dir,Util.HashText(sidecar).Substring(0,12)+"_"+Path.GetFileName(sidecar)),Util.Hash(from,ct),ct);}}
   foreach(var associated in copy.SelectMany(item=>item.Item1.AssociatedFiles??new List<AssociatedFile>()).Where(a=>!string.IsNullOrEmpty(a.RelativePath)).GroupBy(a=>a.RelativePath).Select(g=>g.First())){string from=Path.Combine(repo.Root,associated.RelativePath);if(!Util.Within(from,repo.Root))throw new IOException("Associated metadata path escapes repository.");string directory=Path.Combine(dest,"session-metadata");CheckDestinationPath(directory);Directory.CreateDirectory(directory);string target=Path.Combine(directory,Path.GetFileName(from));CopyMetadata(from,target,associated.Hash,ct);}
   string manifestPath=WriteMetadataText(Path.Combine(dest,"manifest.json"),Util.Serialize(new{App="AstroArchive 1.12.0",Created=DateTime.UtcNow.ToString("o"),Mode=options.Mode,SeparateSessions=options.SeparateSessions,Files=manifest,CalibrationRecipes=recipes,Warnings=warnings}),ct);
   WriteMetadataText(Path.Combine(dest,"READ_ME.txt"),(options.Mode=="Files"?"AstroArchive selected file export\r\n\r\n":"AstroArchive stacking project\r\n\r\n")+string.Join("\r\n",warnings)+"\r\n\r\nOriginal copies are byte-for-byte verified. Explicit converted exports are derived FITS; source and output checksums are recorded in "+Path.GetFileName(manifestPath)+". The repository and original captures are untouched.\r\nThis project prepares input folders; stacking is performed in your chosen software.\r\nUse "+Path.GetFileName(manifestPath)+" for original names, source paths, checksums, metadata and inferred mount classifications.\r\n",ct);}
   ct.ThrowIfCancellationRequested();metrics.Finish(n+" files exported");return dest;
  }
 }
}
