// Export boundaries, opt-in extras and collision handling using real verified copies.
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
namespace AstroArchive {
 public partial class Tests {
  static List<Frame> ExportFixture(Repository repo,string name,bool subs=false){
   string source=Path.Combine(root,name);var headers=LightHeaders(new DateTime(2026,10,8,21,0,0),"M45");if(!subs)headers["NCOMBINE"]="12";
   Write(Path.Combine(source,subs?"Light_M45.fit":"stacked-16_M45_30s40_Astro_20261008-210000123.fits"),64,48,(x,y)=>1400+x,headers);
   File.WriteAllText(Path.Combine(source,"session.json"),"{\"session\":\"export test\"}");
   repo.Import(repo.Scan(source,"Scope-1","Auto",ct,NoProgress).Frames,ct,NoProgress);return repo.All();
  }
  static string ExportDestinationFolder(string name){string path=Path.Combine(root,name);Directory.CreateDirectory(path);return path;}
  static void ExportRegressions(){
   Test("Grouped subs retain temperature-specific dark calibrations",()=>{
    var a=CalibrationFixture("Light",60);a.Calibration="Uncalibrated";a.Temperature=10;a.Hash="light-a";var b=a.Clone();b.Temperature=18;b.Hash="light-b";var darkA=a.Clone();darkA.Kind="Dark";darkA.Hash="dark-a";var darkB=b.Clone();darkB.Kind="Dark";darkB.Hash="dark-b";
    Check(a.Group==b.Group,"Fixture does not share the original export group");var matches=Exporter.AvailableCalibrations(new[]{a,b},new List<Frame>{darkA,darkB},false,false);Check(matches.Count==2&&matches.Contains(darkA)&&matches.Contains(darkB),"Valid darks disappeared when selected subs span temperatures");
   });
   Test("Grouped subs retain each observing night's flats",()=>{
    var a=CalibrationFixture("Light",60);a.Calibration="Uncalibrated";a.Hash="light-a";var b=a.Clone();b.Night="2026-10-07";b.Hash="light-b";var flatA=a.Clone();flatA.Kind="Flat";flatA.Exposure=0.5;flatA.Hash="flat-a";var flatB=flatA.Clone();flatB.Night=b.Night;flatB.Hash="flat-b";
    var matches=Exporter.AvailableCalibrations(new[]{a,b},new List<Frame>{flatA,flatB},false,false);Check(matches.Count==2&&matches.Contains(flatA)&&matches.Contains(flatB),"Valid flats disappeared when selected subs span nights");
   });
   Test("Calibration grouping recombines identical sets without fragmenting compatible subs",()=>{
    var a=CalibrationFixture("Light",60);a.Calibration="Uncalibrated";a.Hash="light-a";a.Session="A";var b=a.Clone();b.Hash="light-b";b.Session="B";b.Temperature=-11;b.Night="2026-10-07";var dark=a.Clone();dark.Kind="Master dark";dark.Hash="master";
    var frames=new[]{a,b};var cals=new List<Frame>{dark};var groups=Exporter.StackingGroups(frames,cals,false,false,true);Check(groups.Count==1&&groups[0].Inputs.Count==2&&groups[0].Calibrations.Single()==dark,"Identical calibration sets fragmented compatible subs");Check(Exporter.StackingGroups(frames,cals,true,false,true).Count==2,"Explicit session separation was lost");
    b.Calibration="Unknown";Check(Exporter.AvailableCalibrations(new[]{b},cals,false,false).Count==0&&Exporter.AvailableCalibrations(new[]{b},cals,false,true).Single()==dark,"Unknown processing-state confirmation was ignored");b.Calibration="Calibrated";Check(Exporter.AvailableCalibrations(new[]{b},cals,false,true).Count==0,"Calibrated lights received extra calibration");
   });
   Test("Selected subframe groups export correct calibration folders and DSS lists",()=>{
    string source=Path.Combine(root,"grouped-cal-export-source");
    for(int session=0;session<2;session++){
     var headers=LightHeaders(new DateTime(2026,10,6+session,21,0,0),"M45");headers["CCD-TEMP"]=(10+session*8).ToString();headers["XBINNING"]=headers["YBINNING"]="1";headers["FILTER"]="'L'";
     for(int sub=0;sub<2;sub++)Write(Path.Combine(source,"Session"+session,"Light_"+sub+".fit"),64,48,(x,y)=>1400+session*200+sub,headers);
     foreach(string kind in new[]{"Dark","Flat","Dark flat"}){var cal=new Dictionary<string,string>(headers);cal["IMAGETYP"]="'"+kind+"'";if(kind!="Dark")cal["EXPTIME"]="0.5";Write(Path.Combine(source,"Calibrations",kind.Replace(' ','_')+"_"+session+".fit"),64,48,(x,y)=>2000+session*100+kind.Length,cal);}
    }
    using(var repo=new Repository(Path.Combine(root,"grouped-cal-export-repo"))){repo.Import(repo.Scan(source,"Scope-1","Auto",ct,NoProgress).Frames,ct,NoProgress);var rows=repo.All();var sessions=SubframeSessions.Build(rows);Check(sessions.Count==2&&sessions.All(s=>s.Frames.Count==2),"Session-group fixture failed");var selected=sessions.SelectMany(s=>s.Frames).ToList();var allCals=Exporter.ExistingCalibrations(repo,rows);
     Check(selected.All(f=>f.Calibration=="Unknown")&&Exporter.AvailableCalibrations(selected,allCals,false,false).Count==0,"Unknown-state fixtures unexpectedly auto-calibrated");Check(Exporter.AvailableCalibrations(selected,allCals,false,true).Count==6,"Grouped selection omitted its dark, flat or dark-flat sets");
     string folder=ExportDestinationFolder("grouped-cal-export");var options=new ExportOptions{Parent=folder,Mode="Subs",IncludeCalibration=true,IncludeUnknownCalibration=true,AddMetadata=true};var result=new ExportResult();Exporter.Create(repo,selected,options,ct,NoProgress,result);var lightDirs=Directory.GetDirectories(folder,"lights",SearchOption.AllDirectories);Check(lightDirs.Length==2&&result.Files.Count==10,"Export lost files or mixed incompatible calibration sets");
     foreach(string lightDir in lightDirs){string parent=Path.GetDirectoryName(lightDir);var copies=result.Files.Where(f=>Util.Within(f.Path,parent)).ToList();var lights=copies.Where(f=>f.Frame.Kind=="Light").ToList();var flats=copies.Where(f=>f.Frame.Kind=="Flat").ToList();Check(lights.Count==2&&copies.Count==5,"Calibration set copied into the wrong group");foreach(var cal in copies.Where(f=>f.Frame.Kind!="Light")){var inputs=cal.Frame.Kind=="Dark flat"?flats:lights;Check(inputs.All(f=>Exporter.MatchesCalibration(f.Frame,cal.Frame)),"Incompatible calibration mixed with a light or flat");}}
     Check(result.Files.All(f=>Util.Hash(f.Path,ct)==f.Frame.Hash),"Grouped export changed original bytes");var manifest=File.ReadAllText(Path.Combine(folder,"manifest.json"));Check(result.Files.All(f=>manifest.Contains(f.Frame.Hash)),"Manifest omitted a calibration or selected sub");
     var jobs=ExternalApps.WriteDssJobs(folder,selected,result.Files,true,true,ct);Check(jobs.Count==2,"DSS recombined different calibration sets");foreach(var job in jobs){var lines=File.ReadAllLines(job.Path).Skip(2).ToList();Check(lines.Count==5,"DSS lost calibration roles");var light=lines.First(l=>l.StartsWith("1\tlight\t")).Substring(8);var input=result.Files.Single(f=>f.Path==light).Frame;foreach(var row in lines.Where(l=>l.StartsWith("1\tdark\t")||l.StartsWith("1\tflat\t"))){var frame=result.Files.Single(f=>f.Path==row.Split('\t')[2]).Frame;Check(Exporter.MatchesCalibration(input,frame),"DSS mixed a night or temperature calibration");}}
     string plain=ExportDestinationFolder("grouped-cal-no-calibrations");Exporter.Create(repo,selected,new ExportOptions{Parent=plain,Mode="Subs",IncludeCalibration=false},ct,NoProgress);Check(Directory.GetDirectories(plain,"lights",SearchOption.AllDirectories).Length==1&&Directory.GetFiles(plain,"*.fit",SearchOption.AllDirectories).Length==4,"Disabling calibration unnecessarily split compatible inputs");
    }
   });
   Test("Siril after export opens the verified stack including collision suffixes and nested paths",()=>{
    using(var repo=new Repository(Path.Combine(root,"siril-result-repo"))){var rows=ExportFixture(repo,"siril-result-source");string executable=Path.Combine(root,"siril.exe");File.WriteAllText(executable,"GUI fixture");
     foreach(string mode in new[]{"Files","Both"}){string directory=ExportDestinationFolder("Siril export Ω "+mode);var options=new ExportOptions{Parent=directory,Mode=mode,IncludeCalibration=false};var first=new ExportResult();Exporter.Create(repo,rows,options,ct,NoProgress,first);var next=new ExportResult();Exporter.Create(repo,rows,options,ct,NoProgress,next);
      var copy=next.Files.Single();Check(next.Folder==directory&&copy.Source==rows.Single()&&copy.Path!=first.Files.Single().Path&&Path.GetFileName(copy.Path).Contains(" (2)"),"Export result guessed the source filename instead of the actual copy");
      Check(Util.Hash(copy.Path,ct)==rows.Single().Hash&&Util.Hash(first.Files.Single().Path,ct)==rows.Single().Hash,"Old or new exported stack changed");var start=SirilHandoff.ExportLaunchInfo(executable,next);string working=Path.GetDirectoryName(copy.Path);
      Check(start.WorkingDirectory==working&&start.Arguments=="--directory "+SirilHandoff.QuoteArgument(working)+" "+SirilHandoff.QuoteArgument(copy.Path)&&!start.UseShellExecute,"Siril did not receive the verified output and its actual working directory");
      options.Parent=directory+"-missing";Expect(()=>Exporter.Create(repo,rows,options,ct,NoProgress,next),"Missing destination exported");Check(next.Folder==null&&next.Files.Count==0,"A failed export retained a stale launch result");Expect(()=>SirilHandoff.ExportLaunchInfo(executable,next),"An incomplete export prepared a launch");
     }
    }
   });
   Test("Siril after converted export opens the derived FITS stack",()=>{
    string source=Path.Combine(root,"siril-converted-source");Directory.CreateDirectory(source);string original=MakeXisf("siril-stack.xisf",new byte[]{12,0,44,1,0,125,255,255},"UInt16",null,"<Property id=\"PixInsight:Image:Linear\" value=\"true\"/><FITSKeyword name=\"IMAGETYP\" value=\"'Stack'\"/>");File.Copy(original,Path.Combine(source,"Stack_M45.xisf"));
    using(var repo=new Repository(Path.Combine(root,"siril-converted-repo"))){repo.Import(repo.Scan(source,"Rig","Auto",ct,NoProgress).Frames,ct,NoProgress);var rows=repo.All();Check(rows.Single().Kind=="Stack","Converted stack fixture was not classified as a stack");var options=new ExportOptions{Parent=root,Name="Siril converted Ω",CreateNewFolder=true,Mode="Stacks",IncludeCalibration=false,ConvertToFits=true};var result=new ExportResult();Exporter.Create(repo,rows,options,ct,NoProgress,result);
     var output=result.Files.Single();Check(output.Path.EndsWith(".fits")&&Fits.ReadPixels(output.Path,Fits.Inspect(output.Path).Images[0],0,ct).Pixels[3]==65535,"Converted handoff did not record the derived FITS");string executable=Path.Combine(root,"siril.exe");File.WriteAllText(executable,"GUI fixture");Check(SirilHandoff.ExportLaunchInfo(executable,result).Arguments.EndsWith(SirilHandoff.QuoteArgument(output.Path)),"Converted launch used the XISF source");Check(Util.Hash(repo.FilePath(rows[0]),ct)==rows[0].Hash,"Converted handoff changed the archive");
    }
   });
   Test("Default stack exports contain only the original verified image",()=>{
    using(var repo=new Repository(Path.Combine(root,"plain-stack-repo"))){var rows=ExportFixture(repo,"plain-stack-source");Check(rows.Single().Kind=="Stack"&&rows.Single().AssociatedFiles.Count==1,"Stack metadata fixture missing");rows[0].OriginalName="Stacked_M45_"+new string('a',210)+".fits";foreach(string mode in new[]{"Files","Stacks"}){string destination=ExportDestinationFolder("plain-stack-"+mode);string result=Exporter.Create(repo,rows,new ExportOptions{Parent=destination,Mode=mode},ct,NoProgress);string image=Path.Combine(destination,rows[0].OriginalName);Check(result==destination&&Directory.GetFileSystemEntries(destination).SequenceEqual(new[]{image})&&Util.Hash(image,ct)==rows[0].Hash,"Default stack produced extra files, renamed the image or changed bytes");}}
   });
   Test("Default subs retain compatible input folders without documentation or metadata",()=>{
    using(var repo=new Repository(Path.Combine(root,"plain-subs-repo"))){var rows=ExportFixture(repo,"plain-subs-source",true);var other=LightHeaders(new DateTime(2026,10,8,21,1,0),"M45");other["EXPTIME"]="30";string source=Path.Combine(root,"plain-subs-extra-source");Write(Path.Combine(source,"Light_M45_30s.fit"),64,48,(x,y)=>1800,other);repo.Import(repo.Scan(source,"Scope-1","Auto",ct,NoProgress).Frames,ct,NoProgress);rows=repo.All();Check(rows.Select(f=>f.Group).Distinct().Count()==2,"Incompatible sub fixture missing");foreach(string mode in new[]{"Files","Subs"}){string destination=ExportDestinationFolder("plain-subs-"+mode);Exporter.Create(repo,rows,new ExportOptions{Parent=destination,Mode=mode,IncludeCalibration=false},ct,NoProgress);var copies=Directory.GetFiles(destination,"*",SearchOption.AllDirectories);Check(Directory.GetDirectories(destination).SequenceEqual(new[]{Path.Combine(destination,"subs")})&&Directory.GetDirectories(Path.Combine(destination,"subs")).Length==2&&copies.Length==2&&copies.All(Util.IsFits),"Subs lost their groups or produced extra files");Check(copies.Select(p=>Util.Hash(p,ct)).OrderBy(h=>h).SequenceEqual(rows.Select(f=>f.Hash).OrderBy(h=>h)),"Sub bytes changed");}}
   });
   Test("Metadata and enclosing folders are independent opt-in export choices",()=>{
    using(var repo=new Repository(Path.Combine(root,"export-options-repo"))){var rows=ExportFixture(repo,"export-options-source");foreach(bool metadata in new[]{false,true})foreach(bool folder in new[]{false,true}){string parent=ExportDestinationFolder("export-options-"+metadata+"-"+folder);string result=Exporter.Create(repo,rows,new ExportOptions{Parent=parent,Name="New export",Mode="Files",AddMetadata=metadata,CreateNewFolder=folder},ct,NoProgress);Check(result==(folder?Path.Combine(parent,"New export"):parent),"Enclosing-folder option ignored");Check(File.Exists(Path.Combine(result,"manifest.json"))==metadata&&File.Exists(Path.Combine(result,"READ_ME.txt"))==metadata&&Directory.Exists(Path.Combine(result,"session-metadata"))==metadata,"Metadata option ignored");if(metadata){string manifest=File.ReadAllText(Path.Combine(result,"manifest.json"));Check(manifest.Contains(rows[0].Hash)&&manifest.Contains(rows[0].OriginalName)&&manifest.Contains("OutputHash"),"Manifest omitted checksum or original filename");Check(Directory.GetFiles(Path.Combine(result,"session-metadata")).Length==1,"Associated metadata lost");}else Check(Directory.GetFiles(result,"*",SearchOption.AllDirectories).Length==1,"Plain copy created extras");if(folder)Expect(()=>Exporter.Create(repo,rows,new ExportOptions{Parent=parent,Name="New export",Mode="Files",CreateNewFolder=true},ct,NoProgress),"Existing named folder reused");}}
   });
   Test("Export preserves existing files and numbers colliding names without losing FITS extensions",()=>{
    using(var repo=new Repository(Path.Combine(root,"export-collision-repo"))){var rows=ExportFixture(repo,"export-collision-source");Frame first=rows[0].Clone(),second;first.OriginalName="Same.fits.gz";string destination=ExportDestinationFolder("export-collision-destination");string existing=Path.Combine(destination,"SAME.fits.gz"),marker=Path.Combine(destination,"INCOMPLETE.txt"),partial=Path.Combine(destination,"Same.fits.gz.partial");File.WriteAllText(existing,"keep image");File.WriteAllText(marker,"keep marker");File.WriteAllText(partial,"keep partial");
     // Distinct repository captures may share a filename; use two valid byte hashes.
     string source=Path.Combine(root,"export-collision-second-source");Write(Path.Combine(source,"Stacked_M45.fit"),64,48,(x,y)=>2200,new Dictionary<string,string>{{"NCOMBINE","12"}});repo.Import(repo.Scan(source,"Scope-1","Auto",ct,NoProgress).Frames,ct,NoProgress);second=repo.All().Single(f=>f.Hash!=first.Hash);second.OriginalName="same.fits.gz";
     Exporter.Create(repo,new List<Frame>{first,second},new ExportOptions{Parent=destination,Mode="Files"},ct,NoProgress);Check(File.ReadAllText(existing)=="keep image"&&File.ReadAllText(marker)=="keep marker"&&File.ReadAllText(partial)=="keep partial","Existing destination file overwritten or deleted");Check(Util.Hash(Path.Combine(destination,"Same (2).fits.gz"),ct)==first.Hash&&Util.Hash(Path.Combine(destination,"same (3).fits.gz"),ct)==second.Hash,"Colliding images lost or extension damaged");Check(Directory.GetFiles(destination).Length==5,"Unexpected collision output");}
   });
   Test("Repeated metadata exports preserve earlier manifests and map each renamed copy",()=>{
    using(var repo=new Repository(Path.Combine(root,"repeat-export-repo"))){var rows=ExportFixture(repo,"repeat-export-source",true);string destination=ExportDestinationFolder("repeat-export-destination");var options=new ExportOptions{Parent=destination,Mode="Subs",IncludeCalibration=false,AddMetadata=true};Exporter.Create(repo,rows,options,ct,NoProgress);string manifest=File.ReadAllText(Path.Combine(destination,"manifest.json")),readme=File.ReadAllText(Path.Combine(destination,"READ_ME.txt"));Exporter.Create(repo,rows,options,ct,NoProgress);Check(File.ReadAllText(Path.Combine(destination,"manifest.json"))==manifest&&File.ReadAllText(Path.Combine(destination,"READ_ME.txt"))==readme,"Earlier documentation overwritten");string next=File.ReadAllText(Path.Combine(destination,"manifest (2).json"));Check(next.Contains("Light_M45 (2).fit")&&File.ReadAllText(Path.Combine(destination,"READ_ME (2).txt")).Contains("manifest (2).json"),"Repeated manifest does not describe renamed output");Check(Directory.GetFiles(destination,"WORKFLOW*.txt",SearchOption.AllDirectories).Length==2&&Directory.GetFiles(Path.Combine(destination,"session-metadata")).Length==2,"Earlier workflow or sidecar overwritten");}
   });
   Test("Cancellation retains verified copies and destination contents without temporary files",()=>{
    using(var repo=new Repository(Path.Combine(root,"cancel-export-repo"))){var rows=ExportFixture(repo,"cancel-export-source");string destination=ExportDestinationFolder("cancel-export-destination"),keep=Path.Combine(destination,"keep.txt");File.WriteAllText(keep,"keep");using(var token=new CancellationTokenSource()){var result=new ExportResult();Expect(()=>Exporter.Create(repo,rows,new ExportOptions{Parent=destination,Mode="Files"},token.Token,p=>{if(p.LiveMetrics!=null&&p.LiveMetrics.Snapshot().Any(s=>s.Stage=="Verification"))token.Cancel();},result),"Copy ignored cancellation");Check(token.IsCancellationRequested&&File.ReadAllText(keep)=="keep"&&result.Folder==null&&result.Files.Count==0,"Cancellation removed an existing file or exposed a partial export for launch");var copies=Directory.GetFiles(destination).Where(p=>p!=keep).ToList();Check(copies.Count<=1&&copies.All(p=>Path.GetFileName(p)==rows[0].OriginalName&&Util.Hash(p,ct)==rows[0].Hash),"Cancelled export left an unverified copy or partial");}Check(repo.All().Count==1&&Util.Hash(repo.FilePath(rows[0]),ct)==rows[0].Hash,"Cancellation damaged repository");}
   });
   Test("Changed archive bytes are refused without publishing an invalid export",()=>{
    using(var repo=new Repository(Path.Combine(root,"changed-export-repo"))){var rows=ExportFixture(repo,"changed-export-source");string destination=ExportDestinationFolder("changed-export-destination");File.AppendAllText(repo.FilePath(rows[0]),"changed");Expect(()=>Exporter.Create(repo,rows,new ExportOptions{Parent=destination,Mode="Files"},ct,NoProgress),"Changed source was exported");Check(!Directory.EnumerateFileSystemEntries(destination).Any(),"Failed verification left an output or partial");}
   });
   Test("A destination containing the repository cannot export through a matching subs folder",()=>{
    string parent=ExportDestinationFolder("nested-boundary-export-destination");using(var repo=new Repository(Path.Combine(parent,"subs"))){var rows=ExportFixture(repo,"nested-boundary-export-source",true);string original=repo.FilePath(rows[0]);Expect(()=>Exporter.Create(repo,rows,new ExportOptions{Parent=parent,Mode="Files"},ct,NoProgress),"Nested output entered repository");Check(Directory.GetFileSystemEntries(parent).Length==1&&Util.Hash(original,ct)==rows[0].Hash,"Overlap validation changed the destination or repository");}
   });
   Test("Export validates destinations before creating any output",()=>{
    using(var repo=new Repository(Path.Combine(root,"boundary-export-repo"))){var rows=ExportFixture(repo,"boundary-export-source");Expect(()=>Exporter.Create(repo,rows,new ExportOptions{Parent=repo.Root,Mode="Files"},ct,NoProgress),"Repository accepted as destination");string missing=Path.Combine(root,"missing-export-destination");Expect(()=>Exporter.Create(repo,rows,new ExportOptions{Parent=missing,Mode="Files"},ct,NoProgress),"Nonexistent parent accepted");Check(!Directory.Exists(missing),"Invalid destination was created");string destination=ExportDestinationFolder("boundary-export-destination");Expect(()=>Exporter.Create(repo,rows,new ExportOptions{Parent=destination,Mode="Files",CreateNewFolder=true},ct,NoProgress),"Unnamed folder accepted");Check(!Directory.EnumerateFileSystemEntries(destination).Any(),"Invalid folder option wrote output");}
   });
  }
 }
}
