// Export boundaries, opt-in extras and collision handling using real verified copies.
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
namespace AstroArchive {
 public partial class Tests {
  static List<Frame> ExportFixture(Repository repo,string name,bool subs=false){
   string source=Path.Combine(root,name);var headers=LightHeaders(new DateTime(2026,10,8,21,0,0),"M45");if(!subs)headers["NCOMBINE"]="12";
   Write(Path.Combine(source,subs?"Light_M45.fit":"stacked-16_M45_30s40_Astro_20261008-210000123.fits"),64,48,(x,y)=>1400+x,headers);
   File.WriteAllText(Path.Combine(source,"session.json"),"{\"session\":\"export test\"}");
   repo.Import(repo.Scan(source,"Scope-1","Auto",ct,NoProgress).Frames,ct,NoProgress);return repo.All();
  }
  static string ExportDestinationFolder(string name){string path=Path.Combine(root,name);Directory.CreateDirectory(path);return path;}
  static void ExportRegressions(){
   Test("Default stack exports contain only the original verified image",()=>{
    using(var repo=new Repository(Path.Combine(root,"plain-stack-repo"))){var rows=ExportFixture(repo,"plain-stack-source");Check(rows.Single().Kind=="Stack"&&rows.Single().AssociatedFiles.Count==1,"Stack metadata fixture missing");rows[0].OriginalName="Stacked_M45_"+new string('a',210)+".fits";foreach(string mode in new[]{"Files","Stacks"}){string destination=ExportDestinationFolder("plain-stack-"+mode);string result=Exporter.Create(repo,rows,new ExportOptions{Parent=destination,Mode=mode},ct,NoProgress);string image=Path.Combine(destination,rows[0].OriginalName);Check(result==destination&&Directory.GetFileSystemEntries(destination).SequenceEqual(new[]{image})&&Util.Hash(image,ct)==rows[0].Hash,"Default stack produced extra files, renamed the image or changed bytes");}}
   });
   Test("Default subs retain compatible input folders without documentation or metadata",()=>{
    using(var repo=new Repository(Path.Combine(root,"plain-subs-repo"))){var rows=ExportFixture(repo,"plain-subs-source",true);var other=LightHeaders(new DateTime(2026,10,8,21,1,0),"M45");other["EXPTIME"]="30";string source=Path.Combine(root,"plain-subs-extra-source");Write(Path.Combine(source,"Light_M45_30s.fit"),64,48,(x,y)=>1800,other);repo.Import(repo.Scan(source,"Scope-1","Auto",ct,NoProgress).Frames,ct,NoProgress);rows=repo.All();Check(rows.Select(f=>f.Group).Distinct().Count()==2,"Incompatible sub fixture missing");foreach(string mode in new[]{"Files","Subs"}){string destination=ExportDestinationFolder("plain-subs-"+mode);Exporter.Create(repo,rows,new ExportOptions{Parent=destination,Mode=mode,IncludeCalibration=false},ct,NoProgress);var copies=Directory.GetFiles(destination,"*",SearchOption.AllDirectories);Check(Directory.GetDirectories(destination).SequenceEqual(new[]{Path.Combine(destination,"subs")})&&Directory.GetDirectories(Path.Combine(destination,"subs")).Length==2&&copies.Length==2&&copies.All(Util.IsFits),"Subs lost their groups or produced extra files");Check(copies.Select(p=>Util.Hash(p,ct)).OrderBy(h=>h).SequenceEqual(rows.Select(f=>f.Hash).OrderBy(h=>h)),"Sub bytes changed");}}
   });
   Test("Metadata and enclosing folders are independent opt-in export choices",()=>{
    using(var repo=new Repository(Path.Combine(root,"export-options-repo"))){var rows=ExportFixture(repo,"export-options-source");foreach(bool metadata in new[]{false,true})foreach(bool folder in new[]{false,true}){string parent=ExportDestinationFolder("export-options-"+metadata+"-"+folder);string result=Exporter.Create(repo,rows,new ExportOptions{Parent=parent,Name="New export",Mode="Files",AddMetadata=metadata,CreateNewFolder=folder},ct,NoProgress);Check(result==(folder?Path.Combine(parent,"New export"):parent),"Enclosing-folder option ignored");Check(File.Exists(Path.Combine(result,"manifest.json"))==metadata&&File.Exists(Path.Combine(result,"READ_ME.txt"))==metadata&&Directory.Exists(Path.Combine(result,"session-metadata"))==metadata,"Metadata option ignored");if(metadata){string manifest=File.ReadAllText(Path.Combine(result,"manifest.json"));Check(manifest.Contains(rows[0].Hash)&&manifest.Contains(rows[0].OriginalName)&&manifest.Contains("OutputHash"),"Manifest omitted checksum or original filename");Check(Directory.GetFiles(Path.Combine(result,"session-metadata")).Length==1,"Associated metadata lost");}else Check(Directory.GetFiles(result,"*",SearchOption.AllDirectories).Length==1,"Plain copy created extras");if(folder)Expect(()=>Exporter.Create(repo,rows,new ExportOptions{Parent=parent,Name="New export",Mode="Files",CreateNewFolder=true},ct,NoProgress),"Existing named folder reused");}}
   });
   Test("Export preserves existing files and numbers colliding names without losing FITS extensions",()=>{
    using(var repo=new Repository(Path.Combine(root,"export-collision-repo"))){var rows=ExportFixture(repo,"export-collision-source");Frame first=rows[0].Clone(),second;first.OriginalName="Same.fits.gz";string destination=ExportDestinationFolder("export-collision-destination");string existing=Path.Combine(destination,"SAME.fits.gz"),marker=Path.Combine(destination,"INCOMPLETE.txt"),partial=Path.Combine(destination,"Same.fits.gz.partial");File.WriteAllText(existing,"keep image");File.WriteAllText(marker,"keep marker");File.WriteAllText(partial,"keep partial");
     // Distinct repository captures may share a filename; use two valid byte hashes.
     string source=Path.Combine(root,"export-collision-second-source");Write(Path.Combine(source,"Stacked_M45.fit"),64,48,(x,y)=>2200,new Dictionary<string,string>{{"NCOMBINE","12"}});repo.Import(repo.Scan(source,"Scope-1","Auto",ct,NoProgress).Frames,ct,NoProgress);second=repo.All().Single(f=>f.Hash!=first.Hash);second.OriginalName="same.fits.gz";
     Exporter.Create(repo,new List<Frame>{first,second},new ExportOptions{Parent=destination,Mode="Files"},ct,NoProgress);Check(File.ReadAllText(existing)=="keep image"&&File.ReadAllText(marker)=="keep marker"&&File.ReadAllText(partial)=="keep partial","Existing destination file overwritten or deleted");Check(Util.Hash(Path.Combine(destination,"Same (2).fits.gz"),ct)==first.Hash&&Util.Hash(Path.Combine(destination,"same (3).fits.gz"),ct)==second.Hash,"Colliding images lost or extension damaged");Check(Directory.GetFiles(destination).Length==5,"Unexpected collision output");}
   });
   Test("Repeated metadata exports preserve earlier manifests and map each renamed copy",()=>{
    using(var repo=new Repository(Path.Combine(root,"repeat-export-repo"))){var rows=ExportFixture(repo,"repeat-export-source",true);string destination=ExportDestinationFolder("repeat-export-destination");var options=new ExportOptions{Parent=destination,Mode="Subs",IncludeCalibration=false,AddMetadata=true};Exporter.Create(repo,rows,options,ct,NoProgress);string manifest=File.ReadAllText(Path.Combine(destination,"manifest.json")),readme=File.ReadAllText(Path.Combine(destination,"READ_ME.txt"));Exporter.Create(repo,rows,options,ct,NoProgress);Check(File.ReadAllText(Path.Combine(destination,"manifest.json"))==manifest&&File.ReadAllText(Path.Combine(destination,"READ_ME.txt"))==readme,"Earlier documentation overwritten");string next=File.ReadAllText(Path.Combine(destination,"manifest (2).json"));Check(next.Contains("Light_M45 (2).fit")&&File.ReadAllText(Path.Combine(destination,"READ_ME (2).txt")).Contains("manifest (2).json"),"Repeated manifest does not describe renamed output");Check(Directory.GetFiles(destination,"WORKFLOW*.txt",SearchOption.AllDirectories).Length==2&&Directory.GetFiles(Path.Combine(destination,"session-metadata")).Length==2,"Earlier workflow or sidecar overwritten");}
   });
   Test("Cancellation retains verified copies and destination contents without temporary files",()=>{
    using(var repo=new Repository(Path.Combine(root,"cancel-export-repo"))){var rows=ExportFixture(repo,"cancel-export-source");string destination=ExportDestinationFolder("cancel-export-destination"),keep=Path.Combine(destination,"keep.txt");File.WriteAllText(keep,"keep");using(var token=new CancellationTokenSource()){Expect(()=>Exporter.Create(repo,rows,new ExportOptions{Parent=destination,Mode="Files"},token.Token,p=>{if(p.LiveMetrics!=null&&p.LiveMetrics.Snapshot().Any(s=>s.Stage=="Verification"))token.Cancel();}),"Copy ignored cancellation");Check(token.IsCancellationRequested&&File.ReadAllText(keep)=="keep","Cancellation removed an existing file");var copies=Directory.GetFiles(destination).Where(p=>p!=keep).ToList();Check(copies.Count<=1&&copies.All(p=>Path.GetFileName(p)==rows[0].OriginalName&&Util.Hash(p,ct)==rows[0].Hash),"Cancelled export left an unverified copy or partial");}Check(repo.All().Count==1&&Util.Hash(repo.FilePath(rows[0]),ct)==rows[0].Hash,"Cancellation damaged repository");}
   });
   Test("Changed archive bytes are refused without publishing an invalid export",()=>{
    using(var repo=new Repository(Path.Combine(root,"changed-export-repo"))){var rows=ExportFixture(repo,"changed-export-source");string destination=ExportDestinationFolder("changed-export-destination");File.AppendAllText(repo.FilePath(rows[0]),"changed");Expect(()=>Exporter.Create(repo,rows,new ExportOptions{Parent=destination,Mode="Files"},ct,NoProgress),"Changed source was exported");Check(!Directory.EnumerateFileSystemEntries(destination).Any(),"Failed verification left an output or partial");}
   });
   Test("A destination containing the repository cannot export through a matching subs folder",()=>{
    string parent=ExportDestinationFolder("nested-boundary-export-destination");using(var repo=new Repository(Path.Combine(parent,"subs"))){var rows=ExportFixture(repo,"nested-boundary-export-source",true);string original=repo.FilePath(rows[0]);Expect(()=>Exporter.Create(repo,rows,new ExportOptions{Parent=parent,Mode="Files"},ct,NoProgress),"Nested output entered repository");Check(Directory.GetFileSystemEntries(parent).Length==1&&Util.Hash(original,ct)==rows[0].Hash,"Overlap validation changed the destination or repository");}
   });
   Test("Export validates destinations before creating any output",()=>{
    using(var repo=new Repository(Path.Combine(root,"boundary-export-repo"))){var rows=ExportFixture(repo,"boundary-export-source");Expect(()=>Exporter.Create(repo,rows,new ExportOptions{Parent=repo.Root,Mode="Files"},ct,NoProgress),"Repository accepted as destination");string missing=Path.Combine(root,"missing-export-destination");Expect(()=>Exporter.Create(repo,rows,new ExportOptions{Parent=missing,Mode="Files"},ct,NoProgress),"Nonexistent parent accepted");Check(!Directory.Exists(missing),"Invalid destination was created");string destination=ExportDestinationFolder("boundary-export-destination");Expect(()=>Exporter.Create(repo,rows,new ExportOptions{Parent=destination,Mode="Files",CreateNewFolder=true},ct,NoProgress),"Unnamed folder accepted");Check(!Directory.EnumerateFileSystemEntries(destination).Any(),"Invalid folder option wrote output");}
   });
  }
 }
}
