// .NET Framework 4.8. Bounded copy tasks; only the coordinator commits SQLite records.
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
namespace AstroArchive {
 public sealed partial class Repository {
  class Prepared {public Frame Frame;public string Temp;public FileStamp Stamp;public Exception Error;public PipelineMetrics.Transfer Transfer;}
  public static bool TryRemove(string path){try{if(File.Exists(path))File.Delete(path);return true;}catch{return false;}}
  public static void CommitTemporary(string temp,string destination,CancellationToken ct){FileRetry.Run(()=>{if(!File.Exists(destination)){File.Move(temp,destination);return true;}try{File.Replace(temp,destination,null);}catch(NotSupportedException){string backup=destination+"."+Guid.NewGuid().ToString("N")+".bak";File.Move(destination,backup);try{File.Move(temp,destination);}catch{File.Move(backup,destination);throw;}TryRemove(backup);}return true;},ct,null);}
  void Manifest(SourceManifest record){db.Exec("INSERT OR REPLACE INTO source_manifest(root,path,identity,size,mtime,hash,destination,status,data) VALUES(?,?,?,?,?,?,?,?,?)",record.Root,record.Path,record.Source==null?"":record.Source.Identity,record.Source==null?"":record.Source.Size.ToString(),record.Source==null?"":record.Source.Modified.ToString(),record.Hash,record.Destination,record.Status,Util.Serialize(record));}
  public string CacheGet(string key){return db.Query("SELECT data FROM sessions WHERE id=?",key).FirstOrDefault();}
  public void CachePut(string key,string data){db.Exec("INSERT OR REPLACE INTO sessions(id,data) VALUES(?,?)",key,data);}
  public string SolverKey(Frame f,Settings settings){string version="";try{if(File.Exists(settings.Astap)){var info=new FileInfo(settings.Astap);version=info.Length+":"+info.LastWriteTimeUtc.Ticks;}}catch{}return "solve180:"+Util.HashText(f.Hash+"|"+f.ImageKey+"|"+f.ImageIndex+"|"+settings.UseOnline+"|"+settings.Astap+"|"+version+"|"+settings.StarDatabase+"|"+settings.FieldHeight);}
  public SolveResult CachedSolve(Frame f,Settings settings,CancellationToken ct,Action<string> progress,Action<int> counted=null){string key=SolverKey(f,settings),cache=CacheGet(key);ValidateCapture(f,ct);if(cache!=null)return Util.Deserialize<SolveResult>(cache);var result=PlateSolve.Solve(f,FilePath(f),settings,ct,progress,counted);CachePut(key,Util.Serialize(result));return result;}
  public void ValidateCapture(Frame f,CancellationToken ct){string path=FilePath(f);var before=FileStamp.Read(path);if(f.RepositoryStamp!=null&&before.VerifiedUnchanged(f.RepositoryStamp))return;if(Util.Hash(path,ct)!=f.Hash)throw new InvalidDataException("Repository contents changed; cached analysis was not applied: "+path);var after=FileStamp.Read(path);if(!before.ContentSame(after))throw new InvalidDataException("Repository file changed during verification: "+path);f.RepositoryStamp=after;Save(f);}
  public void SaveImportReport(ImportResult result){LastReport="AstroArchive import report\r\nArchive: "+Root+"\r\nWorking index: "+WorkingIndex+"\r\n"+result.Imported+" imported; "+(result.Duplicates-result.FastSkipped)+" verified duplicates; "+result.FastSkipped+" unchanged archived inventory skipped; "+result.Failed+" failed; "+result.SkippedDeleted+" previously deleted skipped; "+result.IgnoredFailed+" failed filenames ignored; "+result.IgnoredRaster+" PNG/JPG files ignored; "+result.OriginalsDeleted+" originals deleted.\r\n\r\n"+result.Metrics.Report()+"\r\n\r\nWorker trials (real import batches; workload/cache effects apply):\r\n"+string.Join("\r\n",result.Trials.Select(t=>t.Workers+" workers: "+t.Files+" files, "+t.MBPerSecond.ToString("0.00")+" MB/s, "+t.Failed+" failures"))+"\r\n\r\n"+string.Join("\r\n",result.Errors.Concat(result.CleanupErrors).Concat(result.Warnings));try{File.WriteAllText(Path.Combine(Path.GetDirectoryName(WorkingIndex),"last-import.txt"),LastReport);Directory.CreateDirectory(Path.Combine(Meta,"reports"));File.WriteAllText(Path.Combine(Meta,"reports","last-import.txt"),LastReport);}catch{}}
  Prepared Prepare(Frame original,ImportOptions options,PipelineMetrics metrics,CancellationToken ct,PipelineMetrics.Transfer transfer){var result=new Prepared{Frame=original.Clone(),Transfer=transfer};string directory=Path.Combine(Meta,"staging");result.Temp=Path.Combine(directory,Guid.NewGuid().ToString("N")+".partial");
   try{Directory.CreateDirectory(directory);FileRetry.Run(()=>{TryRemove(result.Temp);transfer.Reset();var before=FileStamp.Read(original.SourcePath);if(original.SourceStamp!=null&&!original.SourceStamp.ContentSame(before))throw new InvalidDataException("Source changed since scanning. Scan again; original retained.");string hash=FileTransfer.CopyHash(original.SourcePath,result.Temp,ct,metrics,options.CloudSource||before.Cloud,transfer);var after=FileStamp.Read(original.SourcePath);if(!before.ContentSame(after))throw new InvalidDataException("Source changed during copying. Original retained.");if(!string.IsNullOrEmpty(original.Hash)&&hash!=original.Hash)throw new InvalidDataException("Source checksum changed since scanning. Original retained.");using(var verify=metrics.Begin("Verification",original.OriginalName)){transfer.BeginVerification();if(Util.Hash(result.Temp,ct,n=>{verify.Bytes(n);transfer.Verified(n);})!=hash)throw new InvalidDataException("Copied file failed SHA-256 verification.");transfer.EndVerification();verify.Complete();}result.Frame.Hash=hash;result.Frame.SourceStamp=after;result.Stamp=after;return true;},ct,message=>{metrics.Current=message;metrics.Pulse(true);});}catch(Exception e){result.Error=e;TryRemove(result.Temp);}return result;
  }
  void Sidecar(Frame f,CancellationToken ct,Dictionary<string,Tuple<FileStamp,string>> copied){if(string.IsNullOrEmpty(f.SourceMetadataPath)||!File.Exists(f.SourceMetadataPath))return;var before=FileStamp.Read(f.SourceMetadataPath);if(f.SourceMetadataStamp!=null&&!f.SourceMetadataStamp.ContentSame(before))throw new InvalidDataException("Session metadata changed since scanning. Scan again.");Tuple<FileStamp,string> cached;if(copied.TryGetValue(f.SourceMetadataPath,out cached)&&cached.Item1.ContentSame(before)){f.SidecarRelativePath=cached.Item2;return;}string sha=Util.Hash(f.SourceMetadataPath,ct),relative=Path.Combine(".astroarchive","session-metadata",sha+".json"),destination=Path.Combine(Root,relative);Directory.CreateDirectory(Path.GetDirectoryName(destination));if(!File.Exists(destination)){string temp=destination+"."+Guid.NewGuid().ToString("N")+".partial";try{FileRetry.Run(()=>{TryRemove(temp);CopyVerified(f.SourceMetadataPath,temp,sha,ct);File.Move(temp,destination);return true;},ct,null);}finally{TryRemove(temp);}}if(Util.Hash(destination,ct)!=sha)throw new InvalidDataException("Preserved session metadata failed verification: "+destination);var after=FileStamp.Read(f.SourceMetadataPath);if(!before.ContentSame(after))throw new InvalidDataException("Session metadata changed while copying.");f.SidecarRelativePath=relative;copied[f.SourceMetadataPath]=Tuple.Create(after,relative);}
  void UpdateOriginal(Frame old,Frame current){old.Hash=current.Hash;old.RelativePath=current.RelativePath;old.SourceStamp=current.SourceStamp;old.RepositoryStamp=current.RepositoryStamp;old.SidecarRelativePath=current.SidecarRelativePath;old.AssociatedFiles=current.AssociatedFiles;old.SourceDisposition=current.SourceDisposition;old.Status=current.Status;old.Notes=current.Notes;old.ScreeningIssue=current.ScreeningIssue;old.IntegrityIssue=current.IntegrityIssue;old.TransferIssue=current.TransferIssue;}
  public ImportResult Import(IEnumerable<Frame> frames,CancellationToken ct,Action<ProgressInfo> progress,ImportOptions options=null){options=options??new ImportOptions();if(options.DumpInbox){ValidateDumpFolder();if(!string.Equals(Path.GetFullPath(options.SourceRoot),DumpFolder,StringComparison.OrdinalIgnoreCase))throw new IOException("Invalid dump source root.");}else if(options.DeleteOriginals)SourceCleanup.ValidateRoots(options.SourceRoot,Root);var candidates=frames.Where(CaptureScreening.Importable).ToList();int ignored=options.IgnoreFailed?candidates.Count(Util.FailedFilename):0;int ignoredRaster=options.IgnoreRaster?candidates.Count(f=>(!options.IgnoreFailed||!Util.FailedFilename(f))&&ImportPolicy.RasterFilename(f.OriginalName??f.SourcePath)):0;var list=candidates.Where(f=>(!options.IgnoreFailed||!Util.FailedFilename(f))&&(!options.IgnoreRaster||!ImportPolicy.RasterFilename(f.OriginalName??f.SourcePath))).ToList();var deleted=DeletedHashes();string source=options.SourceRoot??(list.Count>0?(list[0].SourceRoot??Path.GetDirectoryName(list[0].SourcePath)):Root);var metrics=new PipelineMetrics(progress);metrics.Phase(list.Count,list.Sum(f=>f.Bytes),"Importing",true,true,options.DeleteOriginals);if(options.ScanMetrics!=null)metrics.Accumulate(options.ScanMetrics.Snapshot());var result=new ImportResult{Metrics=metrics,IgnoredFailed=ignored,IgnoredRaster=ignoredRaster};var known=new Dictionary<string,Frame>();var copiedSidecars=new Dictionary<string,Tuple<FileStamp,string>>(StringComparer.OrdinalIgnoreCase);int completed=0;long median=list.Count==0?0:list.OrderBy(f=>f.Bytes).ElementAt(list.Count/2).Bytes;string profile="workers150:"+Util.HashText(Path.GetPathRoot(source)+"|"+Path.GetPathRoot(Root)+"|"+source+"|"+Root+"|"+(options.CloudSource||list.Any(f=>f.SourceStamp!=null&&f.SourceStamp.Cloud))+"|"+(median<1000000?"small":median<16000000?"medium":"large"));double priorRatio;if(double.TryParse(CacheGet("eta150:"+profile),System.Globalization.NumberStyles.Float,System.Globalization.CultureInfo.InvariantCulture,out priorRatio))metrics.SeedVerificationWeight(priorRatio);int saved=0;int.TryParse(CacheGet(profile),out saved);int workers=options.Workers>0?Math.Max(1,Math.Min(8,options.Workers)):saved>0?Math.Min(8,saved):1;var pilotCandidates=list.Where(f=>f.Bytes<=33554432).OrderBy(f=>f.Bytes).ToList();bool tune=pilotCandidates.Count>=32&&options.Workers==0&&(options.Retune||saved==0)&&list.Count>=64&&metrics.TotalBytes>=64000000;var trials=new List<WorkerTrial>();result.Trials=trials;bool pilotActive=tune,completedNormally=false;
   using(var linked=CancellationTokenSource.CreateLinkedTokenSource(ct)){Action<List<Frame>,int> batch=(items,count)=>{var watch=Stopwatch.StartNew();int failuresBefore=result.Failed;var pending=new Dictionary<Task<Prepared>,Frame>();int next=0;try{while(next<items.Count||pending.Count>0){ct.ThrowIfCancellationRequested();metrics.Workers(count);while(next<items.Count&&pending.Count<count){Frame original=items[next++];Manifest(new SourceManifest{Root=source,Path=original.SourcePath,Hash=original.Hash,Source=original.SourceStamp,Status="Copying"});original.Status="Copying";if(options.OnFrame!=null)options.OnFrame(original.Clone());var captured=original;var transfer=metrics.Track(original.Bytes);pending.Add(Task.Run(()=>Prepare(captured,options,metrics,linked.Token,transfer),linked.Token),original);}var finished=Task.WhenAny(pending.Keys).GetAwaiter().GetResult();var originalFrame=pending[finished];pending.Remove(finished);var prepared=finished.GetAwaiter().GetResult();try{
       if(prepared.Error!=null){if(prepared.Error is OperationCanceledException)throw prepared.Error;throw prepared.Error;}Frame current=prepared.Frame,existing;if(deleted.Contains(current.Hash)){MarkDeleted(current);Manifest(new SourceManifest{Root=source,Path=current.SourcePath,Hash=current.Hash,Source=prepared.Stamp,Status="Deleted",Metadata=current});UpdateOriginal(originalFrame,current);result.SkippedDeleted++;if(options.OnFrame!=null)options.OnFrame(current.Clone());continue;}bool duplicate=false;string relative,destination;
       if(options.DumpInbox){if(!known.TryGetValue(current.Hash,out existing))existing=Find(current.Hash);if(existing!=null){var retained=existing.Clone();retained.SourcePath=current.SourcePath;retained.SourceRoot=current.SourceRoot;retained.SourceStamp=current.SourceStamp;retained.SourceMetadataPath=current.SourceMetadataPath;retained.SourceMetadataStamp=current.SourceMetadataStamp;current=retained;}}
       using(var check=metrics.Begin("Duplicate checking",current.OriginalName)){duplicate=false;if(!known.TryGetValue(current.Hash,out existing))existing=Find(current.Hash);if(existing!=null&&File.Exists(FilePath(existing))){var stamp=FileStamp.Read(FilePath(existing));duplicate=stamp.VerifiedUnchanged(existing.RepositoryStamp)||Util.Hash(FilePath(existing),ct,n=>check.Bytes(n))==current.Hash;}relative=duplicate?existing.RelativePath:Destination(current);destination=Path.Combine(Root,relative);check.Complete();}
       if(duplicate){current.RelativePath=relative;current.Status="Duplicate";current.TransferIssue=null;current.SourceDisposition="Original retained (verified duplicate)";result.Duplicates++;}
       else{Directory.CreateDirectory(Path.GetDirectoryName(destination));bool exists=File.Exists(destination);string destinationHash=exists?Util.Hash(destination,ct):null;if(exists&&destinationHash!=current.Hash){relative=Path.Combine(Path.GetDirectoryName(relative),current.Hash+"_recovered_"+Util.SafeFile(current.OriginalName));destination=Path.Combine(Root,relative);exists=File.Exists(destination);destinationHash=exists?Util.Hash(destination,ct):null;}if(exists){if(destinationHash!=current.Hash)throw new IOException("Conflicting repository destination: "+destination);}else FileRetry.Run(()=>{File.Move(prepared.Temp,destination);return true;},ct,message=>{metrics.Current=message;metrics.Pulse(true);});Sidecar(current,ct,copiedSidecars);PreserveAssociated(current,ct,copiedSidecars);current.RelativePath=relative;current.Status="Imported";current.TransferIssue=null;current.SourceDisposition="Original retained";}
       current.RepositoryStamp=FileStamp.Read(destination);var entry=new SourceManifest{Root=source,Path=current.SourcePath,Hash=current.Hash,Destination=relative,Status="Complete",Source=prepared.Stamp,Copy=current.RepositoryStamp,Metadata=current};using(var index=metrics.Begin("Index/checkpoint",current.OriginalName)){db.Transaction(()=>{if(!duplicate)Save(current);Manifest(entry);});if(!duplicate)known[current.Hash]=current;index.Complete();}
       if(!duplicate)result.Imported++;if((!duplicate||options.DumpInbox)&&options.DeleteOriginals){try{using(var stage=metrics.Begin("Index/checkpoint","Saving verified archive index before source removal")){Checkpoint(ct);stage.Complete();}if(!prepared.Stamp.ContentSame(FileStamp.Read(current.SourcePath)))throw new IOException("Source changed before final cleanup.");using(var cleanup=metrics.Begin("Source cleanup",current.OriginalName)){if(options.DumpInbox)SourceCleanup.DeleteDumpVerified(current.SourcePath,destination,current.Hash,Root,ct,n=>{cleanup.Bytes(n);prepared.Transfer.Cleanup(n);});else SourceCleanup.DeleteVerified(current.SourcePath,destination,current.Hash,source,Root,ct,n=>{cleanup.Bytes(n);prepared.Transfer.Cleanup(n);});cleanup.Complete();}current.SourceDisposition="Original deleted after verified import";result.OriginalsDeleted++;}catch(OperationCanceledException){throw;}catch(Exception e){current.SourceDisposition="Original retained: "+e.Message;result.OriginalsKept++;result.CleanupErrors.Add(FileRetry.Detail(current.SourcePath,e));}if(!duplicate)Save(current);}
       UpdateOriginal(originalFrame,current);if(options.OnFrame!=null)options.OnFrame(current.Clone());
      }catch(OperationCanceledException){throw;}catch(Exception e){originalFrame.Status="Failed";originalFrame.TransferIssue=FileRetry.Detail(originalFrame.SourcePath,e);if(e is InvalidDataException)originalFrame.IntegrityIssue=originalFrame.ScreeningIssue=originalFrame.TransferIssue;originalFrame.Notes=(originalFrame.Notes??"")+e.Message+". ";result.Failed++;result.Errors.Add(FileRetry.Detail(originalFrame.SourcePath,e));Manifest(new SourceManifest{Root=source,Path=originalFrame.SourcePath,Hash=originalFrame.Hash,Source=originalFrame.SourceStamp,Status="Failed",Metadata=originalFrame});if(options.OnFrame!=null)options.OnFrame(originalFrame.Clone());if(FileRetry.DiskFull(e))throw new IOException("Destination disk is full. Completed imports are retained; free space and scan again.",e);}finally{TryRemove(prepared.Temp);completed++;prepared.Transfer.Resolve(originalFrame.Status=="Imported"||originalFrame.Status=="Duplicate");}
      if(!pilotActive&&(DateTime.UtcNow-checkpoint).TotalSeconds>=10){try{using(var stage=metrics.Begin("Index/checkpoint","Saving portable index")){Checkpoint(ct);stage.Complete();}}catch(OperationCanceledException){throw;}catch(Exception e){if(!result.Warnings.Any())result.Warnings.Add("Portable index checkpoint failed; the durable local index and verified copies are retained. "+e.Message);checkpoint=DateTime.UtcNow;}}
     }}catch{linked.Cancel();throw;}finally{foreach(var task in pending.Keys){try{var unfinished=task.GetAwaiter().GetResult();TryRemove(unfinished.Temp);}catch{}}}watch.Stop();trials.Add(new WorkerTrial{Workers=count,Files=items.Count,Bytes=items.Sum(f=>f.Bytes),Seconds=watch.Elapsed.TotalSeconds,Failed=result.Failed-failuresBefore});};
    try{var piloted=new HashSet<Frame>();if(tune){
     var sample=Enumerable.Range(0,32).Select(i=>pilotCandidates[(int)((long)i*(pilotCandidates.Count-1)/31)]).ToList();double bestRate=0;
     for(int trial=0;trial<4;trial++){int candidate=new[]{1,2,4,8}[trial];var items=sample.Where((f,i)=>i%4==trial).ToList();foreach(var frame in items)piloted.Add(frame);batch(items,candidate);var measured=trials.Last();if(measured.Failed>0||(trial>0&&measured.MBPerSecond<=bestRate*1.05))break;bestRate=Math.Max(bestRate,measured.MBPerSecond);}
     var baseline=trials.First();var best=trials.Where(t=>t.Failed==0).OrderByDescending(t=>t.MBPerSecond).ThenBy(t=>t.Workers).FirstOrDefault();workers=best!=null&&best.MBPerSecond>baseline.MBPerSecond*1.1?best.Workers:1;CachePut(profile,workers.ToString());pilotActive=false;
    }var remaining=list.Where(f=>!piloted.Contains(f)).ToList();if(remaining.Count>0)batch(remaining,workers);result.Workers=workers;result.Trials=trials;metrics.Current=result.Imported+" imported; "+result.Duplicates+" duplicates; "+result.Failed+" failed";metrics.Pulse(true);completedNormally=true;return result;
    }finally{linked.Cancel();metrics.Finalise("Saving final portable index and report");if(completedNormally&&metrics.HasVerificationTiming){try{CachePut("eta150:"+profile,metrics.VerificationWeight.ToString("R",System.Globalization.CultureInfo.InvariantCulture));}catch(Exception e){result.Warnings.Add("ETA profile could not be saved: "+e.Message);}}try{using(var stage=metrics.Begin("Index/checkpoint","Saving final portable index")){Checkpoint(CancellationToken.None);stage.Complete();}}catch(Exception e){result.Warnings.Add("Portable index checkpoint failed; local index and verified copies retained. "+e.Message);}SaveImportReport(result);if(completedNormally&&!options.DeferFinish&&!ct.IsCancellationRequested)metrics.Finish(result.Imported+" imported; "+result.Duplicates+" duplicates; "+result.Failed+" failed");}
   }
  }
 }
}
