using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using AstroArchive.Remote;
using RemoteConnection=AstroArchive.Remote.Connection;
namespace AstroArchive {
 public static class RemoteIntegrationTests {
  static int checks;static void Check(bool value,string text){if(!value)throw new Exception(text);checks++;Console.WriteLine("PASS remote: "+text);}static void Reject(Action action,string text){try{action();}catch(InvalidDataException){Check(true,text);return;}catch(IOException){Check(true,text);return;}throw new Exception("Expected rejection: "+text);}
  static void Fits(string file,int value){Directory.CreateDirectory(Path.GetDirectoryName(file));string[] cards={"SIMPLE  =                    T","BITPIX  =                   16","NAXIS   =                    2","NAXIS1  =                   64","NAXIS2  =                   48","BZERO   =                32768","OBJECT  = 'M31'","EXPTIME =                   10","DATE-OBS= '2026-10-09T20:00:00'","END"};using(var s=File.Create(file)){byte[] header=Encoding.ASCII.GetBytes(string.Concat(cards.Select(c=>c.PadRight(80))).PadRight(2880));s.Write(header,0,header.Length);for(int i=0;i<64*48;i++){short n=(short)(value-32768);s.WriteByte((byte)(n>>8));s.WriteByte((byte)n);}while(s.Length%2880!=0)s.WriteByte(0);}}
  sealed class Fixture:ISource {
   readonly string root;readonly RemoteConnection c;readonly Action<string> opened;public Fixture(string root,RemoteConnection c,Action<string> opened=null){this.root=root;this.c=c;this.opened=opened;}string Local(string p){return p.TrimEnd('\\','/')==c.Folder.TrimEnd('\\','/')?root:Path.Combine(root,RemoteCapturePaths.Relative(c,p));}
   public List<Entry> List(string folder){return new DirectoryInfo(Local(folder)).GetFileSystemInfos().Select(f=>new Entry{Path=RemoteCapturePaths.Join(c,folder,f.Name),Name=f.Name,Directory=f is DirectoryInfo,Size=f is FileInfo?((FileInfo)f).Length:0,Modified=f.LastWriteTimeUtc}).ToList();}
   public Entry Stat(string path){var f=new FileInfo(Local(path));return new Entry{Path=path,Name=f.Name,Size=f.Length,Modified=f.LastWriteTimeUtc};}public Stream Open(string path){if(opened!=null)opened(path);return File.OpenRead(Local(path));}public void Dispose(){}
  }
  sealed class EscapeSource:ISource {public List<Entry> List(string folder){return new List<Entry>{new Entry{Path=@"\\127.0.0.2\EMMC Images\escape.fit",Name="escape.fit",Size=1}};}public Stream Open(string path){throw new Exception("Should never read unsafe entries");}public Entry Stat(string path){throw new Exception();}public void Dispose(){}}
  public static void NativeTransport(string root,int port,bool ftp){
   string storage=Path.Combine(root,"storage"),file=Path.Combine(storage,"MyWorks","native","Light_native_"+(ftp?"ftp":"smb")+".fit");Fits(file,ftp?1600:1500);File.WriteAllText(Path.Combine(Path.GetDirectoryName(file),"session.json"),"{\"target\":\"M31\"}");
   var c=new RemoteConnection{Kind=ftp?"DWARF FTP":"Seestar SMB",Host="127.0.0.1",Folder=ftp?"/":@"\\127.0.0.1\EMMC Images",Port=port,SmbPort=port,LimitMB=0};List<Entry> chosen;using(var source=Downloader.Source(c))chosen=RemoteCaptureCatalog.Search(source,c,c.Folder,CancellationToken.None).Where(e=>e.Name==Path.GetFileName(file)).ToList();Check(chosen.Count==1,"real "+(ftp?"FTP":"SMB")+" catalog finds the native fixture");
   Repository.LocalIndexBase=Path.Combine(root,"native-indexes");using(var repo=new Repository(Path.Combine(root,ftp?"ftp-archive":"smb-archive"))){var profile=new TelescopeProfile{Id=ftp?"Network DWARF":"Network Seestar",Model=ftp?"Dwarf 3":"Seestar S50",Camera="Auto"};var result=RemoteArchiveImport.Run(repo,profile,c,chosen,Path.Combine(root,"native-cache"),1,CancellationToken.None,p=>{});Check(result.Archive.Import.Imported==1,"real "+(ftp?"FTP":"SMB")+" download imports into the archive");var frame=repo.All().Single();Check(frame.Hash==Util.Hash(file,CancellationToken.None)&&Util.Hash(repo.FilePath(frame),CancellationToken.None)==frame.Hash,"real transport preserves exact original and archived bytes");Check(frame.AssociatedFiles!=null&&frame.AssociatedFiles.Any(a=>!string.IsNullOrEmpty(a.RelativePath)),"real transport preserves adjacent session metadata");var repeat=RemoteArchiveImport.Run(repo,profile,c,chosen,Path.Combine(root,"native-cache"),1,CancellationToken.None,p=>{});Check(repeat.Downloads.Reused==1&&repo.All().Count==1,"real transport retry reuses verified bytes without duplicate archive entries");Check(File.Exists(file)&&repo.Verify(CancellationToken.None,p=>{})==0,"real read-only transport leaves the source unchanged");}
   Console.WriteLine("Native "+(ftp?"FTP":"SMB")+" archive integration passed.");
  }
  static void ConcurrentImports(string root,RemoteConnection firstConnection){
   string firstRoot=Path.Combine(root,"parallel-one"),secondRoot=Path.Combine(root,"parallel-two"),firstFile=Path.Combine(firstRoot,"MyWorks","Light_parallel.fit"),secondFile=Path.Combine(secondRoot,"MyWorks","Light_parallel.fit");Fits(firstFile,1700);Directory.CreateDirectory(Path.GetDirectoryName(secondFile));File.Copy(firstFile,secondFile);
   var secondConnection=Util.Deserialize<RemoteConnection>(Util.Serialize(firstConnection));secondConnection.Host="127.0.0.2";secondConnection.Folder=@"\\127.0.0.2\EMMC Images";
   var firstProfile=new TelescopeProfile{Id="Parallel S50",Model="Seestar S50",Camera="Auto"};var secondProfile=new TelescopeProfile{Id="Parallel S30",Model="Seestar S30",Camera="Auto"};string cache=Path.Combine(root,"parallel-cache");
   Func<RemoteConnection,ISource> factory=c=>new Fixture(c.Host==firstConnection.Host?firstRoot:secondRoot,c);
   List<Entry> first,second;using(var source=factory(firstConnection))first=RemoteCaptureCatalog.Search(source,firstConnection,firstConnection.Folder,CancellationToken.None);using(var source=factory(secondConnection))second=RemoteCaptureCatalog.Search(source,secondConnection,secondConnection.Folder,CancellationToken.None);
   using(var repo=new Repository(Path.Combine(root,"parallel-archive")))using(var opened=new CountdownEvent(2))using(var release=new ManualResetEvent(false)){
    Func<RemoteConnection,ISource> blocked=c=>new Fixture(c.Host==firstConnection.Host?firstRoot:secondRoot,c,path=>{if(path.EndsWith(".fit")){opened.Signal();if(!release.WaitOne(10000))throw new IOException("Parallel downloads did not overlap");}});
    var a=Task.Run(()=>RemoteArchiveImport.Run(repo,firstProfile,firstConnection,first,cache,1,CancellationToken.None,p=>{},sourceFactory:blocked));
    var b=Task.Run(()=>RemoteArchiveImport.Run(repo,secondProfile,secondConnection,second,cache,1,CancellationToken.None,p=>{},sourceFactory:blocked));
    bool overlap=opened.Wait(8000);release.Set();Task.WaitAll(a,b);Check(overlap,"different telescopes download simultaneously");
    Check(a.Result.Archive.Import.Imported+b.Result.Archive.Import.Imported==1&&a.Result.Archive.Import.Duplicates+b.Result.Archive.Import.Duplicates==1&&repo.All().Count==1,"simultaneous identical captures commit once and report the other as a duplicate");
    Fits(secondFile,1800);using(var source=factory(secondConnection))second=RemoteCaptureCatalog.Search(source,secondConnection,secondConnection.Folder,CancellationToken.None);
    var unique=RemoteArchiveImport.Run(repo,secondProfile,secondConnection,second,cache,1,CancellationToken.None,p=>{},sourceFactory:factory);
    Check(unique.Archive.Import.Imported==1&&repo.All().Any(f=>f.Telescope==secondProfile.Id)&&repo.Verify(CancellationToken.None,p=>{})==0,"distinct telescope captures retain their identity and verified archive bytes");
   }
   // Force two selections to overlap on one cache, then cancel only the waiter.
   using(var repo=new Repository(Path.Combine(root,"queue-archive")))using(var transferStarted=new ManualResetEvent(false))using(var release=new ManualResetEvent(false))using(var queued=new ManualResetEvent(false))using(var canceled=new CancellationTokenSource()){
    string queueCache=Path.Combine(root,"queue-cache");int opens=0;Func<RemoteConnection,ISource> blocked=c=>new Fixture(firstRoot,c,path=>{Interlocked.Increment(ref opens);transferStarted.Set();if(!release.WaitOne(10000))throw new IOException("Fixture transfer timed out");});
    var a=Task.Run(()=>RemoteArchiveImport.Run(repo,firstProfile,firstConnection,first,queueCache,1,CancellationToken.None,p=>{},sourceFactory:blocked));
    Check(transferStarted.WaitOne(8000),"first selected download holds its cache lease");
    var b=Task.Run(()=>RemoteArchiveImport.Run(repo,firstProfile,firstConnection,first,queueCache,1,canceled.Token,p=>{if(p.Stage=="Waiting for telescope download")queued.Set();},sourceFactory:factory));
    try{Check(queued.WaitOne(8000),"overlapping selections wait without a download-lock error");canceled.Cancel();try{b.GetAwaiter().GetResult();throw new Exception("Queued import ignored cancellation");}catch(OperationCanceledException){Check(!a.IsCompleted,"canceling a queued selection leaves the active download running");}}
    finally{release.Set();a.GetAwaiter().GetResult();}
    var repeat=RemoteArchiveImport.Run(repo,firstProfile,firstConnection,first,queueCache,1,CancellationToken.None,p=>{},sourceFactory:factory);
    Check(opens==1&&repeat.Downloads.Reused==1&&repeat.Archive.Import.Duplicates==1&&repo.All().Count==1,"overlapping retry reuses verified bytes and never duplicates the archive");
    Check(!Directory.EnumerateFiles(queueCache,"*.partial",SearchOption.AllDirectories).Any()&&repo.Verify(CancellationToken.None,p=>{})==0,"canceled cache waiter leaves no partials or archive corruption");
   }
   using(var repo=new Repository(Path.Combine(root,"live-selection-archive")))using(var stopped=new CancellationTokenSource())using(var baseline=new ManualResetEvent(false))using(var batchDone=new ManualResetEvent(false)){
    string liveCache=Path.Combine(root,"live-selection-cache");int liveImported=0,liveDuplicates=0;
    var watching=Task.Run(()=>RemoteLiveImport.Run(repo,firstProfile,firstConnection,liveCache,1,stopped.Token,p=>{if(p.Stage=="Live import")baseline.Set();},null,null,false,false,factory,r=>{Interlocked.Add(ref liveImported,r.Archive.Import.Imported);Interlocked.Add(ref liveDuplicates,r.Archive.Import.Duplicates);batchDone.Set();}));
    try{
     Check(baseline.WaitOne(8000),"live watcher is running before additional selections");
     var selected=RemoteArchiveImport.Run(repo,firstProfile,firstConnection,first,liveCache,1,CancellationToken.None,p=>{},sourceFactory:factory);
     Check(selected.Archive.Import.Imported==1&&!watching.IsCompleted,"existing captures can be downloaded without stopping live import");
     string fresh=Path.Combine(firstRoot,"MyWorks","Light_manual_then_live.fit");Fits(fresh,1900);
     List<Entry> freshEntries;using(var source=factory(firstConnection))freshEntries=RemoteCaptureCatalog.Search(source,firstConnection,firstConnection.Folder,CancellationToken.None).Where(e=>e.Name==Path.GetFileName(fresh)).ToList();
     var manual=RemoteArchiveImport.Run(repo,firstProfile,firstConnection,freshEntries,liveCache,1,CancellationToken.None,p=>{},sourceFactory:factory);
     Check(batchDone.WaitOne(12000),"live watcher processes a capture also selected manually");
     Check(manual.Archive.Import.Imported+liveImported==1&&manual.Archive.Import.Duplicates+liveDuplicates==1&&repo.All().Count==2,"manual and live overlap produce exactly one capture with duplicate accounting");
    }finally{stopped.Cancel();try{watching.GetAwaiter().GetResult();}catch(OperationCanceledException){}}
    Check(repo.Verify(CancellationToken.None,p=>{})==0&&File.Exists(firstFile),"stopping live import retains selected downloads and original telescope files");
   }
  }
  static void RecoveryChecks(string root,RemoteConnection connection){
   var estimator=new RemoteTransferEstimate(10*1048576,1);var first=estimator.Sample(0,0,1,"capture.fit",0);Check(first.RemainingSeconds.HasValue&&Math.Abs(first.RemainingSeconds.Value-10)<.01,"limited transfers have a numeric ETA before the first chunk");
   var measured=new RemoteTransferEstimate(10*1048576,0);var rate=measured.Sample(1048576,0,1,"capture.fit",1);Check(rate.RemainingSeconds.HasValue&&rate.RemainingSeconds.Value>0&&rate.EffectiveBytesPerSecond==1048576,"unlimited transfer ETA uses measured bytes rather than file count");
   var cached=measured.Sample(9*1048576,1,2,"cached.fit",1.1,true);Check(cached.EffectiveBytesPerSecond==rate.EffectiveBytesPerSecond,"cache reuse does not inflate measured network speed");Check(measured.Sample(10*1048576,2,2,"done",2,true).RemainingSeconds==0,"network ETA reaches zero when all bytes are accounted for");
   var baseline=new Entry{Path="/old.fit",Name="old.fit",Size=5760,Modified=DateTime.UtcNow};var fresh=new Entry{Path="/while-paused.fit",Name="while-paused.fit",Size=5760,Modified=DateTime.UtcNow};
   var tracker=new RemoteLiveTracker();tracker.Observe(new[]{baseline},false);var state=tracker.Snapshot();var resumed=new RemoteLiveTracker(Util.Deserialize<RemoteLiveState>(Util.Serialize(state)));Check(resumed.Observe(new[]{baseline,fresh},false).Count==0&&resumed.Observe(new[]{baseline,fresh},false).Single().Path==fresh.Path,"live recovery preserves baseline and includes captures created while paused");resumed.Imported(fresh.Path);var again=new RemoteLiveTracker(resumed.Snapshot());again.Observe(new[]{baseline,fresh},false);Check(again.Observe(new[]{baseline,fresh},false).Count==0,"live recovery retains completed capture acknowledgements");
   string jobs=Path.Combine(root,"recovery-jobs"),source=Path.Combine(root,"recovery-source");for(int i=0;i<3;i++)Fits(Path.Combine(source,"Light_recovery_"+i+".fit"),2800+i);
   var store=new ImportResumeStore(jobs);using(var repository=new Repository(Path.Combine(root,"recovery-archive"))){
    var plan=repository.Scan(source,"Resume scope","Seestar S50",CancellationToken.None,p=>{},fullScan:true);var record=new ImportResumeRecord{Kind="Files",Title="Recovery test",Repository=repository.Root,Source=source,Frames=plan.Frames.Select(f=>f.Clone()).ToList(),Workers=1};store.Save(record);
    var firstFrame=plan.Frames.First();repository.Import(new List<Frame>{firstFrame},CancellationToken.None,p=>{},new ImportOptions{SourceRoot=source,Workers=1,OnFrame=f=>store.Completed(record,f)});File.Delete(firstFrame.SourcePath);
    File.AppendAllText(Path.Combine(jobs,record.Id+".completed"),"{truncated");var loaded=new ImportResumeStore(jobs).Load().Single();Check(loaded.State=="Interrupted"&&loaded.Frames.Count==3,"a restarted process restores the persisted queue and marks an unclean exit interrupted");
    var pending=store.Remaining(loaded,repository,CancellationToken.None);Check(pending.Count==2&&!pending.Any(f=>f.SourcePath==firstFrame.SourcePath),"resume verifies completed archive bytes even when the source was removed and final acknowledgement was truncated");
    var second=pending.First();repository.Import(new List<Frame>{second},CancellationToken.None,p=>{},new ImportOptions{SourceRoot=source,Workers=1});Check(store.Remaining(loaded,repository,CancellationToken.None).Count==1,"archive commit without journal acknowledgement is recovered without recopying");
    var result=repository.Import(store.Remaining(loaded,repository,CancellationToken.None),CancellationToken.None,p=>{},new ImportOptions{SourceRoot=source,Workers=1,OnFrame=f=>store.Completed(loaded,f)});Check(result.Imported==1&&repository.All().Count==3&&store.Remaining(loaded,repository,CancellationToken.None).Count==0&&repository.Verify(CancellationToken.None,p=>{})==0,"resumed folder import completes without duplicate archive rows");
    var stored=repository.Find(second.Hash);File.WriteAllBytes(repository.FilePath(stored),new byte[new FileInfo(second.SourcePath).Length]);Check(store.Remaining(loaded,repository,CancellationToken.None).Single().SourcePath==second.SourcePath,"recovery never trusts an acknowledgement when the archive copy is corrupt");
    loaded.State="Paused";store.Save(loaded);Check(new ImportResumeStore(jobs).Load().Single().State=="Paused","an intentional pause survives a restart or application update");store.Remove(loaded);Check(store.Load().Count==0&&!File.Exists(Path.Combine(jobs,record.Id+".completed")),"completed or discarded recovery records remove their queue and acknowledgements");
   }
   var secret=new ImportResumeRecord{Kind="RemoteFiles",Repository=Path.Combine(root,"secret-archive"),Connection=Util.Deserialize<RemoteConnection>(Util.Serialize(connection))};secret.Connection.Password="plaintext-never-write";Reject(()=>store.Save(secret),"recovery refuses plaintext telescope passwords");secret.ProtectedPassword=PlateSolve.Protect(secret.Connection.Password);secret.Connection.Password="";store.Save(secret);Check(!File.ReadAllText(Path.Combine(jobs,secret.Id+".json")).Contains("plaintext-never-write")&&PlateSolve.Unprotect(store.Load().Single().ProtectedPassword)=="plaintext-never-write","telescope credentials are recoverable only through protected storage");store.Remove(secret);
   string broken=Path.Combine(jobs,Guid.NewGuid().ToString("N")+".json");File.WriteAllText(broken,"{broken");Check(store.Load().Count==0&&store.Warnings.Count==1&&File.Exists(broken),"corrupt recovery records are reported and retained instead of silently discarded");
  }
  public static void Run(string root){
   string previousIndex=Repository.LocalIndexBase;try{checks=0;root=Path.Combine(root,"remote-integration");Directory.CreateDirectory(root);Repository.LocalIndexBase=Path.Combine(root,"indexes");var c=new RemoteConnection{Kind="Seestar SMB",Host="127.0.0.1",Folder=@"\\127.0.0.1\EMMC Images",LimitMB=0,IncludeExisting=false,PollSeconds=2};string storage=Path.Combine(root,"storage"),cache=Path.Combine(root,"cache"),one=Path.Combine(storage,"MyWorks","M31_sub","Light_M31_0001.fit");Fits(one,1000);File.WriteAllText(Path.Combine(Path.GetDirectoryName(one),"session.json"),"{\"target\":\"M31\"}");File.WriteAllText(Path.Combine(storage,"shotsInfo.json"),"{\"targetName\":\"M31\"}");Directory.CreateDirectory(Path.Combine(storage,".astroarchive"));Fits(Path.Combine(storage,".astroarchive","ignored.fit"),2000);
   Check(RemoteCapturePaths.Relative(c,c.Folder+@"\MyWorks\M31_sub\Light_M31_0001.fit")==Path.Combine("MyWorks","M31_sub","Light_M31_0001.fit"),"capture layout stays relative to telescope storage");Reject(()=>RemoteCapturePaths.Relative(c,@"\\127.0.0.2\EMMC Images\escape.fit"),"another telescope cannot escape selected storage");Reject(()=>RemoteCapturePaths.Relative(c,c.Folder+@"\..\escape.fit"),"remote traversal is rejected before any local write");
   List<Entry> captures;int opens=0;Func<RemoteConnection,ISource> factory=config=>new Fixture(storage,config,p=>opens++);using(var source=factory(c)){captures=RemoteCaptureCatalog.Search(source,c,c.Folder,CancellationToken.None);Check(captures.Count==1,"recursive search excludes sidecars and system folders");Check(opens==0,"search lists names without downloading image data");}
   using(var source=new EscapeSource())Reject(()=>RemoteCaptureCatalog.Search(source,c,c.Folder,CancellationToken.None),"untrusted directory listings cannot switch telescopes");
   Check(!RemoteCaptureCatalog.WarnForNetwork(Enumerable.Range(0,99).Select(i=>new Entry{Size=1})),"small file selections need no network warning");Check(RemoteCaptureCatalog.WarnForNetwork(Enumerable.Range(0,100).Select(i=>new Entry{Size=1})),"100 captures trigger the network versus USB warning");Check(RemoteCaptureCatalog.WarnForNetwork(new[]{new Entry{Size=1073741824}}),"large individual transfers also trigger the network warning");
   RemoteStagingResult first;using(var source=factory(c))first=RemoteCaptureStaging.Download(source,c,captures,cache,CancellationToken.None,null);Check(first.Downloaded==1&&first.Errors.Count==0,"complete capture downloads successfully");Check(Util.Hash(first.Files[0],CancellationToken.None)==Util.Hash(one,CancellationToken.None),"downloaded bytes match an independent original hash");Check(File.Exists(Path.Combine(first.Root,"shotsInfo.json"))&&File.Exists(Path.Combine(first.Root,"MyWorks","M31_sub","session.json")),"ancestor DWARF and adjacent capture metadata are preserved");Check(File.Exists(one),"remote original is retained");int priorOpens=opens;using(var source=factory(c)){var again=RemoteCaptureStaging.Download(source,c,captures,cache,CancellationToken.None,null);Check(again.Reused==1&&opens==priorOpens,"retry verifies and reuses complete local downloads");}
   File.WriteAllBytes(first.Files[0],new byte[new FileInfo(one).Length]);using(var source=factory(c)){var repair=RemoteCaptureStaging.Download(source,c,captures,cache,CancellationToken.None,null);Check(repair.Downloaded==1&&Util.Hash(repair.Files[0],CancellationToken.None)==Util.Hash(one,CancellationToken.None),"corrupted cache is detected and redownloaded");}
   string changing=Path.Combine(storage,"MyWorks","M31_sub","Light_M31_0002.fit");Fits(changing,1100);List<Entry> mutable;using(var source=factory(c))mutable=RemoteCaptureCatalog.Search(source,c,c.Folder,CancellationToken.None).Where(e=>e.Name.EndsWith("0002.fit")).ToList();using(var source=new Fixture(storage,c,p=>{if(p.EndsWith("0002.fit"))File.SetLastWriteTimeUtc(changing,File.GetLastWriteTimeUtc(changing).AddSeconds(2));})){var bad=RemoteCaptureStaging.Download(source,c,mutable,cache,CancellationToken.None,null);Check(bad.Files.Count==0&&bad.Errors.Count==1,"capture changes during transfer remain retryable");Check(!File.Exists(Path.Combine(bad.Root,"MyWorks","M31_sub","Light_M31_0002.fit")),"changing capture is never published as complete");Check(!Directory.EnumerateFiles(bad.Root,"*.partial",SearchOption.AllDirectories).Any(),"failed transfer removes partial local files");}
   string incomplete=Path.Combine(storage,"MyWorks","M31_sub","Light_M31_incomplete.fit");File.WriteAllBytes(incomplete,File.ReadAllBytes(one).Take(2880).ToArray());using(var source=factory(c)){var bad=RemoteCaptureStaging.Download(source,c,RemoteCaptureCatalog.Search(source,c,c.Folder,CancellationToken.None).Where(e=>e.Name.Contains("incomplete")),cache,CancellationToken.None,null);Check(bad.Files.Count==0&&bad.Errors.Count==1,"stable but incomplete FITS is not published");}
   string sidecar=Path.Combine(Path.GetDirectoryName(one),"session.json");File.WriteAllText(sidecar,"{\"target\":\"M42\"}");File.SetLastWriteTimeUtc(sidecar,DateTime.UtcNow.AddSeconds(2));using(var source=new Fixture(storage,c,p=>{if(p.EndsWith("session.json"))throw new IOException("Metadata is changing");})){var metadata=RemoteCaptureStaging.Download(source,c,captures,cache,CancellationToken.None,null);Check(metadata.Files.Count==1&&metadata.Warnings.Count>0&&!File.Exists(Path.Combine(metadata.Root,"MyWorks","M31_sub","session.json")),"changing sidecar cannot leave stale cached evidence for a new import");}
   var scoped=Util.Deserialize<RemoteConnection>(Util.Serialize(c));scoped.Folder+=@"\MyWorks\M31_sub";using(var source=new Fixture(Path.GetDirectoryName(one),scoped)){var scopedFiles=RemoteCaptureCatalog.Browse(source,scoped,scoped.Folder,CancellationToken.None).Where(e=>e.Name.EndsWith("0001.fit")).ToList();var staged=RemoteCaptureStaging.Download(source,scoped,scopedFiles,cache,CancellationToken.None,null);Check(staged.Files.Single()==Path.Combine(staged.Root,"MyWorks","M31_sub",Path.GetFileName(one)),"custom capture scope preserves the original session folder context");}
   using(var source=factory(c))mutable=RemoteCaptureCatalog.Search(source,c,c.Folder,CancellationToken.None).Where(e=>e.Name.EndsWith("0002.fit")).ToList();var token=new CancellationTokenSource();using(var source=new Fixture(storage,c,p=>token.Cancel()))try{RemoteCaptureStaging.Download(source,c,mutable,cache,token.Token,null);throw new Exception("Cancellation did not stop transfer");}catch(OperationCanceledException){Check(!Directory.EnumerateFiles(first.Root,"*.partial",SearchOption.AllDirectories).Any()&&File.Exists(first.Files[0]),"cancel removes only partial files and retains completed downloads");}token.Dispose();
   var tracked=new RemoteLiveTracker();var existing=captures[0];Check(tracked.Observe(new[]{existing},false).Count==0&&tracked.Observe(new[]{existing},false).Count==0,"live import excludes captures present when started");var fresh=new Entry{Path=existing.Path+"-new",Name="new.fit",Size=5760,Modified=DateTime.UtcNow};Check(tracked.Observe(new[]{existing,fresh},false).Count==0,"new live capture waits for a second observation");var changed=new Entry{Path=fresh.Path,Name=fresh.Name,Size=8640,Modified=fresh.Modified.AddSeconds(1)};Check(tracked.Observe(new[]{existing,changed},false).Count==0,"live growth resets stability");Check(tracked.Observe(new[]{existing,changed},false).Count==1,"unchanged new capture becomes eligible");tracked.Imported(changed.Path);Check(tracked.Observe(new[]{existing,changed},false).Count==0,"completed live capture is not imported twice");var include=new RemoteLiveTracker();include.Observe(new[]{existing},true);Check(include.Observe(new[]{existing},true).Count==1,"Advanced can include existing captures in live import");
   using(var repo=new Repository(Path.Combine(root,"archive"))){var profile=new TelescopeProfile{Id="Remote S50 Pro",Model="Seestar S50 Pro",Camera="Auto",SourceMake="Seestar"};var archived=RemoteArchiveImport.Run(repo,profile,c,captures,cache,1,CancellationToken.None,p=>{},sourceFactory:factory);Check(archived.Archive.Import.Imported==1&&repo.All().Count==1,"network captures enter the normal archive importer");var frame=repo.All().Single();Check(frame.Telescope==profile.Id&&frame.Hash==Util.Hash(one,CancellationToken.None)&&Util.Hash(repo.FilePath(frame),CancellationToken.None)==frame.Hash,"archive identity and verified bytes are retained");var repeated=RemoteArchiveImport.Run(repo,profile,c,captures,cache,1,CancellationToken.None,p=>{},sourceFactory:factory);Check(repeated.Archive.Import.Imported==0&&repo.All().Count==1,"repeat network import creates no archive duplicates");Check(File.Exists(one)&&repo.Verify(CancellationToken.None,p=>{})==0,"archive verification succeeds without changing originals");}
   string liveRoot=Path.Combine(root,"live-storage"),baseline=Path.Combine(liveRoot,"MyWorks","Light_M31_baseline.fit");Fits(baseline,1200);using(var repo=new Repository(Path.Combine(root,"live-archive")))using(var stopped=new CancellationTokenSource())using(var baselineSeen=new ManualResetEvent(false))using(var imported=new ManualResetEvent(false)){
    int requests=0,retries=0;var task=Task.Run(()=>RemoteLiveImport.Run(repo,new TelescopeProfile{Id="Live S50",Model="Seestar S50",Camera="Auto"},c,Path.Combine(root,"live-cache"),1,stopped.Token,p=>{if(p.Stage=="Live import")baselineSeen.Set();if(p.Stage=="Reconnecting to telescope")Interlocked.Increment(ref retries);},f=>{if(f.Status=="Imported")imported.Set();},p=>{},false,false,config=>{if(Interlocked.Increment(ref requests)==2)throw new IOException("Test disconnect");return new Fixture(liveRoot,config);}));
    try{Check(baselineSeen.WaitOne(10000),"live importer establishes its baseline");string next=Path.Combine(liveRoot,"MyWorks","Light_M31_live.fit");Fits(next,1300);byte[] complete=File.ReadAllBytes(next);File.WriteAllBytes(next,complete.Take(2880).ToArray());Check(!imported.WaitOne(6500),"live import does not archive an exposure while it is incomplete");File.WriteAllBytes(next,complete);Check(imported.WaitOne(20000),"live importer recovers from disconnect and archives a new capture");}finally{stopped.Cancel();try{task.GetAwaiter().GetResult();}catch(OperationCanceledException){}}
    Check(retries>0&&repo.All().Count==1&&File.Exists(baseline),"live reconnect and stop retain exactly the new archive capture and originals");
   }
   ConcurrentImports(root,c);RecoveryChecks(root,c);
   Console.WriteLine(checks+" remote integration checks passed.");}finally{Repository.LocalIndexBase=previousIndex;}
  }
 }
}
