// Generated-data coverage for saved telescopes, USB discovery, imports and rename rollback.
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
namespace AstroArchive {
 public partial class Tests {
  static void TelescopeTests(){
   Test("Interrupted telescope renames recover files and saved profiles on reopen",()=>{
    foreach(bool committed in new[]{false,true}){
     string suffix=committed?"committed":"rollback",source=Path.Combine(root,"rename-recovery-source-"+suffix),archive=Path.Combine(root,"rename-recovery-repo-"+suffix),config=Path.Combine(root,"rename-recovery-settings-"+suffix+".json");Directory.CreateDirectory(source);Write(Path.Combine(source,"Light_M45.fit"),64,48,(x,y)=>950,new Dictionary<string,string>());
     string oldSettings="{\"Telescope\":\"Old recovery\"}",newSettings="{\"Telescope\":\"New recovery\"}";
     using(var repository=new Repository(archive)){
      repository.Import(repository.Scan(source,"Old recovery","Auto",ct,NoProgress).Frames,ct,NoProgress);var before=repository.All().Single();string oldPath=repository.FilePath(before);var after=before.Clone();after.Telescope="New recovery";after.RelativePath=repository.Destination(after);string newPath=repository.FilePath(after);
      if(committed)repository.RenameTelescope("Old recovery","New recovery",ct,NoProgress);else{Directory.CreateDirectory(Path.GetDirectoryName(newPath));File.Move(oldPath,newPath);}
      var journal=new TelescopeRenameJournal{Id="simulated-interruption",SettingsPath=config,OriginalSettings=oldSettings,RenamedSettings=newSettings,Paths=new List<TelescopeRenamePath>{new TelescopeRenamePath{Before=oldPath,After=newPath,Hash=before.Hash}}};File.WriteAllText(Path.Combine(Path.GetDirectoryName(repository.WorkingIndex),"telescope-rename.json"),Util.Serialize(journal));File.WriteAllText(config,committed?oldSettings:newSettings);if(committed)repository.CachePut("rename:"+journal.Id,"committed");
     }
     using(var repository=new Repository(archive)){Check(repository.All().Single().Telescope==(committed?"New recovery":"Old recovery")&&repository.Verify(ct,NoProgress)==0,"Recovery failed to reconcile file paths with committed index");Check(File.ReadAllText(config)==(committed?newSettings:oldSettings)&&repository.RecoveredTelescopeSettings==File.ReadAllText(config),"Recovery did not reconcile saved profile");Check(!File.Exists(Path.Combine(Path.GetDirectoryName(repository.WorkingIndex),"telescope-rename.json")),"Recovered journal retained");}
    }
   });
   Test("Legacy scope settings migrate and survive serialization",()=>{
    var settings=Util.Deserialize<Settings>("{\"Telescope\":\"Seestar-01\",\"Model\":\"Seestar S50\",\"LastSource\":\"old-source\"}");TelescopeProfiles.Initialize(settings);Check(settings.Telescopes.Count==1&&settings.Telescopes[0].SessionIdentity=="Seestar-01","Legacy telescope lost");settings.SelectedTelescope="Seestar-01";var reopened=Util.Deserialize<Settings>(Util.Serialize(settings));Check(reopened.Telescopes[0].Model=="Seestar S50"&&reopened.SelectedTelescope=="Seestar-01","Saved telescope selection lost");
   });
   Test("Repository scope recovery preserves saved choices and handles conflicts",()=>{
    var settings=new Settings();TelescopeProfiles.Initialize(settings);TelescopeProfiles.Save(settings,"Saved-01","Seestar S50","Wide",null,new UsbVolume[0]);
    var frames=new[]{new Frame{Telescope="Saved-01",Model="Dwarf 3"},new Frame{Telescope="Recovered-02",TelescopeIdentity="Original-02",Model="Dwarf 3"},new Frame{Telescope="Recovered-02",TelescopeIdentity="Original-02",Model="Dwarf 3"},new Frame{Telescope="Conflicting-03",Model="Dwarf 3"},new Frame{Telescope="Conflicting-03",Model="Seestar S50"},new Frame{Telescope="Unknown",Model="Dwarf 3"}};
    Check(TelescopeProfiles.MergeRepository(settings,frames)==2&&TelescopeProfiles.MergeRepository(settings,frames)==0,"Recovery created repeated or unknown scopes");Check(TelescopeProfiles.Find(settings,"Saved-01").Camera=="Wide"&&TelescopeProfiles.Find(settings,"Saved-01").Model=="Seestar S50","Recovery overwrote a saved choice");Check(TelescopeProfiles.Find(settings,"Conflicting-03").Model=="Auto"&&TelescopeProfiles.Find(settings,"Recovered-02").SessionIdentity=="Original-02","Recovery guessed conflicting model or lost session identity");
   });
   Test("USB binding follows volume identity rather than drive path",()=>{
    string first=Path.Combine(root,"usb-first"),second=Path.Combine(root,"usb-remapped");Directory.CreateDirectory(Path.Combine(first,"MyWorks"));Directory.CreateDirectory(Path.Combine(second,"MyWorks"));var settings=new Settings();
    var profile=TelescopeProfiles.Save(settings," Seestar-01 ","Seestar S50","Auto",Path.Combine(first,"MyWorks"),new[]{new UsbVolume{Root=first,Id="usb-serial"}});var found=UsbTelescopeDiscovery.Discover(new[]{new UsbVolume{Root=second,Id="usb-serial"}},settings.Telescopes,null,ct);
    Check(found.Count==1&&found[0].ProfileId==profile.Id&&found[0].Source==Path.Combine(second,"MyWorks"),"Drive remap lost binding");Check(UsbTelescopeDiscovery.Resolve(new UsbVolume{Root=second,Id="other-usb"},profile)==null,"Different volume inherited telescope ID");profile.SourceRelativePath="../escape";Check(UsbTelescopeDiscovery.Resolve(new UsbVolume{Root=second,Id="usb-serial"},profile)==null,"Saved path escaped volume");
   });
   Test("USB discovery recognizes layouts and excludes archives and mixed devices",()=>{
    string sea=Path.Combine(root,"usb-layout-sea"),dwarf=Path.Combine(root,"usb-layout-dwarf"),other=Path.Combine(root,"usb-layout-other");Directory.CreateDirectory(Path.Combine(sea,"MyWorks"));Directory.CreateDirectory(Path.Combine(dwarf,"Astronomy","DWARF_RAW_TELE_M45"));Directory.CreateDirectory(other);
    var volumes=new[]{new UsbVolume{Root=sea,Id="sea"},new UsbVolume{Root=dwarf,Id="dwarf"},new UsbVolume{Root=other,Id="other"}};var found=UsbTelescopeDiscovery.Discover(volumes,new TelescopeProfile[0],null,ct);Check(found.Count==2&&found.All(t=>t.ProfileId==null),"Detection guessed a physical ID or accepted unrelated storage");Check(UsbTelescopeDiscovery.Discover(volumes,new TelescopeProfile[0],Path.Combine(sea,"Archive"),ct).Count==1,"Archive overlap accepted");Directory.CreateDirectory(Path.Combine(sea,"CALI_FRAME"));Check(UsbTelescopeDiscovery.DetectLayout(sea,ct)=="Unknown","Mixed makers silently assigned one scope");
   });
   Test("Saving a scope updates it once and retains disconnected binding",()=>{
    string usb=Path.Combine(root,"usb-save");Directory.CreateDirectory(usb);var settings=new Settings();var profile=TelescopeProfiles.Save(settings,"Scope-01","Dwarf 3","Auto",usb,new[]{new UsbVolume{Root=usb,Id="saved-usb"}});TelescopeProfiles.Save(settings,"scope-01","Dwarf 3","Telephoto",usb,new UsbVolume[0]);Check(settings.Telescopes.Count==1&&settings.Telescopes[0].VolumeId==profile.VolumeId&&settings.SelectedTelescope=="Scope-01","Update duplicated scope or forgot binding");Expect(()=>TelescopeProfiles.Save(settings," ","Auto","Auto",usb,new UsbVolume[0]),"Empty scope saved");
   });
   Test("USB upload screens duplicates, imports only new captures and retains sources",()=>{
    string source=Path.Combine(root,"usb-auto-source");Directory.CreateDirectory(source);string one=Path.Combine(source,"Light_M45.fit"),alias=Path.Combine(source,"renamed.fit");Write(one,64,48,(x,y)=>1000,new Dictionary<string,string>());File.Copy(one,alias);File.WriteAllText(Path.Combine(source,"preview.png"),"unsupported");
    using(var repository=new Repository(Path.Combine(root,"usb-auto-repo"))){var profile=new TelescopeProfile{Id="Scope-01",Model="Seestar S50",Camera="Wide"};var first=UsbAutoUpload.Run(repository,profile,source,1,ct,NoProgress);Check(first.Import.Imported==1&&first.Import.Duplicates==1&&repository.All().Single().Camera=="Wide","First upload or camera override wrong");var again=UsbAutoUpload.Run(repository,profile,source,1,ct,NoProgress);Check(again.Import.Imported==0&&again.Import.Duplicates==2&&Directory.GetFiles(Path.Combine(repository.Meta,"staging")).Length==0,"Repeated upload copied duplicates");Write(Path.Combine(source,"Light_M33.fit"),64,48,(x,y)=>2000,new Dictionary<string,string>());var added=UsbAutoUpload.Run(repository,profile,source,1,ct,NoProgress);Check(added.Import.Imported==1&&repository.All().Count==2&&File.Exists(one)&&File.Exists(alias)&&File.Exists(Path.Combine(source,"preview.png")),"Incremental import changed originals");}
   });
   Test("USB upload recognizes manually imported content and preserves DWARF JSON",()=>{
    string source=Path.Combine(root,"usb-dwarf-source"),manual=Path.Combine(root,"usb-manual-source");Directory.CreateDirectory(source);Directory.CreateDirectory(manual);string file=Path.Combine(source,"raw_M45.fit");Write(file,64,48,(x,y)=>1300,new Dictionary<string,string>());File.Copy(file,Path.Combine(manual,"manual.fit"));string sidecar=Path.Combine(source,"shotsInfo.json");File.WriteAllText(sidecar,"{\"targetName\":\"M45\",\"cameraId\":0}");Write(Path.Combine(source,"raw_M33.fit"),64,48,(x,y)=>1400,new Dictionary<string,string>());
    using(var repository=new Repository(Path.Combine(root,"usb-dwarf-repo"))){repository.Import(repository.Scan(manual,"Dwarf-03","Dwarf 3",ct,NoProgress).Frames,ct,NoProgress);var result=UsbAutoUpload.Run(repository,new TelescopeProfile{Id="Dwarf-03",Model="Dwarf 3",Camera="Auto"},source,1,ct,NoProgress);Check(result.Import.Imported==1&&result.Import.Duplicates==1,"Manual duplicate imported again");var imported=repository.All().Single(f=>f.OriginalName=="raw_M33.fit");Check(imported.Camera=="Telephoto"&&File.Exists(Path.Combine(repository.Root,imported.SidecarRelativePath))&&File.Exists(sidecar),"DWARF metadata lost");}
   });
   Test("USB upload restores missing and changed archive copies",()=>{
    string source=Path.Combine(root,"usb-restore-source");Directory.CreateDirectory(source);Write(Path.Combine(source,"Light_M45.fit"),64,48,(x,y)=>1500,new Dictionary<string,string>());using(var repository=new Repository(Path.Combine(root,"usb-restore-repo"))){var profile=new TelescopeProfile{Id="Restore-01",Model="Auto"};UsbAutoUpload.Run(repository,profile,source,1,ct,NoProgress);File.Delete(repository.FilePath(repository.All().Single()));var missing=UsbAutoUpload.Run(repository,profile,source,1,ct,NoProgress);Check(missing.Restored==1&&repository.Verify(ct,NoProgress)==0,"Missing capture not restored");File.WriteAllText(repository.FilePath(repository.All().Single()),"damaged");var changed=UsbAutoUpload.Run(repository,profile,source,1,ct,NoProgress);Check(changed.Restored==1&&repository.Verify(ct,NoProgress)==0,"Damaged copy counted as duplicate");}
   });
   Test("USB full screening rejects matching metadata with changed bytes",()=>{
    string source=Path.Combine(root,"usb-changed-source");Directory.CreateDirectory(source);string file=Path.Combine(source,"Light_M45.fit");Write(file,64,48,(x,y)=>1600,new Dictionary<string,string>());using(var repository=new Repository(Path.Combine(root,"usb-changed-repo"))){var profile=new TelescopeProfile{Id="Changed-01",Model="Auto"};UsbAutoUpload.Run(repository,profile,source,1,ct,NoProgress);DateTime time=File.GetLastWriteTimeUtc(file);long size=new FileInfo(file).Length;Write(file,64,48,(x,y)=>1700,new Dictionary<string,string>());File.SetLastWriteTimeUtc(file,time);var result=UsbAutoUpload.Run(repository,profile,source,1,ct,NoProgress);Check(new FileInfo(file).Length==size&&result.Import.Imported==1&&repository.All().Count==2,"Same-size content change skipped");}
   });
   Test("USB cancellation and disconnection before copying leave no records",()=>{
    string source=Path.Combine(root,"usb-cancel-source");Directory.CreateDirectory(source);Write(Path.Combine(source,"Light_M45.fit"),64,48,(x,y)=>1800,new Dictionary<string,string>());using(var repository=new Repository(Path.Combine(root,"usb-cancel-repo"))){var profile=new TelescopeProfile{Id="Cancel-01",Model="Auto"};using(var cancel=new CancellationTokenSource())Expect(()=>UsbAutoUpload.Run(repository,profile,source,1,cancel.Token,NoProgress,null,p=>cancel.Cancel()),"Canceled upload continued");int checks=0;Expect(()=>UsbAutoUpload.Run(repository,profile,source,1,ct,NoProgress,null,null,()=>++checks==1),"Disconnected upload copied");Check(repository.All().Count==0,"Canceled/disconnected upload committed records");}
   });
   Test("USB import failures remain isolated and unreadable files are counted",()=>{
    string source=Path.Combine(root,"usb-isolation-source");Directory.CreateDirectory(source);string gone=Path.Combine(source,"gone.fit");Write(gone,64,48,(x,y)=>1900,new Dictionary<string,string>());Write(Path.Combine(source,"good.fit"),64,48,(x,y)=>2000,new Dictionary<string,string>());File.WriteAllText(Path.Combine(source,"broken.fit"),"bad FITS");using(var repository=new Repository(Path.Combine(root,"usb-failure-repo"))){var result=UsbAutoUpload.Run(repository,new TelescopeProfile{Id="Failure-01",Model="Auto"},source,1,ct,NoProgress,null,p=>File.Delete(gone));Check(result.Import.Imported==1&&result.Import.Failed==2&&repository.All().Count==1&&result.Import.Warnings.Any(w=>w.Contains("broken.fit"))&&result.Import.Warnings.Any(w=>w.Contains("gone.fit")),"One failure aborted later files or summary lost scan error");}
   });
   Test("USB uploads honor deletion history and renamed telescope metadata",()=>{
    string source=Path.Combine(root,"usb-deletion-source");Directory.CreateDirectory(source);string file=Path.Combine(source,"Light_M45.fit");Write(file,64,48,(x,y)=>2750,new Dictionary<string,string>());
    using(var repository=new Repository(Path.Combine(root,"usb-deletion-repo"))){var profile=new TelescopeProfile{Id="Old deleted scope",Model="Auto",SessionIdentity="Old deleted scope"};UsbAutoUpload.Run(repository,profile,source,1,ct,NoProgress);var original=repository.All().Single();repository.DeleteFrames(new[]{original},ct,NoProgress);repository.RenameTelescope(profile.Id,"Renamed deleted scope",ct,NoProgress);profile.Id="Renamed deleted scope";File.Move(file,Path.Combine(source,"renamed.fit"));var result=UsbAutoUpload.Run(repository,profile,source,1,ct,NoProgress);
     Check(result.Import.Imported==0&&result.Import.SkippedDeleted==1&&result.Plan.Frames.Single().Status=="Deleted"&&repository.All().Count==0,"USB upload restored a deliberately deleted capture");var deletion=repository.Deletions().Single();Check(deletion.Metadata.Telescope==profile.Id&&deletion.Metadata.TelescopeIdentity==profile.SessionIdentity&&deletion.Metadata.RelativePath.Contains(profile.Id),"Rename missed deletion history or changed session identity");Check(File.Exists(Path.Combine(source,"renamed.fit")),"Skipped USB original was removed");}
   });
   Test("USB automatic imports keep rejected and damaged captures for review",()=>{
    string source=Path.Combine(root,"usb-review-source");Directory.CreateDirectory(source);string good=Path.Combine(source,"good.fit"),rejected=Path.Combine(source,"rejected.fit"),damaged=Path.Combine(source,"damaged.fit");Write(good,64,48,(x,y)=>2800,new Dictionary<string,string>());Write(rejected,64,48,(x,y)=>2850,new Dictionary<string,string>{{"STATUS","'FAILED'"}});Write(damaged,64,48,(x,y)=>2900,new Dictionary<string,string>());using(var stream=new FileStream(damaged,FileMode.Open,FileAccess.Write))stream.SetLength(2880);
    using(var repository=new Repository(Path.Combine(root,"usb-review-repo"))){var result=UsbAutoUpload.Run(repository,new TelescopeProfile{Id="Review scope",Model="Auto"},source,1,ct,NoProgress);Check(result.Import.Imported==1&&result.Import.Failed==1&&repository.All().Single().OriginalName=="good.fit","Automatic import copied a damaged or rejected capture");Check(result.Plan.Frames.Single(f=>f.OriginalName=="rejected.fit").Rejected&&result.Plan.Frames.Single(f=>f.OriginalName=="damaged.fit").Status=="Unreadable","Screening failed to preserve review reasons");Check(new[]{good,rejected,damaged}.All(File.Exists),"USB screening deleted originals");}
   });
   Test("Telescope rename updates paths manifests profiles and future sessions",()=>{
    string source=Path.Combine(root,"scope-rename-source");Directory.CreateDirectory(source);Write(Path.Combine(source,"Light_M45.fit"),64,48,(x,y)=>2100,new Dictionary<string,string>());Write(Path.Combine(source,"Dark.fit"),64,48,(x,y)=>2200,new Dictionary<string,string>{{"IMAGETYP","'DARK'"}});using(var repository=new Repository(Path.Combine(root,"scope-rename-repo"))){var settings=new Settings();var profile=TelescopeProfiles.Save(settings,"Old-01","Seestar S50","Auto",source,new[]{new UsbVolume{Root=source,Id="rename-usb"}});UsbAutoUpload.Run(repository,profile,source,1,ct,NoProgress);var before=repository.All().ToDictionary(f=>f.Hash);TelescopeProfiles.Rename(settings,"Old-01","My Seestar");string config=Path.Combine(root,"renamed-settings.json");var renamed=repository.RenameTelescope("Old-01","My Seestar",ct,NoProgress,()=>Util.AtomicText(config,Util.Serialize(settings)));Check(renamed.Files==2&&repository.All().All(f=>f.Telescope=="My Seestar"&&f.Session==before[f.Hash].Session&&f.RelativePath.Contains("My Seestar")&&Util.Hash(repository.FilePath(f),ct)==f.Hash),"Rename changed bytes/sessions or left old names");using(var database=new Database(repository.WorkingIndex)){var manifests=database.Query("SELECT data FROM source_manifest").Select(Util.Deserialize<SourceManifest>).ToList();Check(manifests.All(m=>m.Metadata.Telescope=="My Seestar"&&m.Destination.Contains("My Seestar")),"Import manifest still uses old name");}Check(!Directory.GetDirectories(repository.Root,"Old-01",SearchOption.AllDirectories).Any(),"Empty old telescope paths retained");var reopened=Util.Deserialize<Settings>(File.ReadAllText(config));Check(reopened.SelectedTelescope=="My Seestar"&&reopened.Telescopes.Single().VolumeId=="rename-usb","Profile selection or binding lost during rename");Write(Path.Combine(source,"Light_M45_002.fit"),64,48,(x,y)=>2300,new Dictionary<string,string>());var next=UsbAutoUpload.Run(repository,reopened.Telescopes.Single(),source,1,ct,NoProgress);Check(next.Import.Imported==1&&repository.All().Single(f=>f.OriginalName=="Light_M45_002.fit").Session==before.Values.Single(f=>f.OriginalName=="Light_M45.fit").Session,"Rename split an existing acquisition session");}
   });
   Test("Telescope rename rolls back paths and index on cancellation or settings failure",()=>{
    string source=Path.Combine(root,"rename-rollback-source");Directory.CreateDirectory(source);for(int i=0;i<2;i++)Write(Path.Combine(source,"Light_M45_"+i+".fit"),64,48,(x,y)=>2400+i,new Dictionary<string,string>());using(var repository=new Repository(Path.Combine(root,"rename-rollback-repo"))){repository.Import(repository.Scan(source,"Old-02","Auto",ct,NoProgress).Frames,ct,NoProgress);var before=repository.All().ToDictionary(f=>f.Hash);using(var cancel=new CancellationTokenSource())Expect(()=>repository.RenameTelescope("Old-02","New-02",cancel.Token,p=>{if(p.Done==1)cancel.Cancel();}),"Rename ignored cancellation");Check(repository.All().All(f=>f.Telescope=="Old-02"&&File.Exists(repository.FilePath(f))&&f.RelativePath==before[f.Hash].RelativePath),"Canceled rename partially committed");Expect(()=>repository.RenameTelescope("Old-02","New-02",ct,NoProgress,()=>{throw new IOException("settings unavailable");}),"Settings failure ignored");Check(repository.All().All(f=>f.Telescope=="Old-02"&&File.Exists(repository.FilePath(f)))&&repository.Verify(ct,NoProgress)==0,"Settings failure lost original captures");}
   });
   Test("Telescope rename rejects existing names and corrupted captures",()=>{
    string source=Path.Combine(root,"rename-conflict-source");Directory.CreateDirectory(source);Write(Path.Combine(source,"Light_M45.fit"),64,48,(x,y)=>2600,new Dictionary<string,string>());using(var repository=new Repository(Path.Combine(root,"rename-conflict-repo"))){repository.Import(repository.Scan(source,"Old-03","Auto",ct,NoProgress).Frames,ct,NoProgress);var reserved=repository.All().Single().Clone();reserved.Hash=Util.HashText("reserved-capture");reserved.Telescope="Reserved";reserved.RelativePath="reserved.fit";repository.Save(reserved);Expect(()=>repository.RenameTelescope("Old-03","Reserved",ct,NoProgress),"Existing device name accepted");var old=repository.All().Single(f=>f.Telescope=="Old-03");File.WriteAllText(repository.FilePath(old),"changed");Expect(()=>repository.RenameTelescope("Old-03","New-03",ct,NoProgress),"Corrupted source renamed");Check(repository.All().Any(f=>f.Telescope=="Old-03"),"Failed preflight changed metadata");}
   });
  }
 }
}
