// Synthetic FITS and end-to-end safety tests. No user files or network calls.
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Text;
using System.Threading;

namespace AstroArchive {
 public partial class Tests {
  static int passed,skipped;static string root;static CancellationToken ct=CancellationToken.None;
  static void Check(bool test,string message){if(!test)throw new Exception(message);}
  static void Test(string name,Action action){try{action();passed++;Console.WriteLine("PASS "+name);}catch(Exception e){Console.WriteLine("FAIL "+name+": "+e);Environment.ExitCode=1;}}
  static void Expect(Action action,string message){bool threw=false;try{action();}catch{threw=true;}Check(threw,message);}
  static void WindowsTest(string name,Action action){if(Environment.OSVersion.Platform==PlatformID.Win32NT)Test(name,action);else{skipped++;Console.WriteLine("SKIP (Windows required) "+name);}}
  public static int Main(string[] args){AppContext.SetSwitch("Switch.System.IO.UseLegacyPathHandling",false);AppContext.SetSwitch("Switch.System.IO.BlockLongPaths",false);root=Path.GetFullPath(args.Length>0?args[0]:"test-data");Directory.CreateDirectory(root);Repository.LocalIndexBase=Path.Combine(root,"working-indexes");
   FileSearchTests();ImportPolicyTests();TelescopeTests();PreviewGestureTests();SkyContextTests();FailedFilenameTests();TableCatalogTests();ObservingCityTests();MountLabelTests();TargetNavigationTests();
   Test("Dump imports nested telescope data and preserves failures and metadata",()=>{
    using(var repo=new Repository(Path.Combine(root,"dump-repo"))){repo.EnsureDumpFolder();Check(Directory.Exists(repo.DumpFolder),"Dump folder missing");string directory=Path.Combine(repo.DumpFolder,"DWARF_RAW_TELE_M45_EXP_60_GAIN_60_2026-10-06-21-00-00-000");Directory.CreateDirectory(directory);
     string file=Path.Combine(directory,"raw_001.fit");Write(file,64,48,(x,y)=>1800,LightHeaders(new DateTime(2026,10,6,21,0,0),"M45"));string hash=Util.Hash(file,ct);File.WriteAllText(Path.Combine(directory,"shotsInfo.json"),"{\"targetName\":\"M45\"}");File.WriteAllText(Path.Combine(repo.DumpFolder,"bad.fit"),"not FITS");File.WriteAllText(Path.Combine(repo.DumpFolder,"keep.txt"),"keep");
     var result=repo.ProcessDump(ct,NoProgress);var capture=repo.All().Single();Check(result.Import.Imported==1&&result.Plan.Errors.Count==1&&result.NeedsReview,"Dump counts or errors wrong");Check(capture.Hash==hash&&capture.Target=="M45"&&capture.Telescope=="Unknown"&&!Util.Within(repo.FilePath(capture),repo.DumpFolder),"Dump sorting or unassigned device metadata wrong");Check(File.Exists(Path.Combine(repo.Root,capture.SidecarRelativePath)),"Session metadata not preserved");Check(File.Exists(Path.Combine(repo.DumpFolder,"bad.fit"))&&File.Exists(Path.Combine(repo.DumpFolder,"keep.txt")),"Failed or unsupported drop removed");Check(File.Exists(Path.Combine(directory,"shotsInfo.json")),"Session JSON removed");Check(File.Exists(Path.Combine(repo.Meta,"reports","last-dump.txt")),"Dump report missing");
     if(Environment.OSVersion.Platform==PlatformID.Win32NT)Check(!File.Exists(file)&&result.Import.OriginalsDeleted==1,"Verified dump source not removed");else Check(File.Exists(file)&&result.Import.OriginalsKept==1,"Unsupported cleanup removed source");
     string pending=Path.Combine(repo.DumpFolder,"pending.fit");Write(pending,64,48,(x,y)=>1900,new Dictionary<string,string>());var reindex=repo.Scan(repo.Root,"X","Auto",ct,NoProgress,true);Check(!reindex.Frames.Any(f=>Util.Within(f.SourcePath,repo.DumpFolder)),"Repository reindex indexed pending dump files");
     Expect(()=>repo.Scan(repo.DumpFolder,"X","Auto",ct,NoProgress),"Normal import allowed nested dump source");Expect(()=>repo.Import(new List<Frame>(),ct,NoProgress,new ImportOptions{DumpInbox=true,DeleteOriginals=true,SourceRoot=repo.Root}),"Forged dump root accepted");Expect(()=>SourceCleanup.DeleteDumpVerified(Path.Combine(root,"outside.fit"),repo.FilePath(capture),hash,repo.Root,ct),"Dump cleanup escaped source boundary");
    }
   });
   Test("Dump duplicate cleanup preserves edited archive metadata and recovers missing copies",()=>{
    using(var repo=new Repository(Path.Combine(root,"dump-duplicate-repo"))){repo.EnsureDumpFolder();string file=Path.Combine(repo.DumpFolder,"Light_M45.fit");Write(file,64,48,(x,y)=>1750,LightHeaders(new DateTime(2026,10,6,21,0,0),"M45"));byte[] original=File.ReadAllBytes(file);repo.ProcessDump(ct,NoProgress);var capture=repo.All().Single();capture.Target="M33";capture.Telescope="UserScope";repo.Refile(capture,ct);File.WriteAllBytes(file,original);
     var duplicate=repo.ProcessDump(ct,NoProgress);Check(duplicate.Import.Imported==0&&duplicate.Import.Duplicates==1&&repo.All().Single().Target=="M33"&&repo.All().Single().Telescope=="UserScope","Duplicate replaced archive metadata");if(Environment.OSVersion.Platform==PlatformID.Win32NT)Check(!File.Exists(file)&&duplicate.Import.OriginalsDeleted==1,"Duplicate remained in Dump");else Check(File.Exists(file)&&duplicate.Import.OriginalsKept==1,"Duplicate removed without native verification");
     File.WriteAllBytes(file,original);File.Delete(repo.FilePath(repo.All().Single()));var restore=repo.ProcessDump(ct,NoProgress);Check(restore.Import.Imported==1&&repo.Verify(ct,NoProgress)==0&&repo.All().Single().Target=="M33"&&repo.All().Single().Telescope=="UserScope","Missing archive copy or edited metadata was not restored");
    }
   });
   Test("Canceled dump ingestion retains pending sources",()=>{using(var repo=new Repository(Path.Combine(root,"dump-cancel-repo"))){repo.EnsureDumpFolder();string file=Path.Combine(repo.DumpFolder,"Light_M45.fit");Write(file,64,48,(x,y)=>1700,new Dictionary<string,string>());using(var canceled=new CancellationTokenSource()){canceled.Cancel();Expect(()=>repo.ProcessDump(canceled.Token,NoProgress),"Dump cancellation ignored");}Check(File.Exists(file)&&repo.All().Count==0,"Canceled dump changed sources or index");}});
   WindowsTest("Locked dump sources retry as duplicates after cleanup failure",()=>{using(var repo=new Repository(Path.Combine(root,"dump-lock-repo"))){repo.EnsureDumpFolder();string file=Path.Combine(repo.DumpFolder,"Light_M45.fit");Write(file,64,48,(x,y)=>1700,new Dictionary<string,string>());using(var locked=File.Open(file,FileMode.Open,FileAccess.Read,FileShare.Read)){var result=repo.ProcessDump(ct,NoProgress);Check(result.Import.Imported==1&&result.Import.OriginalsKept==1&&File.Exists(file),"Locked source not retained with verified archive copy");}var retry=repo.ProcessDump(ct,NoProgress);Check(retry.Import.Duplicates==1&&retry.Import.OriginalsDeleted==1&&!File.Exists(file)&&repo.All().Count==1,"Cleanup retry failed");}});
   WindowsTest("Dump cleanup refuses inbox destinations and identical hard links",()=>{using(var repo=new Repository(Path.Combine(root,"dump-hardlink-repo"))){repo.EnsureDumpFolder();string source=Path.Combine(repo.DumpFolder,"source.fit"),copy=Path.Combine(repo.Root,"copy.fit"),inboxCopy=Path.Combine(repo.DumpFolder,"copy.fit");File.WriteAllText(source,"same-file");Check(CreateHardLink(copy,source,IntPtr.Zero),"Test hard link creation failed");Expect(()=>SourceCleanup.DeleteDumpVerified(source,copy,Util.Hash(source,ct),repo.Root,ct),"Same file identity allowed dump deletion");File.Copy(source,inboxCopy);Expect(()=>SourceCleanup.DeleteDumpVerified(source,inboxCopy,Util.Hash(source,ct),repo.Root,ct),"Inbox copy allowed dump deletion");Check(File.Exists(source)&&File.Exists(copy)&&File.Exists(inboxCopy),"Guarded dump cleanup lost a file");}});
   Test("Siril handoff exports only one eligible stack and uses a positional image argument",()=>{
    string source=Path.Combine(root,"siril-source");Directory.CreateDirectory(source);var headers=LightHeaders(new DateTime(2026,10,6,21,0,0),"M45");headers["NCOMBINE"]="12";string file=Path.Combine(source,"Stacked_M45.fit");Write(file,64,48,(x,y)=>1800,headers);string appDir=Path.Combine(root,"Siril app");Directory.CreateDirectory(appDir);string executable=Path.Combine(appDir,"siril.exe");File.WriteAllText(executable,"launch fixture");
    using(var repo=new Repository(Path.Combine(root,"siril-repo"))){repo.Import(repo.Scan(source,"Scope-1","Auto",ct,NoProgress).Frames,ct,NoProgress);var frames=repo.All();Check(SirilHandoff.CanSend(frames),"Stack handoff unavailable");var options=new ExportOptions{Parent=root,Name="Siril working copy Ω"};string image=SirilHandoff.ExportStack(repo,frames,options,executable,ct,NoProgress);var launch=SirilHandoff.LaunchInfo(executable,image);Check(!Util.Within(image,repo.Root)&&Util.Hash(image,ct)==frames[0].Hash&&File.Exists(file),"Handoff did not preserve a verified working copy");Check(launch.FileName==Path.GetFullPath(executable)&&!launch.UseShellExecute&&launch.Arguments=="\""+image+"\""&&launch.WorkingDirectory==Path.GetDirectoryName(image),"Siril GUI launch contract incorrect");
     frames[0].Kind="Light";Check(!SirilHandoff.CanSend(frames),"Single sub offered as stack");Expect(()=>SirilHandoff.ExportStack(repo,frames,new ExportOptions{Parent=root,Name="bad-siril"},executable,ct,NoProgress),"Light handoff accepted");Check(!Directory.Exists(Path.Combine(root,"bad-siril")),"Invalid handoff created export");frames[0].Kind="Stack";frames[0].Rejected=true;Check(!SirilHandoff.CanSend(frames),"Rejected stack accepted");frames[0].Rejected=false;frames[0].OriginalName+=".gz";Check(!SirilHandoff.CanSend(frames),"Compressed stack offered");Check(!SirilHandoff.CanSend(new List<Frame>{frames[0],frames[0]}),"Multiple images offered as a single sequence");Expect(()=>SirilHandoff.ValidateExecutable(Path.Combine(appDir,"siril-cli.exe")),"CLI executable accepted");
    }
   });
   Test("Catalog aliases and spherical position lookup",()=>{Check(Catalog.Objects.Count>12000,"Catalogue incomplete");Check(Catalog.Normalize("M 045")=="M45","Messier normalisation");Check(Catalog.Normalize("NGC 0224")=="M31","NGC alias");Check(Catalog.Normalize("Pacman Nebula")=="NGC281","Common name");Check(Catalog.Nearby(56.75,24.1167,0.2).Any(c=>c.Name=="M45"),"M45 position");Check(Catalog.Normalize("Object_001")=="Unknown","Generic target");});
   Test("FITS signed integer, BSCALE/BZERO and dimensions",()=>{string p=Path.Combine(root,"unsigned.fit");Write(p,64,48,(x,y)=>32000+x+y,new Dictionary<string,string>());var h=Fits.Header(p);Check(h.Width==64&&h.Height==48,"Dimensions");var i=Fits.Image(p,ct);Check(Math.Abs(i.Pixels[0]-32001)<0.01,"BZERO decode");});
   Test("FITS gzip, empty primary and IMAGE extension",()=>{string p=Path.Combine(root,"extension.fits");Write(p,80,60,(x,y)=>1000+x,new Dictionary<string,string>{{"OBJECT","'M45'"}},true);Check(Fits.Header(p).Get("OBJECT")=="M45","Primary metadata lost");string g=p+".gz";using(var input=File.OpenRead(p))using(var output=File.Create(g))using(var gz=new GZipStream(output,CompressionMode.Compress))input.CopyTo(gz);Check(Fits.Image(g,ct).Width==40,"Gzip decode");});
   Test("FITS floating point, NaN and RGB cube",()=>{string p=Path.Combine(root,"rgb.fits");WriteFloat(p,24,18,3);var i=Fits.Image(p,ct);Check(i.Width==12&&i.Height==9,"RGB dimensions");Check(Math.Abs(i.Pixels[1]-20)<0.01,"RGB averaging");});
   Test("Truncated FITS rejection",()=>{string p=Path.Combine(root,"truncated.fit");File.WriteAllText(p,"not FITS");Expect(()=>Fits.Header(p),"Invalid FITS accepted");string q=Path.Combine(root,"cut.fit");File.Copy(Path.Combine(root,"unsigned.fit"),q,true);using(var s=new FileStream(q,FileMode.Open))s.SetLength(3000);Expect(()=>Fits.Header(q),"Truncated image accepted");});
   Test("Seestar target, subs and stack naming",()=>{string dir=Path.Combine(root,"seestar","MyWorks","M 45_sub");Directory.CreateDirectory(dir);string p=Path.Combine(dir,"Light_M_45_10.0s_2026-10-06-23-59-00.fit");Write(p,64,48,(x,y)=>1000+x+y,new Dictionary<string,string>());var f=Classifier.Read(p,Path.Combine(root,"seestar"),"Seestar-01","Seestar S50 Pro");Check(f.Kind=="Light"&&f.Target=="M45","Seestar sub naming");Check(f.Exposure==10,"Exposure naming");string stack=Path.Combine(root,"seestar","Stacked_M45_180x10sec_T7C_2026-10-06-23-59-00.fit");Write(stack,64,48,(x,y)=>2000+x+y,new Dictionary<string,string>());var s=Classifier.Read(stack,Path.Combine(root,"seestar"),"Seestar-01","Seestar S50 Pro");Check(s.Kind=="Stack"&&s.Target=="M45","Stack naming");Check(s.Exposure==10&&s.Temperature==7,"Stack metadata naming");});
   Test("Dwarf raw, raw dark and master calibration conventions",()=>{string baseDir=Path.Combine(root,"dwarf");string dir=Path.Combine(baseDir,"Astronomy","DWARF_RAW_TELE_NGC_6888_EXP_60_GAIN_60_2026-10-06-21-00-00-000");Directory.CreateDirectory(dir);string p=Path.Combine(dir,"raw_tele_NGC6888_2026-10-06-21-00-00-000.fits");Write(p,64,48,(x,y)=>1000+x+y,new Dictionary<string,string>());var f=Classifier.Read(p,baseDir,"Dwarf-03","Auto");Check(f.Target=="NGC6888"&&f.Kind=="Light"&&f.Camera=="Telephoto","Dwarf raw convention");Check(f.Exposure==60&&f.Gain==60,"Dwarf session parameters");string d=Path.Combine(baseDir,"Astronomy","CALI_FRAME","dark","cam_0","dark_exp_60.000000_gain_60_bin_1_10C_stack_10.fits");Directory.CreateDirectory(Path.GetDirectoryName(d));Write(d,64,48,(x,y)=>1000,new Dictionary<string,string>());var dark=Classifier.Read(d,baseDir,"Dwarf-03","Auto");Check(dark.Kind=="Master dark"&&dark.StackCount==10&&dark.Temperature==10,"Master dark convention");string raw=Path.Combine(baseDir,"DWARF_DARK","cam_1","dark_exp_60_gain_60_bin_1_9C_0001.fits");Directory.CreateDirectory(Path.GetDirectoryName(raw));Write(raw,64,48,(x,y)=>1000,new Dictionary<string,string>());var rd=Classifier.Read(raw,baseDir,"Dwarf-03","Auto");Check(rd.Kind=="Dark"&&rd.Camera=="Wide","Raw dark convention");});
   Test("Header precedence, mount evidence and false calibration flag",()=>{string p=Path.Combine(root,"metadata.fit");Write(p,64,48,(x,y)=>1000,new Dictionary<string,string>{{"OBJECT","'M33'"},{"IMAGETYP","'LIGHT'"},{"EXPTIME","30.0"},{"GAIN","70"},{"MOUNTMOD","'EQ'"},{"CALIBRAT","F"}});var f=Classifier.Read(p,root,"Dwarf-03","Dwarf 3");Check(f.Target=="M33"&&f.Exposure==30&&f.Mount=="EQ","Header precedence");Check(f.Calibration=="Unknown","False calibration interpreted as calibrated");});
   Test("Triangle matching: rotation, shift, missing stars and outliers",()=>{var a=Stars(80,1000,700,123);double angle=17.35*Math.PI/180;var b=a.Where((s,i)=>i%7!=0).Select(s=>new Star(Math.Cos(angle)*s.X-Math.Sin(angle)*s.Y+140,Math.Sin(angle)*s.X+Math.Cos(angle)*s.Y-80,s.Flux)).ToList();b.AddRange(Stars(12,1000,700,75));var m=Rotation.Match(a,b,1000,700,ct);Check(Math.Abs(m.Angle-17.35)<0.01,"Wrong recovered angle: "+m.Angle);Check(m.Matches>55&&m.Rms<0.01,"Match quality");});
   Test("Triangle matching rejects reflected or unrelated fields",()=>{var a=Stars(60,1000,700,123);var b=a.Select(s=>new Star(1000-s.X,s.Y,s.Flux)).ToList();Expect(()=>Rotation.Match(a,b,1000,700,ct),"Reflection accepted");Expect(()=>Rotation.Match(a,Stars(60,1000,700,222),1000,700,ct),"Unrelated sky accepted");});
   Test("Star detector recovers PSFs and rejects isolated hot pixels",()=>{var stars=Stars(70,480,320,44);var image=Paint(stars,480,320,0,0,0,3);var found=Rotation.Detect(image);Check(found.Count>=35,"Too few stars: "+found.Count);Check(found.Count<=90,"Hot pixel detections");var b=Paint(stars,480,320,4.7,7,-4,8);var match=Rotation.Match(found,Rotation.Detect(b),480,320,ct);Check(Math.Abs(match.Angle-4.7)<0.08,"PSF rotation: "+match.Angle);});
   Test("Repository scan, deduplication, refile, restore and verification",()=>{string src=Path.Combine(root,"mirror"),repoPath=Path.Combine(root,"repository");Directory.CreateDirectory(src);string p=Path.Combine(src,"Light_M45.fit");Write(p,64,48,(x,y)=>1000+x+y,LightHeaders(new DateTime(2026,10,6,21,0,0),"M45"));File.Copy(p,Path.Combine(src,"renamed.fit"),true);using(var repo=new Repository(repoPath)){var plan=repo.Scan(src,"Seestar-01","Seestar S50 Pro",ct,NoProgress);Check(plan.Frames.Count==2&&plan.Frames.Count(entry=>entry.Status=="New")==1,"Duplicate-in-source");repo.Import(plan.Frames,ct,NoProgress);Check(repo.All().Count==1,"Duplicate imported twice");var again=repo.Scan(src,"Seestar-01","Seestar S50 Pro",ct,NoProgress);string expectedHash=Util.Hash(p,ct);Check(again.Frames.Count==2&&again.Frames.All(entry=>(entry.Status=="Duplicate"||entry.Status=="Duplicate (cached)")&&entry.Hash==expectedHash),"Renamed duplicate not recognized");var f=repo.All().First();f.Target="M33";repo.Refile(f,ct);Check(repo.FilePath(f).Contains("M33")&&File.Exists(repo.FilePath(f)),"Refile failed");File.Delete(repo.FilePath(f));var restore=repo.Scan(src,"Seestar-01","Seestar S50 Pro",ct,NoProgress);Check(restore.Frames.Any(x=>x.Status=="Restore"),"Missing not detected");repo.Import(restore.Frames,ct,NoProgress);Check(repo.Verify(ct,NoProgress)==0,"Restored checksum mismatch");Expect(()=>repo.Scan(repoPath,"X","Auto",ct,NoProgress),"Nested source accepted");using(var c=new CancellationTokenSource()){c.Cancel();Expect(()=>repo.Scan(src,"X","Auto",c.Token,NoProgress),"Cancellation ignored");}}});
   Test("Calibration matching: camera identity, gain, temperature and state",()=>{Frame l=new Frame{Telescope="Seestar-01",Camera="Telephoto",Width=3840,Height=2160,Channels=1,BinX=1,BinY=1,Bayer="RGGB",Calibration="Uncalibrated",Gain=80,Exposure=60,Temperature=10,Filter="Broadband",Night="2026-10-06"};Frame d=l.Clone();d.Kind="Dark";d.Temperature=11;Check(Exporter.MatchesCalibration(l,d),"Valid dark rejected");d.Telescope="Seestar-02";Check(!Exporter.MatchesCalibration(l,d),"Other telescope dark accepted");d.Telescope=l.Telescope;d.Temperature=null;Check(!Exporter.MatchesCalibration(l,d),"Unknown temperature accepted");d.Temperature=11;l.Calibration="Calibrated";Check(!Exporter.MatchesCalibration(l,d),"Double calibration allowed");});
   Test("Stacking export keeps subs, stacks and manifests separate",()=>{string src=Path.Combine(root,"export-mirror");Directory.CreateDirectory(src);Write(Path.Combine(src,"Light_M45_001.fit"),64,48,(x,y)=>1000+x+y,LightHeaders(new DateTime(2026,10,6,21,0,0),"M45"));var hh=LightHeaders(new DateTime(2026,10,6,21,0,0),"M45");hh["NCOMBINE"]="12";Write(Path.Combine(src,"Stacked_M45.fit"),64,48,(x,y)=>1200+x+y,hh);using(var repo=new Repository(Path.Combine(root,"export-repo"))){var p=repo.Scan(src,"Seestar-01","Seestar S50 Pro",ct,NoProgress);repo.Import(p.Frames,ct,NoProgress);var opts=new ExportOptions{Parent=root,Name="M45_project",Mode="Both"};string project=Exporter.Create(repo,repo.All(),opts,ct,NoProgress);Check(Directory.GetFiles(Path.Combine(project,"subs"),"*.fit",SearchOption.AllDirectories).Length==1,"Subs count");Check(Directory.GetFiles(Path.Combine(project,"stacks"),"*.fit",SearchOption.AllDirectories).Length==1,"Stacks count");Check(File.Exists(Path.Combine(project,"manifest.json"))&&!File.Exists(Path.Combine(project,"INCOMPLETE.txt")),"Manifest/completion marker");foreach(string file in Directory.GetFiles(project,"*.fit",SearchOption.AllDirectories))Check(repo.All().Any(f=>f.Hash==Util.Hash(file,ct)),"Export changed FITS bytes");Expect(()=>Exporter.Create(repo,repo.All(),opts,ct,NoProgress),"Existing project overwritten");}});
   Test("Rotation time-series: coherent Alt/Az inference",()=>Series(false,false));
   Test("Rotation time-series: EQ requires geometry",()=>Series(true,true));
   Test("Rotation time-series: stable field without geometry stays unknown",()=>Series(true,false));
   Test("ASTAP INI protocol and astrometry XY-list format",()=>{var h=PlateSolve.ParseIni("PLTSOLVD=T // success\r\nCRVAL1=56.75\r\nCRVAL2=24.1\r\n");Check(h.Get("PLTSOLVD")=="T"&&h.Number("CRVAL1")==56.75,"INI parsing");byte[] xy=PlateSolve.XYList(Stars(30,480,320,1),480,320);Check(xy.Length%2880==0&&Encoding.ASCII.GetString(xy,2880,80).Contains("BINTABLE"),"XY-list FITS format");});
   Test("Long and reserved filenames preserve FITS extension",()=>{Check(Util.SafeFile(new string('a',160)+".fits.gz").EndsWith(".fits.gz"),"Extension lost");Check(Util.Safe("CON")=="_CON","Reserved name");});
   Test("Frame timestamps take precedence over session folder timestamps",()=>{string baseDir=Path.Combine(root,"timestamp-mirror"),dir=Path.Combine(baseDir,"DWARF_RAW_TELE_M45_EXP_60_GAIN_60_2026-10-06-21-00-00-000");Directory.CreateDirectory(dir);string p=Path.Combine(dir,"raw_M45_2026-10-06-21-08-00-123.fits");Write(p,64,48,(x,y)=>1000,new Dictionary<string,string>());var f=Classifier.Read(p,baseDir,"Dwarf-03","Dwarf 3");Check(f.Observed=="2026-10-06T21:08:00.123","Session timestamp used as frame timestamp");string q=Path.Combine(dir,"0001.fits");Write(q,64,48,(x,y)=>1100,new Dictionary<string,string>());var g=Classifier.Read(q,baseDir,"Dwarf-03","Dwarf 3");Check(g.Observed==""&&g.TimeSource.StartsWith("Session"),"Invented sub timestamps");});
   Test("shotsInfo target metadata and original JSON preservation",()=>{string src=Path.Combine(root,"shots-mirror"),dir=Path.Combine(src,"DWARF_RAW_TELE_Unknown_EXP_60_GAIN_60_2026-10-06-21-00-00-000");Directory.CreateDirectory(dir);Write(Path.Combine(dir,"raw_0001.fit"),64,48,(x,y)=>1200,new Dictionary<string,string>());File.WriteAllText(Path.Combine(dir,"shotsInfo.json"),"{\"targetName\":\"M45\",\"gain\":60,\"binning\":\"1*1\",\"ir\":2}");using(var repo=new Repository(Path.Combine(root,"shots-repo"))){var p=repo.Scan(src,"Dwarf-03","Dwarf 3",ct,NoProgress);var f=p.Frames.First();Check(f.Target=="M45"&&f.Gain==60&&f.BinX==1&&f.Filter=="Dual band","JSON metadata not used");repo.Import(p.Frames,ct,NoProgress);Check(File.Exists(Path.Combine(repo.Root,repo.All().First().SidecarRelativePath)),"Session metadata lost");}});
   Test("Short time span remains unknown",()=>{using(var repo=new Repository(Path.Combine(root,"series-repo-az"))){var frames=repo.All();DateTime start=Util.Time(frames[0].Observed).Value;foreach(var f in frames)f.ObservedUtc=f.Observed=start.AddSeconds(frames.IndexOf(f)*10).ToString("o");var r=Rotation.Analyze(repo,frames,null,null,ct,NoProgress);Check(r.Mount=="Unknown"&&r.SpanMinutes<10,"Short span classified");}});
   Test("Local plate-solver process protocol preserves source bytes",()=>{string solver=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"MockAstap.exe"),file=Path.Combine(root,"unsigned.fit"),sha=Util.Hash(file,ct);var settings=new Settings{Astap=solver};var solution=PlateSolve.Solve(file,settings,ct,t=>{});Check(solution.RA==56.75&&Math.Abs(solution.Dec-24.1167)<0.00001,"Wrong solution readback");Check(solution.Candidates.Any(c=>c.Name=="M45"),"Solved centre not matched to catalogue");Check(Util.Hash(file,ct)==sha,"Plate solver modified source");});
   Test("Search metadata includes common target aliases",()=>{var f=new Frame{Target="M45"};Check(f.SearchText.IndexOf("Pleiades",StringComparison.OrdinalIgnoreCase)>=0,"Alias missing from search");});
   Test("Unknown calibration binning blocks automatic matching",()=>{var l=new Frame{Telescope="Dwarf-03",Camera="Telephoto",Kind="Light",Calibration="Uncalibrated",Gain=60,Exposure=60,Temperature=10};var d=l.Clone();d.Kind="Dark";Check(!Exporter.MatchesCalibration(l,d),"Unknown binning treated as verified");});
   Test("Registered acquisition-like files are excluded from rotation",()=>{string p=Path.Combine(root,"r_pp_M45.fit");Write(p,64,48,(x,y)=>1000+x,LightHeaders(new DateTime(2026,10,6,21,0,0),"M45"));var f=Classifier.Read(p,root,"Seestar-01","Seestar S50 Pro");Check(f.Calibration=="Registered","Registration prefix not recognized");});
   Test("Filename identifiers and common names resolve without image reads",()=>{Check(Catalog.TargetFromFilename("Light_M_33_60s_20261006.fit")=="M33","Separated Messier ID");Check(Catalog.TargetFromFilename("Stacked_Heart_Nebula_120s.fits.gz")=="IC1805","Heart alias");Check(Catalog.TargetFromFilename("heartnebula_001.fit")=="IC1805","Compact common name");Check(Catalog.TargetFromFilename("Light_NGC_281.fit")=="NGC281","NGC ID");var f=new Frame{OriginalName="Light_M33.fit",SourcePath="missing-image.fit",Target="HID001"};Check(TargetIdentification.ApplyFilename(f)&&f.Target=="M33","Filename-only identification required pixels");});
   Test("Ambiguous and niche filename labels require solving",()=>{Check(Catalog.TargetFromFilename("HID1234567_001.fit")==null,"Opaque ID guessed");Check(Catalog.TargetFromFilename("Light_M31_and_M33.fit")==null,"Multiple targets guessed");Check(Catalog.TargetFromFilename("HIDM33_001.fit")==null,"Identifier boundary ignored");Check(Catalog.TargetFromFilename("Light_M330.fit")==null,"Unknown Messier object invented");Check(TargetIdentification.NeedsPlateSolve(new Frame{OriginalName="HID123.fit",Target="HID123"}),"Niche label not routed to solver");Check(TargetIdentification.NeedsPlateSolve(new Frame{OriginalName="M31_and_M33.fit",Target="M31"}),"Conflicting filename did not require solving");Check(!TargetIdentification.NeedsPlateSolve(new Frame{OriginalName="M31_and_M33.fit",Target="Custom target",TargetEvidence="User assigned"}),"Manual target ignored during automatic solving");});
   Test("Mixed source structures identify make without inventing Dwarf model",()=>{string source=Path.Combine(root,"mixed-makes");string a=Path.Combine(source,"MyWorks","M33_sub","Light_M33.fit"),b=Path.Combine(source,"Astronomy","DWARF_RAW_HID123_EXP_60_GAIN_60","raw_0001.fit");Directory.CreateDirectory(Path.GetDirectoryName(a));Directory.CreateDirectory(Path.GetDirectoryName(b));Write(a,64,48,(x,y)=>900,new Dictionary<string,string>());Write(b,64,48,(x,y)=>1100,new Dictionary<string,string>());var seestar=Classifier.Read(a,source,"Unit-01","Auto");var dwarf=Classifier.Read(b,source,"Unit-02","Auto");Check(seestar.Make=="Seestar"&&dwarf.Make=="DWARFLAB","Mixed make detection");Check(dwarf.Model=="Dwarf (model unknown)","Dwarf model invented");var leaf=Classifier.Read(b,Path.GetDirectoryName(b),"Unit-02","Auto");Check(leaf.Make=="DWARFLAB","Selected session root not inspected");});
   Test("Dwarf sidecar establishes make and explicit model remains selectable",()=>{string source=Path.Combine(root,"sidecar-make");Directory.CreateDirectory(source);string file=Path.Combine(source,"raw_0001.fit");Write(file,64,48,(x,y)=>1100,new Dictionary<string,string>());File.WriteAllText(Path.Combine(source,"shotsInfo.json"),"{\"targetName\":\"HID123\"}");var f=Classifier.Read(file,source,"Unit-03","Auto");Check(f.Make=="DWARFLAB"&&f.Model=="Dwarf (model unknown)","Sidecar make detection");Check(Classifier.Read(file,source,"Unit-03","Dwarf 3").Model=="Dwarf 3","Explicit model ignored");Check(InstrumentDetection.MakeOf("DWARF3")=="DWARFLAB","Compact model metadata ignored");});
   Test("Unmarked raw folders remain unknown",()=>{string source=Path.Combine(root,"generic-mirror");Directory.CreateDirectory(source);string file=Path.Combine(source,"raw_0001.fit");Write(file,64,48,(x,y)=>700,new Dictionary<string,string>());Check(Classifier.Read(file,source,"Unit-04","Auto").Make=="Unknown","Generic raw frame assigned a make");});
   Test("Different makes do not share calibration or export groups",()=>{var a=new Frame{Make="Seestar",Telescope="Unit-01",Camera="Telephoto",Kind="Light",BinX=1,BinY=1,Gain=60,Exposure=60,Temperature=10,Calibration="Uncalibrated"};var b=a.Clone();b.Make="DWARFLAB";b.Kind="Dark";Check(!Exporter.MatchesCalibration(a,b)&&a.Group!=b.Group,"Cross-make calibration accepted");});
   Test("Default import keeps originals and records source disposition",()=>{string source=Path.Combine(root,"keep-source");Directory.CreateDirectory(source);string file=Path.Combine(source,"Light_M33.fit");Write(file,64,48,(x,y)=>1600,new Dictionary<string,string>());using(var repo=new Repository(Path.Combine(root,"keep-repo"))){var plan=repo.Scan(source,"Unit-01","Auto",ct,NoProgress);var result=repo.Import(plan.Frames,ct,NoProgress);Check(File.Exists(file)&&result.Imported==1&&result.OriginalsDeleted==0,"Default import removed source");Check(repo.All().First().SourceDisposition=="Original retained","Retention not indexed");var duplicate=repo.Scan(source,"Unit-01","Auto",ct,NoProgress);var empty=repo.Import(duplicate.Frames,ct,NoProgress,new ImportOptions{DeleteOriginals=true,SourceRoot=source});Check(empty.Imported==0&&File.Exists(file),"Known duplicate removed");}});
   Test("Deletion option rejects missing or overlapping source boundaries",()=>{string source=Path.Combine(root,"boundary-source");Directory.CreateDirectory(source);string file=Path.Combine(source,"Light_M33.fit");Write(file,64,48,(x,y)=>2100,new Dictionary<string,string>());using(var repo=new Repository(Path.Combine(root,"boundary-repo"))){var plan=repo.Scan(source,"Unit-01","Auto",ct,NoProgress);Expect(()=>repo.Import(plan.Frames,ct,NoProgress,new ImportOptions{DeleteOriginals=true}),"Missing source root accepted");Expect(()=>SourceCleanup.ValidateRoots(repo.Root,repo.Root),"Same source/repo accepted");Check(File.Exists(file)&&repo.All().Count==0,"Boundary failure mutated data");}});
   Test("Changed source before import is preserved when deletion is enabled",()=>{string source=Path.Combine(root,"changed-source");Directory.CreateDirectory(source);string file=Path.Combine(source,"Light_M33.fit");Write(file,64,48,(x,y)=>1300,new Dictionary<string,string>());using(var repo=new Repository(Path.Combine(root,"changed-repo"))){var plan=repo.Scan(source,"Unit-01","Auto",ct,NoProgress);Write(file,64,48,(x,y)=>1400,new Dictionary<string,string>());var changed=repo.Import(plan.Frames,ct,NoProgress,new ImportOptions{DeleteOriginals=true,SourceRoot=source});Check(changed.Failed==1&&changed.Imported==0,"Changed source imported");Check(File.Exists(file)&&repo.All().Count==0,"Changed source lost");}});
   Test("Canceled import preserves originals",()=>{string source=Path.Combine(root,"cancel-source");Directory.CreateDirectory(source);string file=Path.Combine(source,"Light_M33.fit");Write(file,64,48,(x,y)=>1700,new Dictionary<string,string>());using(var repo=new Repository(Path.Combine(root,"cancel-repo"))){var plan=repo.Scan(source,"Unit-01","Auto",ct,NoProgress);var token=new CancellationTokenSource();token.Cancel();Expect(()=>repo.Import(plan.Frames,token.Token,NoProgress,new ImportOptions{DeleteOriginals=true,SourceRoot=source}),"Cancellation ignored");Check(File.Exists(file)&&repo.All().Count==0,"Canceled import removed source");}});
   WindowsTest("Native verified cleanup removes only newly imported FITS",()=>{string source=Path.Combine(root,"delete-source");Directory.CreateDirectory(source);string file=Path.Combine(source,"Light_M33.fit"),duplicate=Path.Combine(source,"duplicate.fit"),sidecar=Path.Combine(source,"shotsInfo.json");Write(file,64,48,(x,y)=>2200,new Dictionary<string,string>());File.Copy(file,duplicate);File.WriteAllText(sidecar,"{\"targetName\":\"M33\"}");using(var repo=new Repository(Path.Combine(root,"delete-repo"))){var plan=repo.Scan(source,"Unit-01","Auto",ct,NoProgress);string copied=plan.Frames.Single(f=>f.Status=="New").SourcePath,kept=plan.Frames.Single(f=>f.Status=="Duplicate in source").SourcePath;var result=repo.Import(plan.Frames,ct,NoProgress,new ImportOptions{DeleteOriginals=true,SourceRoot=source});Check(result.OriginalsDeleted==1&&result.OriginalsKept==0,string.Join(";",result.CleanupErrors));Check(!File.Exists(copied)&&File.Exists(kept)&&File.Exists(sidecar),"Duplicate or sidecar removed");var stored=repo.All().Single();Check(Util.Hash(repo.FilePath(stored),ct)==stored.Hash&&stored.SourceDisposition.StartsWith("Original deleted"),"Verified copy/index missing");}});
   WindowsTest("Native cleanup rejects a changed repository copy",()=>{string source=Path.Combine(root,"delete-mismatch-source"),destination=Path.Combine(root,"delete-mismatch-repo");Directory.CreateDirectory(source);Directory.CreateDirectory(destination);string original=Path.Combine(source,"source.fit"),copy=Path.Combine(destination,"copy.fit");File.WriteAllText(original,"source-data");File.WriteAllText(copy,"changed-copy");string expected=Util.Hash(original,ct);Expect(()=>SourceCleanup.DeleteVerified(original,copy,expected,source,destination,ct),"Changed copy allowed deletion");Check(File.Exists(original),"Source removed after mismatch");});
   WindowsTest("Native cleanup rejects a hard link to the repository copy",()=>{string source=Path.Combine(root,"hardlink-source"),destination=Path.Combine(root,"hardlink-repo");Directory.CreateDirectory(source);Directory.CreateDirectory(destination);string original=Path.Combine(source,"source.fit"),copy=Path.Combine(destination,"copy.fit");File.WriteAllText(original,"same-file");Check(CreateHardLink(copy,original,IntPtr.Zero),"Test hard link creation failed");Expect(()=>SourceCleanup.DeleteVerified(original,copy,Util.Hash(original,ct),source,destination,ct),"Same file identity allowed deletion");Check(File.Exists(original)&&File.Exists(copy),"Hard-linked file lost");});
   Test("Fast streaming scan defers hashes and deduplicates during verified copy",()=>{string source=Path.Combine(root,"fast-source");Directory.CreateDirectory(source);string one=Path.Combine(source,"Light_M33.fit"),two=Path.Combine(source,"renamed.fit");Write(one,64,48,(x,y)=>1000,new Dictionary<string,string>{{"OBJECT","'M33'"},{"IMAGETYP","'LIGHT'"}});File.Copy(one,two);using(var repo=new Repository(Path.Combine(root,"fast-repo"))){int emitted=0;var plan=repo.Scan(source,"Unit-01","Auto",ct,NoProgress,false,f=>emitted++,true);Check(emitted==2&&plan.Frames.All(f=>string.IsNullOrEmpty(f.Hash)),"Fast scan read payload hashes or withheld rows");var events=new List<string>();var result=repo.Import(plan.Frames,ct,NoProgress,new ImportOptions{SourceRoot=source,Workers=2,OnFrame=f=>events.Add(f.Status)});Check(result.Imported==1&&result.Duplicates==1&&result.Failed==0,"Copy-time deduplication failed");Check(events.Contains("Copying")&&events.Contains("Imported")&&events.Contains("Duplicate"),"Live import states absent");var stored=repo.All().Single();Check(Util.Hash(repo.FilePath(stored),ct)==stored.Hash,"Combined-copy hash incorrect");}});
   Test("Same filename size and restored modification time do not establish duplicates",()=>{string source=Path.Combine(root,"same-size-source");Directory.CreateDirectory(source);string file=Path.Combine(source,"Light_M33.fit");Write(file,64,48,(x,y)=>1200,new Dictionary<string,string>());using(var repo=new Repository(Path.Combine(root,"same-size-repo"))){var first=repo.Scan(source,"Unit-01","Auto",ct,NoProgress,false,null,true);repo.Import(first.Frames,ct,NoProgress,new ImportOptions{SourceRoot=source});long size=new FileInfo(file).Length;DateTime time=File.GetLastWriteTimeUtc(file);Write(file,64,48,(x,y)=>2400,new Dictionary<string,string>());File.SetLastWriteTimeUtc(file,time);Check(new FileInfo(file).Length==size,"Fixture size changed");var second=repo.Scan(source,"Unit-01","Auto",ct,NoProgress,false,null,true);var result=repo.Import(second.Frames,ct,NoProgress,new ImportOptions{SourceRoot=source});Check(result.Imported==1&&repo.All().Count==2,"Same-size changed contents skipped");}});
   Test("Import isolates one failed source and completes later valid files",()=>{string source=Path.Combine(root,"failure-source");Directory.CreateDirectory(source);string bad=Path.Combine(source,"Light_bad.fit"),good=Path.Combine(source,"Light_M33.fit");Write(bad,64,48,(x,y)=>1000,new Dictionary<string,string>());Write(good,64,48,(x,y)=>2000,new Dictionary<string,string>());using(var repo=new Repository(Path.Combine(root,"failure-repo"))){var plan=repo.Scan(source,"Unit-01","Auto",ct,NoProgress,false,null,true);File.Delete(bad);var result=repo.Import(plan.Frames,ct,NoProgress,new ImportOptions{SourceRoot=source,Workers=2});Check(result.Failed==1&&result.Imported==1&&repo.All().Count==1,"One error aborted the whole batch");Check(result.Errors.Single().Contains(bad)&&result.Errors.Single().Contains("0x"),"Error lacks path/code");Check(File.Exists(good)&&Directory.GetFiles(Path.Combine(repo.Meta,"staging")).Length==0,"Original or staging cleanup incorrect");}});
   Test("Indexed manifest and portable checkpoint survive reopening",()=>{string source=Path.Combine(root,"manifest-source"),destination=Path.Combine(root,"manifest-repo"),working="";Directory.CreateDirectory(source);Write(Path.Combine(source,"Light_M33.fit"),64,48,(x,y)=>1800,new Dictionary<string,string>());using(var repo=new Repository(destination)){var plan=repo.Scan(source,"Unit-01","Auto",ct,NoProgress,false,null,true);repo.Import(plan.Frames,ct,NoProgress,new ImportOptions{SourceRoot=source});working=repo.WorkingIndex;Check(!Util.Within(working,destination)&&File.Exists(Path.Combine(repo.Meta,"index.sqlite")),"Working/portable index placement wrong");using(var database=new Database(working)){var manifest=Util.Deserialize<SourceManifest>(database.Query("SELECT data FROM source_manifest").Single());Check(manifest.Status=="Complete"&&manifest.Source.Size>0&&manifest.Source.Modified>0&&!string.IsNullOrEmpty(manifest.Hash)&&!string.IsNullOrEmpty(manifest.Destination),"Manifest identity/content fields missing");}}using(var repo=new Repository(destination))Check(repo.All().Count==1,"Reopening lost records");using(var portable=new Database(Path.Combine(destination,".astroarchive","index.sqlite")))Check(portable.Query("SELECT hash FROM files").Count==1,"Portable snapshot incomplete");});
   Test("Untrusted metadata cannot enable unchanged-content shortcuts",()=>{var a=new FileStamp{Identity="volume:file",Reliable=true,Size=123,Modified=456,Created=2,Changed=3};var b=Util.Deserialize<FileStamp>(Util.Serialize(a));Check(a.VerifiedUnchanged(b),"Stable trusted identity rejected");b.Identity="other:file";Check(!a.VerifiedUnchanged(b),"Changed identity accepted");b.Identity=a.Identity;b.Reliable=false;Check(!a.VerifiedUnchanged(b),"Unsupported filesystem trusted");b.Reliable=true;b.Attributes=0x400000;Check(!a.VerifiedUnchanged(b),"Offline placeholder trusted");b.Attributes=0;b.Changed++;Check(!a.VerifiedUnchanged(b),"Preserved mtime concealed metadata change");});
   Test("Header byte accounting measures actual FITS header reads",()=>{string file=Path.Combine(root,"header-count.fit");Write(file,64,48,(x,y)=>1200,new Dictionary<string,string>());long bytes=0;var header=Fits.Header(file,n=>bytes+=n);Check(bytes==2880&&header.Width==64,"Header read accounting includes payload or misses bytes");});
   Test("Adaptive import benchmarks 1 2 4 8 workers and retains its choice",()=>{string source=Path.Combine(root,"workers-source"),template=Path.Combine(root,"workers-template.fit");Directory.CreateDirectory(source);Write(template,512,1024,(x,y)=>1500,new Dictionary<string,string>{{"OBJECT","'M33'"},{"IMAGETYP","'LIGHT'"}});for(int i=0;i<64;i++){string file=Path.Combine(source,"Light_M33_"+i.ToString("000")+".fit");File.Copy(template,file);using(var output=new FileStream(file,FileMode.Open,FileAccess.Write)){output.Position=2880;output.WriteByte((byte)i);}}using(var repo=new Repository(Path.Combine(root,"workers-repo"))){var plan=repo.Scan(source,"Unit-01","Auto",ct,NoProgress,false,null,true);var result=repo.Import(plan.Frames,ct,NoProgress,new ImportOptions{SourceRoot=source,Retune=true});Check(result.Imported==64&&result.Failed==0&&result.Trials.Count>=2&&result.Trials.First().Workers==1&&result.Trials.All(t=>new[]{1,2,4,8}.Contains(t.Workers)),"Pilot did not exercise all worker counts");Check(new[]{1,2,4,8}.Contains(result.Workers)&&result.Trials.All(t=>t.Seconds>0),"Worker selection/timing missing");using(var database=new Database(repo.WorkingIndex))Check(database.Query("SELECT data FROM sessions WHERE id LIKE 'workers150:%'").Single()==result.Workers.ToString(),"Tuning decision not retained");Check(repo.Verify(ct,NoProgress)==0,"Concurrent copy changed bytes");}});
   Test("Stage throughput reports processed bytes and completes byte-weighted ETA",()=>{var metrics=new PipelineMetrics(NoProgress){Total=2,TotalBytes=300};using(var scope=metrics.Begin("Copy + source hash","fixture")){scope.Bytes(100);scope.Complete();}metrics.Complete(100);var mid=metrics.Progress();Check(mid.Stages.Single(s=>s.Stage=="Copy + source hash").Bytes==100,"ETA or stage bytes missing");metrics.Complete(200);Check(!metrics.Progress().Finished,"Pending finalisation reported complete");metrics.Finish("Complete");Check(metrics.Progress().RemainingSeconds==0,"Completed ETA is not zero");});
   Test("DWARF calibration cam folders stay separate and conflicts remain unknown",()=>{string source=Path.Combine(root,"camera-source"),tele=Path.Combine(source,"Astronomy","CALI_FRAME","Dark","cam_0","dark_exp_60_gain_60_bin_2_10C_stack_10.fit"),wide=Path.Combine(source,"Astronomy","CALI_FRAME","Dark","cam_1","dark_exp_60_gain_60_bin_1_10C_stack_10.fit");Directory.CreateDirectory(Path.GetDirectoryName(tele));Directory.CreateDirectory(Path.GetDirectoryName(wide));Write(tele,64,48,(x,y)=>1200,new Dictionary<string,string>());Write(wide,64,48,(x,y)=>1600,new Dictionary<string,string>());var a=Classifier.Read(tele,source,"Dwarf-03","Auto");var b=Classifier.Read(wide,source,"Dwarf-03","Auto");Check(a.Camera=="Telephoto"&&b.Camera=="Wide"&&a.Kind=="Master dark"&&b.Kind=="Master dark","Factory cam folder distinction failed");var light=a.Clone();light.Kind="Light";light.Calibration="Uncalibrated";Check(!Exporter.MatchesCalibration(light,b),"Wide dark supplied to tele lights");Write(wide,64,48,(x,y)=>1600,new Dictionary<string,string>{{"CAMID","'0'"}});Check(Classifier.Read(wide,source,"Dwarf-03","Auto").Camera=="Unknown","Contradictory camera markers guessed");string unknown=Path.Combine(source,"DWARF_DARK","dark_bin_2.fit");Directory.CreateDirectory(Path.GetDirectoryName(unknown));Write(unknown,64,48,(x,y)=>1000,new Dictionary<string,string>());Check(Classifier.Read(unknown,source,"Dwarf-03","Auto").Camera=="Unknown","Binning/dimensions used as camera identity");});
   Test("Export session separation is opt-in for subs and stacks",()=>{string source=Path.Combine(root,"sessions-source");foreach(string session in new[]{"SessionA","SessionB"})Write(Path.Combine(source,session,"Light_M33.fit"),64,48,(x,y)=>session=="SessionA"?1400:1800,LightHeaders(new DateTime(2026,10,6,21,0,0),"M33"));var stack=LightHeaders(new DateTime(2026,10,6,21,0,0),"M33");stack["NCOMBINE"]="10";Write(Path.Combine(source,"SessionA","Stacked_M33.fit"),64,48,(x,y)=>2200,stack);using(var repo=new Repository(Path.Combine(root,"sessions-repo"))){var plan=repo.Scan(source,"Unit-01","Seestar S50",ct,NoProgress);repo.Import(plan.Frames,ct,NoProgress);var merged=Exporter.Create(repo,repo.All(),new ExportOptions{Parent=root,Name="sessions-merged",Mode="Both",IncludeCalibration=false},ct,NoProgress);Check(!Directory.Exists(Path.Combine(merged,"sessions"))&&Directory.GetDirectories(merged,"lights",SearchOption.AllDirectories).Length==1,"Default separates sessions");var separate=Exporter.Create(repo,repo.All(),new ExportOptions{Parent=root,Name="sessions-separated",Mode="Both",IncludeCalibration=false,SeparateSessions=true},ct,NoProgress);Check(Directory.GetDirectories(Path.Combine(separate,"sessions")).Length==2&&Directory.GetDirectories(separate,"lights",SearchOption.AllDirectories).Length==2&&Directory.GetFiles(Path.Combine(separate,"sessions"),"*Stacked_M33.fit",SearchOption.AllDirectories).Length==1&&Directory.GetFiles(separate,"*.fit",SearchOption.AllDirectories).Length==3,"Session export lost or merged files");}});
   Test("Archive reset deletes indexed copies and cache but retains sources and unindexed files",()=>{string source=Path.Combine(root,"reset-source"),destination=Path.Combine(root,"reset-repo");Directory.CreateDirectory(source);string file=Path.Combine(source,"Light_M33.fit");Write(file,64,48,(x,y)=>1900,new Dictionary<string,string>());using(var repo=new Repository(destination)){var plan=repo.Scan(source,"Unit-01","Auto",ct,NoProgress);repo.Import(plan.Frames,ct,NoProgress);repo.CachePut("solve120:test","cached");File.WriteAllText(Path.Combine(destination,"unindexed.txt"),"keep");string copy=repo.FilePath(repo.All().Single());var errors=repo.ResetArchive(ct,NoProgress);Check(errors.Count==0&&!File.Exists(copy)&&File.Exists(file)&&File.Exists(Path.Combine(destination,"unindexed.txt")),"Reset crossed its deletion scope");Check(repo.All().Count==0&&repo.CacheGet("solve120:test")==null,"Reset retained archive data/cache");Check(repo.Deletions().Count==1&&repo.Scan(source,"Unit-01","Auto",ct,NoProgress).Frames.Single().Status=="Deleted","Reset lost deletion exclusions");}});
   Test("Reset boundaries and cancellation keep indexed files",()=>{string source=Path.Combine(root,"reset-cancel-source");Directory.CreateDirectory(source);Write(Path.Combine(source,"Light_M33.fit"),64,48,(x,y)=>1800,new Dictionary<string,string>());using(var repo=new Repository(Path.Combine(root,"reset-cancel-repo"))){var plan=repo.Scan(source,"Unit-01","Auto",ct,NoProgress);repo.Import(plan.Frames,ct,NoProgress);string copy=repo.FilePath(repo.All().Single());Expect(()=>Repository.CheckManagedPath(source,repo.Root),"Outside reset path accepted");using(var cancel=new CancellationTokenSource()){cancel.Cancel();Expect(()=>repo.ResetArchive(cancel.Token,NoProgress),"Reset ignored cancellation");}Check(File.Exists(copy)&&repo.All().Count==1,"Canceled reset deleted a file");}});
   Test("Cloud provider directories are distinct from path redirects",()=>{Check(!FileStamp.IsRedirectTag(0x9000001A)&&!FileStamp.IsRedirectTag(0x9000F01A),"Cloud placeholders treated as links");Check(FileStamp.IsRedirectTag(0xA000000C)&&FileStamp.IsRedirectTag(0xA0000003),"Symlink/junction traversal allowed");});
   Test("Unreadable FITS remain visible in scan results with their error",()=>{string source=Path.Combine(root,"unreadable-source");Directory.CreateDirectory(source);File.WriteAllText(Path.Combine(source,"broken.fit"),"not FITS");using(var repo=new Repository(Path.Combine(root,"unreadable-repo"))){int emitted=0;var plan=repo.Scan(source,"Unit-01","Auto",ct,NoProgress,false,f=>emitted++,true);Check(plan.Errors.Count==1&&plan.Frames.Single().Status=="Unreadable"&&emitted==1,"Failed scan row was hidden");Check(repo.Import(plan.Frames,ct,NoProgress,new ImportOptions{SourceRoot=source}).Imported==0,"Unreadable data imported");}});
   Test("Cloud hydration preserves content guards without enabling metadata shortcuts",()=>{var cloud=new FileStamp{Size=100,Modified=2,Created=1,Identity="",Attributes=0x400000};var local=new FileStamp{Size=100,Modified=2,Created=1,Identity="volume:file",Changed=50,Reliable=true};Check(cloud.ContentSame(local)&&!cloud.VerifiedUnchanged(local),"Hydration mistaken for content change or trusted shortcut");local.Modified++;Check(!cloud.ContentSame(local),"Modified cloud content accepted");});
   Test("Header captures source state while its read handle is open",()=>{string file=Path.Combine(root,"locked-header.fit");Write(file,64,48,(x,y)=>1400,new Dictionary<string,string>());FileStamp stamp=null;Fits.Header(file,null,s=>stamp=s);Check(stamp!=null&&stamp.Size==new FileInfo(file).Length&&stamp.ContentSame(FileStamp.Read(file)),"Header source state missing");});
   Test("Session metadata is read once per scan and protected against later changes",()=>{string source=Path.Combine(root,"metadata-cache-source");Directory.CreateDirectory(source);string sidecar=Path.Combine(source,"shotsInfo.json");File.WriteAllText(sidecar,"{\"targetName\":\"HID123\",\"cameraId\":0}");for(int i=0;i<2;i++)Write(Path.Combine(source,"raw_"+i+".fit"),64,48,(x,y)=>1200+i,new Dictionary<string,string>());using(var repo=new Repository(Path.Combine(root,"metadata-cache-repo"))){var plan=repo.Scan(source,"Unit-01","Auto",ct,NoProgress,false,null,true);Check(plan.Metrics.Snapshot().Single(m=>m.Stage=="Metadata").Bytes==5760+new FileInfo(sidecar).Length,"Sidecar was reread for each frame");Check(plan.Frames.All(f=>f.SourceMetadataStamp!=null&&f.Camera=="Telephoto"),"Sidecar state/channel missing");File.AppendAllText(sidecar," ");var result=repo.Import(plan.Frames,ct,NoProgress,new ImportOptions{SourceRoot=source});Check(result.Failed==2&&repo.All().Count==0&&Directory.GetFiles(source,"*.fit").Length==2,"Changed sidecar committed or source removed");}});
   Test("Cached plate solutions validate repository content before reuse",()=>{string source=Path.Combine(root,"solve-cache-source");Directory.CreateDirectory(source);Write(Path.Combine(source,"Light_M33.fit"),64,48,(x,y)=>1500,new Dictionary<string,string>());using(var repo=new Repository(Path.Combine(root,"solve-cache-repo"))){var plan=repo.Scan(source,"Unit-01","Auto",ct,NoProgress);repo.Import(plan.Frames,ct,NoProgress);var f=repo.All().Single();var settings=new Settings{Astap="not-installed.exe"};repo.CachePut(repo.SolverKey(f,settings),Util.Serialize(new SolveResult{Solver="Cached test solution",RA=23.4,Dec=30.6,Suggested="M33"}));Check(repo.CachedSolve(f,settings,ct,t=>{}).Suggested=="M33","Valid solution cache not used");string copy=repo.FilePath(f);using(var stream=new FileStream(copy,FileMode.Open,FileAccess.Write)){stream.Position=2880;stream.WriteByte(123);}Expect(()=>repo.CachedSolve(f,settings,ct,t=>{}),"Changed repository content reused cache");}});
   Test("Import report retains discovery metadata and error stage details",()=>{string source=Path.Combine(root,"stage-report-source");Directory.CreateDirectory(source);Write(Path.Combine(source,"Light_M33.fit"),64,48,(x,y)=>1700,new Dictionary<string,string>());using(var repo=new Repository(Path.Combine(root,"stage-report-repo"))){var plan=repo.Scan(source,"Unit-01","Auto",ct,NoProgress,false,null,true);var result=repo.Import(plan.Frames,ct,NoProgress,new ImportOptions{SourceRoot=source,ScanMetrics=plan.Metrics});Check(result.Metrics.Snapshot().Single(m=>m.Stage=="Discovery").Files==1&&result.Metrics.Snapshot().Single(m=>m.Stage=="Metadata").Bytes==2880,"Scan counters lost at import");Check(File.ReadAllText(Path.Combine(repo.Meta,"reports","last-import.txt"))==repo.LastReport,"Saved report differs");}});
   Test("A portable legacy index migrates into the local working index",()=>{string destination=Path.Combine(root,"legacy-index-repo"),meta=Path.Combine(destination,".astroarchive");Directory.CreateDirectory(meta);using(var old=new Database(Path.Combine(meta,"index.sqlite")))old.Exec("INSERT INTO files(hash,data) VALUES(?,?)","legacy",Util.Serialize(new Frame{Hash="legacy",OriginalName="legacy.fit",RelativePath="legacy.fit"}));using(var repo=new Repository(destination)){Check(repo.All().Single().Hash=="legacy"&&File.Exists(repo.WorkingIndex),"Legacy records lost during migration");}});
   Test("Merged sessions receive calibration compatible with every light",()=>{string source=Path.Combine(root,"merged-cal-source");Directory.CreateDirectory(source);Write(Path.Combine(source,"Light_M33_A.fit"),64,48,(x,y)=>1600,LightHeaders(new DateTime(2026,10,5,21,0,0),"M33"));Write(Path.Combine(source,"Light_M33_B.fit"),64,48,(x,y)=>1800,LightHeaders(new DateTime(2026,10,6,21,0,0),"M33"));var headers=LightHeaders(new DateTime(2026,10,5,21,0,0),"M33");headers["IMAGETYP"]="'FLAT'";Write(Path.Combine(source,"Flat_A.fit"),64,48,(x,y)=>2100,headers);using(var repo=new Repository(Path.Combine(root,"merged-cal-repo"))){var plan=repo.Scan(source,"Unit-01","Dwarf 3",ct,NoProgress);repo.Import(plan.Frames,ct,NoProgress);foreach(var f in repo.All()){f.Filter="Standard";f.BinX=f.BinY=1;f.Calibration="Uncalibrated";repo.Save(f);}string project=Exporter.Create(repo,repo.All(),new ExportOptions{Parent=root,Name="merged-cal-project"},ct,NoProgress);Check(Directory.GetFiles(project,"*Flat_A.fit",SearchOption.AllDirectories).Length==0,"First-night flat applied to both nights");}});
   Test("Repeated checkpoints preserve every indexed record across close and reopen",()=>{string destination=Path.Combine(root,"checkpoint-stress-repo");for(int iteration=0;iteration<8;iteration++){using(var repo=new Repository(destination)){for(int i=0;i<12;i++){string hash="record-"+(iteration*12+i);repo.Save(new Frame{Hash=hash,OriginalName=hash+".fit",RelativePath=hash+".fit"});if(i%3==0)repo.Checkpoint(ct);}Check(repo.All().Count==(iteration+1)*12,"Checkpoint lost active records");using(var reader=new Database(repo.WorkingIndex))Check(reader.Query("SELECT hash FROM files").Count==(iteration+1)*12,"Concurrent read sees incomplete index");}using(var repo=new Repository(destination))Check(repo.All().Count==(iteration+1)*12,"Reopen lost verified records");}using(var portable=new Database(Path.Combine(destination,".astroarchive","index.sqlite")))Check(portable.Query("SELECT hash FROM files").Count==96,"Portable snapshot lost records");});
   Test("Pixel reading reports only the header and consumed pixel bytes",()=>{string file=Path.Combine(root,"pixel-count.fit");Write(file,64,48,(x,y)=>1200,new Dictionary<string,string>());long bytes=0;Fits.Image(file,ct,n=>bytes+=n);Check(bytes==2880+64*48*2,"Pixel read accounting includes padding or omits payload");});
   Test("Analysis defaults are disabled",()=>{var settings=new Settings();Check(!settings.AutoSolve&&!settings.AutoRotation,"Analysis defaults enabled");});
   Test("Selected exports include arbitrary frame types and only selected files",()=>{
    string source=Path.Combine(root,"selected-export-source");Directory.CreateDirectory(source);for(int i=0;i<3;i++)Write(Path.Combine(source,"capture_"+i+".fit"),64,48,(x,y)=>1200+i,new Dictionary<string,string>());
    using(var repo=new Repository(Path.Combine(root,"selected-export-repo"))){var plan=repo.Scan(source,"Unit-01","Dwarf 3",ct,NoProgress);repo.Import(plan.Frames,ct,NoProgress);var frames=repo.All();frames[0].Kind="Dark";frames[0].Rejected=true;frames[1].Kind="Unknown";repo.Save(frames[0]);repo.Save(frames[1]);
     string project=Exporter.Create(repo,frames.Take(2).ToList(),new ExportOptions{Parent=root,Name="selected-export",Mode="Files",IncludeCalibration=false},ct,NoProgress);
     var copies=Directory.GetFiles(project,"*.fit",SearchOption.AllDirectories);Check(copies.Length==2&&copies.Select(p=>Util.Hash(p,ct)).OrderBy(h=>h).SequenceEqual(frames.Take(2).Select(f=>f.Hash).OrderBy(h=>h)),"Selected export copied the wrong files");Check(repo.All().Count==3&&Directory.GetFiles(source,"*.fit").Length==3&&!File.Exists(Path.Combine(project,"INCOMPLETE.txt")),"Export changed inputs or remained incomplete");
     Expect(()=>Exporter.Create(repo,frames,new ExportOptions{Parent=root,Name="invalid-export",Mode="Invalid"},ct,NoProgress),"Invalid mode accepted");Check(!Directory.Exists(Path.Combine(root,"invalid-export")),"Invalid export created a folder");
    }
   });
   Test("Stacking exports opt into available matching calibrations",()=>{
    string source=Path.Combine(root,"selection-cal-source");Directory.CreateDirectory(source);for(int i=0;i<5;i++)Write(Path.Combine(source,"capture_"+i+".fit"),64,48,(x,y)=>1700+i,LightHeaders(new DateTime(2026,10,5,21,0,0),"M33"));
    using(var repo=new Repository(Path.Combine(root,"selection-cal-repo"))){repo.Import(repo.Scan(source,"Unit-01","Dwarf 3",ct,NoProgress).Frames,ct,NoProgress);var frames=repo.All();for(int i=0;i<frames.Count;i++){var f=frames[i];f.Kind=i==0?"Light":i==1?"Master dark":"Dark";f.Calibration=i==0?"Uncalibrated":"Calibration frame";f.Camera=i==3?"Wide":"Telephoto";f.Filter="Standard";f.BinX=f.BinY=1;f.Rejected=i==4;repo.Save(f);}var selection=new List<Frame>{frames[0]};Check(Exporter.AvailableCalibrations(selection,repo.All(),false,false).Select(f=>f.Hash).SequenceEqual(new[]{frames[2].Hash}),"Calibration availability included wrong camera, rejected or duplicate master");
     string plain=Exporter.Create(repo,selection,new ExportOptions{Parent=root,Name="selection-without-cal",IncludeCalibration=false},ct,NoProgress),with=Exporter.Create(repo,selection,new ExportOptions{Parent=root,Name="selection-with-cal",IncludeCalibration=true},ct,NoProgress);Check(Directory.GetFiles(plain,"*.fit",SearchOption.AllDirectories).Length==1&&Directory.GetFiles(with,"*.fit",SearchOption.AllDirectories).Length==2,"Calibration export choice ignored");
     frames[0].Calibration="Calibrated";Check(Exporter.AvailableCalibrations(selection,repo.All(),false,true).Count==0,"Calibrated lights offered calibration");frames[0].Calibration="Unknown";Check(Exporter.AvailableCalibrations(selection,repo.All(),false,false).Count==0&&Exporter.AvailableCalibrations(selection,repo.All(),false,true).Count==1,"Unknown calibration opt-in ignored");
     frames[0].Calibration="Uncalibrated";File.Delete(repo.FilePath(frames[2]));var available=Exporter.ExistingCalibrations(repo,repo.All());Check(Exporter.AvailableCalibrations(selection,available,false,false).Single().Hash==frames[1].Hash,"Missing raw calibration prevented the available master fallback");string fallback=Exporter.Create(repo,selection,new ExportOptions{Parent=root,Name="selection-master-fallback",IncludeCalibration=true},ct,NoProgress);Check(Directory.GetFiles(fallback,"*.fit",SearchOption.AllDirectories).Length==2,"Export included a missing calibration");
    }
   });
   Test("Selected stacking exports keep multiple targets in separate folders",()=>{
    string source=Path.Combine(root,"multi-target-source");Directory.CreateDirectory(source);for(int i=0;i<2;i++)Write(Path.Combine(source,"Light_"+i+".fit"),64,48,(x,y)=>1800+i,LightHeaders(new DateTime(2026,10,5,21,0,0),i==0?"M33":"M45"));using(var repo=new Repository(Path.Combine(root,"multi-target-repo"))){repo.Import(repo.Scan(source,"Unit-01","Dwarf 3",ct,NoProgress).Frames,ct,NoProgress);string project=Exporter.Create(repo,repo.All(),new ExportOptions{Parent=root,Name="multi-target-export",IncludeCalibration=false},ct,NoProgress);Check(Directory.GetDirectories(Path.Combine(project,"targets")).Length==2&&Directory.GetFiles(project,"*.fit",SearchOption.AllDirectories).Length==2,"Targets were mixed or lost");}
   });
   Test("Capture filters combine review, camera, night, calibration and search",()=>{
    var rows=new[]{new Frame{Target="M33",Camera="Telephoto",Night="2026-10-06",Calibration="Uncalibrated",Kind="Light",Mount="EQ (likely)",Status="New",OriginalName="Light_M33.fit"},new Frame{Target="M33",Camera="Wide",Night="2026-10-06",Calibration="Calibrated",Kind="Light",Mount="Unknown",Rejected=true,Status="New",OriginalName="failed_M33.fit"},new Frame{Target="M45",Camera="Telephoto",Night="2026-10-05",Status="Missing",OriginalName="M45.fit"}};
    var filters=new CaptureFilters();filters.Values["Review"]="Needs review";Check(filters.Apply(rows,"").Count==2,"Review filter missed rejected or missing captures");filters.Values["Camera"]="Wide";Check(filters.Apply(rows,"M33 failed").Single()==rows[1],"Combined import filters or multiword search failed");filters.Values.Clear();filters.Values["Mount"]="EQ";filters.Values["Night"]="2026-10-06";filters.Values["Calibration"]="Uncalibrated";Check(filters.Apply(rows,"").Single()==rows[0],"Mount normalization or metadata filters failed");filters.Values.Clear();Check(filters.Apply(rows,"").Count==3,"Reset retained filters");filters.Values["Review"]="No issues flagged";Check(filters.Apply(rows,"").Single()==rows[0],"No-issues filter retained a telescope rejection");filters.Values["Review"]="Rejected / reference";Check(filters.Apply(rows,"").Single()==rows[1],"Rejected-only filter missed a telescope rejection");
   });
   Test("Telescope failure markers use filename boundaries and FITS status",()=>{
    string source=Path.Combine(root,"capture-marker-source");Directory.CreateDirectory(source);
    foreach(string name in new[]{"failed.fit","rejected_M33.fit","M33_failure.fits","Light_M33.fit","unfailed_M33.fit"})Write(Path.Combine(source,name),64,48,(x,y)=>1000,new Dictionary<string,string>());
    Check(new[]{"failed.fit","rejected_M33.fit","M33_failure.fits"}.All(name=>Classifier.Read(Path.Combine(source,name),source,"Unit-01","Auto").Rejected),"Telescope failure filename missed");Check(!Classifier.Read(Path.Combine(source,"unfailed_M33.fit"),source,"Unit-01","Auto").Rejected,"Partial word falsely flagged");
    Write(Path.Combine(source,"Light_M33.fit"),64,48,(x,y)=>1000,new Dictionary<string,string>{{"STATUS","'OK'"},{"CAPSTAT","'FAILED'"}});var flagged=Classifier.Read(Path.Combine(source,"Light_M33.fit"),source,"Unit-01","Auto");Check(flagged.Rejected&&flagged.ScreeningIssue.Contains("CAPSTAT: FAILED")&&flagged.ReviewText=="Needs review","FITS failure status absent from scan review");
   });
   Test("Import screening flags telescope rejection and truncated compressed data",()=>{
    string source=Path.Combine(root,"screen-import-source"),destination=Path.Combine(root,"screen-import-repo");Directory.CreateDirectory(source);
    string good=Path.Combine(source,"Light_M33.fit"),rejected=Path.Combine(source,"raw_capture.fit"),gzip=Path.Combine(source,"Light_cut.fits.gz");Write(good,64,48,(x,y)=>1000,new Dictionary<string,string>());Write(rejected,64,48,(x,y)=>2000,new Dictionary<string,string>{{"REJECTED","T"}});
    using(var input=File.OpenRead(good))using(var output=File.Create(gzip))using(var compressed=new GZipStream(output,CompressionMode.Compress)){var partial=new byte[3000];input.Read(partial,0,partial.Length);compressed.Write(partial,0,partial.Length);}
    using(var repo=new Repository(destination)){var plan=repo.Scan(source,"Unit-01","Auto",ct,NoProgress,false,null,true);Check(plan.Frames.Count==3,"Compressed header scan failed");var result=repo.Screen(plan.Frames,true,ct,NoProgress);Check(result.Checked==3&&result.Problems==2,"Rejected/truncated captures not both screened");Check(plan.Frames.Single(f=>f.SourcePath==good).ReviewText=="Passed","Healthy capture failed screening");Check(plan.Frames.Single(f=>f.SourcePath==gzip).Status=="Unreadable","Truncated gzip offered for import");Check(plan.Frames.Single(f=>f.SourcePath==rejected).Rejected,"FITS rejection flag lost");Check(Directory.GetFiles(source).Length==3&&repo.All().Count==0,"Screening copied or deleted files");}
   });
   Test("Current-file screening persists telescope failures and checksum problems",()=>{
    string source=Path.Combine(root,"screen-library-source"),destination=Path.Combine(root,"screen-library-repo");Directory.CreateDirectory(source);for(int i=0;i<4;i++)Write(Path.Combine(source,"Light_"+i+".fit"),64,48,(x,y)=>1000+i,i==3?new Dictionary<string,string>{{"STATUS","'REJECTED'"}}:new Dictionary<string,string>());
    using(var repo=new Repository(destination)){repo.Import(repo.Scan(source,"Unit-01","Auto",ct,NoProgress).Frames,ct,NoProgress);var frames=repo.All();var flagged=frames.Single(f=>f.Rejected);flagged.Rejected=false;flagged.ScreeningIssue="";repo.Save(flagged);frames=frames.OrderBy(f=>f==flagged?1:0).ToList();File.Delete(repo.FilePath(frames[0]));using(var stream=new FileStream(repo.FilePath(frames[1]),FileMode.Open,FileAccess.Write)){stream.Position=2880;stream.WriteByte(42);}var result=repo.Screen(frames,false,ct,NoProgress);Check(result.Problems==3&&frames.Count(f=>f.Rejected)==1&&frames.Count(f=>f.Status=="Missing")==1&&frames.Count(f=>f.Status=="Changed")==1&&frames.Count(f=>f.ReviewText=="Passed")==1,"Archive screening lost file integrity states");}
    using(var reopened=new Repository(destination))Check(reopened.All().Count(CaptureScreening.NeedsReview)==3&&reopened.All().All(f=>f.Screened),"Screening state was not durable");
   });
   Test("Deletion history skips renamed direct telescope copies and survives portable restore",()=>{
    string source=Path.Combine(root,"history-source"),direct=Path.Combine(root,"direct-telescope"),destination=Path.Combine(root,"history-repo"),moved=Path.Combine(root,"portable-history-repo");Directory.CreateDirectory(source);Directory.CreateDirectory(direct);string file=Path.Combine(source,"Light_M33.fit");Write(file,64,48,(x,y)=>1700,new Dictionary<string,string>());File.Copy(file,Path.Combine(direct,"renamed.fit"));
    using(var repo=new Repository(destination)){repo.Import(repo.Scan(source,"Unit-01","Auto",ct,NoProgress).Frames,ct,NoProgress);repo.DeleteFrames(repo.All(),ct,NoProgress);Check(repo.Deletions().Single().DeletedUtc.Length>0,"Deletion timestamp missing");var rescan=repo.Scan(direct,"Unit-01","Auto",ct,NoProgress,false,null,true,true);Check(rescan.Frames.Single().Status=="Deleted"&&repo.Import(rescan.Frames,ct,NoProgress).Imported==0,"New telescope path bypassed deletion history");}
    Directory.CreateDirectory(Path.Combine(moved,".astroarchive"));File.Copy(Path.Combine(destination,".astroarchive","index.sqlite"),Path.Combine(moved,".astroarchive","index.sqlite"));
    using(var restored=new Repository(moved))Check(restored.All().Count==0&&restored.Deletions().Count==1&&restored.Scan(direct,"Unit-01","Auto",ct,NoProgress,false,null,true).Frames.Single().Status=="Deleted","Portable snapshot lost deletion exclusions");
   });
   Test("Changed content at a deleted filename remains importable",()=>{
    string source=Path.Combine(root,"history-changed-source");Directory.CreateDirectory(source);string file=Path.Combine(source,"Light_M33.fit");Write(file,64,48,(x,y)=>1400,new Dictionary<string,string>());
    using(var repo=new Repository(Path.Combine(root,"history-changed-repo"))){repo.Import(repo.Scan(source,"Unit-01","Auto",ct,NoProgress).Frames,ct,NoProgress);repo.DeleteFrames(repo.All(),ct,NoProgress);Write(file,64,48,(x,y)=>2400,new Dictionary<string,string>());var plan=repo.Scan(source,"Unit-01","Auto",ct,NoProgress,false,null,true);Check(plan.Frames.Single().Status=="New"&&repo.Import(plan.Frames,ct,NoProgress).Imported==1,"Filename-only deletion exclusion blocked new content");}
   });
   Test("Import rechecks deletion history for a stale deferred-hash plan",()=>{
    string source=Path.Combine(root,"stale-history-source");Directory.CreateDirectory(source);string file=Path.Combine(source,"Light_M33.fit");Write(file,64,48,(x,y)=>1400,new Dictionary<string,string>());
    using(var repo=new Repository(Path.Combine(root,"stale-history-repo"))){var stale=repo.Scan(source,"Unit-01","Auto",ct,NoProgress,false,null,true);repo.Import(repo.Scan(source,"Unit-01","Auto",ct,NoProgress).Frames,ct,NoProgress);repo.DeleteFrames(repo.All(),ct,NoProgress);var result=repo.Import(stale.Frames,ct,NoProgress,new ImportOptions{SourceRoot=source,DeleteOriginals=true});Check(result.Imported==0&&result.SkippedDeleted==1&&result.OriginalsDeleted==0&&repo.All().Count==0&&File.Exists(file),"Stale plan resurrected a deleted capture or removed its source");Check(!Directory.EnumerateFiles(Path.Combine(repo.Meta,"staging")).Any(),"Skipped copy left staging data");}
   });
   Test("Deleting a selection preserves sources, shared metadata and other captures",()=>{
    string source=Path.Combine(root,"selected-delete-source"),destination=Path.Combine(root,"selected-delete-repo");Directory.CreateDirectory(source);for(int i=0;i<3;i++)Write(Path.Combine(source,"Light_M33_"+i+".fit"),64,48,(x,y)=>1600+i,new Dictionary<string,string>());
    string remaining;using(var repo=new Repository(destination)){repo.Import(repo.Scan(source,"Unit-01","Dwarf 3",ct,NoProgress).Frames,ct,NoProgress);var frames=repo.All();remaining=frames[2].Hash;string unindexed=Path.Combine(repo.Root,"keep.fit"),sidecar=Path.Combine(repo.Meta,"shared.json");File.WriteAllText(unindexed,"unindexed");File.WriteAllText(sidecar,"shared");var forged=frames[0].Clone();forged.RelativePath="keep.fit";var result=repo.DeleteFrames(new[]{forged,frames[0],frames[1]},ct,NoProgress);Check(result.Deleted==2&&result.Errors.Count==0&&repo.All().Single().Hash==remaining,"Deletion did not use exactly the unique indexed selection");Check(File.Exists(unindexed)&&File.Exists(sidecar)&&Directory.GetFiles(source,"*.fit").Length==3,"Deletion affected unrelated files");var rescan=repo.Scan(source,"Unit-01","Dwarf 3",ct,NoProgress);Check(rescan.Frames.Count(f=>f.Status=="Deleted")==2&&repo.Deletions().Count==2,"Deleted captures were offered for reimport");}
    using(var reopened=new Repository(destination))Check(reopened.All().Single().Hash==remaining,"Deleted records returned after reopen");
   });
   Test("Deletion preflights stale and escaping selections before removing anything",()=>{
    string source=Path.Combine(root,"delete-boundary-source");Directory.CreateDirectory(source);for(int i=0;i<2;i++)Write(Path.Combine(source,"Light_"+i+".fit"),64,48,(x,y)=>1300+i,new Dictionary<string,string>());
    using(var repo=new Repository(Path.Combine(root,"delete-boundary-repo"))){repo.Import(repo.Scan(source,"Unit-01","Dwarf 3",ct,NoProgress).Frames,ct,NoProgress);var frames=repo.All();Expect(()=>repo.DeleteFrames(new[]{frames[0],new Frame{Hash="stale"}},ct,NoProgress),"Stale selection accepted");frames[1].RelativePath="../outside.fit";repo.Save(frames[1]);Expect(()=>repo.DeleteFrames(frames,ct,NoProgress),"Escaping indexed path accepted");Check(repo.All().Count==2&&File.Exists(repo.FilePath(frames[0])),"Preflight deleted an earlier valid capture");using(var canceled=new CancellationTokenSource()){canceled.Cancel();Expect(()=>repo.DeleteFrames(new[]{frames[0]},canceled.Token,NoProgress),"Canceled deletion continued");}Check(File.Exists(repo.FilePath(frames[0])),"Canceled capture removed");}
   });
   WindowsTest("Locked selected files retain records while other selected files are deleted",()=>{
    string source=Path.Combine(root,"delete-lock-source");Directory.CreateDirectory(source);for(int i=0;i<2;i++)Write(Path.Combine(source,"Light_"+i+".fit"),64,48,(x,y)=>1400+i,new Dictionary<string,string>());using(var repo=new Repository(Path.Combine(root,"delete-lock-repo"))){repo.Import(repo.Scan(source,"Unit-01","Dwarf 3",ct,NoProgress).Frames,ct,NoProgress);var frames=repo.All();using(File.Open(repo.FilePath(frames[0]),FileMode.Open,FileAccess.Read,FileShare.None)){var result=repo.DeleteFrames(frames,ct,NoProgress);Check(result.Deleted==1&&result.Errors.Count==1&&repo.All().Single().Hash==frames[0].Hash,"Locked capture was removed or other selected capture was skipped");}}
   });
   WindowsTest("Verified unchanged sources skip payload reads on subsequent fast scans",()=>{string source=Path.Combine(root,"cached-source");Directory.CreateDirectory(source);Write(Path.Combine(source,"Light_M33.fit"),64,48,(x,y)=>1100,new Dictionary<string,string>());using(var repo=new Repository(Path.Combine(root,"cached-repo"))){var plan=repo.Scan(source,"Unit-01","Auto",ct,NoProgress,false,null,true);repo.Import(plan.Frames,ct,NoProgress,new ImportOptions{SourceRoot=source});var second=repo.Scan(source,"Unit-01","Auto",ct,NoProgress,false,null,true);Check(second.CacheHits==1&&second.Frames.Single().Status=="Duplicate (cached)"&&second.Metrics.Snapshot().Single(s=>s.Stage=="Metadata").Bytes==0,"Unchanged source reread payload");}});
   PreviewTests();
   PerformanceTests();
   WorkflowRegressions();FilterRegressions();EditedRegressions();HelpTests();
   CompatibilityCases();Console.WriteLine(passed+" tests passed; "+skipped+" platform/optional-codec tests skipped.");File.WriteAllText(Path.Combine(root,"test-results.txt"),passed+" tests passed; "+skipped+" platform/optional-codec tests skipped. Exit code "+Environment.ExitCode);return Environment.ExitCode;
  }
  [System.Runtime.InteropServices.DllImport("kernel32.dll",EntryPoint="CreateHardLinkW",CharSet=System.Runtime.InteropServices.CharSet.Unicode,SetLastError=true)]static extern bool CreateHardLink(string link,string existing,IntPtr security);
  static void NoProgress(ProgressInfo p){}
  static Dictionary<string,string> LightHeaders(DateTime t,string target){return new Dictionary<string,string>{{"OBJECT","'"+target+"'"},{"IMAGETYP","'LIGHT'"},{"DATE-OBS","'"+t.ToString("yyyy-MM-ddTHH:mm:ss",CultureInfo.InvariantCulture)+"'"},{"EXPTIME","60"},{"GAIN","80"},{"CCD-TEMP","10"},{"CAMID","'0'"},{"OBJCTRA","'03:47:00'"},{"OBJCTDEC","'+24:07:00'"}};}
  static List<Star> Stars(int n,int w,int h,int seed){var random=new Random(seed);var a=new List<Star>();for(int i=0;i<n;i++)a.Add(new Star(20+random.NextDouble()*(w-40),20+random.NextDouble()*(h-40),2500+random.NextDouble()*10000));return a;}
  static FitsImage Paint(List<Star> stars,int w,int h,double degrees,double dx,double dy,int seed){var r=new Random(seed);var p=new double[w*h];for(int i=0;i<p.Length;i++)p[i]=900+0.04*(i%w)+0.03*(i/w)+(r.NextDouble()-0.5)*30;double a=degrees*Math.PI/180;
   foreach(var star in stars){double xx=star.X-w/2,yy=star.Y-h/2;double x=Math.Cos(a)*xx-Math.Sin(a)*yy+w/2+dx,y=Math.Sin(a)*xx+Math.Cos(a)*yy+h/2+dy;for(int j=Math.Max(0,(int)y-5);j<Math.Min(h,(int)y+6);j++)for(int k=Math.Max(0,(int)x-5);k<Math.Min(w,(int)x+6);k++)p[j*w+k]+=star.Flux*Math.Exp(-((k-x)*(k-x)+(j-y)*(j-y))/2.4);}
   for(int k=0;k<12;k++)p[r.Next(p.Length)]=40000;return new FitsImage{Pixels=p,Width=w,Height=h};}
  static void Series(bool stable,bool geometry){string tag=stable?(geometry?"eq":"unknown"):"az",src=Path.Combine(root,"series-"+tag);Directory.CreateDirectory(src);var stars=Stars(90,480,320,86);for(int i=0;i<9;i++){var image=Paint(stars,480,320,stable?0:i*0.35,i*0.3,-i*0.2,100+i);var head=LightHeaders(new DateTime(2026,10,6,0,0,0).AddMinutes(i*4),"M45");if(!geometry){head.Remove("OBJCTRA");head.Remove("OBJCTDEC");}Write(Path.Combine(src,"Light_"+i.ToString("000")+".fit"),960,640,(x,y)=>image.Pixels[(y/2)*480+x/2],head);}
   using(var repo=new Repository(Path.Combine(root,"series-repo-"+tag))){var p=repo.Scan(src,"Seestar-01","Seestar S50 Pro",ct,NoProgress);repo.Import(p.Frames,ct,NoProgress);var result=Rotation.Analyze(repo,repo.All(),geometry?(double?)51.5:null,geometry?(double?)0:null,ct,NoProgress);if(stable&&geometry)Check(result.Mount=="EQ?",result.Evidence);else if(stable)Check(result.Mount=="Unknown",result.Evidence);else Check(result.Mount=="Alt-Az?",result.Evidence);Check(result.Points.Count>=6,"Too few series matches");Console.WriteLine("  "+result.Mount+"; "+result.DriftDegrees.ToString("0.000")+"°; "+result.Points.Count+" frames");}
  }
  static string Card(string k,string v){return (k.PadRight(8)+"= "+v).PadRight(80).Substring(0,80);}
  static void Header(Stream s,List<string> cards){string t=string.Concat(cards)+"END".PadRight(80);t=t.PadRight((t.Length+2879)/2880*2880);byte[] b=Encoding.ASCII.GetBytes(t);s.Write(b,0,b.Length);}
  static void Write(string path,int w,int h,Func<int,int,double> value,Dictionary<string,string> extra,bool extension=false){Directory.CreateDirectory(Path.GetDirectoryName(path));using(var s=File.Create(path)){
   if(extension){var primary=new List<string>{Card("SIMPLE","T"),Card("BITPIX","8"),Card("NAXIS","0"),Card("EXTEND","T")};primary.AddRange(extra.Select(kv=>Card(kv.Key,kv.Value)));Header(s,primary);}
   var cards=new List<string>{Card(extension?"XTENSION":"SIMPLE",extension?"'IMAGE'":"T"),Card("BITPIX","16"),Card("NAXIS","2"),Card("NAXIS1",w.ToString()),Card("NAXIS2",h.ToString()),Card("BSCALE","1"),Card("BZERO","32768")};if(extension){cards.Add(Card("PCOUNT","0"));cards.Add(Card("GCOUNT","1"));}else cards.AddRange(extra.Select(kv=>Card(kv.Key,kv.Value)));Header(s,cards);
   for(int y=0;y<h;y++)for(int x=0;x<w;x++){int v=(int)Math.Max(0,Math.Min(65535,value(x,y)))-32768;short n=(short)v;s.WriteByte((byte)(n>>8));s.WriteByte((byte)n);}while(s.Length%2880!=0)s.WriteByte(0);
  }}
  static void WriteFloat(string path,int w,int h,int channels){using(var s=File.Create(path)){Header(s,new List<string>{Card("SIMPLE","T"),Card("BITPIX","-32"),Card("NAXIS","3"),Card("NAXIS1",w.ToString()),Card("NAXIS2",h.ToString()),Card("NAXIS3",channels.ToString())});for(int c=0;c<channels;c++)for(int y=0;y<h;y++)for(int x=0;x<w;x++){byte[] b=BitConverter.GetBytes((float)(10*(c+1)));Array.Reverse(b);s.Write(b,0,b.Length);}while(s.Length%2880!=0)s.WriteByte(0);}}
 }
}
