using System;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
namespace AstroArchive {
 public static class UiHelp {
  public static void Tip(FrameworkElement control,string text){if(string.IsNullOrEmpty(text))return;control.ToolTip=new ToolTip{Content=new TextBlock{Text=text,TextWrapping=TextWrapping.Wrap,MaxWidth=360}};ToolTipService.SetShowOnDisabled(control,true);ToolTipService.SetShowDuration(control,20000);AutomationProperties.SetHelpText(control,text);}
  public static void For(FrameworkElement control,string label){string text;if(DialogTips.TryGetValue(label.TrimEnd('…','.'),out text))Tip(control,text);}
  static readonly Dictionary<string,string> DialogTips=new Dictionary<string,string>{
   {"Physical telescope ID","Name of the physical telescope for these captures. Use Rename telescope in Import to rename a saved device across the repository."},
   {"Camera channel","Telephoto or Wide. Leave blank to keep each capture's camera; separate channels use separate calibration groups."},
   {"Instrument model","Choose the known model, or Keep existing to preserve each capture's current metadata."},
   {"Frame type","Light, Stack, Dark, Flat or Bias; master calibration frames stay separate from individual calibration frames."},
   {"Mount mode","Assign EQ or Alt/Az when known. Unknown preserves uncertainty; rotation analysis provides evidence rather than certainty."},
   {"Calibration state","Describe processing already applied. Calibrated and registered lights do not receive additional calibration during export."},
   {"Exposure seconds (optional)","Exposure duration in seconds, using a decimal dot. Leave blank to keep existing values; zero is valid for bias frames."},
   {"Gain (optional)","Camera gain, using a decimal dot. Leave blank to keep existing values."},
   {"Sensor temperature °C (optional)","Sensor temperature in Celsius, using a decimal dot; negative values are allowed. Leave blank to keep existing values."},
   {"Binning x × y (optional, e.g. 1x1)","Enter horizontal and vertical binning, such as 1x1 or 2x2. Leave blank to keep existing values."},
   {"Apply to entire selected sessions","Extend these metadata edits to every capture in the sessions containing the selected rows."},
   {"Archive folder","Selected repository folder. Use Choose repository folder; the new location takes effect after Save settings."},
   {"Choose repository folder","Choose the repository where AstroArchive stores and indexes verified capture copies."},
   {"ASTAP executable","Path to astap.exe. Local solving also needs an installed ASTAP star database."},
   {"Browse ASTAP","Choose the local ASTAP executable; this does not install ASTAP or its star database."},
   {"ASTAP star database folder (blank uses ASTAP default)","Folder containing the installed ASTAP star database. Leave blank to use ASTAP's default location."},
   {"Browse star database","Select the folder containing your installed ASTAP star database."},
   {"ASTAP image height in degrees (blank: automatic; useful for wide cameras)","Vertical field of view, greater than 0 and at most 180 degrees. Leave blank for automatic estimation."},
   {"Use Astrometry.net instead of ASTAP","Use your online Astrometry.net account to solve detected star coordinates. Requires internet and an API key."},
   {"Copy workers","Auto benchmarks supported worker counts on sufficiently large imports. A fixed count controls concurrent copies."},
   {"Check for and download new releases","Check the latest stable release and download a verified installer. Close the app before installing it."},
   {"Delete all archive data","Open the permanent deletion dialog for this repository. Source folders and unindexed files are retained."},
   {"Delete permanently","Permanently remove the listed archive data after dragging the confirmation slider fully right."},
   {"Destination folder","Parent folder for a new export. Export copies do not replace an existing project."},
   {"Browse destination","Choose the parent folder for the new export."},
   {"New folder name","Name of the new export folder. Use a fresh name for each project."},
   {"Separate sessions into their own folders","Keep each acquisition session in its own folder. Off combines compatible sessions into each input group."},
   {"Include matching calibration files","Export available compatible dark, flat and bias files for use in your stacking software."},
   {"Include calibrations for subs with unknown calibration state","Allow matching calibration exports for subs whose processing state is unknown. Review these files before applying calibration."},
   {"Include files marked rejected/reference","Include files normally excluded as rejected or reference frames; review them before stacking."},
   {"New telescope name","Unique saved name for this physical telescope. Renaming also updates matching indexed captures, manifests and paths in the current repository."},
   {"Export selected files","Copy only the selected archive files into a new folder with a checksum manifest."},
   {"Ready-to-stack folder","Create a project from selected lights or stacks, grouped by compatible acquisition settings."},
   {"Ready-to-stack with calibrations","Create a stacking project with available matching calibration files; review the offered options before exporting."},
   {"Preview image","Open a sampled monochrome FITS preview. Pinch or use the wheel to zoom, drag to pan, and choose Fit to recenter. Select one file."},
   {"Show file in Explorer","Locate the selected archive copy in Windows Explorer. Select one file."},
   {"Delete selected files","Remove selected archive copies after confirmation. Telescope/source originals are retained."},
   {"Edit metadata","Edit classification and labels for the selected captures. Blank fields retain their current values."},
   {"Identify target","Use recognised filename targets first; unresolved fields require a configured plate solver."},
   {"Verify repository checksums","Compare archive copies with their recorded checksums and report missing or changed files."},
   {"Index an existing repository","Discover and index FITS already in the repository without copying or moving them. Review uncertain telescope identities afterwards."},
   {"Export searchable catalogue CSV","Save indexed capture metadata as a CSV catalogue for external searching or analysis."},
   {"Show selected file location","Locate the selected archive copy in Windows Explorer."},
   {"Open exported folder","Open the completed export project in Windows Explorer."},
   {"Export files","Create verified copies of the selected captures in a new export folder."},
   {"Export folder","Create the stacking project using the selected inputs and calibration options."},
   {"Search catalogue or enter a custom target","Search the bundled catalogue, select a nearby candidate or enter the intended custom target name."},
   {"Use target","Assign the selected catalogue or custom name to the solved field."},
   {"Zoom out","Reduce preview magnification around the centre. Keyboard shortcut: minus."},
   {"Zoom in","Increase preview magnification around the centre. Keyboard shortcut: plus."},
   {"100%","Show one sampled preview pixel per screen pixel. The FITS preview may be downsampled."},
   {"Save report","Save the displayed report to a text file."},
   {"Save settings","Validate and save settings, then open the chosen repository."},
   {"Save metadata","Validate and apply the entered metadata to the selected captures or sessions."},
  };
 }
 public partial class MainUi {
  static readonly Dictionary<string,string> ControlTips=new Dictionary<string,string>{
   {"LibraryViewBox","Browse files, targets or targets with observing sessions."},
   {"ReviewLibraryButton","Review flagged captures and their full reasons in this library view."},
   {"ReviewImportsButton","Review flagged captures and screen selected files again."},
   {"RetryImportsButton","Retry failed transfers in this filtered scan; changed sources require another scan."},
   {"SkipFlaggedCheck","Exclude rejected or damaged captures from ordinary imports. Failed transfers can be retried separately."},
   {"LibraryFiltersButton","Combine library filters, including review types and mosaic membership."},
   {"ImportFiltersButton","Filter scan results. Only eligible visible files are imported."},
   {"ImportClearButton","Clear import search and filters."},
   {"IgnoreFailedCheck","Skip filenames containing failed in folder, USB and Dump imports; keep those source files."},
   {"ScreenImportsButton","Screen visible scanned captures for rejection and FITS integrity problems."},
   {"ScreenLibraryButton","Screen selected or visible archive captures for rejection and FITS integrity problems."},
   {"PreviewToggle","Show or hide the library image preview."},
   {"OpenPreviewButton","Open a supported image in the image preview."},
   {"StretchMode","Adjust the display stretch without changing image data."},
   {"PreviewZoom","Set image magnification."},
   {"CoffeeButton","Support AstroArchive on Ko-fi. Opens https://ko-fi.com/arijguest in your default browser."},
   {"ThemeButton","Switch between the light and dark themes."},
   {"DismissUpdateNotice","Dismiss the confirmation for the installed update."},
   {"NewMosaicButton","Create a mosaic collection manually."},
   {"DetectMosaicsButton","Suggest collections and panels using existing metadata."},
   {"AssignMosaicButton","Assign selected library captures to a collection and panel."},
   {"MosaicExportButton","Export this collection with separate panel folders and a portable manifest."},
   {"MosaicToolsButton","Manage collection labels, panels and metadata."},
   {"MosaicConfirmButton","Confirm suggested membership for selected captures."},
   {"MosaicRemoveButton","Remove selected captures from the collection without deleting their files."},
   {"ImportSearchBox","Search scan results. Only eligible captures in this view are imported."},
   {"ImportToolsButton","Edit scan metadata, identify targets or read the scan report."},
   {"MosaicCollectionsList","Choose a mosaic collection to inspect its panels and membership."},
   {"MosaicPanelsList","Choose a panel to inspect its assigned captures."},
   {"MosaicGrid","Review mosaic membership and select captures to confirm or remove."},
   {"SettingsButton","Choose your repository and configure plate solving, copy workers, observing site and app updates."},
   {"HelpButton","Browse or search the guide, troubleshooting and shortcuts. F1 opens help for the current tab."},
   {"AutoUploadButton","Screen a connected USB telescope for FITS files, import missing captures and retain telescope originals."},
   {"SearchBox","Search targets, dates, device names, filters, exposure, filenames and notes. Every word must match."},
   {"ClearButton","Reset library search, filters and target selection to show all captures."},
   {"LibraryColumnsButton","Choose repository headings. Check or uncheck columns, drag headings to rearrange, or restore the default layout. This table remembers its own choices."},
   {"ImportColumnsButton","Choose import headings. Drag headings to rearrange; right-click one for Move left/right. Choices are saved independently of the repository table."},
   {"TargetList","Choose a target to filter the library. All targets shows every target matching the current filters."},
   {"FramesGrid","Click a column header to sort; click again to reverse. Shift-click adds a sort column. Ctrl/Shift selects files; right-click opens file tools."},
   {"ExportButton","Export selected captures, or all visible captures when none are selected. Choose file copies or a stacking project."},
   {"RotationButton","Analyse rotation in acquisition subs to assess EQ or Alt/Az evidence. Device stacks are not used; sufficient timestamps and stars are required."},
   {"SolveButton","Identify selected or visible light/stack targets from recognised filenames first; other fields require a configured solver."},
   {"EditButton","Edit metadata for selected files, or all visible files when none are selected. Blank fields keep their existing values."},
   {"MoreButton","Verify archive checksums, index existing FITS, export a catalogue CSV or locate a selected file."},
   {"SavedTelescopeBox","Select a saved physical telescope to reuse its device name, model and source association."},
   {"SaveTelescopeButton","Save the current telescope name, model and source folder for future imports and USB recognition."},
   {"RenameTelescopeButton","Rename the selected saved telescope and matching captures, manifests and archive paths in this repository."},
   {"RebuildTelescopesButton","Recover missing saved telescope profiles from repository metadata without replacing your saved choices."},
   {"RefreshUsbButton","Check again for connected USB telescope storage and saved source associations."},
   {"SourceButton","Choose a telescope capture folder using Windows Explorer. Mounted cloud folders must expose a filesystem path."},
   {"SourceBox","Source capture folder on USB, local storage or a mounted cloud drive. Scan before importing."},
   {"TelescopeBox","Use a unique name for each physical telescope. Save it to reuse the same identity on later imports."},
   {"ModelBox","Auto detects each capture's model from metadata and folders. Choose an override only when the model is known."},
   {"CameraBox","Auto uses camera metadata. Telephoto and Wide overrides apply to all scanned captures and keep calibration channels separate."},
   {"DeleteOriginalsCheck","Remove newly imported/restored source FITS only after verification. Duplicates and session metadata remain. Cloud deletions sync too."},
   {"ImportSolveMode","Off skips automatic solving. Ambiguous only analyses uncertain light/stack targets; All analyses every eligible target. Requires a configured solver."},
   {"ImportRotationMode","Off skips rotation analysis. Ambiguous mounts only analyses uncertain sessions; All light sessions analyses eligible acquisition subs."},
   {"ScanButton","Discover supported FITS and read metadata without copying. Review classification and duplicate status before importing."},
   {"ImportGrid","Review discovered files and their status. Click headers to sort; Ctrl/Shift selects files for metadata or target actions."},
   {"ImportButton","Copy and verify new, missing or retryable captures from the scan. Verified duplicates are skipped."},
   {"MetricsGrid","Compare measured work by stage. Click headers to sort numerically; concurrent stage times can overlap."},
   {"PerformanceButton","Open import timing, throughput and error diagnostics. Save the report when troubleshooting."},
   {"CancelButton","Cancel the current operation safely. Files already imported remain in the repository."}
  };
  void InitializeTooltips(){foreach(var entry in ControlTips){var control=Window.FindName(entry.Key) as FrameworkElement;if(control!=null)UiHelp.Tip(control,entry.Value);}}
 }
}
