using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using AstroArchive.Remote;
public static class CoreTests {
 static int checks;static void Assert(bool ok,string message){if(!ok)throw new Exception(message);checks++;Console.WriteLine("PASS "+message);}
 static void Throws(Action action,string message){try{action();}catch{Assert(true,message);return;}throw new Exception("Expected failure: "+message);}
 static void Sample(string path,int seed){Directory.CreateDirectory(Path.GetDirectoryName(path));string h=("SIMPLE  =                    T".PadRight(80)+"BITPIX  =                   16".PadRight(80)+"NAXIS   =                    2".PadRight(80)+"NAXIS1  =                   16".PadRight(80)+"NAXIS2  =                   16".PadRight(80)+"END".PadRight(80)).PadRight(2880);byte[] b=new byte[5760];Encoding.ASCII.GetBytes(h).CopyTo(b,0);for(int i=2880;i<3392;i++)b[i]=(byte)(seed+i);File.WriteAllBytes(path,b);}
 static Connection Config(string source,string destination){return new Connection{Kind="Local simulator",Folder=source,Destination=destination,LimitMB=0};}
 static int Main(string[] args){try{string root=Path.GetFullPath(args[0]);Directory.CreateDirectory(root);string source=Path.Combine(root,"source"),dest=Path.Combine(root,"downloads");Directory.CreateDirectory(source);var events=new List<Notice>();string file=Path.Combine(source,"session-a","raw_001.fits");Sample(file,1);FitsCheck.Validate(file);Assert(true,"valid generated FITS accepted");Throws(()=>Paths.SafeRelative("../escape.fits"),"remote traversal rejected");Throws(()=>Paths.SafeRelative("CON.fits"),"Windows device filename rejected");Throws(()=>Paths.SafeRelative("file:stream.fits"),"Windows ADS filename rejected");Throws(()=>Config(source,Path.Combine(source,"downloads")).Validate(true),"overlapping source and destination rejected");Throws(()=>FitsCheck.Validate(Path.Combine(root,"missing.fits")),"missing FITS rejected");string truncated=Path.Combine(root,"truncated.fits");File.WriteAllBytes(truncated,File.ReadAllBytes(file).Take(2880).ToArray());Throws(()=>FitsCheck.Validate(truncated),"header-only truncated FITS rejected");
 var c=Config(source,dest);using(var remote=new LocalSource()){var d=new Downloader(c,remote,events.Add);d.Poll();Assert(!Directory.EnumerateFiles(dest,"*.fits",SearchOption.AllDirectories).Any(),"first observation is not downloaded");d.Poll();var copies=Directory.EnumerateFiles(dest,"*.fits",SearchOption.AllDirectories).ToArray();Assert(copies.Length==1&&Downloader.Hash(file)==Downloader.Hash(copies[0]),"stable exposure downloaded byte-for-byte");d.Poll();Assert(Directory.EnumerateFiles(dest,"*.fits",SearchOption.AllDirectories).Count()==1,"repeat poll produces no duplicate");d=new Downloader(c,remote,events.Add);d.Poll();Assert(Directory.EnumerateFiles(dest,"*.fits",SearchOption.AllDirectories).Count()==1,"restart retains completed download");string second=Path.Combine(source,"session-b","raw_001.fits");Sample(second,2);d.Poll();d.Poll();Assert(Directory.EnumerateFiles(dest,"*.fits",SearchOption.AllDirectories).Count()==2,"same filename in new session remains separate");d.Verify();Assert(events.Last().State=="Verified","local receipt verification passes");File.WriteAllBytes(copies[0],new byte[5760]);d.Verify();Assert(events.Any(e=>e.State=="Failed"),"corrupted local download detected by verification");
 string slow=Path.Combine(source,"session-b","raw_002.fits");Sample(slow,3);byte[] complete=File.ReadAllBytes(slow);File.WriteAllBytes(slow,complete.Take(2880).ToArray());d.Poll();d.Poll();Assert(events.Last(e=>e.File.EndsWith("raw_002.fits")).State=="Retry","stable incomplete file rejected");File.WriteAllBytes(slow,complete);d.Poll();d.Poll();Assert(events.Last(e=>e.File.EndsWith("raw_002.fits")).State=="Downloaded","incomplete exposure recovers after completed write");Sample(file,8);File.SetLastWriteTimeUtc(file,DateTime.UtcNow.AddMinutes(2));d.Poll();d.Poll();Assert(events.Any(e=>e.State=="Retry"&&e.Message.Contains("different file already exists")),"changed remote exposure never overwrites local original");}
 string fresh=Path.Combine(root,"new-only");var only=Config(source,fresh);only.IncludeExisting=false;using(var remote=new LocalSource()){var d=new Downloader(only,remote,events.Add);d.Poll();d.Poll();Assert(!Directory.EnumerateFiles(fresh,"*.fits",SearchOption.AllDirectories).Any(),"new-only mode excludes baseline");Sample(Path.Combine(source,"session-c","raw_001.fits"),9);d.Poll();d.Poll();Assert(Directory.EnumerateFiles(fresh,"*.fits",SearchOption.AllDirectories).Count()==1,"new-only mode downloads later exposure");}
 if(args.Length>1){var ftp=new Connection{Kind="DWARF FTP",Host="127.0.0.1",Port=int.Parse(args[1]),Folder="/",Destination=Path.Combine(root,"ftp-downloads"),LimitMB=0};using(var remote=new FtpSource(ftp)){Assert(remote.List("/").Any(e=>e.Directory&&e.Name=="session-a"),"FTP LIST directories parsed");var meta=remote.Stat("/session-b/raw_002.fits");Assert(meta.Size==5760,"FTP listing size and MDTM read correctly");var d=new Downloader(ftp,remote,events.Add);d.Poll();d.Poll();Assert(Directory.EnumerateFiles(ftp.Destination,"*.fits",SearchOption.AllDirectories).Count()==4,"FTP transfer downloads all complete exposures");Assert(Directory.EnumerateFiles(ftp.Destination,"*.fits",SearchOption.AllDirectories).All(p=>{FitsCheck.Validate(p);string relative=p.Substring(ftp.Destination.Length+1);relative=relative.Substring(relative.IndexOf(Path.DirectorySeparatorChar)+1);return Downloader.Hash(p)==Downloader.Hash(Path.Combine(source,relative));}),"FTP downloaded FITS structures and original hashes validated");ftp.Port++;Throws(()=>remote.List("/"),"lost FTP endpoint reports an error");ftp.Port--;Assert(remote.List("/").Count>0,"FTP source recovers when endpoint returns");}}
 Console.WriteLine(checks+" checks passed.");return 0;}catch(Exception e){Console.Error.WriteLine(e);return 1;}}
}
