// Read-only telescope transfer engine. C# 5 / .NET Framework 4.8.
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Web.Script.Serialization;
namespace AstroArchive.Remote {
 public class Connection {
  public string Kind="DWARF FTP",Host="192.168.88.1",Folder="/",Destination="",User="anonymous",Password="";
  public string SmbMode="Direct";public int SmbPort=445;
  public int Port=21,PollSeconds=5;public double LimitMB=2;public bool IncludeExisting=true;
  public void Validate(bool downloading){
   if(Kind!="DWARF FTP"&&Kind!="Seestar SMB"&&Kind!="Local simulator")throw new ArgumentException("Choose a connection type.");
   if(Kind=="DWARF FTP"){IPAddress address;if(!IPAddress.TryParse(Host,out address)||address.AddressFamily!=System.Net.Sockets.AddressFamily.InterNetwork)throw new ArgumentException("Enter the telescope IPv4 address, such as 192.168.88.1. Do not enter your PC address or an ftp:// URL.");if(Port<1||Port>65535)throw new ArgumentException("FTP port must be between 1 and 65535.");if(!Folder.StartsWith("/")||Folder.Contains("\\")||Folder.Split('/').Any(p=>p==".."||p=="."))throw new ArgumentException("Use an absolute FTP folder such as /Astronomy.");}
   else if(Kind=="Seestar SMB"){var path=SmbPath.Parse(Folder);if(path.Host!=Host)throw new ArgumentException("The capture folder and telescope address must match.");if(SmbMode!="Direct"&&SmbMode!="Windows")throw new ArgumentException("Choose Direct or Windows file access.");if(SmbPort<1||SmbPort>65535)throw new ArgumentException("Invalid SMB port.");}else if(!Path.IsPathRooted(Folder))throw new ArgumentException("Choose an absolute source folder.");
   if(PollSeconds<2||PollSeconds>120||LimitMB<0||LimitMB>1000)throw new ArgumentException("Use a poll interval of 2–120 seconds and a non-negative bandwidth limit.");
   if(downloading){if(string.IsNullOrWhiteSpace(Destination)||!Path.IsPathRooted(Destination)||Destination.StartsWith(@"\\"))throw new ArgumentException("Choose a local download folder on this PC.");string dest=Path.GetFullPath(Destination);if(dest.TrimEnd('\\','/')==Path.GetPathRoot(dest).TrimEnd('\\','/'))throw new ArgumentException("Choose a dedicated folder, rather than a drive root.");if(Kind!="DWARF FTP"&&(Paths.Within(dest,Folder)||Paths.Within(Folder,dest)))throw new ArgumentException("Source and destination must be separate folders.");}
  }
 }
 public class Entry {public string Path,Name;public bool Directory;public long Size;public DateTime Modified;public string Version {get{return Size+"|"+Modified.ToUniversalTime().Ticks;}}}
 public class Notice {public string Time=DateTime.Now.ToString("HH:mm:ss"),File,State,Message,Hash;public long Bytes;}
 public class Receipt {public string Version,Hash,LocalPath;public long Size;}
 public static class Json {
  public static string Serialize(object value){return new JavaScriptSerializer{MaxJsonLength=int.MaxValue}.Serialize(value);}
  public static T Read<T>(string path){return new JavaScriptSerializer{MaxJsonLength=int.MaxValue}.Deserialize<T>(File.ReadAllText(path));}
  public static void Save(string path,object value){Directory.CreateDirectory(Path.GetDirectoryName(path));string temp=path+".tmp";File.WriteAllText(temp,Serialize(value),new UTF8Encoding(false));if(File.Exists(path))File.Replace(temp,path,null);else File.Move(temp,path);}
 }
 public static class Paths {
  public static bool Within(string value,string root){value=Path.GetFullPath(value).TrimEnd('\\','/');root=Path.GetFullPath(root).TrimEnd('\\','/');return value.Equals(root,StringComparison.OrdinalIgnoreCase)||value.StartsWith(root+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase);}
  public static string SafeRelative(string relative){if(string.IsNullOrEmpty(relative)||relative.StartsWith("/")||relative.StartsWith("\\")||Path.IsPathRooted(relative))throw new InvalidDataException("Unsafe remote path.");foreach(string part in relative.Replace('\\','/').Split('/')){string baseName=part.Split('.')[0];if(part.Length==0||part=="."||part==".."||part.EndsWith(" ")||part.EndsWith(".")||part.Any(c=>c<32||"<>:\"|?*".Contains(c))||Regex.IsMatch(baseName,@"^(CON|PRN|AUX|NUL|COM[0-9]|LPT[0-9])$",RegexOptions.IgnoreCase))throw new InvalidDataException("Filename cannot be safely saved on Windows: "+part);}return relative.Replace('\\','/').Replace('/',Path.DirectorySeparatorChar);}
  public static string Local(string root,string relative){string path=Path.GetFullPath(Path.Combine(root,SafeRelative(relative)));if(!Within(path,root))throw new InvalidDataException("Path leaves the download folder.");CheckLinks(path,root);return path;}
  public static void CheckLinks(string path,string root){for(string p=path;p!=null;p=Path.GetDirectoryName(p)){if((Directory.Exists(p)||File.Exists(p))&&(File.GetAttributes(p)&FileAttributes.ReparsePoint)!=0)throw new IOException("Linked paths cannot be used for downloads: "+p);if(p==Path.GetPathRoot(p))break;}}
 }
 public interface ISource:IDisposable {List<Entry> List(string folder);Stream Open(string path);Entry Stat(string path);}
 public sealed class LocalSource:ISource {
  public List<Entry> List(string folder){Paths.CheckLinks(folder,folder);return new DirectoryInfo(folder).EnumerateFileSystemInfos().Where(f=>(f.Attributes&FileAttributes.ReparsePoint)==0).Select(f=>new Entry{Path=f.FullName,Name=f.Name,Directory=(f.Attributes&FileAttributes.Directory)!=0,Size=f is FileInfo?((FileInfo)f).Length:0,Modified=f.LastWriteTimeUtc}).ToList();}
  public Stream Open(string path){Paths.CheckLinks(path,path);return new FileStream(path,FileMode.Open,FileAccess.Read,FileShare.ReadWrite|FileShare.Delete);}
  public Entry Stat(string path){var f=new FileInfo(path);return new Entry{Path=path,Name=f.Name,Size=f.Length,Modified=f.LastWriteTimeUtc};}public void Dispose(){}
 }
 public sealed class FtpSource:ISource {
  readonly Connection config;public FtpSource(Connection c){config=c;}
  FtpWebRequest Request(string path,string method){string escaped=string.Join("/",path.Split('/').Select(Uri.EscapeDataString));var req=(FtpWebRequest)WebRequest.Create("ftp://"+config.Host+":"+config.Port+escaped);req.Method=method;req.Credentials=new NetworkCredential(string.IsNullOrWhiteSpace(config.User)?"anonymous":config.User,config.Password??"");req.UseBinary=true;req.UsePassive=true;req.KeepAlive=false;req.Proxy=null;req.Timeout=15000;req.ReadWriteTimeout=15000;return req;}
  public List<Entry> List(string folder){var items=new List<Entry>();using(var response=(FtpWebResponse)Request(folder.TrimEnd('/')+"/",WebRequestMethods.Ftp.ListDirectoryDetails).GetResponse())using(var reader=new StreamReader(response.GetResponseStream(),Encoding.UTF8)){string line;while((line=reader.ReadLine())!=null){var unix=Regex.Match(line,@"^([d\-l])[rwxstST\-]{9}\s+\d+\s+\S+\s+\S+\s+(\d+)\s+([A-Za-z]{3})\s+(\d{1,2})\s+(\d{2}:\d{2}|\d{4})\s+(.+)$");var dos=Regex.Match(line,@"^(\d{2}-\d{2}-\d{2,4})\s+(\d{2}:\d{2}[AP]M)\s+(<DIR>|\d+)\s+(.+)$",RegexOptions.IgnoreCase);string name;bool dir;long size;DateTime modified;
   if(unix.Success){if(unix.Groups[1].Value=="l")continue;name=unix.Groups[6].Value;dir=unix.Groups[1].Value=="d";size=long.Parse(unix.Groups[2].Value,CultureInfo.InvariantCulture);string date=unix.Groups[3].Value+" "+unix.Groups[4].Value+" "+unix.Groups[5].Value;string format=unix.Groups[5].Value.Contains(":")?"MMM d HH:mm yyyy":"MMM d yyyy";if(format.Contains("HH"))date+=" "+DateTime.UtcNow.Year;if(!DateTime.TryParseExact(date,format,CultureInfo.InvariantCulture,DateTimeStyles.AssumeUniversal|DateTimeStyles.AdjustToUniversal,out modified))throw new InvalidDataException("Unsupported FTP listing date.");}
   else if(dos.Success){name=dos.Groups[4].Value;dir=dos.Groups[3].Value.Equals("<DIR>",StringComparison.OrdinalIgnoreCase);size=dir?0:long.Parse(dos.Groups[3].Value,CultureInfo.InvariantCulture);if(!DateTime.TryParseExact(dos.Groups[1].Value+" "+dos.Groups[2].Value,new[]{"MM-dd-yy hh:mmtt","MM-dd-yyyy hh:mmtt"},CultureInfo.InvariantCulture,DateTimeStyles.AssumeUniversal|DateTimeStyles.AdjustToUniversal,out modified))throw new InvalidDataException("Unsupported FTP listing date.");}
   else {if(string.IsNullOrWhiteSpace(line)||line.StartsWith("total "))continue;throw new InvalidDataException("This telescope's FTP listing is not supported yet. Export a report for diagnosis.");}
   if(name=="."||name=="..")continue;Paths.SafeRelative(name);items.Add(new Entry{Path=folder.TrimEnd('/')+"/"+name,Name=name,Directory=dir,Size=size,Modified=modified});}}
   return items;}
  public Entry Stat(string path){int slash=path.LastIndexOf('/');string parent=slash<=0?"/":path.Substring(0,slash);var entry=List(parent).SingleOrDefault(e=>e.Path==path&&!e.Directory);if(entry==null)throw new IOException("Remote file is no longer available.");long size=entry.Size;DateTime time;using(var r=(FtpWebResponse)Request(path,WebRequestMethods.Ftp.GetDateTimestamp).GetResponse())time=DateTime.SpecifyKind(r.LastModified,DateTimeKind.Utc);return new Entry{Path=path,Name=path.Split('/').Last(),Size=size,Modified=time};}
  public Stream Open(string path){var response=(FtpWebResponse)Request(path,WebRequestMethods.Ftp.DownloadFile).GetResponse();return new OwnedStream(response.GetResponseStream(),response);}public void Dispose(){}
 }
 sealed class OwnedStream:Stream {readonly Stream inner;readonly IDisposable owner;public OwnedStream(Stream s,IDisposable o){inner=s;owner=o;}public override int Read(byte[] b,int o,int c){return inner.Read(b,o,c);}public override bool CanRead{get{return true;}}public override bool CanSeek{get{return false;}}public override bool CanWrite{get{return false;}}public override long Length{get{throw new NotSupportedException();}}public override long Position{get{throw new NotSupportedException();}set{throw new NotSupportedException();}}public override void Flush(){}public override long Seek(long o,SeekOrigin s){throw new NotSupportedException();}public override void SetLength(long v){throw new NotSupportedException();}public override void Write(byte[] b,int o,int c){throw new NotSupportedException();}protected override void Dispose(bool d){if(d){inner.Dispose();owner.Dispose();}base.Dispose(d);}}
 public static class FitsCheck {
  public static void Validate(string path){using(var f=File.OpenRead(path)){if(f.Length==0||f.Length%2880!=0)throw new InvalidDataException("FITS file is empty or truncated (2880-byte blocks required).");bool first=true;while(f.Position<f.Length){var values=new Dictionary<string,string>();bool end=false;int blocks=0;while(!end){byte[] block=new byte[2880];if(f.Read(block,0,block.Length)!=block.Length)throw new InvalidDataException("Incomplete FITS header.");if(++blocks>4096)throw new InvalidDataException("FITS header exceeds tester limit.");for(int i=0;i<2880;i+=80){string card=Encoding.ASCII.GetString(block,i,80),key=card.Substring(0,8).Trim();if(first&&blocks==1&&i==0&&!(key=="SIMPLE"&&card.Substring(10).TrimStart().StartsWith("T")))throw new InvalidDataException("Missing FITS SIMPLE header.");if(key=="END"){end=true;break;}if(card[8]=='=')values[key]=card.Substring(10).Split('/')[0].Trim();}}
   long bitpix=Number(values,"BITPIX"),naxis=Number(values,"NAXIS");if(!new long[]{8,16,32,64,-32,-64}.Contains(bitpix)||naxis<0||naxis>999)throw new InvalidDataException("Invalid FITS image dimensions.");long data;try{checked{long count=naxis==0?0:1;for(int i=1;i<=naxis;i++){long axis=Number(values,"NAXIS"+i);if(axis<0)throw new InvalidDataException("Negative FITS dimension.");count*=axis;}long p=values.ContainsKey("PCOUNT")?Number(values,"PCOUNT"):0,g=values.ContainsKey("GCOUNT")?Number(values,"GCOUNT"):1;if(p<0||g<1)throw new InvalidDataException("Invalid FITS group dimensions.");data=(count+p)*g*(Math.Abs(bitpix)/8);data=((data+2879)/2880)*2880;}}catch(OverflowException){throw new InvalidDataException("FITS dimensions overflow.");}if(data>f.Length-f.Position)throw new InvalidDataException("Incomplete FITS pixel data.");f.Position+=data;first=false;}}}
  static long Number(Dictionary<string,string> values,string key){string value;long result;if(!values.TryGetValue(key,out value)||!long.TryParse(value,NumberStyles.Integer,CultureInfo.InvariantCulture,out result))throw new InvalidDataException("Missing or invalid FITS "+key+".");return result;}
 }
 public sealed class Downloader {
  readonly Connection c;readonly ISource source;readonly Action<Notice> report;readonly Dictionary<string,Receipt> receipts;readonly Dictionary<string,string> observed=new Dictionary<string,string>(StringComparer.Ordinal);readonly HashSet<string> baseline=new HashSet<string>(StringComparer.Ordinal);readonly string state,journal,scope;bool first=true;
  public static ISource Source(Connection c){return c.Kind=="DWARF FTP"?(ISource)new FtpSource(c):c.Kind=="Seestar SMB"&&c.SmbMode=="Direct"?(ISource)new DirectSmbSource(c):new LocalSource();}
  public static string Hash(string path){using(var sha=SHA256.Create())using(var f=File.OpenRead(path))return BitConverter.ToString(sha.ComputeHash(f)).Replace("-","").ToLowerInvariant();}
  public static string HashText(string value){using(var sha=SHA256.Create())return BitConverter.ToString(sha.ComputeHash(Encoding.UTF8.GetBytes(value))).Replace("-","").ToLowerInvariant();}
  public Downloader(Connection config,ISource remote,Action<Notice> notify){c=config;c.Validate(true);source=remote;report=notify;Directory.CreateDirectory(c.Destination);Paths.CheckLinks(c.Destination,c.Destination);state=Paths.Local(c.Destination,".remote-tester");Directory.CreateDirectory(state);journal=Path.Combine(state,"journal-"+HashText(c.Kind+"|"+c.Host+"|"+c.Port+"|"+c.Folder)+".json");scope=HashText(c.Kind+"|"+c.Host+"|"+c.Port+"|"+c.Folder).Substring(0,12);receipts=File.Exists(journal)?Json.Read<Dictionary<string,Receipt>>(journal):new Dictionary<string,Receipt>();}
  void Emit(string file,string status,string message,long bytes=0,string hash=null){report(new Notice{File=file,State=status,Message=message,Bytes=bytes,Hash=hash});}
  public List<Entry> Inventory(){var all=new List<Entry>();var pending=new Queue<string>();pending.Enqueue(c.Folder);int count=0;while(pending.Count>0){string folder=pending.Dequeue();foreach(var e in source.List(folder)){if(++count>50000)throw new IOException("More than 50,000 entries. Choose a smaller capture folder.");if(e.Directory){if(!e.Name.StartsWith(".")&&e.Name!="System Volume Information"&&e.Name!="$RECYCLE.BIN")pending.Enqueue(e.Path);}else if(new[]{".fit",".fits",".fts"}.Contains(Path.GetExtension(e.Name).ToLowerInvariant())&&!e.Name.StartsWith("stack",StringComparison.OrdinalIgnoreCase))all.Add(e);}}return all;}
  string Relative(Entry e){string root=c.Folder.TrimEnd('/','\\')+(c.Kind=="DWARF FTP"?"/":c.Kind=="Seestar SMB"?"\\":Path.DirectorySeparatorChar.ToString());if(!e.Path.StartsWith(root,c.Kind=="DWARF FTP"?StringComparison.Ordinal:StringComparison.OrdinalIgnoreCase))throw new IOException("File outside selected source folder.");return Paths.SafeRelative(e.Path.Substring(root.Length));}
  public void Poll(){var entries=Inventory();foreach(var e in entries){string relative=Relative(e),version=e.Version;Receipt receipt;string old;bool stable=observed.TryGetValue(e.Path,out old)&&old==version;observed[e.Path]=version;if(first&&!c.IncludeExisting&&!receipts.ContainsKey(relative))baseline.Add(e.Path+"|"+version);if(baseline.Contains(e.Path+"|"+version)){Emit(relative,"Excluded","Already present when this run started.");continue;}string local=Paths.Local(c.Destination,scope+"/"+relative);
   if(receipts.TryGetValue(relative,out receipt)&&receipt.Version==version&&receipt.LocalPath==local&&File.Exists(local)&&new FileInfo(local).Length==receipt.Size){Emit(relative,"Downloaded","Previously downloaded; use Verify downloads to recheck local hashes.",receipt.Size,receipt.Hash);continue;}
   if(!stable||e.Size==0){Emit(relative,"Waiting","Waiting for two unchanged listings.",e.Size);continue;}
   string temp=Paths.Local(state,"partial/"+HashText(relative)+".partial");Directory.CreateDirectory(Path.GetDirectoryName(temp));try{Entry before=source.Stat(e.Path);if(before.Size!=e.Size){Emit(relative,"Waiting","Source changed before transfer.");continue;}var drive=new DriveInfo(Path.GetPathRoot(c.Destination));if(drive.AvailableFreeSpace<before.Size+16*1024*1024)throw new IOException("Not enough free disk space. Choose a larger destination.");Emit(relative,"Downloading","Copying original FITS bytes.",before.Size);var watch=System.Diagnostics.Stopwatch.StartNew();long bytes=0;using(var input=source.Open(e.Path))using(var output=new FileStream(temp,FileMode.Create,FileAccess.Write,FileShare.None)){byte[] buffer=new byte[65536];int n;while((n=input.Read(buffer,0,buffer.Length))>0){output.Write(buffer,0,n);bytes+=n;if(bytes>before.Size)throw new IOException("Source grew during transfer.");if(c.LimitMB>0){double delay=bytes/(c.LimitMB*1024*1024)*1000-watch.Elapsed.TotalMilliseconds;if(delay>0)Thread.Sleep((int)Math.Min(delay,1000));}}output.Flush(true);}Entry after=source.Stat(e.Path);if(bytes!=before.Size||before.Version!=after.Version)throw new IOException("Source changed or transfer was incomplete; will retry.");FitsCheck.Validate(temp);string hash=Hash(temp);Directory.CreateDirectory(Path.GetDirectoryName(local));Paths.CheckLinks(local,c.Destination);
   if(File.Exists(local)){if(Hash(local)!=hash)throw new IOException("A different file already exists at the destination. Choose a fresh destination; existing files are retained.");File.Delete(temp);}else File.Move(temp,local);
   receipts[relative]=new Receipt{Version=version,Hash=hash,Size=bytes,LocalPath=local};Json.Save(journal,receipts);Emit(relative,"Downloaded","FITS structure checked; local SHA-256 recorded.",bytes,hash);
   }catch(Exception ex){Emit(relative,"Retry",ex.Message);try{if(File.Exists(temp))File.Delete(temp);}catch{}}
  }first=false;var live=new HashSet<string>(entries.Select(e=>e.Path),StringComparer.Ordinal);foreach(string gone in observed.Keys.Where(k=>!live.Contains(k)).ToArray())observed.Remove(gone);}
  public void Verify(){foreach(var item in receipts){try{string safe=Paths.Local(c.Destination,scope+"/"+item.Key);if(safe!=item.Value.LocalPath)throw new IOException("Journal path does not match this destination.");FitsCheck.Validate(safe);if(Hash(safe)!=item.Value.Hash)throw new IOException("Local hash differs from the saved receipt.");Emit(item.Key,"Verified","Local file matches its download receipt.",item.Value.Size,item.Value.Hash);}catch(Exception e){Emit(item.Key,"Failed",e.Message);}}}
 }
}
