using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net.NetworkInformation;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Script.Serialization;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Markup;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
using Microsoft.Win32;
[assembly: AssemblyTitle("AstroArchive Remote tester")]
[assembly: AssemblyVersion("0.1.2.0")]
[assembly: AssemblyFileVersion("0.1.2.0")]
namespace AstroArchive.Remote {
 public class ProbeResult {public bool Success;public string Error;public int ErrorCode;public List<Entry> Entries;}
 public class FileRow {public string File{get;set;}public string State{get;set;}public string Size{get;set;}public string Message{get;set;}}
 public class FolderRow {public string Name{get;set;}public string Type{get;set;}public string Path{get;set;}public bool Directory;}
 public static class Program {
  [STAThread] public static int Main(string[] args){
   if(args.Length>=3&&args[0]=="--worker")return Worker(args[1],args[2]);
   try{return RunUi(args);}catch(Exception e){if(args.Length>0&&args[0]=="--ui-test")StartupDiagnostics.Save(e);else ShowError(e);return 1;}
  }
  // Keep WPF loading inside the catch boundary so missing framework assemblies
  // can be reported through the independent Windows Forms fallback.
  [MethodImpl(MethodImplOptions.NoInlining)] static int RunUi(string[] args){
   var app=new Application();RemoteUi ui=null;
   app.DispatcherUnhandledException+=(s,e)=>{if(args.Length>0&&args[0]=="--ui-test"){StartupDiagnostics.Save(e.Exception);Environment.Exit(1);}else{ShowError(e.Exception);e.Handled=true;}};
   ui=new RemoteUi();
   if(args.Length==2&&args[0]=="--ui-test"){
    string output=Path.GetFullPath(args[1]);Directory.CreateDirectory(output);
    ui.CheckDiscoverySelection();ui.Window.Show();ui.Window.UpdateLayout();
    var frame=new DispatcherFrame();ui.Window.Dispatcher.BeginInvoke(DispatcherPriority.ApplicationIdle,new Action(()=>frame.Continue=false));Dispatcher.PushFrame(frame);
    foreach(string theme in new[]{"Light","Dark"}){Theme.Apply(ui.Window,theme);ui.Window.UpdateLayout();var bitmap=new System.Windows.Media.Imaging.RenderTargetBitmap((int)ui.Window.ActualWidth,(int)ui.Window.ActualHeight,96,96,System.Windows.Media.PixelFormats.Pbgra32);bitmap.Render(ui.Window);var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(bitmap));using(var f=File.Create(Path.Combine(output,"Remote-"+theme+".png")))encoder.Save(f);}
    File.WriteAllText(Path.Combine(output,"ui-startup-passed.txt"),"Native WPF window loaded and rendered in Light and Dark themes.");ui.Window.Close();return 0;
   }
   app.Run(ui.Window);return 0;
  }
  [MethodImpl(MethodImplOptions.NoInlining)] static void ShowError(Exception error){
   string path=StartupDiagnostics.Save(error),details=StartupDiagnostics.Details(error);
   try{using(var dialog=new System.Windows.Forms.Form{Text="Remote tester could not continue",Width=820,Height=550,StartPosition=System.Windows.Forms.FormStartPosition.CenterScreen}){
    var message=new System.Windows.Forms.Label{Text="The error has been saved. Use Copy details to share it.\r\n"+(path??"No writable log location was available."),Dock=System.Windows.Forms.DockStyle.Top,Height=62,Padding=new System.Windows.Forms.Padding(12)};
    var text=new System.Windows.Forms.TextBox{Text=details,Multiline=true,ReadOnly=true,ScrollBars=System.Windows.Forms.ScrollBars.Both,Dock=System.Windows.Forms.DockStyle.Fill,WordWrap=false};
    var buttons=new System.Windows.Forms.FlowLayoutPanel{Dock=System.Windows.Forms.DockStyle.Bottom,Height=48,Padding=new System.Windows.Forms.Padding(8)};
    var copy=new System.Windows.Forms.Button{Text="Copy details",Width=120};copy.Click+=(s,e)=>{try{System.Windows.Forms.Clipboard.SetText(details);}catch{}};buttons.Controls.Add(copy);
    var close=new System.Windows.Forms.Button{Text="Close",Width=90};close.Click+=(s,e)=>dialog.Close();buttons.Controls.Add(close);dialog.Controls.Add(text);dialog.Controls.Add(message);dialog.Controls.Add(buttons);dialog.ShowDialog();
   }}catch{try{System.Windows.Forms.MessageBox.Show(details,"Remote tester startup error");}catch{}}
  }
  static int Worker(string configPath,string work){try{Connection c=Json.Read<Connection>(configPath);string mode=File.ReadAllText(Path.Combine(work,"mode"));c.Validate(mode!="list");using(var source=Downloader.Source(c)){if(mode=="list"){Json.Save(Path.Combine(work,"result.json"),new ProbeResult{Success=true,Entries=source.List(c.Folder)});return 0;}
   Action<Notice> report=n=>File.AppendAllText(Path.Combine(work,"events.jsonl"),Json.Serialize(n)+Environment.NewLine,new UTF8Encoding(false));var downloader=new Downloader(c,source,report);if(mode=="verify"){downloader.Verify();return 0;}
   // OS releases the lock if the worker is stopped or crashes.
   string lockFile=Paths.Local(c.Destination,".remote-tester/download.lock");using(var guard=new FileStream(lockFile,FileMode.OpenOrCreate,FileAccess.ReadWrite,FileShare.None)){int failures=0;while(true){try{downloader.Poll();failures=0;}catch(Exception e){failures++;report(new Notice{State="Connection",Message="File access unavailable; retrying: "+e.Message});}Thread.Sleep(TimeSpan.FromSeconds(failures==0?c.PollSeconds:Math.Min(30,5*failures)));}}
  }}catch(Exception e){try{Json.Save(Path.Combine(work,"result.json"),new ProbeResult{Success=false,Error=e.Message,ErrorCode=e.HResult});}catch{}return 1;}}
  public static void WriteSample(string path,int seed,bool slow){string[] cards={Card("SIMPLE","T"),Card("BITPIX","16"),Card("NAXIS","2"),Card("NAXIS1","16"),Card("NAXIS2","16"),"END".PadRight(80)};byte[] header=Encoding.ASCII.GetBytes(string.Join("",cards).PadRight(2880)),pixels=new byte[2880];for(int i=0;i<256;i++){short value=(short)(seed*100+i);pixels[i*2]=(byte)(value>>8);pixels[i*2+1]=(byte)value;}Directory.CreateDirectory(Path.GetDirectoryName(path));using(var f=new FileStream(path,FileMode.CreateNew,FileAccess.Write,FileShare.ReadWrite)){f.Write(header,0,header.Length);f.Flush();if(slow)Thread.Sleep(1200);f.Write(pixels,0,512);f.Flush();if(slow)Thread.Sleep(1200);f.Write(pixels,512,pixels.Length-512);f.Flush(true);}}
  static string Card(string key,string value){return (key.PadRight(8)+"= "+value.PadLeft(20)).PadRight(80);}
 }
 public sealed class RemoteUi {
  public readonly Window Window;readonly string state=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"AstroArchive.RemoteTester");readonly ObservableCollection<FileRow> rows=new ObservableCollection<FileRow>();readonly Dictionary<string,FileRow> indexed=new Dictionary<string,FileRow>(StringComparer.Ordinal);readonly List<Notice> notices=new List<Notice>();Process worker;string work;long eventOffset;readonly DispatcherTimer timer;bool busy,closing,simulating;CancellationTokenSource simulatorCancel,discoveryCancel;Connection active;
  T Find<T>(string n) where T:class{return Window.FindName(n) as T;}TextBox Box(string n){return Find<TextBox>(n);}Button Button(string n){return Find<Button>(n);}ComboBox Combo(string n){return Find<ComboBox>(n);}TextBlock Label(string n){return Find<TextBlock>(n);}
  public RemoteUi(){using(var s=Assembly.GetExecutingAssembly().GetManifestResourceStream("RemoteWindow.xaml"))Window=(Window)XamlReader.Load(s);Theme.Apply(Window,"System");using(var stream=Assembly.GetExecutingAssembly().GetManifestResourceStream("AstroArchive_Logo.png")){var image=new BitmapImage();image.BeginInit();image.StreamSource=stream;image.CacheOption=BitmapCacheOption.OnLoad;image.EndInit();image.Freeze();Find<Image>("BrandLogo").Source=image;Window.Icon=image;}Window.MinWidth=Math.Min(Window.MinWidth,SystemParameters.WorkArea.Width-24);Window.MinHeight=Math.Min(Window.MinHeight,SystemParameters.WorkArea.Height-24);Window.Width=Math.Min(Window.Width,SystemParameters.WorkArea.Width-24);Window.Height=Math.Min(Window.Height,SystemParameters.WorkArea.Height-24);
   Combo("ThemeBox").ItemsSource=new[]{"System","Light","Dark"};Combo("ThemeBox").SelectedIndex=0;Combo("ThemeBox").SelectionChanged+=(s,e)=>Theme.Apply(Window,Convert.ToString(Combo("ThemeBox").SelectedItem));Combo("KindBox").ItemsSource=new[]{"DWARF FTP","Seestar SMB","Local simulator"};Combo("NetworkBox").ItemsSource=new[]{"Telescope hotspot","Home network (STA)"};Combo("NetworkBox").SelectedIndex=0;Combo("LimitBox").ItemsSource=new[]{"1 MB/s","2 MB/s","5 MB/s","Unlimited"};Combo("LimitBox").SelectedIndex=1;Combo("KindBox").SelectedIndex=0;Box("HostBox").Text="192.168.88.1";Box("FolderBox").Text="/";Box("DestinationBox").Text=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"AstroArchive Remote Downloads");Find<DataGrid>("FilesGrid").ItemsSource=rows;
   try{string saved=Path.Combine(state,"settings.json");if(File.Exists(saved))Apply(Json.Read<Connection>(saved));}catch{Log("Saved test settings could not be loaded; defaults restored.");}
   Combo("KindBox").SelectionChanged+=(s,e)=>{Box("FolderBox").Text=Kind=="DWARF FTP"?"/":Kind=="Seestar SMB"?@"\\10.0.0.1\EMMC Images\MyWorks":Path.Combine(state,"Simulator");Box("HostBox").Text=Kind=="DWARF FTP"?"192.168.88.1":Kind=="Seestar SMB"?"10.0.0.1":"";Guide();Find<DataGrid>("FolderGrid").ItemsSource=null;};Combo("NetworkBox").SelectionChanged+=(s,e)=>Guide();
   Find<DataGrid>("DiscoveryGrid").SelectionChanged+=(s,e)=>Button("UseDiscoveryButton").IsEnabled=!busy&&Find<DataGrid>("DiscoveryGrid").SelectedItem is DiscoveredTelescope;
   Button("DiscoverButton").Click+=async(s,e)=>await Discover();Button("RefreshNetworksButton").Click+=(s,e)=>RefreshNetworks();Button("CancelDiscoveryButton").Click+=(s,e)=>{if(discoveryCancel!=null)discoveryCancel.Cancel();};Button("UseDiscoveryButton").Click+=(s,e)=>UseDiscovered();
   Button("SmbHelpButton").Click+=async(s,e)=>await CheckSmb();Button("SmbGuideButton").Click+=(s,e)=>Open("https://bbs.zwoastro.com/d/25334-transfer-files-using-wi-fi-ask-me-credentials");RefreshNetworks();Guide();
   Button("DefaultsButton").Click+=(s,e)=>{if(Combo("NetworkBox").SelectedIndex!=0){SetStatus("Hotspot defaults apply only to the telescope hotspot. Find the current STA address in the telescope app or router.");return;}Box("HostBox").Text=Kind=="DWARF FTP"?"192.168.88.1":"10.0.0.1";Box("FolderBox").Text=Kind=="DWARF FTP"?"/":@"\\10.0.0.1\EMMC Images\MyWorks";};Button("WifiButton").Click+=(s,e)=>Open("ms-settings:network-wifi");Button("AddressesButton").Click+=(s,e)=>Addresses();Button("GuideButton").Click+=(s,e)=>Open(Kind=="DWARF FTP"?"https://help.dwarflab.com/en/docs/How-to-View-and-Edit-DWARF-3-Files-Wirelessly-on-Your-Computer":"https://www.seestar.com/blogs/tutorial/simulated-stargazing");Button("TestButton").Click+=async(s,e)=>await Probe();Button("ParentButton").Click+=async(s,e)=>{string f=Box("FolderBox").Text.TrimEnd('/','\\');Box("FolderBox").Text=Kind=="DWARF FTP"?(f.LastIndexOf('/')<=0?"/":f.Substring(0,f.LastIndexOf('/'))):(Path.GetDirectoryName(f)??f);await Probe();};Find<DataGrid>("FolderGrid").MouseDoubleClick+=async(s,e)=>{var row=Find<DataGrid>("FolderGrid").SelectedItem as FolderRow;if(row!=null&&row.Directory&&!busy){Box("FolderBox").Text=row.Path;await Probe();}};
   Box("HostBox").LostKeyboardFocus+=(s,e)=>{if(Kind=="Seestar SMB"){string path=Box("FolderBox").Text;int end=path.IndexOf('\\',2);if(path.StartsWith(@"\\")&&end>2)Box("FolderBox").Text=@"\\"+Box("HostBox").Text.Trim()+path.Substring(end);}};Box("FolderBox").LostKeyboardFocus+=(s,e)=>{if(Kind=="Seestar SMB"){string path=Box("FolderBox").Text;int end=path.IndexOf('\\',2);if(path.StartsWith(@"\\")&&end>2)Box("HostBox").Text=path.Substring(2,end-2);}};Button("SourceBrowseButton").Click+=(s,e)=>{Pick("FolderBox");if(Kind=="Seestar SMB"){string path=Box("FolderBox").Text;int end=path.IndexOf('\\',2);if(path.StartsWith(@"\\")&&end>2)Box("HostBox").Text=path.Substring(2,end-2);}};Button("DestinationBrowseButton").Click+=(s,e)=>Pick("DestinationBox");Button("OpenButton").Click+=(s,e)=>{string path=Box("DestinationBox").Text;if(Directory.Exists(path))Open(path);else SetStatus("Start a download or choose an existing local folder first.");};Button("StartButton").Click+=(s,e)=>Start();Button("StopButton").Click+=(s,e)=>Stop();Button("VerifyButton").Click+=async(s,e)=>await Verify();Button("ReportButton").Click+=(s,e)=>Export();Button("SimulatorButton").Click+=async(s,e)=>await Simulate();
   timer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(400)};timer.Tick+=(s,e)=>Tick();timer.Start();Window.Closing+=(s,e)=>{closing=true;if(discoveryCancel!=null)discoveryCancel.Cancel();Stop();if(simulatorCancel!=null)simulatorCancel.Cancel();timer.Stop();};
  }
  string Kind{get{return Convert.ToString(Combo("KindBox").SelectedItem);}}
  void Guide(){bool ftp=Kind=="DWARF FTP",sim=Kind=="Local simulator",hotspot=Combo("NetworkBox").SelectedIndex==0;Find<Grid>("FtpCredentials").Visibility=ftp?Visibility.Visible:Visibility.Collapsed;Box("HostBox").IsEnabled=!sim;Button("SourceBrowseButton").Visibility=ftp?Visibility.Collapsed:Visibility.Visible;Button("DefaultsButton").Visibility=sim?Visibility.Collapsed:Visibility.Visible;Button("GuideButton").Visibility=sim?Visibility.Collapsed:Visibility.Visible;Combo("NetworkBox").IsEnabled=!sim;Find<StackPanel>("DiscoveryPanel").Visibility=sim?Visibility.Collapsed:Visibility.Visible;Button("DiscoverButton").IsEnabled=!busy&&Combo("DiscoveryNetworkBox").SelectedItem!=null;Button("UseDiscoveryButton").IsEnabled=!busy&&Find<DataGrid>("DiscoveryGrid").SelectedItem is DiscoveredTelescope;
   Label("SetupGuide").Text=sim?"Use a local folder as the source. The built-in simulator creates unique, slowly written FITS exposures for this tester. Choose a separate destination.":ftp?(hotspot?"Power on DWARF 3 or mini and tap Connect in the DWARFLAB app to enable its Wi-Fi. On this PC, open Wi-Fi settings and join the DWARF hotspot. Use the Wi-Fi password shown in the app; the documented DWARF 3 default is DWARF_12345678. Keep shooting in the phone app.":"In the DWARFLAB app, connect the telescope to your home Wi-Fi using STA mode. Connect this PC to the same LAN. Verify FTP access on your model and firmware; hotspot defaults do not apply on the home LAN."):(hotspot?"Power on Seestar. Connect your phone through the Seestar app, then join the Seestar hotspot from this PC. Use the Wi-Fi password shown in the app; the documented default is 12345678. Enable Save Each Frame in Seestar's capture settings.":"In Seestar settings, open Wi-Fi → STA Mode and join your home Wi-Fi. Reconnect the app, and connect this PC to the same LAN. Enable Save Each Frame so individual exposures are stored.");
   Label("IpGuide").Text=sim?"No IP address is needed. Browse to a local source folder or use Start local simulator.":hotspot?(ftp?"The documented DWARF hotspot address is 192.168.88.1. Choose Use hotspot defaults, then test FTP access. This tester defaults to anonymous FTP; use different credentials only if your device instructions specify them. DWARF II support must be checked on its firmware.":"The documented Seestar hotspot address is 10.0.0.1. Choose Use hotspot defaults. In File Explorer, open \\"+"10.0.0.1 and inspect the shares. The documented share is EMMC Images; its capture folder is MyWorks. Use the names your device actually exposes."):(ftp?"Find the DWARF address in its app's connection/STA information if displayed. Otherwise open your router's connected-device list and identify the DWARF by its device name or MAC address. Enter that IPv4 address here. Do not use this PC's IPv4 address.":"In the Seestar app, open device settings → Wi-Fi → STA Mode → the connected network's information icon. Copy its IP address. Alternatively identify Seestar in your router's connected-device list. Enter that IP below and replace the IP in the source folder too.");if(!sim)Label("IpGuide").Text="Choose Find telescopes below to discover devices on this network. Select yours and choose Use selected telescope.\n\n"+Label("IpGuide").Text;Label("FolderHint").Text=ftp?"Start with /, test the connection, then enter Astronomy and the desired DWARF_RAW session. Folder names may vary by firmware.":sim?"Select a source folder that is separate from the download folder.":@"Open \\<telescope-IP>\ in File Explorer to confirm the share, then paste its full path here. Authenticate in Windows if prompted.";
  }
  void RefreshNetworks(){try{var previous=Combo("DiscoveryNetworkBox").SelectedItem as DiscoveryNetwork;var networks=DiscoveryNetwork.Available();Combo("DiscoveryNetworkBox").ItemsSource=networks;Combo("DiscoveryNetworkBox").SelectedItem=previous==null?networks.FirstOrDefault():networks.FirstOrDefault(n=>n.Address==previous.Address)??networks.FirstOrDefault();Label("DiscoveryStatus").Text=networks.Count==0?"No active Wi-Fi or Ethernet IPv4 network. Connect this PC, then Refresh networks.":"Choose the network shared with the telescope, then Find telescopes (about 8 seconds).";Button("DiscoverButton").IsEnabled=!busy&&networks.Count>0;}catch(Exception e){Label("DiscoveryStatus").Text="Could not read network connections: "+e.Message;Button("DiscoverButton").IsEnabled=false;}}
  async Task Discover(){if(busy)return;var network=Combo("DiscoveryNetworkBox").SelectedItem as DiscoveryNetwork;if(network==null){RefreshNetworks();return;}Find<DataGrid>("DiscoveryGrid").ItemsSource=null;var cancel=new CancellationTokenSource();discoveryCancel=cancel;SetBusy(true,false);Button("CancelDiscoveryButton").Visibility=Visibility.Visible;Label("DiscoveryStatus").Text="Searching "+network.Display+"…";SetStatus("Discovering DWARF and Seestar devices. Capture continues in the telescope app.");try{var result=await Task.Run(()=>TelescopeDiscovery.Find(network,cancel.Token));if(closing)return;Find<DataGrid>("DiscoveryGrid").ItemsSource=result.Devices.OrderBy(d=>d.Name).ThenBy(d=>d.Host).ToList();foreach(string warning in result.Warnings)Log(warning);string message=result.Devices.Count==0?"No telescope replies. Confirm the same subnet, the telescope is awake and guest/client isolation is off. Check Windows firewall permission for this app on your trusted private network, or enter the IP manually.":result.Devices.Count+" telescope(s) found. Select yours, then Use selected telescope and Test connection / list.";if(result.Warnings.Count>0)message+=" "+string.Join(" ",result.Warnings);Label("DiscoveryStatus").Text=message;SetStatus(result.Devices.Count==0?"Discovery finished without a telescope reply. See the network guidance above.":"Discovery complete. Select a telescope to fill in its address.");Log("Discovery on "+network.Display+": "+result.Devices.Count+" device(s). File access has not yet been tested.");}catch(OperationCanceledException){if(!closing){Label("DiscoveryStatus").Text="Search cancelled. You can search again or enter the IP manually.";SetStatus("Discovery cancelled.");}}catch(Exception e){if(!closing){Label("DiscoveryStatus").Text="Discovery failed: "+e.Message;Log("Discovery: "+e.Message);SetStatus("Discovery failed. You can still enter the telescope IP manually.");}}finally{discoveryCancel=null;cancel.Dispose();if(!closing){Button("CancelDiscoveryButton").Visibility=Visibility.Collapsed;SetBusy(false,false);}}}
  void UseDiscovered(){if(busy)return;var device=Find<DataGrid>("DiscoveryGrid").SelectedItem as DiscoveredTelescope;if(device==null)return;string oldKind=Kind,folder=Box("FolderBox").Text;Combo("KindBox").SelectedItem=device.Kind;Box("HostBox").Text=device.Host;if(device.Kind=="Seestar SMB"){int end=folder.IndexOf('\\',2);Box("FolderBox").Text=oldKind==device.Kind&&folder.StartsWith(@"\\")&&end>2?@"\\"+device.Host+folder.Substring(end):@"\\"+device.Host+@"\EMMC Images\MyWorks";}else Box("FolderBox").Text=oldKind==device.Kind&&folder.StartsWith("/")?folder:"/";Find<DataGrid>("FolderGrid").ItemsSource=null;SetStatus("Selected "+device.Name+" at "+device.Host+". Test connection / list to check file access; discovery does not verify SMB credentials or FTP availability.");Log("Selected discovered "+device.Name+" · "+device.Host);}
  public void CheckDiscoverySelection(){var original=Read();var grid=Find<DataGrid>("DiscoveryGrid");Combo("KindBox").SelectedItem="Seestar SMB";Box("FolderBox").Text=@"\\10.0.0.1\EMMC Images\MyWorks\session";var device=new DiscoveredTelescope{Kind="Seestar SMB",Name="Seestar test",Host="192.168.1.42"};grid.ItemsSource=new[]{device};grid.SelectedItem=device;UseDiscovered();if(Box("HostBox").Text!=device.Host||Box("FolderBox").Text!=@"\\192.168.1.42\EMMC Images\MyWorks\session")throw new InvalidOperationException("Discovery did not preserve the selected SMB folder.");device=new DiscoveredTelescope{Kind="DWARF FTP",Name="DWARF test",Host="192.168.1.43"};grid.ItemsSource=new[]{device};grid.SelectedItem=device;UseDiscovered();if(Kind!=device.Kind||Box("HostBox").Text!=device.Host||Box("FolderBox").Text!="/")throw new InvalidOperationException("Discovery did not switch telescope connection type.");grid.ItemsSource=null;Apply(original);Guide();Box("ActivityBox").Clear();SetStatus("Choose a connection type, follow the setup guide, then test the connection.");}
  async Task CheckSmb(){Button("SmbHelpButton").IsEnabled=false;Label("SmbStatus").Visibility=Visibility.Visible;Label("SmbStatus").Text="Reading Windows SMB client settings…";try{string text=await Task.Run(()=>{using(var process=Process.Start(new ProcessStartInfo{FileName=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System),@"WindowsPowerShell\v1.0\powershell.exe"),Arguments="-NoProfile -NonInteractive -Command \"Get-SmbClientConfiguration -ErrorAction Stop | Select-Object EnableInsecureGuestLogons,RequireSecuritySignature | Format-List\"",UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true,RedirectStandardError=true})){if(!process.WaitForExit(10000)){process.Kill();throw new IOException("Reading SMB settings timed out.");}string output=process.StandardOutput.ReadToEnd(),error=process.StandardError.ReadToEnd();if(process.ExitCode!=0)throw new IOException(error.Trim());return output.Trim();}});if(closing)return;Label("SmbStatus").Text=text+"\n\nThese are read-only results. EnableInsecureGuestLogons=False or RequireSecuritySignature=True can prevent access to a guest-only Seestar share. Clear only stale credentials for this telescope in Windows Credential Manager, then retry in File Explorer. If it still fails, compare these settings with Seestar login help. Discovery cannot bypass SMB authentication or signing.";Log("SMB client settings (read only): "+text);}catch(Exception e){if(!closing)Label("SmbStatus").Text="Could not read SMB settings: "+e.Message+"\nIn PowerShell run: Get-SmbClientConfiguration | Select-Object EnableInsecureGuestLogons, RequireSecuritySignature";}finally{if(!closing)Button("SmbHelpButton").IsEnabled=true;}}
  void Addresses(){var lines=new List<string>{"These are this PC's addresses. Use Find telescopes to discover the telescope."};foreach(var adapter in NetworkInterface.GetAllNetworkInterfaces().Where(a=>a.OperationalStatus==OperationalStatus.Up&&a.NetworkInterfaceType!=NetworkInterfaceType.Loopback)){var properties=adapter.GetIPProperties();foreach(var address in properties.UnicastAddresses.Where(a=>a.Address.AddressFamily==System.Net.Sockets.AddressFamily.InterNetwork))lines.Add(adapter.Name+": PC "+address.Address+" · mask "+address.IPv4Mask);foreach(var gateway in properties.GatewayAddresses)lines.Add("Gateway / router: "+gateway.Address);}lines.Add("On a home LAN, the gateway is usually your router. Its connected-device list can show the telescope IP. On a telescope hotspot, the gateway may be the telescope; confirm by testing file access.");Label("AddressesText").Text=string.Join(Environment.NewLine,lines);Label("AddressesText").Visibility=Visibility.Visible;}
  Connection Read(){int port,poll;if(!int.TryParse(Box("PortBox").Text,out port)||!int.TryParse(Box("PollBox").Text,out poll))throw new ArgumentException("Enter whole numbers for FTP port and poll interval.");string limit=Convert.ToString(Combo("LimitBox").SelectedItem);return new Connection{Kind=Kind,Host=Box("HostBox").Text.Trim(),Folder=Box("FolderBox").Text.Trim(),Destination=Box("DestinationBox").Text.Trim(),User=Box("UserBox").Text.Trim(),Password=Find<PasswordBox>("PasswordBox").Password,Port=port,PollSeconds=poll,LimitMB=limit=="Unlimited"?0:double.Parse(limit.Split(' ')[0],CultureInfo.InvariantCulture),IncludeExisting=Find<CheckBox>("ExistingCheck").IsChecked==true};}
  void Apply(Connection c){Combo("KindBox").SelectedItem=c.Kind;Box("HostBox").Text=c.Host;Box("FolderBox").Text=c.Folder;Box("DestinationBox").Text=c.Destination;Box("UserBox").Text=c.User;Box("PortBox").Text=c.Port.ToString();Box("PollBox").Text=c.PollSeconds.ToString();Combo("LimitBox").SelectedItem=c.LimitMB==0?"Unlimited":c.LimitMB.ToString(CultureInfo.InvariantCulture)+" MB/s";Find<CheckBox>("ExistingCheck").IsChecked=c.IncludeExisting;}
  void Save(Connection c){var safe=new Connection{Kind=c.Kind,Host=c.Host,Folder=c.Folder,Destination=c.Destination,User=c.User,Port=c.Port,PollSeconds=c.PollSeconds,LimitMB=c.LimitMB,IncludeExisting=c.IncludeExisting};Json.Save(Path.Combine(state,"settings.json"),safe);}
  Process Launch(Connection c,string mode,out string path){path=Path.Combine(state,"runs",Guid.NewGuid().ToString("N"));Directory.CreateDirectory(path);string config=Path.Combine(path,"connection.json");Json.Save(config,c);File.WriteAllText(Path.Combine(path,"mode"),mode);return Process.Start(new ProcessStartInfo{FileName=Assembly.GetExecutingAssembly().Location,Arguments="--worker \""+config+"\" \""+path+"\"",UseShellExecute=false,CreateNoWindow=true});}
  async Task Probe(){if(busy)return;Process process=null;string path=null;SetBusy(true,false);try{var c=Read();c.Validate(false);SetStatus("Testing file access and listing the selected folder…");process=Launch(c,"list",out path);await Task.Run(()=>{if(!process.WaitForExit(30000)){process.Kill();process.WaitForExit();throw new IOException("File access timed out. Check the network, telescope IP and selected folder.");}});var result=Json.Read<ProbeResult>(Path.Combine(path,"result.json"));if(!result.Success)throw new IOException(result.Error+" (0x"+result.ErrorCode.ToString("X8")+")");Find<DataGrid>("FolderGrid").ItemsSource=result.Entries.OrderByDescending(e=>e.Directory).ThenBy(e=>e.Name).Select(e=>new FolderRow{Name=e.Name,Path=e.Path,Directory=e.Directory,Type=e.Directory?"Folder":"File"}).ToList();Save(c);SetStatus("Connected. "+result.Entries.Count+" entries in the selected folder. Choose the capture session, then Start watching.");Log("File access succeeded: "+c.Folder);}catch(Exception e){SetStatus(e.Message);Log("Connection test: "+e.Message);if(!closing&&Kind=="Seestar SMB"){Label("SmbStatus").Visibility=Visibility.Visible;Label("SmbStatus").Text="Windows SMB returned: "+e.Message+"\nOpen the same source folder in File Explorer to test Windows access. If credentials are rejected, choose Check SMB access. Discovery finds the IP but cannot fix guest-access or signing restrictions.";}}finally{if(process!=null)process.Dispose();DeleteConfig(path);if(!closing)SetBusy(false,false);}}
  void Start(){if(busy)return;try{var c=Read();c.Validate(true);Save(c);rows.Clear();indexed.Clear();eventOffset=0;active=c;worker=Launch(c,"watch",out work);SetBusy(true,true);SetStatus("Watching selected folder. New files wait for stable listings before downloading.");Log("Watching "+c.Kind+" "+c.Folder+" → "+c.Destination);}catch(Exception e){SetStatus(e.Message);}}
  void Stop(){if(worker!=null){try{if(!worker.HasExited){worker.Kill();worker.WaitForExit(2000);}ReadEvents();}catch(Exception e){Log("Stop: "+e.Message);}finally{worker.Dispose();worker=null;DeleteConfig(work);SetBusy(false,false);}SetStatus("Stopped. Completed downloads are retained. Start watching to catch up.");}}
  async Task Verify(){if(busy)return;Process process=null;string path=null;SetBusy(true,false);try{var c=Read();c.Validate(true);process=Launch(c,"verify",out path);SetStatus("Checking downloaded FITS files against their saved local hashes…");await Task.Run(()=>{if(!process.WaitForExit(120000)){process.Kill();process.WaitForExit();throw new IOException("Verification timed out. Choose a smaller test destination.");}});if(File.Exists(Path.Combine(path,"result.json"))){var result=Json.Read<ProbeResult>(Path.Combine(path,"result.json"));if(!result.Success)throw new IOException(result.Error);}if(File.Exists(Path.Combine(path,"events.jsonl")))foreach(string line in File.ReadAllLines(Path.Combine(path,"events.jsonl")))Consume(new JavaScriptSerializer().Deserialize<Notice>(line));SetStatus("Verification finished. Review Verified / Failed rows.");}catch(Exception e){SetStatus(e.Message);}finally{if(process!=null)process.Dispose();DeleteConfig(path);if(!closing)SetBusy(false,false);}}
  void Tick(){if(worker==null)return;ReadEvents();if(worker.HasExited){try{string result=Path.Combine(work,"result.json");SetStatus(File.Exists(result)?Json.Read<ProbeResult>(result).Error:"Download worker stopped.");}catch{SetStatus("Download worker stopped; export the report for diagnosis.");}worker.Dispose();worker=null;DeleteConfig(work);SetBusy(false,false);}}
  void ReadEvents(){try{string path=Path.Combine(work,"events.jsonl");if(!File.Exists(path))return;using(var f=new FileStream(path,FileMode.Open,FileAccess.Read,FileShare.ReadWrite)){f.Position=eventOffset;using(var reader=new StreamReader(f,Encoding.UTF8)){string tail=reader.ReadToEnd();int last=tail.LastIndexOf('\n');if(last<0)return;string complete=tail.Substring(0,last+1);eventOffset+=Encoding.UTF8.GetByteCount(complete);foreach(string line in complete.Split(new[]{'\n'},StringSplitOptions.RemoveEmptyEntries))Consume(new JavaScriptSerializer().Deserialize<Notice>(line));}}}catch(IOException){}catch(Exception e){Log("Report read: "+e.Message);}}
  void Consume(Notice n){if(notices.Count>=10000)notices.RemoveAt(0);notices.Add(n);if(!string.IsNullOrEmpty(n.File)){FileRow row;if(!indexed.TryGetValue(n.File,out row)){row=new FileRow{File=n.File};indexed[n.File]=row;rows.Add(row);}bool changed=row.State!=n.State||row.Message!=n.Message;row.State=n.State;row.Size=n.Bytes>0?(n.Bytes/1048576.0).ToString("0.00")+" MB":"";row.Message=n.Message;if(changed)Log(n.File+": "+n.State+" · "+n.Message);Find<DataGrid>("FilesGrid").Items.Refresh();}else{SetStatus(n.Message);Log(n.Message);}Label("SummaryText").Text=rows.Count(r=>r.State=="Downloaded"||r.State=="Verified")+" downloaded · "+rows.Count(r=>r.State=="Waiting")+" waiting · "+rows.Count(r=>r.State=="Retry"||r.State=="Failed")+" need attention";}
  void SetBusy(bool value,bool watching){busy=value;foreach(string n in new[]{"KindBox","NetworkBox","HostBox","PortBox","UserBox","PasswordBox","FolderBox","DestinationBox","ExistingCheck","PollBox","LimitBox","TestButton","ParentButton","SourceBrowseButton","DestinationBrowseButton","DefaultsButton","StartButton","VerifyButton","SimulatorButton","DiscoverButton","RefreshNetworksButton","DiscoveryNetworkBox","DiscoveryGrid","UseDiscoveryButton"})Find<Control>(n).IsEnabled=!value;Button("StopButton").IsEnabled=watching;if(!value){Guide();Button("SimulatorButton").IsEnabled=!simulating;}}
  void SetStatus(string text){Label("StatusText").Text=text;}
  void Log(string text){var box=Box("ActivityBox");if(box.Text.Length>50000)box.Text=box.Text.Substring(box.Text.Length-25000);box.AppendText(DateTime.Now.ToString("HH:mm:ss")+"  "+text+Environment.NewLine);box.ScrollToEnd();}
  static void DeleteConfig(string path){try{if(path!=null)File.Delete(Path.Combine(path,"connection.json"));}catch{}}
  void Pick(string box){using(var dialog=new System.Windows.Forms.FolderBrowserDialog{Description=box=="DestinationBox"?"Choose a dedicated local download folder":"Choose the telescope network folder or local simulator source",SelectedPath=Box(box).Text,ShowNewFolderButton=box=="DestinationBox"})if(dialog.ShowDialog()==System.Windows.Forms.DialogResult.OK)Box(box).Text=dialog.SelectedPath;}
  void Open(string path){try{Process.Start(new ProcessStartInfo(path){UseShellExecute=true});}catch(Exception e){SetStatus(e.Message);}}
  void Export(){var picker=new SaveFileDialog{Title="Save Remote tester report",FileName="AstroArchive-Remote-Test-"+DateTime.Now.ToString("yyyyMMdd-HHmmss")+".json",Filter="JSON report|*.json"};if(picker.ShowDialog(Window)!=true)return;try{var c=active??Read();File.WriteAllText(picker.FileName,Json.Serialize(new{Application="AstroArchive Remote tester 0.1.2",Generated=DateTimeOffset.Now.ToString("o"),Connection=new{c.Kind,c.Host,c.Port,c.Folder,c.Destination,c.PollSeconds,c.LimitMB,c.IncludeExisting},Events=notices,Activity=Box("ActivityBox").Text,Limitations="FITS structure and local hashes only; no independent source checksums. Individual FITS exposures; no session sidecars."}),new UTF8Encoding(false));SetStatus("Report saved. It includes network addresses and file paths, but no passwords.");}catch(Exception e){SetStatus(e.Message);}}
  async Task Simulate(){if(busy||simulating)return;simulating=true;simulatorCancel=new CancellationTokenSource();var cancel=simulatorCancel;string folder=Path.Combine(state,"Simulator",DateTime.Now.ToString("yyyyMMdd-HHmmss")+"-"+Guid.NewGuid().ToString("N").Substring(0,6));Combo("KindBox").SelectedItem="Local simulator";Box("FolderBox").Text=folder;Directory.CreateDirectory(folder);Log("Simulator source: "+folder);SetStatus("Simulator running. Click Start watching to download its arriving exposures.");Button("SimulatorButton").IsEnabled=false;try{await Task.Run(()=>{for(int i=1;i<=12;i++){cancel.Token.ThrowIfCancellationRequested();Program.WriteSample(Path.Combine(folder,"DWARF_RAW_TEST","raw_"+i.ToString("0000")+".fits"),i,true);if(cancel.Token.WaitHandle.WaitOne(1500))cancel.Token.ThrowIfCancellationRequested();}});if(!closing)Log("Simulator finished: 12 unique FITS exposures.");}catch(OperationCanceledException){}catch(Exception e){if(!closing)Log("Simulator: "+e.Message);}finally{simulating=false;cancel.Dispose();simulatorCancel=null;if(!closing)Button("SimulatorButton").IsEnabled=!busy;}}
 }
}
