param(
    [string]$AppExecutable = (Join-Path $PSScriptRoot '..\Application_Source\dist\AstroArchive.exe'),
    [string]$OutputDirectory = (Join-Path $PSScriptRoot 'dist'),
    [switch]$SkipTests,
    [switch]$PreparePayloadOnly,
    [switch]$UsePreparedPayload
)
$ErrorActionPreference = 'Stop'
if ($PreparePayloadOnly -and $UsePreparedPayload) { throw 'Choose either preparation or packaging.' }
$compiler = Join-Path $env:WINDIR 'Microsoft.NET\Framework64\v4.0.30319\csc.exe'
if (-not (Test-Path $compiler)) { throw 'Install .NET Framework 4.8 on 64-bit Windows.' }
$release = Get-Content (Join-Path $PSScriptRoot 'release.json') -Raw | ConvertFrom-Json
if ($release.application_version -notmatch '^\d+\.\d+\.\d+$') { throw 'Use a three-part application version in release.json.' }
$appVersion = [version]$release.application_version
$revision = [int]$release.installer_revision
if ($revision -lt 1 -or $revision -gt 65534) { throw 'Installer revision must be between 1 and 65534.' }
$packageVersion = "$($release.application_version).$revision"
if (-not (Test-Path $AppExecutable)) {
    $defaultApp = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\Application_Source\dist\AstroArchive.exe'))
    if ([IO.Path]::GetFullPath($AppExecutable) -ne $defaultApp) { throw "Application executable not found: $AppExecutable" }
    & (Join-Path $PSScriptRoot '..\Application_Source\build.ps1')
}
$AppExecutable = (Resolve-Path $AppExecutable).Path
$inputVersion = [Diagnostics.FileVersionInfo]::GetVersionInfo($AppExecutable)
if ($inputVersion.FileMajorPart -ne $appVersion.Major -or
    $inputVersion.FileMinorPart -ne $appVersion.Minor -or
    $inputVersion.FileBuildPart -ne $appVersion.Build -or
    $inputVersion.FilePrivatePart -ne $revision) {
    throw 'The app file version does not match release.json. Build the app first.'
}
if (-not $SkipTests) { & (Join-Path $PSScriptRoot 'test.ps1') -Compiler $compiler }
$OutputDirectory = [IO.Path]::GetFullPath($OutputDirectory)
[IO.Directory]::CreateDirectory($OutputDirectory) | Out-Null
$build = Join-Path $PSScriptRoot '.build'
[IO.Directory]::CreateDirectory($build) | Out-Null
$payload = Join-Path $build 'payload'
[IO.Directory]::CreateDirectory($payload) | Out-Null
if (-not $UsePreparedPayload) {
    Copy-Item (Join-Path $PSScriptRoot 'Payload\*') $payload -Force
    Copy-Item (Join-Path $PSScriptRoot '..\Application_Source\Quick_Start.txt') (Join-Path $payload 'Quick_Start.txt') -Force
    Copy-Item (Join-Path $PSScriptRoot '..\Application_Source\Validation.txt') (Join-Path $payload 'Validation.txt') -Force
    Copy-Item (Join-Path $PSScriptRoot '..\Application_Source\City_Catalogue_Notice.md') (Join-Path $payload 'City_Catalogue_Notice.md') -Force
    # Keep licence material in the existing managed notice for older launchers.
    $noticePath = Join-Path $payload 'Catalogue_Notice.md'
    $skyNoticePath = Join-Path $PSScriptRoot '..\Application_Source\Sky_Catalogue_Notice.md'
    [IO.File]::WriteAllText($noticePath, ([IO.File]::ReadAllText($noticePath) + "`r`n`r`n" + [IO.File]::ReadAllText($skyNoticePath)), (New-Object Text.UTF8Encoding($false)))
    Copy-Item $AppExecutable (Join-Path $payload 'AstroArchive.exe') -Force
}
$generatedVersion = @"
// Generated by build.ps1 from release.json.
using System.Reflection;
using System.Runtime.Versioning;
#if LAUNCHER
[assembly: AssemblyTitle("AstroArchive Launcher")]
[assembly: AssemblyProduct("AstroArchive")]
#else
[assembly: AssemblyTitle("AstroArchive Setup")]
[assembly: AssemblyProduct("AstroArchive Installer")]
#endif
[assembly: AssemblyVersion("$packageVersion")]
[assembly: AssemblyFileVersion("$packageVersion")]
[assembly: TargetFramework(".NETFramework,Version=v4.8")]
namespace AstroArchive.Installation {
 internal static class ReleaseVersion {
  public const string Application="$($release.application_version)";
  public const string Package="$packageVersion";
  public const int Revision=$revision;
 }
}
"@
Set-Content (Join-Path $build 'GeneratedVersion.cs') $generatedVersion -Encoding UTF8
[xml]$manifest = Get-Content (Join-Path $PSScriptRoot 'app.manifest') -Raw
$manifest.assembly.assemblyIdentity.version = $packageVersion
$manifest.Save((Join-Path $build 'app.manifest'))
$shared = @('/nologo', '/langversion:5', '/target:winexe', '/platform:x64', '/optimize+',
    '/r:System.Core.dll', '/r:System.Web.Extensions.dll', '/r:System.Windows.Forms.dll', '/r:System.Drawing.dll',
    "/win32icon:$PSScriptRoot\Assets\AstroArchive.ico", "/win32manifest:$build\app.manifest")
if (-not $UsePreparedPayload) {
    $launcherArgs = $shared + @('/define:LAUNCHER', "/out:$payload\Start.exe",
        "$PSScriptRoot\InstallCore.cs", "$PSScriptRoot\Launcher.cs", "$PSScriptRoot\Updates.cs",
        "$PSScriptRoot\WindowsIntegration.cs", "$build\GeneratedVersion.cs")
    & $compiler @launcherArgs
    if ($LASTEXITCODE -ne 0) { throw 'Launcher compilation failed.' }
}
foreach ($name in @('AstroArchive.exe', 'Start.exe')) {
    $path = Join-Path $payload $name
    if (-not (Test-Path $path)) { throw "Prepared payload is missing $name. Run preparation first." }
    if ([version][Diagnostics.FileVersionInfo]::GetVersionInfo($path).FileVersion -ne [version]$packageVersion) {
        throw "Prepared $name does not match release.json. Run preparation again."
    }
}
if ($PreparePayloadOnly) { Write-Output $payload; return }
# Packaging preserves any signatures applied to the prepared executables.
# Hash and embed them only after signing.
Add-Type -AssemblyName System.IO.Compression
$names = @('AstroArchive.exe', 'Start.exe', 'Quick_Start.txt', 'Validation.txt',
    'Catalogue_Notice.md', 'City_Catalogue_Notice.md', 'OpenNGC_README.md', 'Release_Notes.txt')
$hashes = [ordered]@{}
$zipPath = Join-Path $build 'payload.zip'
if (Test-Path $zipPath) { Remove-Item $zipPath }
$stream = [IO.File]::Open($zipPath, [IO.FileMode]::CreateNew)
$zip = New-Object IO.Compression.ZipArchive($stream, [IO.Compression.ZipArchiveMode]::Create, $false)
try {
    foreach ($name in $names) {
        $path = Join-Path $payload $name
        $hashes[$name] = (Get-FileHash $path -Algorithm SHA256).Hash.ToLowerInvariant()
        $entry = $zip.CreateEntry($name, [IO.Compression.CompressionLevel]::Optimal)
        $entry.LastWriteTime = [DateTimeOffset]::new(2026, 1, 1, 0, 0, 0, [TimeSpan]::Zero)
        $input = [IO.File]::OpenRead($path)
        $output = $entry.Open()
        try { $input.CopyTo($output) } finally { $input.Dispose(); $output.Dispose() }
    }
} finally { $zip.Dispose(); $stream.Dispose() }
$payloadManifest = [ordered]@{ Version=$release.application_version; PackageVersion=$packageVersion; Revision=$revision; Hashes=$hashes }
$json = $payloadManifest | ConvertTo-Json -Depth 4
[IO.File]::WriteAllText((Join-Path $build 'payload.json'), $json, (New-Object Text.UTF8Encoding($false)))
$setupPath = Join-Path $OutputDirectory "AstroArchive$packageVersion.exe"
$setupArgs = $shared + @("/out:$setupPath", '/r:System.Drawing.dll', '/r:System.IO.Compression.dll',
    "/resource:$build\payload.zip,payload.zip", "/resource:$build\payload.json,payload.json",
    "/resource:$PSScriptRoot\Assets\AstroArchive_Logo.png,logo.png",
    "$PSScriptRoot\InstallCore.cs", "$PSScriptRoot\WindowsIntegration.cs", "$PSScriptRoot\NativeFolderPicker.cs",
    "$PSScriptRoot\Setup.cs", "$PSScriptRoot\Updates.cs", "$build\GeneratedVersion.cs")
& $compiler @setupArgs
if ($LASTEXITCODE -ne 0) { throw 'Installer compilation failed.' }
$actual = [Diagnostics.FileVersionInfo]::GetVersionInfo($setupPath).FileVersion
if ([version]$actual -ne [version]$packageVersion) { throw 'Installer file version verification failed.' }
$checksum = (Get-FileHash $setupPath -Algorithm SHA256).Hash.ToLowerInvariant()
Set-Content "$setupPath.sha256" "$checksum  $([IO.Path]::GetFileName($setupPath))" -Encoding ASCII
Write-Output $setupPath
