using System;
using System.IO;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using AstroArchive.Installation;
static class ReleaseMonitorTests {
 static void Check(bool condition,string message){if(!condition)throw new Exception(message);}
 static UpdateManifest Release(){return new UpdateManifest{schema=1,application_version="1.2.0",package_version="1.2.0.2",url=UpdateClient.Repository+"/releases/download/v1.2.0.2/AstroArchive-1.2.0-Windows-x64-Offline-Setup.exe",size=1,sha256=InstallCore.Hash(new byte[]{1})};}
 static InstallRecord Installed(){return new InstallRecord{Version="1.2.0",PackageVersion="1.2.0.1"};}
 public static void Run(Action<string,Action> test,string scratch){
  test("Release checks coalesce and reuse validated cache across launcher/app",()=>{DateTime now=new DateTime(2026,10,9,12,0,0,DateTimeKind.Utc);string path=Path.Combine(scratch,"coalesced.json");int calls=0;using(var started=new ManualResetEventSlim())using(var finish=new ManualResetEventSlim()){
   var monitor=new ReleaseMonitor(scratch,Installed(),()=>{Interlocked.Increment(ref calls);started.Set();if(!finish.Wait(5000))throw new Exception("Test timed out");return Release();},()=>now,path);Check(monitor.Due,"First check not due");var first=monitor.CheckAsync();Check(started.Wait(5000),"Check not started");var second=monitor.CheckAsync();Check(first==second,"Checks overlapped");finish.Set();first.GetAwaiter().GetResult();Check(calls==1&&!monitor.Due,"Success not throttled");Check(monitor.MarkNotified()&&!monitor.MarkNotified(),"Repeated release notice");
   var reopened=new ReleaseMonitor(scratch,Installed(),()=>{throw new Exception("Unexpected network access");},()=>now,path);Check(!reopened.Due&&reopened.State.Available.package_version=="1.2.0.2"&&!reopened.MarkNotified(),"Launcher/app cache lost notice state");now=now.AddHours(7);Check(reopened.Due,"Wake after overdue check not due");
  }});
  test("Offline backoff retains availability and recovers after a manual check",()=>{DateTime now=new DateTime(2026,10,9,12,0,0,DateTimeKind.Utc);bool fail=false;var monitor=new ReleaseMonitor(scratch,Installed(),()=>{if(fail)throw new IOException("Offline");return Release();},()=>now,Path.Combine(scratch,"backoff.json"));monitor.CheckAsync().GetAwaiter().GetResult();fail=true;foreach(int minutes in new[]{15,60,360}){try{monitor.CheckAsync().GetAwaiter().GetResult();throw new Exception("Expected failure");}catch(IOException){}Check(monitor.State.Available!=null&&DateTime.Parse(monitor.State.NextCheckUtc).ToUniversalTime()==now.AddMinutes(minutes),"Retry or known release lost");}fail=false;monitor.CheckAsync().GetAwaiter().GetResult();Check(monitor.State.Failures==0&&monitor.State.Error==null,"Recovery retained failure");monitor.SetAutomatic(false);now=now.AddDays(1);Check(!monitor.Due,"Disabled monitor polled");monitor.CheckAsync().GetAwaiter().GetResult();Check(monitor.State.AutomaticDisabled,"Manual check enabled automatic checks");});
  test("Changed installed package and corrupt caches cannot offer stale or untrusted releases",()=>{DateTime now=DateTime.UtcNow;string path=Path.Combine(scratch,"invalid-cache.json");File.WriteAllText(path,"broken");var monitor=new ReleaseMonitor(scratch,Installed(),()=>Release(),()=>now,path);Check(monitor.Due&&monitor.State.Available==null,"Corrupt cache accepted");monitor.CheckAsync().GetAwaiter().GetResult();monitor.SetAutomatic(false);var installed=Installed();installed.PackageVersion="1.2.0.3";var newer=new ReleaseMonitor(scratch,installed,()=>Release(),()=>now,path);Check(newer.State.Available==null&&newer.State.AutomaticDisabled,"New installed package retained old offer or changed preference");newer.CheckAsync().GetAwaiter().GetResult();Check(newer.State.Available==null,"Older package offered");var untrusted=Release();untrusted.url="https://example.com/update.exe";try{new ReleaseMonitor(scratch,Installed(),()=>untrusted,()=>now,Path.Combine(scratch,"untrusted.json")).CheckAsync().GetAwaiter().GetResult();throw new Exception("Untrusted manifest accepted");}catch(IOException){} });
 }
}
