// C# 5 / .NET Framework 4.8, Windows 10/11 x64. Fully offline setup and local updates.
using System;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Collections.Generic;
using System.Drawing;
using System.Reflection;
using System.Diagnostics;
using System.Threading.Tasks;
using System.Windows.Forms;
namespace AstroArchive.Installation {
 class PayloadManifest {public string Version,PackageVersion;public int Revision;public Dictionary<string,string> Hashes;}
 static class Setup {
  public static string ApplicationVersion=ReleaseVersion.Application;
  static byte[] Resource(string name){using(var stream=Assembly.GetExecutingAssembly().GetManifestResourceStream(name)){if(stream==null)throw new IOException("Missing installer payload: "+name);using(var bytes=new MemoryStream()){stream.CopyTo(bytes);return bytes.ToArray();}}}
  public static InstallPackage Package(){var manifest=InstallCore.Json().Deserialize<PayloadManifest>(System.Text.Encoding.UTF8.GetString(Resource("payload.json")));var package=new InstallPackage{Version=manifest.Version,PackageVersion=manifest.PackageVersion,Revision=manifest.Revision};using(var input=new MemoryStream(Resource("payload.zip")))using(var zip=new ZipArchive(input,ZipArchiveMode.Read)){foreach(var entry in zip.Entries){if(entry.Length>100*1024*1024)throw new IOException("Payload entry is too large.");string hash;if(!manifest.Hashes.TryGetValue(entry.FullName,out hash)||package.Files.Any(f=>f.Name==entry.FullName))throw new IOException("Unexpected installer payload.");using(var stream=entry.Open())using(var bytes=new MemoryStream()){stream.CopyTo(bytes);package.Files.Add(new PayloadFile{Name=entry.FullName,Hash=hash,Bytes=bytes.ToArray()});}}}if(package.Files.Count!=manifest.Hashes.Count)throw new IOException("Incomplete installer payload.");return package;}
  static string Arg(string[] args,string name,string fallback){int i=Array.IndexOf(args,name);if(i<0)return fallback;if(i+1>=args.Length)throw new IOException("A value is required after "+name);return args[i+1];}
  static bool Has(string[] args,string name){return Array.IndexOf(args,name)>=0;}
  static InstallCore Engine(Action<string> progress){return new InstallCore{Progress=progress,EnsureClosed=WindowsIntegration.EnsureClosed,Register=WindowsIntegration.Register,Unregister=WindowsIntegration.Unregister,ShortcutPaths=WindowsIntegration.ShortcutPaths};}
  static void Wait(string[] args){int id;if(int.TryParse(Arg(args,"--waitpid","0"),out id)&&id>0)try{using(var p=Process.GetProcessById(id)){if(!p.WaitForExit(60000))throw new IOException("AstroArchive is still running. Close it and run setup again.");}}catch(ArgumentException){}}
  static void Launch(string root){var record=InstallCore.Read(root);Process.Start(new ProcessStartInfo(InstallCore.Managed(root,record.ActiveDirectory+"\\Start.exe")){UseShellExecute=true});}
  static void CleanupTempSelf(){string location=Assembly.GetExecutingAssembly().Location,name=Path.GetFileName(location);if(!System.Text.RegularExpressions.Regex.IsMatch(name,@"^AstroArchive-uninstall-[a-f0-9]+\.exe$")||Path.GetDirectoryName(location)!=Path.GetTempPath().TrimEnd('\\','/'))return;try{Process.Start(new ProcessStartInfo(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System),"cmd.exe"),"/d /q /c \"timeout /t 2 /nobreak >nul & del /f /q "+name+"\""){UseShellExecute=false,CreateNoWindow=true,WorkingDirectory=Path.GetDirectoryName(location)});}catch{}}
  [STAThread]static int Main(string[] args){bool silent=Has(args,"--silent");try{AppContext.SetSwitch("Switch.System.IO.UseLegacyPathHandling",false);AppContext.SetSwitch("Switch.System.IO.BlockLongPaths",false);WindowsIntegration.CheckEnvironment();Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);Wait(args);string self=Assembly.GetExecutingAssembly().Location;bool remove=Has(args,"--uninstall")||Path.GetFileName(self).Equals("Uninstall.exe",StringComparison.OrdinalIgnoreCase);string root=Arg(args,"--root",remove?Path.GetDirectoryName(self):WindowsIntegration.RegisteredRoot());
    if(remove){root=InstallCore.Root(root);if(!silent&&MessageBox.Show("Remove AstroArchive application files and shortcuts? Your repositories, images and user settings will be retained.","Uninstall AstroArchive",MessageBoxButtons.OKCancel,MessageBoxIcon.Warning)!=DialogResult.OK)return 0;if(self.Equals(Path.Combine(root,"Uninstall.exe"),StringComparison.OrdinalIgnoreCase)){string temp=Path.Combine(Path.GetTempPath(),"AstroArchive-uninstall-"+Guid.NewGuid().ToString("N")+".exe");File.Copy(self,temp);Process.Start(new ProcessStartInfo(temp,"--uninstall --silent --root "+WindowsIntegration.Quote(root)+" --waitpid "+Process.GetCurrentProcess().Id){UseShellExecute=false});return 0;}Engine(s=>{}).Uninstall(root);if(!silent)MessageBox.Show("AstroArchive was removed. Repositories and settings were retained.","AstroArchive");CleanupTempSelf();return 0;}
    if(silent){Engine(s=>{}).Install(root,Package(),File.ReadAllBytes(self),Has(args,"--update"));if(Has(args,"--restart"))Launch(root);return 0;}using(var form=new SetupForm(root,Has(args,"--update"))){Application.Run(form);return form.Result;}
   }catch(Exception e){try{File.WriteAllText(Path.Combine(Path.GetTempPath(),"AstroArchive-setup-error.txt"),e.ToString());}catch{}if(!silent)MessageBox.Show(e.Message,"AstroArchive Setup",MessageBoxButtons.OK,MessageBoxIcon.Error);CleanupTempSelf();return 1;}}
  sealed class SetupForm:Form {
   TextBox location;Button install,browse,cancel;Label status;ProgressBar progress;CheckBox launch;bool busy;readonly bool updateOnly;public int Result=1;
   public SetupForm(string root,bool onlyUpdate){updateOnly=onlyUpdate;Text="AstroArchive "+ApplicationVersion+" Setup";Icon=Icon.ExtractAssociatedIcon(Assembly.GetExecutingAssembly().Location);AutoScaleDimensions=new SizeF(96,96);AutoScaleMode=AutoScaleMode.Dpi;ClientSize=new Size(690,415);MinimumSize=Size;MaximumSize=Size;MaximizeBox=false;StartPosition=FormStartPosition.CenterScreen;Font=new Font("Segoe UI",10);BackColor=Color.FromArgb(245,247,249);var header=new Panel{Dock=DockStyle.Top,Height=112,BackColor=Color.FromArgb(16,35,57)};Controls.Add(header);using(var s=new MemoryStream(Resource("logo.png")))header.Controls.Add(new PictureBox{Image=new Bitmap(Image.FromStream(s)),SizeMode=PictureBoxSizeMode.Zoom,Location=new Point(18,9),Size=new Size(94,94)});header.Controls.Add(new Label{Text="AstroArchive "+ApplicationVersion,ForeColor=Color.White,Font=new Font("Segoe UI",22,FontStyle.Bold),Location=new Point(130,24),Size=new Size(500,40)});header.Controls.Add(new Label{Text="Install, update or repair your Windows installation",ForeColor=Color.FromArgb(155,215,226),Location=new Point(133,72),AutoSize=true});Controls.Add(new Label{Text="Install location",Location=new Point(28,139),AutoSize=true});location=new TextBox{Text=root,Location=new Point(28,169),Width=520};Controls.Add(location);browse=new Button{Text="Browse...",Location=new Point(556,166),Size=new Size(103,30)};browse.Click+=(s,e)=>{string path=AstroArchive.NativeFolderPicker.Select(Handle,"Choose a local installation folder",location.Text);if(path!=null)location.Text=path;};Controls.Add(browse);Controls.Add(new Label{Text="Setup detects the existing AstroArchive installation and upgrades it in place.\nRepositories, images and app settings are retained. Installation is for this\nWindows account. Updates use a newer installer downloaded by you.",Location=new Point(28,214),Size=new Size(630,70),ForeColor=Color.FromArgb(70,88,104)});launch=new CheckBox{Text="Launch AstroArchive when finished",Checked=true,Location=new Point(28,297),AutoSize=true};Controls.Add(launch);status=new Label{Text="Ready. Close AstroArchive before installing or updating.",Location=new Point(28,331),Size=new Size(630,24),AutoEllipsis=true};Controls.Add(status);progress=new ProgressBar{Location=new Point(28,368),Size=new Size(357,18),Visible=false,Style=ProgressBarStyle.Marquee};Controls.Add(progress);cancel=new Button{Text="Cancel",Location=new Point(558,365),Size=new Size(101,32)};cancel.Click+=(s,e)=>Close();Controls.Add(cancel);install=new Button{Text=File.Exists(Path.Combine(root,"install.json"))?"Update / Repair":"Install",Location=new Point(408,365),Size=new Size(137,32),BackColor=Color.FromArgb(22,104,118),ForeColor=Color.White,FlatStyle=FlatStyle.Flat};install.Click+=InstallClick;Controls.Add(install);AcceptButton=install;CancelButton=cancel;FormClosing+=(s,e)=>{if(busy)e.Cancel=true;};}
   async void InstallClick(object sender,EventArgs args){if(busy)return;busy=true;install.Enabled=browse.Enabled=cancel.Enabled=location.Enabled=launch.Enabled=false;progress.Visible=true;try{string root=location.Text;var engine=Engine(message=>BeginInvoke(new Action(()=>status.Text=message)));await Task.Run(()=>engine.Install(root,Package(),File.ReadAllBytes(Assembly.GetExecutingAssembly().Location),updateOnly));Result=0;status.Text="Installed. Desktop and Start menu shortcuts are ready.";progress.Visible=false;install.Visible=false;cancel.Enabled=true;cancel.Text="Finish";if(launch.Checked){try{Launch(root);}catch(Exception e){MessageBox.Show("Installation completed, but the app could not start: "+e.Message,Text);}}}catch(Exception e){status.Text="Installation could not finish.";MessageBox.Show(e.Message,Text,MessageBoxButtons.OK,MessageBoxIcon.Error);install.Enabled=browse.Enabled=cancel.Enabled=location.Enabled=launch.Enabled=true;progress.Visible=false;}finally{busy=false;}}
  }
 }
}
