// C# 5 / .NET Framework 4.8. Generated directories only; no registry or user-data writes.
using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using AstroArchive.Installation;
class Tests {
 static int passed,failed;static string scratch;
 static void Check(bool valid,string text){if(!valid)throw new Exception(text);}
 static void Test(string name,Action action){try{action();passed++;Console.WriteLine("PASS "+name);}catch(Exception e){failed++;Console.WriteLine("FAIL "+name+": "+e);}}
 static void Expect(Action action){try{action();}catch(IOException){return;}throw new Exception("Expected refusal.");}
 static string Root(string name){return Path.Combine(scratch,name);}
 static InstallPackage Package(string version="1.2.0",int revision=1){var p=new InstallPackage{Version=version,PackageVersion=version+"."+revision,Revision=revision};foreach(string name in new[]{"AstroArchive.exe","Start.exe","Release_Notes.txt","Quick_Start.txt"}){byte[] bytes=Encoding.UTF8.GetBytes(version+":"+revision+":"+name);p.Files.Add(new PayloadFile{Name=name,Bytes=bytes,Hash=InstallCore.Hash(bytes)});}return p;}
 static byte[] Setup{get{return Encoding.UTF8.GetBytes("test installer");}}
 static InstallRecord Install(string name,InstallPackage p=null){return new InstallCore().Install(Root(name),p??Package(),Setup);}
 static int Main(string[] args){scratch=Path.GetFullPath(args.Length>0?args[0]:"installer-test-data");Directory.CreateDirectory(scratch);
  Test("Fresh install publishes verified payload, versioned folder and record",()=>{var r=Install("fresh");Check(r.Version=="1.2.0"&&r.PackageVersion=="1.2.0.1","Incorrect version");Check(File.Exists(InstallCore.Managed(Root("fresh"),r.ActiveDirectory+"\\AstroArchive.exe"))&&File.Exists(Path.Combine(Root("fresh"),"Uninstall.exe")),"Missing installation files");Check(InstallCore.Read(Root("fresh")).Files.Length==4,"Record incomplete");});
  Test("City catalogue attribution installs, repairs and uninstalls as a managed file",()=>{var package=Package();byte[] bytes=Encoding.UTF8.GetBytes("GeoNames CC BY 4.0");package.Files.Add(new PayloadFile{Name="City_Catalogue_Notice.md",Bytes=bytes,Hash=InstallCore.Hash(bytes)});var record=Install("city-notice",package);string path=InstallCore.Managed(Root("city-notice"),record.ActiveDirectory+"/City_Catalogue_Notice.md");Check(File.ReadAllText(path)=="GeoNames CC BY 4.0","Attribution not installed");File.WriteAllText(path,"damaged");Install("city-notice",package);Check(InstallCore.HashFile(path)==InstallCore.Hash(bytes),"Attribution not repaired");new InstallCore().Uninstall(Root("city-notice"));Check(!File.Exists(path),"Attribution not removed with the managed app");});
  Test("Software licensing files install, repair and uninstall with the application",()=>{
   var package=Package();foreach(string name in new[]{"LICENSE.txt","LICENSING.md"}){byte[] bytes=Encoding.UTF8.GetBytes("PolyForm Noncommercial 1.0.0: "+name);package.Files.Add(new PayloadFile{Name=name,Bytes=bytes,Hash=InstallCore.Hash(bytes)});}
   var record=Install("software-licence",package);
   foreach(var file in package.Files.Where(f=>f.Name=="LICENSE.txt"||f.Name=="LICENSING.md")){string path=InstallCore.Managed(Root("software-licence"),record.ActiveDirectory+"/"+file.Name);Check(InstallCore.HashFile(path)==file.Hash,"Licence file not installed");File.WriteAllText(path,"damaged");}
   Install("software-licence",package);
   foreach(var file in package.Files.Where(f=>f.Name=="LICENSE.txt"||f.Name=="LICENSING.md"))Check(InstallCore.HashFile(InstallCore.Managed(Root("software-licence"),record.ActiveDirectory+"/"+file.Name))==file.Hash,"Licence file not repaired");
   new InstallCore().Uninstall(Root("software-licence"));Check(!Directory.Exists(Path.Combine(Root("software-licence"),record.ActiveDirectory)),"Licence files left behind after uninstall");
  });
  Test("Same-version rerun repairs a missing or changed application",()=>{var r=Install("repair");string p=InstallCore.Managed(Root("repair"),r.ActiveDirectory+"\\AstroArchive.exe");File.WriteAllText(p,"damaged");Install("repair");Check(InstallCore.HashFile(p)==Package().Files[0].Hash,"Damaged executable not repaired");File.Delete(p);Install("repair");Check(File.Exists(p),"Missing executable not restored");});
  Test("Legacy example record is adopted without changing unrelated files",()=>{string root=Root("legacy"),dir=Path.Combine(root,"app-1.1.0");Directory.CreateDirectory(dir);foreach(string n in new[]{"AstroArchive.exe","Start.exe","Release_Notes.txt"})File.WriteAllText(Path.Combine(dir,n),"old");File.WriteAllText(Path.Combine(root,"Uninstall.exe"),"old setup");File.WriteAllText(Path.Combine(root,"install.json"),"{\"Product\":\"AstroArchive\",\"Version\":\"1.1.0\",\"Files\":[\"app-1.1.0\\\\AstroArchive.exe\",\"app-1.1.0\\\\Start.exe\",\"app-1.1.0\\\\Release_Notes.txt\"],\"Shortcuts\":[]}");File.WriteAllText(Path.Combine(root,"unrelated.txt"),"keep");var r=Install("legacy");Check(r.Files.Length==7&&r.ActiveDirectory=="app-1.2.0-r1"&&File.ReadAllText(Path.Combine(root,"unrelated.txt"))=="keep","Legacy migration incorrect");});
  Test("Newer application installer upgrades the existing installation",()=>{Install("upgrade");var r=Install("upgrade",Package("1.3.0"));Check(r.Version=="1.3.0"&&r.ActiveDirectory=="app-1.3.0-r1"&&r.Files.Length==8,"Upgrade not activated");});
  Test("Attached example's 1.2.0 record upgrades to offline revision without a downgrade",()=>{string root=Root("example-120"),dir=Path.Combine(root,"app-1.2.0");Directory.CreateDirectory(dir);foreach(string n in new[]{"AstroArchive.exe","Start.exe","Release_Notes.txt"})File.WriteAllText(Path.Combine(dir,n),"original");var old=new InstallRecord{Version="1.2.0",Files=new[]{"app-1.2.0\\AstroArchive.exe","app-1.2.0\\Start.exe","app-1.2.0\\Release_Notes.txt"}};File.WriteAllText(Path.Combine(root,"install.json"),InstallCore.Json().Serialize(old));var r=Install("example-120");Check(r.Version=="1.2.0"&&r.PackageVersion=="1.2.0.1"&&r.ActiveDirectory=="app-1.2.0-r1"&&r.Files.Length==7,"Attached-example migration failed");});
  Test("Newer installer revision updates the same app version",()=>{Install("revision");var r=Install("revision",Package("1.2.0",2));Check(r.PackageVersion=="1.2.0.2"&&r.ActiveDirectory=="app-1.2.0-r2","Revision update failed");});
  Test("Application and package downgrades are rejected",()=>{Install("downgrade",Package("1.3.0"));Expect(()=>Install("downgrade"));Install("package-downgrade",Package("1.2.0",10));Expect(()=>Install("package-downgrade",Package("1.2.0",2)));Check(InstallCore.Read(Root("downgrade")).Version=="1.3.0","Downgrade changed existing installation");});
  Test("Numeric versions compare 1.10 above 1.9",()=>{Install("numeric",Package("1.10.0"));Expect(()=>Install("numeric",Package("1.9.0")));});
  Test("Update-only mode requires an existing installation",()=>{Expect(()=>new InstallCore().Install(Root("update-only"),Package(),Setup,true));Check(!File.Exists(Path.Combine(Root("update-only"),"install.json")),"Update created a new installation");});
  Test("Fresh install refuses unrelated nonempty directories",()=>{Directory.CreateDirectory(Root("foreign"));File.WriteAllText(Path.Combine(Root("foreign"),"important.txt"),"keep");Expect(()=>Install("foreign"));Check(File.ReadAllText(Path.Combine(Root("foreign"),"important.txt"))=="keep","Unrelated file changed");});
  Test("Invalid product records are rejected",()=>{Directory.CreateDirectory(Root("bad-product"));File.WriteAllText(Path.Combine(Root("bad-product"),"install.json"),"{\"Product\":\"Other\",\"Version\":\"1.2.0\",\"Files\":[]}");Expect(()=>Install("bad-product"));});
  Test("Payload hash mismatch prevents installation",()=>{var p=Package();p.Files[0].Bytes[0]++;Expect(()=>Install("bad-hash",p));Check(!Directory.Exists(Root("bad-hash")),"Bad payload wrote files");});
  Test("Payload path traversal and duplicate names are rejected",()=>{var p=Package();p.Files[0].Name="../outside.exe";Expect(()=>Install("bad-payload-path",p));p=Package();p.Files.Add(p.Files[0]);Expect(()=>Install("duplicate-payload",p));});
  Test("Installation record traversal cannot remove an external file",()=>{Install("record-path");string outside=Path.Combine(scratch,"outside.txt");File.WriteAllText(outside,"keep");var r=InstallCore.Read(Root("record-path"));r.Files=r.Files.Concat(new[]{"../outside.txt"}).ToArray();File.WriteAllText(Path.Combine(Root("record-path"),"install.json"),InstallCore.Json().Serialize(r));Expect(()=>new InstallCore().Uninstall(Root("record-path")));Check(File.Exists(outside),"External file deleted");});
  Test("Failure after staging leaves the installed version unchanged",()=>{Install("stage-failure");var core=new InstallCore{TestHook=s=>{if(s=="staged")throw new IOException("Injected disk failure");}};Expect(()=>core.Install(Root("stage-failure"),Package("1.3.0"),Setup));Check(InstallCore.Read(Root("stage-failure")).Version=="1.2.0"&&!Directory.GetDirectories(Root("stage-failure"),".stage-*").Any(),"Stage failure changed the installation");});
  Test("Failure before record commit restores an existing same-version folder",()=>{Install("commit-failure");string before=File.ReadAllText(Path.Combine(Root("commit-failure"),"install.json"));var core=new InstallCore{TestHook=s=>{if(s=="before-record")throw new IOException("Injected commit failure");}};Expect(()=>core.Install(Root("commit-failure"),Package(),Setup));Check(File.ReadAllText(Path.Combine(Root("commit-failure"),"install.json"))==before&&InstallCore.HashFile(InstallCore.Managed(Root("commit-failure"),"app-1.2.0-r1\\AstroArchive.exe"))==Package().Files[0].Hash,"Repair rollback lost old files");});
  Test("Registration failure rolls back the new version and record",()=>{Install("registration-failure");var core=new InstallCore{Register=(root,r)=>{if(r.Version=="1.3.0")throw new IOException("Injected registry failure");}};Expect(()=>core.Install(Root("registration-failure"),Package("1.3.0"),Setup));Check(InstallCore.Read(Root("registration-failure")).Version=="1.2.0"&&!Directory.Exists(Path.Combine(Root("registration-failure"),"app-1.3.0-r1")),"Registration failure left partial upgrade");});
  Test("Running-application refusal prevents modification",()=>{Install("running");var core=new InstallCore{EnsureClosed=r=>{throw new IOException("Close application");}};Expect(()=>core.Install(Root("running"),Package("1.3.0"),Setup));Check(InstallCore.Read(Root("running")).Version=="1.2.0","Running app modified");});
  Test("Repair refuses additional files inside its application folder",()=>{var r=Install("additional");string extra=Path.Combine(Root("additional"),r.ActiveDirectory,"user.txt");File.WriteAllText(extra,"keep");Expect(()=>Install("additional"));Check(File.ReadAllText(extra)=="keep","User file replaced");});
  Test("Uninstall removes all managed versions and preserves repository/settings files",()=>{Install("remove");Install("remove",Package("1.3.0"));Directory.CreateDirectory(Path.Combine(Root("remove"),"repository"));File.WriteAllText(Path.Combine(Root("remove"),"repository","capture.fits"),"keep data");File.WriteAllText(Path.Combine(Root("remove"),"settings.json"),"keep preferences");File.WriteAllText(Path.Combine(Root("remove"),"app-1.2.0-r1","extra.txt"),"keep extra");new InstallCore().Uninstall(Root("remove"));Check(!File.Exists(Path.Combine(Root("remove"),"Uninstall.exe"))&&!File.Exists(Path.Combine(Root("remove"),"install.json"))&&File.Exists(Path.Combine(Root("remove"),"repository","capture.fits"))&&File.Exists(Path.Combine(Root("remove"),"settings.json"))&&File.Exists(Path.Combine(Root("remove"),"app-1.2.0-r1","extra.txt")),"Uninstall exceeded its scope");});
  Test("Drive root and linked installation directories are rejected",()=>{Expect(()=>InstallCore.Root(Path.GetPathRoot(scratch)));if(Environment.OSVersion.Platform==PlatformID.Unix){Directory.CreateDirectory(Root("link-target"));Check(symlink(Root("link-target"),Root("linked"))==0,"Unable to create fixture link");Expect(()=>Install("linked"));Check(!Directory.EnumerateFileSystemEntries(Root("link-target")).Any(),"Linked target changed");}});
  Test("Version fields must agree between app and installer",()=>{var p=Package();p.PackageVersion="1.1.0.1";Expect(()=>Install("mismatched-version",p));});
  Test("Progress display failures cannot damage a completed installation",()=>{Install("progress-failure");var core=new InstallCore{Progress=s=>{throw new InvalidOperationException("Disposed progress window");}};core.Install(Root("progress-failure"),Package("1.3.0"),Setup);Check(InstallCore.Read(Root("progress-failure")).Version=="1.3.0"&&File.Exists(Path.Combine(Root("progress-failure"),"app-1.3.0-r1","AstroArchive.exe")),"Display failure rolled back a committed upgrade");});
  UpdateTests.Run(Test, scratch);
  Test("Application Control failures explain the policy and preserve the rejected file",()=>{
   foreach(int code in new[]{1260,4551,577}){
    var error=new IOException("Could not start C:\\Example\\Start.exe",new System.ComponentModel.Win32Exception(code));
    string message=WindowsPolicyError.Message(error);
    Check(message.Contains("Application Control")&&message.Contains("C:\\Example\\Start.exe")&&message.Contains("AstroArchive-setup-error.txt")&&message.Contains("administrator"),"Policy failure lost diagnosis or context");
    Check(WindowsPolicyError.Details(error).Contains("Native Windows error: "+code),"Diagnostic log lost the native policy code");
   }
   string com=WindowsPolicyError.Message(new COMException("Blocked component",unchecked((int)0x800711c7)));
   Check(com.Contains("Application Control"),"COM policy HRESULT was not recognized");
   Check(WindowsPolicyError.Message(new IOException("Disk full"))=="Disk full","Unrelated failure was mislabeled as policy");
  });
  File.WriteAllText(Path.Combine(scratch,"test-results.txt"),passed+" passed; "+failed+" failed");Console.WriteLine(passed+" passed; "+failed+" failed");return failed==0?0:1;
 }
 [DllImport("libc",SetLastError=true)]static extern int symlink(string target,string link);
}
